In [1]:
import os
import json
import pandas as pd

In [2]:
pet_data = pd.read_csv("./train.csv")
query = pet_data[pet_data['PetID']=="d24c30b4b"]


print(query['Age'].item())
print(query['Breed1'].item())
print(query['Breed2'].item())
print(query['Gender'].item())
print(query['Color1'].item())
print(query['Color2'].item())
print(query['Color3'].item())
print(query['MaturitySize'].item())
print(query['FurLength'].item())
print(query['Vaccinated'].item())
print(query['Dewormed'].item())
print(query['Sterilized'].item())
print(query['Quantity'].item())
print(query['Fee'].item())
print(query['PhotoAmt'].item())
print(query['AdoptionSpeed'].item())

3
266
0
2
5
6
0
2
1
2
2
2
1
0
2.0
2

In [3]:
directory = './train_sentiment'
destination = 'json_with_labels'

try:  
    os.mkdir(destination)
except OSError:  
    print ("Creation of the directory %s failed")
else:  
    print ("Successfully created the directory %s ")

for filename in os.listdir(directory):
    if filename.endswith(".json"):
        with open('./train_sentiment/' + filename) as json_file:
            print(filename)
            data = json.load(json_file)
            
            # keep everything english
            if (data["language"] != "en"):
                continue
                
            pet_hash = filename[:-5]
            query = pet_data[pet_data['PetID']==pet_hash]
            print(pd.to_numeric(query["Type"]))
            print(type(pd.to_numeric(query["Type"])))
            
            age = query['Age'].item()
            breed1 = query['Breed1'].item()
            breed2 = query['Breed2'].item()
            gender = query['Gender'].item()
            color1 = query['Color1'].item()
            color2 = query['Color2'].item()
            color3 = query['Color3'].item()
            maturitySize = query['MaturitySize'].item()
            furLength = query['FurLength'].item()
            vaccinated = query['Vaccinated'].item()
            dewormed = query['Dewormed'].item()
            sterilized = query['Sterilized'].item()
            quantity = query['Quantity'].item()
            fee = query['Fee'].item()
            photoAmt = query['PhotoAmt'].item()
            label = query['AdoptionSpeed'].item()

            data['Age'] = age
            data['Breed1'] = breed1
            data['Breed2'] = breed2
            data['Gender'] = gender
            data['Color1'] = color1
            data['Color2'] = color2
            data['Color3'] = color3
            data['MaturitySize'] = maturitySize
            data['FurLength'] = furLength
            data['Vaccinated'] = vaccinated           
            data['Dewormed'] = dewormed
            data['Sterilized'] = sterilized
            data['Quantity'] = quantity           
            data['Fee'] = fee
            data['PhotoAmt'] = photoAmt
            data['label'] = label
    
            
            with open('./' + destination + "/with_label_" + filename, 'w') as outfile:
                json.dump(data, outfile, indent=4)

Successfully created the directory %s
b5e7e4539.json
13151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41e824cbe.json
11940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0833744e6.json
12823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc229a9d7.json
11031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3589a8a0d.json
2716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdfe6125d.json
12441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57af29aba.json
3591    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94afcd90c.json
9919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa7dc1913.json
11988    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
868dcd617.json
2805    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f1d6224d.json
10825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
811f9407f.json
5192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15a206d0d.json
1603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d45776f61.json
9676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7a74fca8.json
423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe4bb01a6.json
7332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
029e79030.json
1677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e77941c00.json
5895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f72c46b5.json
651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e92b33580.json
14061    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e6d8b614.json
1079    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1e816568.json
45    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e40073625.json
14876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8fc0d746.json
652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a97062f5.json
5265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
081c0a12d.json
12749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49a867af7.json
9958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24c1d5a33.json
5305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fc7557be.json
8087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e98b9e24.json
6455    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a062234cb.json
10782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66b206dbe.json
5106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6819ce556.json
456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8d27db32.json
13308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bd573e1.json
5158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6b28fc29.json
5337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cd8ca49f.json
4924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4e1afd9e.json
12810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
718c4b524.json
2896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
435f419f9.json
3903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
096a97631.json
11914    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
409740892.json
11248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0982978a.json
6558    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e152df77a.json
1145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a854aca45.json
8260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6f0972d4.json
2971    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e246ecfdc.json
4705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43b99bc40.json
13263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133ca8c90.json
14401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71f93d157.json
6497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0edb4e3b2.json
14508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
261a88440.json
13022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fcd44bf9.json
7548    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15f89f939.json
8115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9115f86cb.json
5105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b39f3f7ad.json
10233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7810092ba.json
11916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f49d2828.json
3731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f2bd07e8.json
8862    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eb8a8e8e.json
1291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf50b399e.json
342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81a1cb1b2.json
3808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1db9573c.json
7176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86228db7e.json
13252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87a243fe6.json
4208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fd44f9f3.json
10226    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a80687cf1.json
7594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13966b6a8.json
6288    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0211e2f2d.json
3724    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b4745340.json
8888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
360215e23.json
13418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fa04723a.json
5377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aca9ddee7.json
12111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eddac3328.json
3412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba3ee71f8.json
4498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e774a9c7.json
6164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f33216f7.json
10831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36edc334e.json
6864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a58d8080b.json
811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0278d962.json
3994    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69f4a00df.json
14328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e78230b.json
6825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
828f48390.json
7612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
603dbe569.json
13027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a05674125.json
9337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bacb98ab.json
8274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa0901313.json
9625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
062e2772c.json
10697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb48e2353.json
5970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9ee26e3.json
9760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1ae07ad5.json
5230    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0be7a4adf.json
4723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46d88ca3e.json
116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
897fde926.json
4175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a12a494f.json
4111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c38afccab.json
12398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3be835fa8.json
6954    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a6197f6d.json
7522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4aa3713a.json
1193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6471c7195.json
11719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6607c6e22.json
5998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30eb1004f.json
3981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
200a0df49.json
6697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe2209833.json
5089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c09a67b3a.json
12161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21b5e3d22.json
7461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a76937df3.json
9955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bcae32b7.json
7729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
056bb97e4.json
5049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99f5b19b5.json
3608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d4f585b5.json

14256    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a0db11a9.json
13038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d71310023.json
9783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6668704bf.json
6566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de1f49c9d.json
11648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc8bf5e79.json
839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76042f693.json
12191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27ef6e605.json
14805    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d19917cb.json
10546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b9cd9253.json
12631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e3aad5f3.json
409    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ea365a6f.json
729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7ab271b1.json
12861    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69ba8d92e.json
6603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8697f0fd.json
9043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1991b0817.json
8911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04bad9310.json
6896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a59aa3f80.json
11911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
463be5788.json
12634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28dfa1c39.json
13328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7f5a8bd0.json
11604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
029b05087.json
8985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee370b5cf.json
6486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9206bc13.json
12114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61ba636f0.json
9546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51e25fe8b.json
9157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c863daf49.json
2059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
948a1a82c.json
2526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c909e8d0.json
6133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d41773368.json
11060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c969e8b17.json
3448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e276a9ad1.json
14353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f54941314.json
1859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7843a9dca.json
28    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b271a8246.json
5341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e6c42df6.json
2933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fee500b95.json
13939    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49ad94a6a.json
13449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56b63bfb3.json
5355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
332ae5ab2.json
12656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97d823486.json
13743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8abb96298.json
10201    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bb96a979.json
2803    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d994c50c.json
7708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e17c1fde.json
7057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6c1048af.json
7832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d39ce00b.json
9388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ba05432d.json
10994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5649192e9.json
8317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da5ae6aa9.json
838    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96b39751e.json
11324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37c989ac5.json
3663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c4af5f08.json
12299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53964c5d0.json
9440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf4d18e3.json
10458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355756bdc.json
1904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc99804de.json
292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edc5c168a.json
7926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee57c8d53.json
10317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f50d46b2.json
8025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adc51c1a7.json
12103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
574b9ab4f.json
9058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1988cdd5.json
12537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be38039cc.json
6255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e50d881a7.json
14968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1efbef49e.json
13177    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3486b178.json
5886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2416a2da1.json
14763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bebfc2a8.json
8954    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ce0f64b4.json
4134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bd13d3e5.json
1604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d8c4f66b.json
4136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dcce539c.json
8289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
456c7a365.json
14755    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
310c3f884.json
7425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bdf3471b.json
13681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db0a53c3a.json
9687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54224dada.json
1544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
219444cb8.json
7738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45f8df95e.json
9811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e3fba2c2.json
1625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa73b1181.json
11805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ddb2eb4.json
101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ded98af9.json
5934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd8f64c6d.json
10291    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b71de34e.json
1439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04b5f77c0.json
2245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93e058345.json
3589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
607744326.json
7401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbc7dc778.json
11297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ca3bc8f5.json
9332    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e97e1afc1.json
13089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05aaee8ce.json
10439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36f1c9d61.json
8476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015fdb354.json
10324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b69d479cf.json

8129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5780fe74a.json
13933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1da3eb996.json
11611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a44b2389a.json
3151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d40cfa55.json
9643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38e3b6744.json
11950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d66ac1e7.json
5950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecb6979fa.json
11503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baf543aa6.json
12772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97dd55a08.json
9250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef086278a.json
8508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33826a08a.json
10797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84057a73d.json
11734    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12c65f314.json
11506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dac572be.json
950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
155d18f5f.json
11973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f74af51f.json
13513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71cc0a02e.json
374    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e96d122ed.json
5685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dc36183c.json
1474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88fa13291.json
7665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c82e4964c.json
10738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30506e8c1.json
12381    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4ba78b62.json
8466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3085ca2c6.json
5866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42d565331.json
14441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f402845d.json
2385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dce7af31c.json
9081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3f8bb113.json
11401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a496733d.json
10940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7362590d5.json
4265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0d4b988a.json
2709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6326e5387.json
11428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0327b8e94.json
7706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33a373ca9.json
5764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a90a72141.json
5573    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ce620a7a.json
4632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b80074591.json
2597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3acfe9fcd.json
13685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb3d2466f.json
3222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c63dc4adb.json
13975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03ae93b48.json
9000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8be6ec3c.json
983    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c196faec.json
2051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba6ea2d18.json
1653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc02869d9.json
14691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdf5760e8.json
10119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08048fee2.json
12512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4872c28b4.json
4036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fed61438.json
5951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ede86b28.json
4827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b4ff27b3.json
7518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
022606901.json
3588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1870f34b.json
8523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93f620b68.json
7565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63912e2b8.json
3440    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48fd10660.json
6302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f434b444.json
12176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75a11e0f8.json
410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af39d67a5.json
10427    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b307a8ec.json
13510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d336e6953.json
14290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd015cd22.json
5959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0146f6d2c.json
11759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0058586f1.json
2388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45dba413a.json
6215    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd405bac.json
7125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b9739cef.json
14101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc93e5aa5.json
4910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21655a8bc.json
2484    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1633b105b.json
6500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f861c3c77.json
7150    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2c98c186.json
13988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b928c0a6.json
9899    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a0746a1f.json
14059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
425804cd2.json
14016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e5d845dc.json
12595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2107c9788.json
7488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
434691342.json
4394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78f87a45d.json
1438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9415bc79e.json
33    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3b39a9f5.json
217fcf5f1.json
2147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9304f9f8b.json
8266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
183160bf0.json
5152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
747359fcb.json
825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3595648ea.json
1584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bc5b2ced.json
8123    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38436063c.json
3315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
708ce5f42.json
5960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35c9855f5.json
10591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
958a86135.json
7361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b67f6ed6.json
11079    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7696fdac.json
8994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9495309b.json
11227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e488a36cf.json
9989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0658597c9.json
1560    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a3c85e3c.json
6071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
233ddf40c.json
4182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
446748891.json
4811    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6551137d.json
55    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb21c0250.json
6813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74cd0ff66.json

8100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0af536283.json
8791    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14cbb81c8.json
10188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d452218f1.json
1950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd2ebd5e.json
13285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4aa86e0a.json
10455    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8e5ae23a.json
1920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd57abde.json
12131    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
570b3eb92.json
13351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40f1ee340.json
13827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09f75d8e1.json
14883    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45af03266.json
4831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11cc5a797.json
5963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07cfb3380.json
9701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe0a74b2b.json
11586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01573c686.json
2357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3f28534a.json
9914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec250ea11.json
5735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
832a83f42.json
3199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a1e3aa63.json
4683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4464fa621.json
11470    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61e477c0a.json
9880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41bcb5de4.json
5361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4405cc72c.json
2800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3db279d0.json
13066    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b5a9db5.json
14724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc492b6b5.json
11929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
732a2ed35.json
5094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d277ebe6.json
7237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f57efd0b9.json
3803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3449e0d0.json
12534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1adb69797.json
11679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb568959e.json
2790    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
662f8c2a9.json
14119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e9f82a98.json
6848    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
997db5df5.json
406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f522ad8d4.json
5449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2aac4b61a.json
7359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64c2d93c9.json
11807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ac3ca459.json
10862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5377c3a3c.json
13367    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e3b1dcd1.json
12269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
262c8cc14.json
6305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2398599fc.json
1214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e742a643d.json
6411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d474edc5.json
9721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85c65d28b.json
12618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af14a63c.json
6158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02a2a622c.json
6945    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5980b0699.json
1238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87f4ea65f.json
556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6df6932d.json
6266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a72cfda7.json
7300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
196504d88.json
1635    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c05a85bbb.json
5211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
412d7406c.json
8463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfb7301a8.json
9331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c9a2baf6.json
7587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ad6c7675.json
3535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3f83cef6.json
10376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a9ca7419.json
1723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f8824a3b.json
13408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ce528284.json
4046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2185647c2.json
12565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c675f3b10.json
269    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c148399c0.json
3519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae00eded4.json
3996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f89c6f6a6.json
9386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee4cb45ea.json
12731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcb22c952.json
2745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fec4436f.json
11722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31e14c50a.json
7872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fbf2cb7c.json
12233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88c193102.json
5883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a39ad6dc7.json
14655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49d1423d5.json
9842    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfdd20655.json
10475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0a2122d4.json
114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
854edf08f.json
12874    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85078bc71.json
11289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c6cc4bba.json
3747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95563629d.json
9640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d18d572dd.json
11504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b091feb55.json
6746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97db95d21.json
1056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffd697903.json
10707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65ba8b6a0.json
11695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a345b4406.json
8737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c1fa6bd2.json
9862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37884b086.json
5667    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f45b9967.json
4635    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c92256e41.json
498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28e14ee81.json
9427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de489fcd8.json
2950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0995bd489.json
14466    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2be40d43.json
9511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5112b0c92.json
14485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a358b56f.json
14924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e974f807.json
9230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7f1381ba.json
037464956.json
1863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd9489e42.json
3059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd7bae691.json
6573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
132a28bc9.json
8071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aa432e1d.json
6861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b89c365c3.json
12358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
554965e66.json
1929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e011d469.json
13122    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b92781dca.json
6212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8390dbef8.json
12547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c75e5189.json
13026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

86ea9dda0.json
3572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42331ae6f.json
7214    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7d1cf92c.json
3076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b00d0fe1c.json
2580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eaab63bd7.json
4112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1de8444a7.json
6437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fda10b9ed.json
5724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07bd5a7a9.json
4969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b3fc0265.json
924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23d784a8a.json
12490    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f262fd637.json
14345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fc2dc3cb.json
4057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
169e5aef1.json
12190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a3224461.json
4591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37865f566.json
5621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54fd5fde4.json
6983    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64f563069.json
6798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00ac364a4.json
13803    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5daea1779.json
7420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b73a7ea8.json
5869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ba11975b.json
3539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4212d640.json
8116    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea92dcef6.json
3446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28e86bb13.json
9470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ae92889d.json
14646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eba510fc.json
6657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02e072cbd.json
11857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfb33b149.json
390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d40c291a9.json
2345    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cac68ead1.json
2464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10337747f.json
8613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ad546c7.json
3444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d8ffca23.json
14690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6af385f0.json
5806    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df9cc49a1.json
10869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffe0f06ab.json
4485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1929d8aea.json
4976    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b64325b9.json
2519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ea337520.json
12885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8328ec7f4.json
6338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8df693c0.json
7691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e29fd3f0a.json
10365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92586e5a3.json
3157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b3ce72d1.json
7186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c67a27f5.json
13535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f904be121.json
4830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32eb3673a.json
2223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c220fd5cc.json
8013    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c7619fdc.json
6970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0eb1073d.json
fbcea110f.json
7660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59913444e.json
2623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe3950458.json
7244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abbe2568f.json
6626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bf02a5f8.json
6076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14b3376eb.json
3741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69ba6c8d8.json
8724    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bbc1017c.json
4789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fba9cbc9.json
5902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
351f3746c.json
3261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f8890a94.json
7505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3cb6ffea.json
11897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
467aed7e3.json
1467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52602ec39.json
13335    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec9da833d.json
9344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67a68df4a.json
4841    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
623138a05.json
7308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed9885dcd.json
9812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf9a6b80.json
356    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b8a09f2d.json
11595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45afc38e4.json
10594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5145c1766.json
13759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54e2508de.json
469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9df8656a.json
60    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c4488c48.json
11590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed81d1da8.json
6318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bd8e5830.json
12202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4892ceb8d.json
3989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30dbb2e50.json
719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52da0c86c.json
13905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88e2d97b2.json
8188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e27adf529.json
14031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a05289ebd.json
343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb062285d.json
6629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6be47a3c.json
14668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19abfb0c6.json
6866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f35cb8e6.json
1309    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e6d7cbb3.json
10744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5164d828.json
531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c06b0725.json
13583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8969b314b.json
9453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30bfebc76.json
11402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
018e4d193.json
13090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bda8f113.json
744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87bdcbcdd.json
4f1d0410d.json
5321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f2301bac.json
10121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23ed3e349.json
7853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd37edf46.json
4168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
925c3854a.json
3351    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1195168b6.json
535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25f6db0fd.json
1417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f5fd467a.json
13781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e940019a3.json
5704    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9f6ed0cb.json
3206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cb5ad250.json
5606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2f1f5377.json
394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f344595d7.json
14799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c001473a1.json
9975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10b9af23d.json
13589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ec0fc838.json

12033    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3d9bc3aa.json
11495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0b5fece1.json
12561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d25fb291.json
11291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cbae6e2a.json
14747    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
828ac8371.json
2116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e553e40a.json
13389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72e76bc9b.json
12954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3672355d.json
14837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ef9c777.json
61    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e39881452.json
2778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ca6debf5.json
8619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcd19b26b.json
2630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d4574c90.json
10886    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95855babf.json
8413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7f9eacc9.json
14775    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34221a4f8.json
7669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08b7e05a5.json
13649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f623a979.json
4494    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5962e049.json
6533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4ed1a08e.json
213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c4ba8c4e.json
11144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4835ee5c.json
1425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3cc5de2b.json
13815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
417c109aa.json
3341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31a77d7ba.json
10477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cdc94986.json
10052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e37f91b.json
2097    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dfd5312c.json
4405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
489466e53.json
11371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
564ad520f.json
6749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8a8f95f6.json
306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd6556bc.json
10955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66fcb54d7.json
8883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd123a15d.json
5539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa1c96e93.json
3922    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0b92d7a2.json
5030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1c0405ef.json
9074    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
660dd8ded.json
8474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c943ed53a.json
13505    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bdc6f196.json
9894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba804d3fa.json
3122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faf4322a0.json
4042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23bcfa015.json
13623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1543decd.json
11165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eaee2353.json
13738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c69315120.json
8762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2656874e.json
10082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a7fcc8cd.json
2016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a79e1889c.json
5412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c612e8df.json
5390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c45e47c4c.json
4582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28e86de6d.json
9450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad5692ee7.json
13936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e21227d75.json
2200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc0d4cec3.json
12386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a27f0cc49.json
243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26a1a063b.json
14455    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d06076338.json
1809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd074b8ba.json
10046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f891f500.json
6423    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
110242085.json
3174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55553842f.json
6065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daed4ac40.json
10412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ec6fbb61.json
8175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c79c98af1.json
7845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b52b8d946.json
3567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d010fb743.json
12913    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f38aabf4.json
4909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b5f208fc.json
6630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f15a31a01.json
7947    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f205b0649.json
5dca19c12.json
6147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a64d70c84.json
5087    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e453a294.json
12587    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
791e6dc19.json
6509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91df1b68f.json
8006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c554f052c.json
11146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fe2e44a2.json
3771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65df826e8.json
7961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1a11cf42.json
2962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c178d0f4.json
11219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e267af6d8.json
13388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb33000d9.json
13741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b62d80c49.json
6446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36e7f8d83.json
14986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eda8eecc6.json
5522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e9e910d4.json
10716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4679d01e2.json
7022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0645d6c9.json
9308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5601bd45c.json
2047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff80e84d.json
4529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
818b12621.json
11883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15721ae3c.json
6571    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c45a57747.json
13303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5009ff19c.json
14052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbaa03313.json
3224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e17f6ac56.json
5676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25ef79825.json
9638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4605a3467.json
6431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f64fd2354.json
14164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4abb93bf.json
150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f258665b.json
5821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb567f5cd.json
6354    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f59b246d.json
4156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0b61aedc.json
851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b18e25ae6.json
8928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8eef30bd.json
8160    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c6e35149.json
8299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
106f7b51d.json
10182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e21d09b79.json
1123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8468db069.json
6096    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

3f936cb8a.json
603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8264b581.json
10816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab503c64a.json
2844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
953416879.json
6117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b3dcf712.json
12342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f1a516f4.json
14417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a2f33fec.json
1624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edeab1cc8.json
6916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11a3055b7.json
2107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e809de3b9.json
14145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd38d0da0.json
8778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
306c74aa9.json
1813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2633bc461.json
9866    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08f8df31d.json
7561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b6f894a1.json
4906    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e4ba4429.json
1166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
082b9a2de.json
2878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
681eb7101.json
13471    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecba83b43.json
13999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9951dff79.json
7572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f1d86875.json
4785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b5dbc3cf.json
2879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1531602c.json
13961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d6944a82.json
1161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a89fd1f1e.json
13924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d51c3200.json
2453    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38cf8b2f5.json
5231    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eac9c6b7a.json
11562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8947bf4b9.json
8968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5027f31e5.json
6818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51022a643.json
682    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e470b6bd3.json
4966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ca7983b5.json
2129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
443005b65.json
9608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
303ecdb58.json
867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fba191e3.json
9325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17fb33fc8.json
11141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52820e80e.json
12685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1caa6fcdb.json
6    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2bb56f7a.json
5281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b052d37d.json
3402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc9f9c4c1.json
14265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bfbb098d.json
f96ccddd5.json
1667    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28ec2de89.json
1308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6a3de42f.json
11819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea4cea375.json
14565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8df310c9.json
13115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c10b6035.json
10236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ea1f2c39.json
4471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f43fb067.json
6014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e24a04c10.json
6436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1ecd33ac.json
9571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7125e101b.json
9245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52363327c.json
3690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5074cf806.json
12279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
639fed947.json
2888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a94db6dc4.json
3047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5a71bc27.json
12370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31da37bc0.json
1655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
773243cf2.json
11555    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a651d147.json
8839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec8411943.json
7474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b87c512e.json
618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd9de4e83.json
7162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1c66fa13.json
5844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7efce4735.json
9236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f43738b5.json
14545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea6129e3d.json
2914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f20e24ef.json
14696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f7363767.json
11148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
487531377.json
3740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bfc5658b.json
11517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcefbb974.json
1575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ef9ac2a6.json
14940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aab56f3ff.json
1788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ea58b8ac.json
1476    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
652787a1f.json
9938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe9307848.json
5698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c5bf2766.json
1709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c48a8f2f.json
6481    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40ca5f1a0.json
13858    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c34a5944.json
283ce4b9b.json
2363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75bbaa3fa.json
375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f06cf606d.json
2322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6661be84.json
8960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3a9092a2.json
3616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f1ccbc6f.json
10026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8d831236.json
462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac71c2c1.json
11776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ef67ba31.json
9898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de813940a.json
dad58d0a7.json
12633    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28c005011.json
780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d168f0e6.json
2234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9eb6e75e2.json
13796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76b67f389.json
9422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0677007e.json
13293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0819ac2f6.json
9279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdffad0c0.json
13891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ea9f1228.json
9993    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caa16cc3c.json
13149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3497c1ad0.json
13042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd7ab4e26.json
14361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea3ebc38a.json
14250    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2c4f5f40.json
6661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a8dc3644.json
3601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06db81e31.json
8455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19470706b.json
3695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24ea0569a.json
8664    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

7cdd625cc.json
10570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e94f842c0.json
4713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f3e595eb.json
10441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
171113c99.json
10010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a555d688.json
6680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b628f538.json
7511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de61ca522.json
3060    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ec367f79.json
4737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
078fb1715.json
5840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abe9e2d91.json
2845    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f8f45a35.json
496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a1bd7d28.json
13755    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c7d61133.json
3924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb8193d43.json
11256    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41c83dda8.json
12828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7d595174.json
10627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
916c891aa.json
12580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74b73209e.json
dc2354851.json
3558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
656c5e0ff.json
5800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daa7f33d4.json
14445    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43894825a.json
13364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e1af1787.json
8982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90e582b0c.json
9580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cc2eea7f.json
5356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf0deefda.json
6743    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25ebacf03.json
904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1ed7562f.json
7870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c68bc0253.json
11944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af2b1473.json
281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f40dbc58.json
13202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bdffc917.json
9216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cad1a9f54.json
1140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe3a83fe5.json
1228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ad939a78.json
2369    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77bb4ce3a.json
4594    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a88e6c8f.json
4e1034525.json
2044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be4acc363.json
3302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8e2a9092.json
14024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25fc96414.json
2751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4850786d.json
14249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7983db8d9.json
4307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35b9530a6.json
6401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cf058ab3.json
7824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84ce5f32b.json
13991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39bf24ec8.json
7915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5f20f40f.json
1306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
243f7f43e.json
3900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72896003b.json
6530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58e24d608.json
2755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
199f37bc2.json
1786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae1d9f63a.json
6756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d25e2e3b.json
6094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33aa18b41.json
4508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
105fd5ad7.json
5849    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
890dc359d.json
7937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4cf82def.json
379da0b71.json
7009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b378329b.json
2664    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6aa1281f.json
8030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db77fdb46.json
7111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ab1ff108.json
7196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bc4559f.json
8398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab1777794.json
11692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4298e4c15.json
910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ace26786b.json
8835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79bf5eb37.json
2150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62d822791.json
9928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc0a49f6f.json
9541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa8cdf62e.json
10991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2204729ca.json
10776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81da09ea9.json
382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f629151c.json
11817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c87d70e5.json
348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10a6c97d5.json
461    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f78698cc4.json
5199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a2998a32.json
4257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94fa9ff25.json
991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39e0cc98e.json
8694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e41f018c.json
4917    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5abbde253.json
14029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc8220250.json
1441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb170fd98.json
5575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dd958339.json
1090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44f048354.json
10035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a83683f66.json
4947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe1edf930.json
14882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd8e11d2.json
13945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a085d132.json
1629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bf9dfa21.json
11333    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd8f63c0b.json
10630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7edefab1a.json
8031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f0bb9d58.json
12536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7176bba4.json
11674    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b25ad3ff0.json
2040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
553752e54.json
12473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bb035799.json
5690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b939b40c.json
5581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02fee7295.json
4615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc1ac0d75.json
7836    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3b05e0f0.json
5872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0510cacd0.json
9135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcc316599.json
6898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e33faa32.json
7574    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8edfea832.json
800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70aa95825.json
1409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e69dd7d09.json
8314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
336504b7d.json
13740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffe7f0b70.json
7270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6adb9a9f.json
9235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

310ea711c.json
1365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddd7cc601.json
14302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b5bee232.json
7285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0052dcf47.json
545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37fdaf339.json
5004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bec6db97.json
6413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af317c330.json
5085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01231c438.json
2692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8063090ec.json
2219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c2dfa92d.json
13805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d320b7121.json
9658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a811da408.json
7105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
087804d85.json
9200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87c19915b.json
2520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8140d2734.json
1273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6d2c9972.json
14317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53f3e56a3.json
13356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcdaf8640.json
4243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1811b1412.json
13502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c93e63352.json
12638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e19ee42ce.json
1518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
901ff85c1.json
10469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2016fa08.json
10316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1683f03de.json
7450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e218c632b.json
9133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d33f898e4.json
10333    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da65afb8.json
1535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70ffcfbcb.json
10056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
975d32d75.json
4331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9296eb09d.json
5468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffb9869f.json
6038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba84d40f.json
10980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
694cc5569.json
4170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49f06aa59.json
5019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a927d96ba.json
6408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1169ea6c5.json
9239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7554fc9e.json
4530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89d80665a.json
6130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cb1d59ad.json
4130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
798a0cb05.json
11855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6fd7962e.json
10619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f79b840f.json
13485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7a772967.json
6938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9430d84c5.json
6102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d6b42991.json
3571    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eeb4ea81.json
12068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ac7dad15.json
14326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
632b28a99.json
13841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d53d4bfb.json
12014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
810ae61da.json
11404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd7f07424.json
7644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d3e3a146.json
12619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81a805fda.json
8946    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15f62e911.json
8086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0aa767c04.json
14533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75bd3a017.json
7010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12b47b4e8.json
14097    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b84058aa2.json
5111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2abfa66d6.json
10018    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccd36a0f2.json
5007    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c9e1c82f.json
8886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cfd5f1b5.json
6bd1fee01.json
4a4d8cadb.json
9165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2caa6639a.json
14819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c5f43178.json
3471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bc346340.json
12124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1db8712e.json
3286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f47e7ad3.json
13531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ac66a1c2.json
2749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba29c00b.json
12761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acc327f18.json
12940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b82317efb.json
1027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0f2a1939.json
11008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c40ad026.json
2540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87074d17f.json
918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
110682438.json
9005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f544b558.json
7259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1faffda03.json
9340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40f17b3a1.json
12747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56937e269.json
12469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2630db5dc.json
7383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ada9811e.json
7622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a8503d2f.json
2666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88448bdc5.json
11882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cea0ad08.json
4334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b48460ef7.json
5454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f64d3191.json
3099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52abcc0fe.json
7206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7d9a3d7e.json
6083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1278fe60.json
3221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbcadae16.json
13175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30846007c.json
6092    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b42c0d29.json
13947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9a00b80f.json
1213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83b705aaa.json
13470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c78fa1a45.json
6968    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc52c0c82.json
6545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21c163648.json
1600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
983879402.json
2256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e73b8f98b.json
11222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
477456925.json
13523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

0fa6ba30b.json
9982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
521320b95.json
10564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e9a2fed4.json
14644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cafd9500.json
9033    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70c1e9c61.json
4377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daabe5f9d.json
4703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e985acab0.json
3063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82b43d9cd.json
10254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b932b3915.json
4486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdff3528c.json
9044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f986901c.json
13585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb5eb875a.json
11094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0425756.json
9792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f222ca167.json
2815    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26ceb4ba8.json
9597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cd5d9102.json
6715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50503b223.json
6776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4df43033d.json
311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da1e7c53d.json
12091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6fe4ded3.json
6385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ab616a68.json
4981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ab591301.json
6989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40d430494.json
2781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80a2e14af.json
12501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f72d4b56.json
11368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3141b7931.json
1314    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9223ae4c4.json
1969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37cb01a87.json
8180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
301e16ab9.json
407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c74d479c.json
2868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62ad62e0a.json
8706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
323803a9b.json
10225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6fb16dbb.json
3622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9467b9867.json
5595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c001a0b58.json
4087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98fc3ff8e.json
5527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ae5689d3.json
3043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dbed5324.json
4484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02f89bdcb.json
9875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ea900f4d.json
2589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e92ed29c2.json
1271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df356def7.json
8632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44594e996.json
10688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
165e11d30.json
14126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ef82137f.json
13345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21ae91701.json
1951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67967b0b0.json
8658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50abab539.json
2874    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc7eb8b16.json
11091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b55086b6.json
8150    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85587ad13.json
3202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae2c2b372.json
9730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e052a2a39.json
5425    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a81084ff0.json
1026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eade2f7c.json
11703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abc69ab7f.json
776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
426132585.json
2639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2857efde3.json
5805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
460426eb4.json
1493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fc06cf73.json
8978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2edeb7931.json
2210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
705117847.json
13053    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f43bf90ea.json
8856    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24dfcc985.json
3166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9024c21fc.json
13009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a64a5704.json
13131    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
538a89b59.json
3521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
632a3742c.json
10323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9238eb7fc.json
6472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea72fce5.json
859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c292a8b67.json
13063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e97e4eb52.json
10509    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdb855a69.json
546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c04cf0018.json
1430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98780fbb6.json
13315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42ea4ccd8.json
4823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c960b413e.json
3530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20ef89810.json
13762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
084e4c05b.json
792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fc753430.json
4701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cea713af9.json
9771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41b98eea2.json
1889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eacd0a22.json
7678    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
694b994c8.json
2626    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89cefaa7b.json
6753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4079020a6.json
8598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98782b403.json
13835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93a9cf943.json
7470    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a6f301fa.json
9330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddafef3c4.json
11121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a627ad95.json
ab94fb958.json
13213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ece82128e.json
11275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d37de633e.json
2511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615e51eef.json
7987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2bc9cfc3.json
3749    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acf9a72ca.json
2697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cca005e96.json
5475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

b3ff03304.json
5142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
084b7e7eb.json
11981    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d86df9b0.json
13171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f03ea3fd5.json
5131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cca4ba626.json
8205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b65fd06e2.json
12686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e49c7f19.json
1283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d11e6213.json
11158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fba2f803d.json
9076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
651d63dd7.json
2269    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7611934a0.json
3379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30f92e1ab.json
12013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4370b5ff7.json
3277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
915173d4d.json
412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f40cce5f.json
12297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7133307db.json
8225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf7ee1354.json
3605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c07d6061c.json
5138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cb770ad7.json
9176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
761523328.json
8305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a73c2356.json
6217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
024bc29f1.json
5767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b77b75f2d.json
7399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c17624f8.json
14311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
094c2c3bf.json
5639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ab4214b4.json
11985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
107864aeb.json
14863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc0b0843c.json
10174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f93fe66ef.json
8697    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
986e26eeb.json
9930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15be0f894.json
4185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee3b21a9a.json
6107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3285d041f.json
4651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2334b5d7.json
5143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3975e1bd.json
10658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e77550de.json
2766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edf74226c.json
12453    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97dc6aa32.json
560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80c134db8.json
10198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba7adcbe5.json
1230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db9539604.json
5413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
218f8bb3a.json
3971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1de0bba.json
4843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
979710375.json
12909    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2831bd2b0.json
1850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f68a56b90.json
2418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38fb7c50c.json
14133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65afa2be4.json
2349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd30ea4fa.json
949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44ddc2e22.json
11758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c137b9a4.json
4729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
078bf7e5a.json
3705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
163133ac9.json
13362    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ead547f1b.json
482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16504b328.json
10014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb108730.json
14826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9dc82251.json
598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e3c8edaf.json
8520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ac986fd4.json
9534    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed7754046.json
9548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
846ca7805.json
13146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bba70dd12.json
9558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a3c966a9.json
522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bff5e06f5.json
8312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45b8360a.json
8446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f80c1cf7d.json
9023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
750f8baba.json
14482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e064d3504.json
1687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdb89b424.json
56e91b142.json
4865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c96f8ed3.json
14937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e86a055e3.json
11905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10124968c.json
9306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0788c412.json
11122    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10949ac80.json
8921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fbd06366.json
13666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97c13bdf2.json
6771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04f7eafde.json
2005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f3b3314c.json
11812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35fdb89c9.json
1980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95af010cb.json
11664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf4994e7.json
7412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c55f2f503.json
13075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49c8a0216.json
1665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c565589a8.json
5679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c14f7807.json
14116    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7915144f9.json
13372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
693a90fda.json
3842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56d7f894f.json
3554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e811cd880.json
8320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f53c216e2.json
2389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
728c78b39.json
244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81015c1aa.json
6794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cb79284e.json
13942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97a10da78.json
4855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6878a6fe0.json
11344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d6390b1f.json
3985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80bbb481b.json
3613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07b2296d7.json

11012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1379a575.json
4658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
649930cc8.json
5436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6aceb97f.json
2387    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
380deeb29.json
1842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89dd8e9e9.json
1999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab6c8aca6.json
7685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cb325d19.json
5194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa94cdf93.json
6670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
391da7c7d.json
11748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
485772d7e.json
5205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06afa3c64.json
14757    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17d578acc.json
3876    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22594186e.json
7190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec39cb917.json
11658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0b337200.json
5744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be5fb246e.json
7778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a1283447.json
419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d22192b4.json
14027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1d7bcd8.json
5372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffd506899.json
5153    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d63dfd14.json
2158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd1cd576c.json
14083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cbaa3e59.json
4139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
485cff597.json
de41ebc79.json
1914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30e900b4a.json
1461    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
151481179.json
14198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c996b2baf.json
11828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66c28f55b.json
2875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72e9e5442.json
7421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d76134f00.json
10975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5546a54ef.json
14161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef50eab33.json
5734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cccc67d4.json
3179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7c443855.json
9917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
903523a17.json
9504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
796382bf4.json
1091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62b2ac9fd.json
853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8019d0c63.json
14162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cc7f24f2.json
3423    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d0b85658.json
10961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d229effbf.json
11923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bddf43d72.json
6048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0db02527a.json
4396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17cbebba6.json
3604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1945e2783.json
8809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cb5e1b06.json
6097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
190eba3c6.json
1121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b02f2fafa.json
11900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abaf6c9ee.json
4596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dc92008d.json
13746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b41cb9e51.json
4711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58bfbd845.json
10857    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f98b9d62a.json
3156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42eac4984.json
4360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64cf73826.json
12326    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6097a5c1d.json
14923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d6847fba.json
1983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a140a67e.json
5584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bff9728d.json
665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2d48985e.json
5530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2117b204.json
11694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc32a88f1.json
4220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d85a78cf9.json
8171    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d43335198.json
13334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
469bd2504.json
11760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c2fdb3cd.json
6510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3b94defa.json
8879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02eb29707.json
7762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4e5ea1d2.json
422    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a61da96ad.json
12274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87615b2c6.json
5311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eda2151fa.json
5262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8b702182.json
333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
878e36da4.json
466    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75b13bc88.json
14460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2056e185.json
1198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4ae0ba7a.json
4728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
325a6a746.json
1654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75fa09239.json
12720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f026fa4b5.json
12262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89a6620e3.json
6627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
858f4c013.json
3041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d98e5623.json
8126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89523a695.json
209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b60bc872a.json
11616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
143a52d8b.json
5261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff2c63c4.json
7434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8415aff49.json
897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b59f9f38.json
7039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc56ff89a.json
549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5113edf84.json
14054    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d1030b42.json
4540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f60db1f7.json
633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e95d902dc.json
9679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8be13bdf.json
8336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63057be1d.json
8683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db03ddc32.json
1335    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eebee574e.json
13630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a6a9aace.json
6888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b98316a91.json
8177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
322244807.json
7336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0193b572.json
14418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f1c0947d.json
9072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fcdfb0e1.json

1436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
685b2cbe4.json
4575    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
109c4f5a8.json
332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d572bc20.json
13944    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4501c8125.json
10932    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f2c9671d.json
10503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c128e02a.json
10071    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b80b51bda.json
962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c674cc1f.json
10358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffa9e326.json
8925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c40052aba.json
8843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1498a5e81.json
13267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15df9cd46.json
3317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9e2b26c4.json
13809    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4359d65e7.json
9623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fb24b53d.json
4887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
002278114.json
6760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0008c5398.json
3057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb9eb954c.json
4641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78c3c7f21.json
2966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff16e6dad.json
8900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81c4d25d6.json
12133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ad448a42.json
13501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8606e8738.json
2354    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca8306c33.json
14247    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e76929e2b.json
6397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
687e9c33c.json
157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7554df6d.json
9493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52a23ae9d.json
12808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e585b064b.json
7406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d0aedfb3.json
14288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74f391caa.json
2649    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea383096f.json
2608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b6022baa.json
14669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62eac41fa.json
9474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87f9ef7a5.json
7509    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2e7a93fe.json
7006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1c83d13b.json
8019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
736b228b9.json
10095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8abd212c6.json
3023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b1151deb.json
11066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3d4585c2.json
1669    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb0b26ff.json
6206    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
410490c8d.json
11281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87ef4d3ca.json
10565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51572cdd3.json
5823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
220d4394a.json
6955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
162e703e6.json
10677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ef7f0012.json
3592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5742d498f.json
3821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
605f9cd41.json
3463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9364a529.json
10566    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a1715a97.json
2920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10d83c05d.json
8950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9baf0d577.json
3824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48d1bb550.json
10399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72c9986ac.json
3541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbbeb3ab0.json
13775    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf456451e.json
4142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd7ad37e7.json
497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
571ce0202.json
13616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
603d1d51c.json
14807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146005aa0.json
3811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cad25c91b.json
11733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba03a4c5.json
12541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08438c720.json
6634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8520800b1.json
495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
850a43f90.json
4    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55a754f92.json
7141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b8924342.json
653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfa8ac290.json
844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74b7d275a.json
12946    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a66f74ff.json
10659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ee9c210.json
13662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ced67d36.json
974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
275ce4c9b.json
7769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b74c47541.json
10731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb0309848.json
970    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5aefb7197.json
9398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7185ffc1.json
2348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f160ae385.json
9334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcffea7c0.json
9907    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d471c1ff7.json
6363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e3c58de2.json
9251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e6e9b877.json
2122    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5cf352b2.json
2907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6648175ff.json
6885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d11f10b1.json
2288    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59f4e3255.json
8984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9d24314b.json
5236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
175f4a910.json
4538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c4089e4f.json
8117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d56674978.json
3556    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb8efea32.json
1178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4deffd71.json
2029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
915c4ba66.json
13342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1069c72a9.json
8614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aa74d2d2.json
7786    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1be1868fd.json
5626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
756d92515.json
2627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d59f3a6cc.json
3307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79531026f.json
7983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e80386a28.json
1004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89af60ff3.json
852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207ad2902.json
8556    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dd6ea6bb.json
9105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a1609dd4.json
5435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69a1c3147.json
2211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b641cecaf.json
13697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e89b02af3.json
4908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc7b17cd5.json
11798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e53933782.json
11799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f0c30d12.json
12145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d6208f11.json
1997    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0497f7012.json
6355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2512e37a.json
6960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0af685a60.json
6608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b48aa9d4a.json
7112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cbe873e7.json
8932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ff23c65c.json
5511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69f986aaf.json
13982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b36616178.json
140    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd4404a60.json
10184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32f97388e.json
2242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

ddc94666d.json
10666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e4cf50f4.json
2569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9307b1ee.json
6856    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e1b8bb74.json
14072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b29b45d9.json
11801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb30d51aa.json
12751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5955c1678.json
8871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26b70a13a.json
3148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d1b799e7.json
4668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44175f75c.json
3331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d60dbdd7a.json
14240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb4c66e7a.json
6659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
353187b3d.json
12332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37b2e740.json
4870    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da7c5b19f.json
3323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bbadc050.json
4516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
121af879a.json
8977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3de6bc035.json
1175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee8bf2efb.json
11022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
921817343.json
3999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7dc2efde.json
678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c251767cf.json
2333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14e52bdaf.json
3585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
316756c4e.json
13916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f66047cfa.json
5875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfaca902b.json
11244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f1d071a8.json
8242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
083f50328.json
9418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f845bd0c0.json
6308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f1136ad3.json
7901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
007ffeccd.json
3893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52e6abd35.json
1639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b47536db5.json
13156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d88536fc.json
3489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
967ee6c2e.json
10600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a34ddc8b.json
146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db33da35e.json
2039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
111748c15.json
12542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49d4a0adf.json
8097    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
495ce6c73.json
6572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb90447e5.json
9130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19fd91f5b.json
2842    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1dd64fa6.json
4687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea7548f0.json
8537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23d2b8824.json
548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
923a58e31.json
8345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
181fb7dae.json
747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f7bfcb68.json
4258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e65d72c2.json
3025    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015c353ce.json
7211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba021efa9.json
12035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e3e0ffde.json
9213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29b60faaa.json
4838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50fe7d515.json
2715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ac1e8eb6.json
4864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09a024035.json
14921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d5e5ad20.json
12650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccf24ab8f.json
11120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dff412d60.json
10224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b04a0dd9e.json
11280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8dc8fa13.json
951352bea.json
2500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a4db4d32.json
67    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35c0c3aca.json
126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6be53d844.json
7348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
beea1e1dd.json
12539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c27c5a029.json
14938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
348a982e2.json
13533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad002785c.json
4761    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e991c023.json
7956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0d9596e3.json
4885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53abff075.json
2940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9193c38af.json
3469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52d0469f8.json
10205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9c54752f.json
637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8efa040f.json
8896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fb9fc3d1.json
5452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
611c6421b.json
6757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb5ef5522.json
4352    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce2319154.json
3031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a678a4342.json
11702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1adb292f6.json
8567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea1736eec.json
1595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3890935ed.json
5400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e830259ca.json
14568    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b42f2e5.json
763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ba86cc6.json
9915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99859bab7.json
9903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
917ca93b3.json
14090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fef6df98c.json
6834    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ca247f84.json
14965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88a264f0d.json
3256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
270bd311c.json
5861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b74f813f.json
8010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7195edba.json
8829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a108fa61.json
8173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e77d52ad.json
4733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a30803552.json
6456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e62224eeb.json
14483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa91c3400.json
10000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80de23d7a.json
3430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06f523361.json
581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6774f84e3.json
13190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c0eb7188.json
13386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd32ce3ef.json
378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b34a4f038.json
8891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c573a0ce7.json
9281    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400cbe759.json
953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
060e4ed30.json
8538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d24fab68.json
11439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae3c2cb86.json
13271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23e36bfd9.json
9297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ca7a1543.json
7929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
128293a4d.json
13064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cca1ec6df.json
3611    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd7ae9b79.json
8587    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7d2d752f.json
13191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72bb30805.json
14709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0691034ac.json
4932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f86b59db0.json
4939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c17de5f6.json
5418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e899d33d5.json
5077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fed3c719a.json
5328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62c16fa1a.json
11603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2b705117.json
9328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92ee6241d.json
5421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e30bac76c.json

14175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53cd20574.json
7318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1e58cd50.json
7974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4445fb72d.json
14627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2fb45c15.json
7157    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b666036a.json
10451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0322013c.json
13324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
228e88a51.json
7790    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76dae2b3e.json
10990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a6ba0a40.json
6145    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8071fcc9c.json
4128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19a36eaab.json
11696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
427acc248.json
6796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61dc8345a.json
1324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d62c55d90.json
2741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d63321570.json
2185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d50a1665e.json
2227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b45ae85f.json
8439    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcfd80e17.json
10356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de59f42db.json
6521    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf8250644.json
4419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
992d82305.json
5609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44598cf69.json
12852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d13aab91.json
7528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eda903960.json
11213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73717bc4f.json
5594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39ec77c60.json
5126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05d3e4d55.json
3872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e797dcdd.json
73    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4595acb4d.json
6847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f14086e70.json
13232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56ae25223.json
4620    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e711ed8d.json
14780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91f87fa27.json
12045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd248bb10.json
945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cbbe5cd9.json
9791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f03a41229.json
13986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa1cf9c0c.json
5044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e441b406.json
12801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
763264fa2.json
11518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1877d9a0d.json
3004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ffe668f9.json
467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70a33ed88.json
14695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f9bfa4d9.json
2793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a0499255.json
5910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a12ecdfc.json
14602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c3b8c99c.json
6140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400b56d39.json
6357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f432329f.json
10957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5893f7a9e.json
9983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16f74099a.json
7305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f58143fd5.json
5730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1da4026cd.json
14117    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45a283ed6.json
6870    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
452a50855.json
7320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4bc5b7ca.json
2905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db095d92a.json
6950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25bdd7d90.json
7218    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e3a1f99b.json
2139    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63afbf2f2.json
10395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24573b56d.json
13339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab385bfae.json
2004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cebbeec1.json
3357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77d38bd16.json
12851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e13d34d6.json
6649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0820696a3.json
14071    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dafa3b086.json
12304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4f161ae.json
3686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf6b6627.json
9121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e76c15d3.json
10996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1d936001.json
13559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b89f5335.json
13383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e172ab13.json
12516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67f174628.json
3125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d72113d5.json
2465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
427343625.json
4162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be3508ce5.json
4576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d48e16ef4.json
9280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26fb642bb.json
5486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12653b9bc.json
9817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaf7d5da8.json
13541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f22ff0f64.json
13661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c763f19ef.json
9669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
061f6b476.json
13437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45beac10.json
2205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5ea737ec.json
13129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db71b8b85.json
14804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d672df50c.json
11359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ace8a42bd.json
2889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d9cdfbde.json
2726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a15d8c8a8.json
379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d930f411f.json
8906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
405b63ca5.json
3930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7a28b4f4.json
1824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9000f2766.json
8734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b488dc067.json
14334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
062633cb1.json
14440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
969634296.json

9654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec2c40301.json
5233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6684c4b7.json
4081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ef2ebef.json
14243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f780d04ae.json
2794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cccd16111.json
14606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
809ca8efd.json
8295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf74891fd.json
12246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d0e2bebf.json
11515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
406528ab5.json
12039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03e5bf50b.json
2873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7351540f.json
9113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c64363af.json
13750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0574c31a.json
5050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88ac92eed.json
1033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b991a694f.json
12232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8edd5d505.json
5175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16e922149.json
7581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cf37c7e2.json
4550    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f519310b.json
8362    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4813a0d67.json
12621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef2ee6e9b.json
8200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad160afc4.json
3050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dada5ac5.json
4083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36681d1d5.json
7932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54c2d49bb.json
1000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b8ea11de.json
10501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80cedf6b9.json
7743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0137d4e3.json
7982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35fc0fd89.json
13068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc14a0fb9.json
6056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72d68bbd0.json
7771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1565d09ad.json
4672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f4d6a956.json
14564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18f9fe19c.json
3294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
880d3c594.json
13135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef4df30d.json
8774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4b2dcfb6.json
12830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db45d8505.json
7007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69a7461c2.json
2120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd7c3baa.json
8873    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b4dd9fb3.json
13836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bded2690b.json
9246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b1391dda.json
6946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8102d6dc7.json
2275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fc55b842.json
9319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f860b014.json
5833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a030b8f0.json
12051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28b64c198.json
223    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dfd484a6.json
12863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3d10f7cc.json
1770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4aa44d3c9.json
5466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b980624e.json
1005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d09a7dda3.json
10368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0858dfca.json
9554    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2def67952.json
12797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0ca6dd73.json
650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07ee26c3c.json
12952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc96276a7.json
12665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd89328a8.json
7670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a849a445.json
5270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba433a9d3.json
3066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66b978701.json
1761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c05adb8fe.json
8748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acada131d.json
7656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d460fe7a.json
8361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5933da514.json
6384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fe419dc3.json
14772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
406a1e534.json
630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91fca388a.json
13253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f86f15c15.json
3178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e4ac998c.json
6782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcc2ea490.json
10576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b63d76ef4.json
984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5965cea5.json
7309    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e67f7787d.json
10128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72519f841.json
13229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f069c7c28.json
3692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6b229568.json
12283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2fae31e8.json
3710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5757bc3f.json
4240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
156da1714.json
12419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
576f4893f.json
12992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa1add776.json
10453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7cecd5d2.json
13363    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc948a166.json
12066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d20a375dd.json
10778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb5597fb1.json
1073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dde3750a1.json
9271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5d1a1271.json
4129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66bd449fc.json
10203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb102e06d.json
3582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a7835503.json
11398    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae52ea5c4.json
14373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
158bc6f24.json
6491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f1580039.json
6177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb307f308.json
5457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cc6c4102.json
4106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46cf6356e.json
6265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
777f82721.json
11196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4407e70f3.json

108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d8ff1b29.json
6917    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
182aa4a29.json
5675    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ea00c9fd.json
3975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c559dedd.json
4167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2f8980cd.json
8011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f97c8edc4.json
6981    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
310045474.json
12022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d68357af5.json
4985    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
487bbfb6d.json
3898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac809f1ba.json
2457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe38b7b23.json
2515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d83dd7fc2.json
4007    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a8215249.json
7964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
840538f14.json
4132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef5b1310.json
9039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2868f9f3f.json
3883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d473d632a.json
1459    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbdf8c03a.json
10454    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48432dfa0.json
9065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6278a50c.json
6925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f980544af.json
4656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c17e1f32.json
395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
656246ceb.json
10075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
553b720c2.json
3693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b460a9761.json
14087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
870d3b2aa.json
3970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb675d874.json
2384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd308e46b.json
94    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da56f7030.json
1576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98c17f102.json
1143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e99eda1f6.json
8098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fe9fc6d9.json
10690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d307ce9.json
8207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d526090e.json
1046    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1769f482.json
6584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c753c9bd8.json
14758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48c9474d9.json
9161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23adab0a9.json
7034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2716e1e5.json
13423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
169fc07e1.json
12115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02c39fd73.json
10681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebdf19959.json
13844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b968b85c1.json
9789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac9feb346.json
14086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab13611c9.json
11467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0b98e001.json
3197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee459f62d.json
13450    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
652ad7684.json
6416    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0286dd665.json
11993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad70b1120.json
8372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
392df6910.json
2700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02868b720.json
8383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3101ea018.json
2036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c3d7804c.json
4578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc710f1e8.json
7417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9c023b3e.json
4949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58ee93558.json
12214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22e9d72ce.json
13595    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0885aa00.json
817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af843bbce.json
5516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eef094950.json
5365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be4275440.json
7925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f662bdf71.json
8272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e90e0ffae.json
10403    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c93c0faa3.json
805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73e1b299a.json
7143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0b2787f5.json
2066    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a76a6cf3.json
5209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74e316be1.json
218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04e829d49.json
1427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2ee6f2da.json
5736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
066498aa1.json
4487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d181b3c6.json
722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ac4dd8c2.json
141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1e8c0afc.json
12456    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e40368c38.json
11999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5d95d72.json
12787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e463e29e.json
5387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a878a916e.json
5870    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474bccd75.json
149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60d72fc85.json
8201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dd91ba4d.json
7798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e373923e.json
1561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a31d17c7.json
4898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c0f6076a.json
7114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24dbfaf39.json
10974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8727d356.json
10335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6256e92e.json
2587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90a967a14.json
1087    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13fcf57ff.json
12482    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33a51709e.json
13300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cca88204d.json
14983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad786540e.json
2646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ae4fc251.json
7351    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fd7b7583.json
596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd331b74e.json
13427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05bbc9111.json
13995    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8d3b2e51.json
11737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea5bf906.json
5644    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

90bfb8cb2.json
10829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14ae60869.json
866    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
792e8c192.json
11187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
306989556.json
6144    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8fceeb86.json
850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
768fb166d.json
11930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
536af3840.json
2653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fccff52b.json
14744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a674a0bd7.json
14298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9795ce5b0.json
14416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ddfaab43.json
7661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c220b4764.json
7138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b6c04393.json
2768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43cd2eb4e.json
7954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24fd7c8d8.json
2431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcb911968.json
4278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc94a986f.json
5952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c1be8f0.json
5331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a63c59c80.json
7051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5261f14.json
9873    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
129df65b1.json
508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb4dde79e.json
11949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8106b5f6f.json
5001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77544cbd4.json
10988    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
716167b76.json
9652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6335223e.json
12267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9afc068ae.json
9556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94ae813d8.json
4241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
814c9043a.json
9014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1f1a42bf.json
5388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b9f04df5.json
9612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6691251b.json
14751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96e9f6fd8.json
4662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
690de80b5.json
10555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60786724b.json
13626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7901e98d.json
818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
791f6c077.json
8514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a13ed5e9d.json
325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e3631a29.json
14880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0594ed847.json
9393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81af50144.json
7908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
238c76ea1.json
1864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acf573d1c.json
12107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ea7eaf00.json
6660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef0bf320.json
6666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
134b82d89.json
8454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
004709939.json
10472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47a142b50.json
5353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c55e596d.json
9501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ee623346.json
5323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d76c16ab.json
12255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eded59b25.json
13850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa4314902.json
10462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7964fc4ad.json
2050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eec2fedc.json
11494    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d38ce48c2.json
4210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0aaf6976a.json
159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
046dcb8fb.json
9767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29f2fd4c6.json
8441    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38fd4509d.json
5577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1da8c2de.json
9924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b574af70f.json
4570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
620796ee7.json
7325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b3deeb66.json
7066    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71e5aca0a.json
1923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cfee2fbe.json
1711    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a01a10c4b.json
1854    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16852e32.json
3684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b421d0d48.json
1330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c70ffd9c5.json
6862    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9551ed6d.json
4432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc996a1a4.json
7916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4bc92fc6.json
12918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cbae8539.json
8432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a809464ca.json
13611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8e4a881b.json
7097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5569b346f.json
6246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4525391a7.json
2471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cf8487d4.json
8805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2b2da9dd.json
3419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97aa9eeac.json
7    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cccbf8c47.json
5079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68a4cd579.json
3061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7cc44152.json
8655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cb9d0599.json
2965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a9465eee.json
2613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfb0b0928.json
5232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
338d441f4.json
7825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e932a94c6.json
3169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfa54aa27.json
3074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
993113176.json
14374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ddf00d90.json
4520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8054aad26.json
2053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8a94961e.json
2814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcee746ce.json
14945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c22078c20.json
2943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
936e8cc95.json
4255    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6846c8340.json
12845    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
346c5abcd.json
12736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5b97062a.json
6439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0880d7f1e.json
7972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
defc7be05.json
864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59b66be84.json
2383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a54d4e92.json
338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
991b35363.json
2420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9495fed48.json
11941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a669b77aa.json
11956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4d945501.json
12438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20559d623.json
472    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41e4cc1de.json
10117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0f3a1cb4.json
11082    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f5d6ee4f.json
5063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fd68ca16.json
7189    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9427a0125.json
8174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6f4d14a0.json
8307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfae2101c.json
11647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
084874570.json
399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aec4488c.json
10337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae116d640.json
3278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8e7caaff.json
14526    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07e427e0c.json
7907    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf927db8.json
5722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f95680d84.json
3880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cade4f9b9.json
13512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cc02d983.json
11044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74a9b9a9e.json

10522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40b53f6c2.json
1181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79669f807.json
280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99e9a454d.json
5407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0f8b280d.json
13030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
578880eb3.json
6052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9ae7d12.json
5921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d7c78428.json
2505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53b996932.json
10197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edfe1377f.json
7957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21c8d5f0e.json
6673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acca0b2ed.json
4200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b70d0abec.json
3193    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fa39858f.json
4061    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2ac99dfe.json
12305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146cd69b3.json
13373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73d28220c.json
12957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d441a71b.json
12311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9795221d0.json
14459    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb4dbddea.json
11482    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2a23ac85.json
963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d0b0238c.json
5793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aee1ad5e4.json
10508    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6171ee98.json
14112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207aa47a6.json
3584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efc478e64.json
4226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eddd81378.json
3181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f527634f7.json
6811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a9fa9d9e.json
7903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5489e2b50.json
6399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b9c38ed2.json
12393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
023979a33.json
9225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84998166f.json
9729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c61869b9b.json
7478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
662011890.json
2881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3796a0068.json
8405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f07e35bb8.json
4584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc5058e64.json
8728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5cb75a44.json
12593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35c9336dc.json
9095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebbf04d10.json
716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7f58a6e4.json
3194    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cb5381cb.json
303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82aa52460.json
328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
555e742f9.json
10639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc261e309.json
5037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
458e8f61c.json
95e206d02.json
1963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355048bb7.json
10662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f29cacb97.json
5989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68e46ed0e.json
14528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b83e15288.json
7830    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91328d9f8.json
5058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd8e62b81.json
3576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71297d780.json
14591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8310e47df.json
10877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47d68f63c.json
13054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a87f5839e.json
14796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c8a8385e.json
9757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
519bc8382.json
7374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a118d66aa.json
12766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f03979157.json
1053    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4263cc9ed.json
12427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46b2782d5.json
3026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8722dfeed.json
5476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3622c0bcf.json
1455    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7efb36b65.json
8500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5f576bb1.json
10519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d16c37008.json
13918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ca147dd8.json
11792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed9d88a61.json
2772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
861af7cd5.json
5957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51c99e8fb.json
1405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
460edc419.json
2308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a36bdba5.json
6346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6dba1642.json
6951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd3fb8531.json
3511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bef935312.json
2337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d43edbe9.json
4070    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
848338a56.json
7052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac1629362.json
10660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
523f4a05e.json
3363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee65ac339.json
3288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fda733a81.json
11833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91acbbf47.json
9484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2c365994.json
11976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b6add800.json
4533    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42444811d.json
1645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8528b3d49.json
4862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5876df456.json
11466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff618d36f.json
13231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed84380a5.json
6507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53976b229.json
212    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3422e4906.json
2    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f44a6cdaf.json
2046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2f718e94.json
11394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
581ce1910.json

7177    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7b67fd7f.json
3614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af2f3a166.json
8318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebd3ef2f9.json
5052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
074042a24.json
1772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67d786538.json
12596    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
546a913cc.json
7392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10fbc9548.json
12655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93c16b08b.json
13614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53b89efb9.json
13565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d7c5b6f6.json
7360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b269c6aa.json
3014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29bf0cb2c.json
1236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80ec7f00d.json
9109    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70900313d.json
13678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe86005a1.json
12087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f29e9d88.json
14879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9c968c38.json
11246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d94f0378.json
13295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03a694927.json
6918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
165e76ebb.json
10562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e517961.json
7174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d7b61eb5.json
13476    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff8e4c708.json
13690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c6fe4100.json
34    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e01638894.json
5147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdab9b66a.json
951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
457bdfb16.json
2788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63562f208.json
9294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f26f1acb2.json
11751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24787403d.json
5706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
636389c7d.json
4970    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26d17afbd.json
10494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2101b7d1.json
13222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
511b245a5.json
14436    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2198e9c3.json
13490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c32ecd5bf.json
7935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f61cb2ecd.json
4483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10e26690b.json
14413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c9f111f1.json
329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65180c32a.json
5958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bcdd9bef.json
1473    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd469a42f.json
8561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d6696a32.json
8054    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb492add6.json
7240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6593bd2a2.json
1248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f51f68a13.json
11100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d181ce519.json
6260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44ab64cad.json
9394    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2cd8b4ae.json
14257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d4bdde4c.json
1207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a437cc78c.json
3336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
454607f26.json
12455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e62c62127.json
10332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d0a5c20a.json
14800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45bf47f58.json
1120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa18941f4.json
6820    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b247a426a.json
6810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
183eb3fe5.json
1446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
682cbe0f9.json
6471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3679001f5.json
14748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2a6b4117.json
2548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9510b7eba.json
11560    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85ca390a0.json
1301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d768c4324.json
7324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23056b4b6.json
13280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be467e42b.json
10514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2d6ff297.json
6028    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20845a37b.json
7927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8885f346b.json
554    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffd61a488.json
3289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88b60278f.json
12281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f665c704.json
14146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79ad78fc4.json
4834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c89ffa58.json
b4bf9e247.json
11212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3cef1c4b.json
2921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
699a81c51.json
4233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ad400ba0.json
4496    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b9b65bde.json
7423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77fa5cdd7.json
667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400eaa6d5.json
4373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc32f63d1.json
1776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4792b6d06.json
6311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a06b5eb73.json
2636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b53610ea.json
11895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b06c1ad30.json
2740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0306e85dd.json
10089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
672cc8af8.json
9699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
277210bb9.json
9373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01b3356f5.json
4014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc6d86a40.json
7759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29eda0717.json
10602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c491ec026.json
10013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f4cf8745.json
8352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46dea66ea.json
478    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4683d863b.json
737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0edff1e1.json
14853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bb09fefb.json
12207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c3a2c536.json
7686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
189637f90.json
7485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b05d0484f.json
14227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f2b619bb.json
2786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0545b660.json
4604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bfb6a77f.json
3143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
583d4b36c.json
10435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5452fea14.json
10795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2816bd92.json
6905    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
655cbd9ad.json
5944    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

cb278aa01.json
2487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fee5e43b2.json
12201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e31e27ce7.json
9538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2fe3684a.json
3003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bea097f1.json
12147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29ac4357e.json
6692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e0f474bc.json
8753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f0219fd7.json
2014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ec9364a7.json
11310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a9be9456.json
4739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b8f1e583.json
9159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ef15a1c6.json
3483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60f9fee55.json
4674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5682330ad.json
3506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
884b9a6ec.json
7720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b15103b97.json
10770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f792e0ff5.json
10633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbfb1869f.json
6969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21db2af7c.json
9872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
742dcad55.json
10652    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b181fa99a.json
5053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a01ffaa7.json
5487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7218c8328.json
6447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39f1d116e.json
14128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6786609aa.json
9447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3e1f5f86.json
3249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19efe1616.json
14534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0308c9eda.json
10030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e827bee5e.json
6201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45bec784b.json
2007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97dc40c6f.json
5122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13bbf723c.json
1626    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36cc00cf3.json
662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e9eec98f.json
6738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
596cf7334.json
6996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c736e9c1.json
9683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e8daf8fd.json
1982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
423c5b45f.json
12745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c551fd9b.json
2079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
935098bbf.json
11790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea7ef6aee.json
13224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6c59bc1e.json
13754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8facdc86a.json
11253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20f05426f.json
9830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04eda1e46.json
10682    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b6b350c8.json
10901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbf20c4b0.json
3527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf68421ff.json
14020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
251e884b7.json
3881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc20a0cea.json
1243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b67261194.json
5179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41c163f8a.json
8434    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2816bdff.json
3251    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94f353c2f.json
7209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03c323fcf.json
4117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8564fa7be.json
9025    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf9de0a6.json
12303    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c5b71bf0.json
13360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6b0179fb.json
7504    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e276617a4.json
11242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93e53882d.json
9660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9edf8fff1.json
11752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18286db6a.json
14021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7a39d71.json
1345    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3411347b.json
1622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7dda91fe.json
7430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea3fe3286.json
11917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14dcf6ec8.json
10854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f4ebd382.json
11827    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45851036.json
1634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d150e90c.json
14352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
339a623c4.json
2022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6709f43e8.json
3549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f85e69ee.json
207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adff46aad.json
1789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab8a8e5c9.json
4489    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0c1d6b64.json
13143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b84922ac.json
12644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6967987d5.json
5884    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4009f9200.json
2045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d560b8003.json
11346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b342437c5.json
10828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcc58b6ba.json
3373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ff11cef6.json
2273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78b51f6a0.json
7831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c161afd26.json
1773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64c6eb71c.json
2405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
038d06218.json
14516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd62c76f.json
2798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b1009a30.json
3106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60b188249.json
484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c69842c2a.json
592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
357707ba7.json
13211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2dbc61fd.json
9362    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92fae4396.json
2523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9a2f1a7e.json
12559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a20d1e637.json
6352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8664fb93.json
7994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82ea3883e.json
7718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
437b06047.json
4706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e55bed12.json
2145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd1e7ec9d.json
4381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9493ee8ee.json
5489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb9e12e8.json
12286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2c120250.json
1480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11a337bfa.json
7358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b4bb9973.json
6118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df39a5468.json
464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07227963b.json
12181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
747c82f83.json

171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
812240d28.json
4671    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6c338f94.json
4744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05fb5b403.json
11615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea39ef3ae.json
4572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5181f9924.json
9497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a4d9f6e1.json
7969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71a614388.json
4119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e8080bbe.json
11810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e67cffa8b.json
11080    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8db25430.json
6415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae7f59170.json
7785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80bf7a371.json
5119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25d4c7493.json
6340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75ca78a5a.json
10154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fc9d6c1a.json
14070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e0d65b3e.json
145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b6064845.json
3700    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86d87d5f7.json
4120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2b656028.json
591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
815f4cc08.json
83    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8eab07081.json
6361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf162bb42.json
4894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d30c88c64.json
6787    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4e9f53c9.json
13421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4501e7e4f.json
2536    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa253c6e7.json
14060    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e4f81782.json
876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90f1bb168.json
4934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e73038b62.json
655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a65ec6d03.json
11523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b9d93d4.json
10215    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c90558513.json
1534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00904fc2c.json
6047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1696155ce.json
1481    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ac1366f4.json
2222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f69bd4b27.json
4891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59a3ee7ff.json
5334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
774289137.json
12409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff96988fc.json
1276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47008c34b.json
13670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87ec8e435.json
4207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a567392e.json
2360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9945962c3.json
10661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2dccbe51.json
8366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d930d08c.json
2980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd2ad0f9d.json
4428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0fe34d97.json
625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d46a58371.json
4041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39ef18e70.json
10278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c4afcc03.json
8568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b40a8ff86.json
12578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70112a1b9.json
4552    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a11245368.json
12632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e98e609ac.json
13240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80621df6b.json
3674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dff88b6f.json
9997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc49be2a.json
12704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9f58834b.json
8944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89a5e9a9d.json
9962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bec8eb5e.json
6035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a0a8eec0.json
11526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a640f7cf6.json
7531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c97d1670.json
2759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b256f479c.json
13065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f38033e1.json
12275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deac22864.json
3683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d011c364.json
5822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14e788800.json
5983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
300337abe.json
1086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3099254c2.json
7674    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5925cf3fa.json
10577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbe1d6739.json
6005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd8e75d3.json
10080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca5a9ff9c.json
8702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bacce548.json
7846    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cab545282.json
7323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e5d4e317.json
13801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a63a0ac25.json
2159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99ab7c701.json
3657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a2cadc09.json
5604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cc36a057.json
14409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c131db77.json
56    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37e15671b.json
3829    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa21ddfa3.json
4745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fff24fcb5.json
534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5a7a1ef.json
9187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a97467fb6.json
5615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
773d10217.json
8268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6518a598b.json
11488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35b1c5db4.json
13205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f810c2cae.json
13965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52dae90aa.json
9253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
937c2e14f.json
9e758c0b0.json
10029    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bef75882.json
275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4daad230c.json
10727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2c9be724.json
4062    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fab4e65f.json
13927    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f09d025a9.json
7520    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9bb7253.json
10549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1db71d88.json
8154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
737413132.json
14226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64dbb2214.json
9774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39c02e302.json
3254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01ce66bd5.json
3071    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7282183b.json
8570    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f1105e2a.json
10965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dc40f9b5.json
9566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b3c81931.json

9689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a0ec4977.json
2254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aefafcc66.json
1117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b0b80ef6.json
4753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0b3f2081.json
11465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f64329201.json
5608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
203e2bd3c.json
601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6eb71dc0.json
6277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b2d9c8f5.json
4769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
086ed2122.json
11829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70c88aab8.json
3706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
497d68d48.json
6941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3aa13a0b0.json
12754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9801a0f9c.json
5349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75a803430.json
10796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21c3157e8.json
12983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a54a03db.json
7382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a68361fdb.json
6105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4194f0f66.json
2506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b11103508.json
13730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d39684633.json
6585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
272a3fb52.json
2887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f2d1ff6c.json
14551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab821872c.json
4001    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2ec1becc.json
13034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa741b626.json
11864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
074d26284.json
10069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df03e957d.json
14376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6945dbebb.json
7245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c29e8689.json
12390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dfc9cc69.json
4754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13eafff41.json
4262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3b4f29f8.json
2249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
184ea777b.json
480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5d1b9bf9.json
2644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22cc0413.json
12247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce0e8f18f.json
14331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9981e5f29.json
5602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
707b0c535.json
8057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4b1b7afe.json
13980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133a0db2c.json
1029    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adc03f8b6.json
7944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a90161422.json
10993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f7ef9681.json
5145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
634aa14a6.json
6020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4195e3052.json
7985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22e1f3438.json
11578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89c980093.json
10396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3002577b8.json
6935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8ba4dfa1.json
10247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a63364c39.json
11922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc068a979.json
4020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38e87cee8.json
11972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37438ea50.json
1451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85a12f70c.json
13376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c8ae4c7e.json
179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c9cd051a.json
14728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
115d6458f.json
11214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
527b6112b.json
11239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2898238f2.json
12485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
108da3f0d.json
2499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ffbe0538.json
4527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
442f853b2.json
6654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26161bad4.json
5016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff5e30380.json
5426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3c6b71c8.json
14169    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa156faf0.json
10746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8111f6d4a.json
12566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52238d3bf.json
1127    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f095385ff.json
8287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10f4c8d8c.json
10567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b28acaaeb.json
9411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abea0e83e.json
10655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90dd998e2.json
6578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb79f1cfa.json
13044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f32c880e.json
7803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b6d08cba.json
118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfefbcea0.json
9444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
125522846.json
1326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6268d4d68.json
1893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84222fa53.json
7617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6416e28a.json
12487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5457a593a.json
2792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a85a1c8c3.json
132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56f7b3216.json
11709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b279ec774.json
696    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec14446ba.json
13915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d898de7ff.json
3555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b85cdc8a5.json
2739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54ab4b5d2.json
14513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59c3497c1.json
5347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8d14470d.json
111be067f.json
4967    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
152d25978.json
8952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1925aff9d.json
6833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f08e9c5f.json
13909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

920a44cbb.json
9172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78c217b2a.json
1070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
beb93c6ab.json
4364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2716a01b4.json
9389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36f7fbe5a.json
6740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9772bfa3.json
14944    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de97498e6.json
9263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4614847a.json
3416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a90cfe39.json
12770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e26edfa8.json
5897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d9d04836.json
3344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e6a888d.json
9843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
503a096e7.json
4780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0aaffcc6.json
12036    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
682fa5135.json
10081    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dff390828.json
10842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d680ddf5d.json
9071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32918fcdf.json
1107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3947180ba.json
8622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c5f2907a.json
14958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f97d14e01.json
9715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aeda0ac0d.json
13824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d14a86fd4.json
13877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e4a80297.json
3726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be0635ef2.json
8796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
046d3a9d9.json
2723    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a2073b86.json
12231    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff361d3b6.json
10366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf918bff.json
12795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d97d4b420.json
1370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7986a1870.json
10898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
780c099b4.json
11836    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e9abddf0.json
4256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cc86be4e.json
7582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd36ab692.json
8626    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e2335bf5.json
7971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b085671fa.json
8562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46c834c70.json
6854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b09ecfb53.json
14004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
413489a34.json
4076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
466862270.json
5146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f135e422d.json
11027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5b717bc2.json
12930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44229bb72.json
1732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
495ad1b56.json
4700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a8980074.json
8749    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a23dbbf9c.json
5357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a99e4b365.json
6478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e6fc0342.json
1105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
514202b22.json
13107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55ccb364d.json
12824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bb86aa8f.json
4479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7f938acd.json
162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f2edae7c.json
846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be55e5ef8.json
6388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e5e366c.json
9882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
585a705fc.json
3065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad8b02fcc.json
3236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67d74124e.json
2151    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32387ac37.json
14899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e45f7387.json
10998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4407477.json
11582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4c6c89ab.json
7062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2acf3fdce.json
152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f07e684f.json
10628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30669fef4.json
12457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7675eb96.json
4332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e400a579.json
11063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d7bd3d7.json
1209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
251b3b086.json
7456    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25765058c.json
7166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cf709a59.json
9869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
370d17232.json
8668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00c19f4fa.json
8854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70337537c.json
3399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dce619e3.json
10016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc0eced0d.json
11699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d38fca349.json
12058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7028931ed.json
5984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a0a6f8a7.json
13615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49c216bf8.json
4303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f214e361.json
10283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58bebf13.json
11163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66757255c.json
190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87639ef4c.json
13281    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6975353f1.json
10574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8c9545c7.json
4246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d305f8c2.json
7725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a39e58f1f.json
2659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e486185f9.json
1727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f568e3a2.json
9011    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adb97bde0.json
11109    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f50997846.json
6550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
638a1f488.json
12234    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83d15cf4d.json
14909    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
150257980.json
4735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3060d192f.json
14828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0e762abd.json
3836    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe88a5777.json
301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7439df9c4.json
1216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ca057824.json
7499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d24c7ab5b.json
7152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8039a31ae.json
12888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b63e1b21.json
684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cf995ca4.json
2467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85327438d.json
13517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b278cd182.json
5066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
343962804.json
4338    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e736ab042.json
383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af28491d1.json
4439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61e7f4ebe.json
9087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71e96f977.json
7580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
237551493.json
14107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fbf04fab.json
2338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2469e58fd.json
1643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98c36e1bc.json
5752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd7811109.json
3034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a2ea6461.json
10362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c444c2936.json
7274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0bdb767f.json
1151    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2acc0a068.json
887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
918ae2c95.json
8003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e48598033.json
3574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f341e7af.json
12059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4ab38782.json
11414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

3b5a8db4f.json
12180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b96d69dc8.json
14824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
191fb0046.json
4631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef7555da8.json
2218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79e0ef004.json
10248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c50926700.json
5026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99af63c63.json
12966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5ec4df1d.json
12486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1d9012db.json
8357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48d1e6446.json
5352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5be134946.json
2111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bf24d8be.json
23    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4802207be.json
14868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a54202bba.json
10596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1df75b45.json
4018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
206db8d8d.json
4782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2212e16c.json
4322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce768b010.json
9837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ce613036.json
4642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dfe4da6a.json
587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78d60ffcf.json
7012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf6995fef.json
1898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8a1d4151.json
3318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f2065428.json
9606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69262e404.json
1017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c64a0f1b.json
8412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3166b0f31.json
12663    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6830bac1.json
3564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe250bce9.json
10329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98bb9d9dc.json
10411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a672ea96d.json
310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1fb61b31.json
2182    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd1eaf778.json
8445    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bb0c9458.json
9188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62550cf78.json
235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af1125994.json
12029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c296177eb.json
9100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffa25e61.json
14341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bbb46822.json
187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb5dc081c.json
4031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e2bf402c.json
2049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4715f897c.json
2327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca3312b77.json
1681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85ed50b25.json
3957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
717b573f8.json
12169    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd5f7e678.json
1934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dbb13673.json
2890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
748943e29.json
12948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38f6d8ab9.json
12978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4ece4eca.json
8494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54959e674.json
4438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e5356302.json
5257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a45e8492.json
3845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
634f65242.json
14236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e2258f0.json
10891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
397be6b99.json
8989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1de97c49.json
14131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ad87f5c5.json
6762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46f6472bb.json
8881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63adeea51.json
3192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d440e9ebf.json
5740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0b33bec3.json
1697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
453cf6271.json
12496    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dbb0a012.json
5393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa7c7d1be.json
3376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2d35633c.json
7542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
170fa3d49.json
13819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
021c24928.json
4189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88cc9be30.json
6947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb9e47b4a.json
12817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c64b6e891.json
4010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4cc525db.json
2779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4140b3b5a.json
7620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4f6acdb6.json
8899    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdb4a7a7d.json
12054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d5678b98.json
11538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c576fd55e.json
10130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a17411df1.json
2946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c4c1d10c.json
9368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da9339584.json
14323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ca524fbf.json
11906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
244144067.json
10288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c91bfb2a1.json
12350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e27cb9ac7.json
11490    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e039f2392.json
14949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
748ca0bd4.json
11718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89d8b797c.json
13396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b051c8b3.json
5189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
324232e54.json
2438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9278f7216.json
5889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2fbb0332.json
14651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4ff3b712.json
9832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8afeab374.json
8337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d92c326f8.json
8170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd48a560c.json
10835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16c53ebf9.json
51a0d55ba.json
8032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34fe22f69.json
2179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59ad17125.json
4636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71b8ca636.json
14812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af56651cb.json
6997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd3172797.json
88    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d8b42d21.json
7436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
248eca1fa.json
13093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0076e01.json
1675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b47ab81c9.json
10967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4f512d95.json
11619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
079785984.json
13823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5df70cb5a.json
1278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f53be74bd.json
12939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
365f29337.json
8662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9caf7e92.json
5197    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5943080b2.json
8497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a8f9aa52.json
2736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
573ebc9a8.json
14672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3b29563b.json
12338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09c7b610e.json
6993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e4f0e111.json
9024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e89692f96.json
6165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf15c0b6.json
3300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b81592b9.json
5366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf12ff750.json
958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb8a0278.json
198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0de58288.json
11304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20a9ffb5c.json
13453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a302ccba.json
9987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

1e5aeb31d.json
11285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76e071fcb.json
726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b95747f3.json
13956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24731a12c.json
2002    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4335b2207.json
1240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b5b2c882.json
13037    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38f6f3011.json
4628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
115299f16.json
13783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
998de7b77.json
3933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7adf54516.json
6203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cef342d22.json
2699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
236824e39.json
1847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
403cf8d32.json
10279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1945c0690.json
7137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32168f6f5.json
9544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fc71c87e.json
1537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a056486e.json
10220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0781fb0a.json
2278    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00af25fc0.json
10260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc4e5abfd.json
3886    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13f07ee9a.json
262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af86d93ba.json
1610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36632f72b.json
930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8084fe32.json
12681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c3f75c04.json
12120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a860f4b4.json
2287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2fc23444.json
5010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51d8da535.json
562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
365aaebc8.json
9145    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6764e8752.json
3793    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a218ea6c.json
2922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f7cacce.json
4406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9003318e5.json
2687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2910c35cc.json
6678    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8e3fabe6.json
2556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
863947277.json
10861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
003dd2e26.json
12296    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
843738a2a.json
11226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82a97cd8d.json
12130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a4c20f98.json
8957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a06a2ee4e.json
2734    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cba86658.json
6374    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d026d2fb8.json
11780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
939268f8e.json
11627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b469d4b.json
11204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb5e73024.json
14267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f78031e4.json
3305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc60d07c7.json
1052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b02fcb74b.json
2098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d33077f2.json
790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94d65e361.json
9378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f0805ceb.json
1411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5971694db.json
4444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1f0972e3.json
3580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05d2022eb.json
14271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3a6a081b.json
11252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92935062a.json
11770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d92ada81.json
3952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd39fef15.json
9223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dba5f0e5c.json
3867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b9976e20.json
14305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44930f85a.json
5561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3cafb38c.json
515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d30b90a39.json
471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe790ba60.json
7643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95636a0d9.json
10245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1530366d2.json
6080    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6198e214e.json
3018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe854f6a1.json
2271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2317e5b0.json
14961    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9adf0f234.json
13446    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b525ee190.json
6044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c7a27088.json
3954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80fd005d2.json
2757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
360dcecb1.json
8410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23987e634.json
8709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09ffe1d02.json
8142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc4e55d5b.json
3624    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3b4e3f5c.json
889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ed26a84a.json
1394    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
accca912b.json
537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be23e42d0.json
258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f08386f4.json
9080    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
106de20f0.json
6837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5b9e0322.json
246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a12589a09.json
11059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bce76c66.json
238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e0519e3d.json
2154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d25ac957.json
10063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3f8d5097.json
14094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cccd87749.json
4159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d120df077.json
9874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2f04a19a.json
10728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6fac7b56.json
4567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1dcf0e9e.json
9498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a65853183.json

5731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7013035d9.json
3144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4df06287.json
6522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad8569001.json
11942    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a8ce175d.json
1514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf85bd080.json
8866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee2793324.json
7005    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d30068375.json
5563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8d56dff.json
9503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54b2051c1.json
13550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4c2ab3c4.json
6869    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7af35cc82.json
13701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f3a4dab0.json
3237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d08efa704.json
11018    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d089036f.json
10540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3625dd7cf.json
1527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e3c6f81d.json
9102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
784d3319e.json
1996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ad9ea6f0.json
11069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8715d47e.json
273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a89f8b241.json
13305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe19d134c.json
6582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20336bf88.json
13791    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b243b8e93.json
208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbae7b0d5.json
11954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3735485c1.json
11535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93b692cd7.json
6444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bcc9f10a.json
4268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8b79357a.json
12931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3335796f3.json
13635    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e92d3d4cf.json
11965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c969d36e.json
11726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
181c10e45.json
4099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfd0fbde8.json
3001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cacbb858d.json
6940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dfe71419.json
12141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9160fdb5f.json
11034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56cba1beb.json
5097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0084b888.json
12859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40309f25c.json
3149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a20880c1d.json
4522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46fdbf640.json
5678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be6435852.json
4104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5010c15b.json
14596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5296fb183.json
6817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74e81519b.json
5104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f726dd490.json
2996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bf7eec1e.json
1543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66ac9f1b7.json
6512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ef5f0537.json
8376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da840f8d4.json
6633    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
279ca5034.json
11321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
743b67b44.json
8351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42448336b.json
4037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6c60a52d.json
3767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
393198f9d.json
14495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d13441b9.json
12973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95708d284.json
9711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cef75bfab.json
12002    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d513f46a.json
3451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10c24c385.json
10471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
547a18b80.json
8833    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a92877f7.json
2748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d2e6ed97.json
9241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2ecf822a.json
6963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00c71a320.json
1700    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba8ead296.json
3184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1696809dd.json
8075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9726ab93e.json
11225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39944ac3f.json
8889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a91761e54.json
5649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2755d8bf.json
879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10836809d.json
4033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21d79f603.json
6863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d20f6163.json
967    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e83f846eb.json
226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b589d804e.json
11580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
766c2cd92.json
12492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ced977d7.json
14191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e902691.json
516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0270a5f1.json
6729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
210b8d077.json
10836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5bed2b62.json
1424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
375905770.json
391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df7aa79a4.json
1801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8834ac7da.json
13802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf17492c7.json
3673    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab9dd85b2.json
6826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3501d8f4f.json
14503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4084b0a93.json
2854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b2c806b.json
7076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed44605a0.json
6638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0dc745da.json
13225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
284c50f77.json
9465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db6082ae6.json
bd263a880.json
13116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2f333b86.json
13092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3695274de.json

14174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5da6b63bc.json
8344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af1dedf7.json
3670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dad97c60d.json
12672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77322d6cb.json
10230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cbc126fc.json
8275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fd882044.json
5593    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af1b915b3.json
4422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd62a2e7f.json
2954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09af85878.json
6179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4409a68b9.json
6823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb6c692dc.json
330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38f06e4fe.json
1991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b431377d.json
13283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdf00be34.json
5431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b346ef59.json
8246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e639b8dcc.json
9642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d837689d.json
837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a72ba3d7.json
11038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a342f6a85.json
12196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87a3ef269.json
10183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8715f663.json
13493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab09748d1.json
1191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4550efe5.json
12511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d64f2a210.json
10515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a554dbeca.json
13452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db9af2894.json
13637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c24017264.json
12009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16afc5dc.json
1294    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ea6cde88.json
3276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3b263e8f.json
4282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f74b89005.json
7874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a67c850b3.json
6127    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c70eee7b.json
7306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c93c0c11.json
77    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85a0bad4f.json
7703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb4814fb9.json
10320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec322a0f2.json
9173    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebb34fea1.json
7055    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb81b0503.json
10640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fded1ee28.json
2409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da34209ec.json
5333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90a7474ec.json
10218    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3a42fc4a.json
14194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dac8ec35.json
1886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70aeba909.json
5422    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66eb1d49b.json
5127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2e480f4.json
11982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3503528f8.json
4640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a486e2ab6.json
7776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56856fe73.json
12835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f7e9db52.json
1307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ebfa37d.json
5828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bd434dc9.json
4812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbcaecdd4.json
2807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7432630e3.json
13014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66a1d5bc4.json
4727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f90bba4c.json
9867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8530e295.json
9126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de2d4f372.json
13087    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83502a253.json
9248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aeb17dd99.json
6789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc681e945.json
3610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90caf70eb.json
1877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21c955172.json
13189    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37fb97f8b.json
1428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dd3f3eb0.json
2682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c06b6d8bf.json
1619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af6477aa.json
13996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b12bdec95.json
1115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7867f152c.json
12447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
234b2a6b6.json
6c7db281b.json
11107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ed568ab9.json
11715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca11826f9.json
7199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34d5748f7.json
11919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d72ef0c4.json
14823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a67ffb8b.json
8392    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
356d41ee2.json
3866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f7563006.json
9666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af862a239.json
1987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
444d1c6d6.json
14957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
393b4d104.json
5790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be0888771.json
1418    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c740abfe1.json
54    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d76e9dedd.json
10893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68d514216.json
13125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
420193f17.json
9180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
810b069f2.json
2704    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00bfa5da9.json
03f65bdd3.json
4008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7338db23.json
5269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ad5153bb.json
5641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1cc9dd25.json
1262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01b167b92.json
9254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b9d9a18b.json
14572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a05c489dc.json
4358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5fb38d4.json
7905    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49bf3272d.json
11273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a58cfb6e.json
6690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
184a51562.json

7394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abdeff83f.json
1110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f895c20f3.json
11448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9c3f27cc.json
9591    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24379b58d.json
13103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e13488562.json
5478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b6ffc0a1.json
6129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db08f8564.json
4311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a21f183ed.json
13950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3653c9384.json
1831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
842528c2a.json
793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbba51f97.json
5600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c0bae9fb.json
4664    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
785150e60.json
9345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65d0ea00b.json
4192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f600bc8d1.json
11409    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5b943ccc.json
13663    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76aba4871.json
13744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c88aa53a.json
8798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4040a04bb.json
9084    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c484dec95.json
13742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eeaa5c53c.json
2760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9da5c9d23.json
9963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e946254a.json
9399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b261a0ee.json
8226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
972a081f2.json
8703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eba8b0ad.json
438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9590d4de.json
170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dba9050f5.json
5622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b35e6306c.json
2857    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29ca8f313.json
12878    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
078a26f06.json
6004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31049dc2e.json
6078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
982c6aa5b.json
12434    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90f1b0525.json
1990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37f8a39c4.json
2972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
256f40704.json
4426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7117385a0.json
12198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16b24c21.json
7815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df2d9957f.json
6501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec780b913.json
7229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2cad7ef6.json
9564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
073484a7d.json
7486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3be9dc4cd.json
2033    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
120805f93.json
151    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ebb5aa64.json
5946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f27974780.json
4382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4cff3785.json
7289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
316f30229.json
14712    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a631eba2c.json
7639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42b4b0024.json
12410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9697ebf42.json
5851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b660cb310.json
6394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c58018973.json
6082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93bffe78b.json
11105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee2def69f.json
13548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b02a097c.json
13422    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b9b55f0b.json
9674    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f08503742.json
5164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4b85d322.json
11656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93cdb10e6.json
8074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f5cb9583.json
5098    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb999f812.json
11802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8cfb849e.json
5217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69d04f61e.json
8399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5dc6f316.json
14225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29e2ac645.json
4774    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c24655fe.json
450    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79db05f63.json
12076    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83703d7e0.json
8758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48f5de7e9.json
f293ae915.json
10611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a37b96d01.json
7085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
321c14446.json
14105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3e7124c8.json
11861    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
541904323.json
1807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83ea92fcc.json
2082    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb0c04621.json
8148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a07a65495.json
13732    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d9604897.json
11997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5360d72a3.json
4232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65daac431.json
2585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94d5ded81.json
8755    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d096658bb.json
331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee421d21a.json
4121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
803c3b444.json
9492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3d68b63c.json
8179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a3c44785.json
14209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91c2159dd.json
441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
233aeb07c.json
8292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bc084196.json
14659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2774ef93f.json
3603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
502a2a9db.json
0b819602d.json
134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58906d012.json
2414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6f2f9424.json
4863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afaadb62f.json
1251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ae84d311.json
3312    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f10390965.json
2006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d5942493.json
8324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c86c76857.json
1967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbfc8a037.json
1947    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e76362c0.json
9737    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
637e741e8.json
5046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdde3b5ca.json
8007    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72ae87d2b.json
14866    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8f5f9120.json
1821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f06da7096.json
7834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf0e2e817.json
11325    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7addf37de.json
1795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa32ec730.json
12719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eff0639c.json
2550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c67d871e3.json
7193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ad7a82a.json
5836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3d47c67d.json
372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79a6cc443.json
10264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07417927d.json
1878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0be76af8.json
9333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c3d81083.json
7497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e73146163.json
8825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f83096577.json
4478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c8209bae.json
11599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fdd708f3.json
9820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28ef05fe6.json
10709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c983fe89.json
10616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94dac1ddf.json
11287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b17f7a1fc.json
12819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3091d24f7.json
9584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c19e8ac4d.json
6417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

f288b4919.json
4474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea6d8cb1d.json
2302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3740baed.json
2190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c272d9284.json
10647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e45ec98a4.json
1279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da53f587.json
4836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
311799b58.json
6727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea4c18b67.json
9823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4b316827.json
14377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9183ef863.json
7427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72ec92880.json
13514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
746f52206.json
11800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee0e059cb.json
10805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34d387261.json
4066    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2831adaff.json
3492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65f311c09.json
10958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
841bcd63f.json
4197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4c32b8a5.json
9583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed29f6592.json
11821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23f45d56f.json
11901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50e061767.json
1691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
672e80119.json
12203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
219bf9c22.json
13160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
107d56dc4.json
9763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
048cd8bc0.json
14762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb07ad856.json
6846    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94dc20e92.json
7086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc0a5524c.json
5324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edb154f1c.json
9991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eaa9f888.json
709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc515ec8c.json
12057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8d98877d.json
13955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb32a589b.json
10445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
975091325.json
2547    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e18cc7a60.json
12778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
948f580dd.json
1906    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27c4981c9.json
538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e2440e26.json
e0e604fc2.json
7702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28484f496.json
7064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
737069cee.json
4889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edba94b45.json
5375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a1240a5d.json
5827    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13296aae7.json
2747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
150bf58e2.json
10722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd64fac1.json
10585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4af5cffc.json
11084    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
267bf57c8.json
3997    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a21b6c40a.json
7546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00f3a3993.json
14129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fa277b19.json
12786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
427755203.json
7602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfe361097.json
12699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8ee48e12.json
13575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cf90beff.json
10160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2786b8c37.json
11493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a78dcb663.json
13597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d24c695e.json
711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfb19deda.json
13266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe41e15d5.json
7043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2a14bd0.json
11162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5c5278b8.json
14959    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cdb80095.json
2255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3083ab744.json
7584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78599649f.json
9749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1b3455c8.json
11824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b1e90385.json
8495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff065ec7b.json
2370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6e342121.json
896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4feb7269.json
773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a1274da0.json
10189    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7eb5dd36.json
7028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd2fd9be8.json
12132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1aa11cb5.json
2259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
943e9242f.json
745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5cb16efb.json
8395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bba3070ad.json
4346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7a44933c.json
7491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d873789a.json
9742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3f1dc170.json
7760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdd7aee45.json
364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5cfb76b3.json
14721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a420e638.json
5350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b268202d8.json
13884    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76017363e.json
10866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dbc5c968.json
353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cc66d907.json
8606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86953ea0b.json
648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c542e43e.json
12148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e56a693b.json
9507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa3ee9d0b.json
10902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27058d03f.json
9609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
132670005.json
7861    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4e6a9aab.json
13914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b41fd3816.json
9451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d18707ee.json
7036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63dad490d.json
c87f6d0e4.json
8353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe9e5aa06.json
3238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99558ec92.json
966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d412201f6.json
12484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26cb1c2c0.json
2821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4059df1bf.json
3743    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
040b028f1.json
8976    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ea31a03a.json

8403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9676b5e36.json
1901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbeb9fc1d.json
10470    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f28b76d7.json
2221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
550405709.json
3745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76d5726c4.json
434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5f027ab8.json
9219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40d7cb083.json
12757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8910e2c01.json
6422    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b0b2a86a.json
474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5071e525c.json
14694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58dd05c8.json
3947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca7c6095a.json
4344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
283d0763f.json
14640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
727d25d09.json
6166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e3f52620.json
7820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd4b67059.json
12792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a3fc490f.json
8811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
685010499.json
2727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b147d1870.json
2496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
209dab64b.json
12886    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4128e8e80.json
8253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9edb2d79a.json
13976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cef5b961.json
8699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7c1eb9ec.json
5072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e290a43a.json
7188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dbd7f61b.json
6707    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03188ecad.json
85332d295.json
2955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
331c39c92.json
6542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a60fde1f.json
7858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc549e010.json
6653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d73d97fd.json
7997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9acd96273.json
12840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d2a7f0dd.json
8547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93b91a46a.json
3296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
884c82597.json
14822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
880a0ac07.json
8326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf9fe33d0.json
11389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7dd2c184.json
7203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22a0baf52.json
12205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db0213107.json
4292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15e5b6d26.json
13695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76288167b.json
1020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eab8c8c03.json
185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f52510492.json
3723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
240ddd506.json
13786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a2c8a05f.json
371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3c27d97c.json
7168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9a2b71d8.json
ae4ebeb3e.json
2444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20854e428.json
11183    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
056768390.json
5702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
269192694.json
10269    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
230009c15.json
9560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c02be41e6.json
7193a5332.json
11055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbe6ff890.json
6358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
086857d70.json
9651    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d1451061.json
7346    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00be0a63e.json
5040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a875f3f6.json
2732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f47fc05a6.json
1285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9e96f77b.json
1557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f7863209.json
9030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a19305a1a.json
6465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b67778d17.json
2930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
081f88f27.json
11282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cbad35f9.json
1078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
000a290e4.json
4839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa1badbb7.json
7494    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6004bb5d.json
10657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b567ca662.json
13985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
105456da4.json
11505    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fb490c9b.json
293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbf579546.json
3536    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bce639e60.json
7598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec2b6c036.json
7658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af4941f15.json
9098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e56dc823a.json
12200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1df948d0e.json
9994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d31b3f33b.json
1381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0822db812.json
3557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc32d375d.json
4692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
692bde33a.json
8559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71ec53012.json
12691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee640a6ba.json
4125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9a62b53.json
3164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab1ed5c13.json
14190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2db00a064.json
13001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a804fded8.json
5785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
970910885.json
9068    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bc5e3faa.json
1774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b48b65ef2.json
13158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cc8bae3b.json
4138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5155cda1.json
9951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed9936705.json
8165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a1b27ab1.json
1150    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f95eb4d75.json
5450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
547c7bf41.json
3772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f6a4a76a.json
5414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa1608a29.json
12333    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f98d0ea9b.json
11405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3077e6b1.json
5718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43b277272.json
661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c26f0fed.json
7173    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11c88e3be.json
10378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cbe52a0f.json
e67b88329.json
8464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a1010bca.json
231    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c9aeeb27.json
14324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02f31f1ba.json
11348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd9e87899.json
13448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bf2c6260.json

4588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deb0ad8cd.json
9290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2aa25dbc.json
3625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bb1c8a6f.json
3569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
495528ba4.json
3212    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355e8bc38.json
5754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e42a8863f.json
3774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a1f83080.json
10905    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
231ad764f.json
7737    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1e99433d.json
10815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba2904fd9.json
9061    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99defcb66.json
7727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b68679817.json
4092    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd7dc461.json
13555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5baf5497.json
14018    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5422c04b.json
12623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f252006a7.json
5332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e418eb448.json
12040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dddf96e8.json
11959    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c07c6ee5.json
12871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c7064ed1.json
6232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b148edd2.json
10025    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b56b73e4c.json
7142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146d950bc.json
568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ca49ce85.json
14103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86379f12f.json
122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04e966b1c.json
30254b35d.json
12897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
393e0c8a5.json
7077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27a776558.json
11230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
358270782.json
8591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
becd6c70d.json
9888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8c7ef646.json
4585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
741524a39.json
10750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94e9e97c4.json
10077    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b79e52f0.json
11473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f1bdc253.json
3434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61ac348d1.json
13005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
161de24f6.json
3680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c680a5bbb.json
7376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b6b9398.json
12364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4d7e410b.json
2140    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6381b1706.json
7967    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efc55563a.json
1641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b810732ac.json
3408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b8ef81e3.json
10347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c85f29411.json
6656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27eedd440.json
10973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
005afe792.json
12407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4e2b49f5.json
11907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
176516c7a.json
4264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5756030f.json
13625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05d8b5a9d.json
2860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a362ad62e.json
2181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a02551367.json
12098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11fa9d216.json
14026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8939a1ac8.json
2125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5264f98c4.json
2492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8a6c0351.json
14429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec4351554.json
13182    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a289a426.json
13728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f35683806.json
11065    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3df923a0e.json
3432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c5d5968b.json
1eb041ff3.json
13497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c9e666a7.json
7787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdb6ebb91.json
2617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b4bb9906.json
307    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd4624a1a.json
14720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c61c33ee.json
7015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6408ec0f7.json
12355    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef487165c.json
9525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce0412bad.json
10057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b26aecb5a.json
5977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac71e856b.json
14956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a8ee7520.json
327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18b2da498.json
7296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2b06e1fc.json
12987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e3c988cd.json
6805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abf0f2579.json
2153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b12b6dc93.json
1652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9ec4d543.json
4571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a96f0d5bc.json
5210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c053ae854.json
3823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5295b0e2.json
11300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7b53e5ca.json
12794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
279a5187c.json
13185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7e7c5c9b.json
11842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95e61ce61.json
8631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65f56897d.json
6878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32bc0b4fa.json
11968    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e2c46391.json
1849    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
122b47acc.json
9008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4f349714.json
513    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb6c84ec0.json
10792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d87ff9c80.json
8239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e5627478.json
2404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77b247a02.json
8929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df3756483.json
3160    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2205b952.json
7172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89c7be602.json
7115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54b0c0564.json
1836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa39dd076.json
7919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7dca0b2b.json
8051    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c12ae3214.json
8147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2023404f9.json
10363    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99a705efe.json
3036    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
303696f08.json

10408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ebe00ac2.json
3967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39fcd2ca4.json
4123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
672ddf4a9.json
14742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be9474b85.json
82    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b49d7a9db.json
10548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f28d2ab3.json
1837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbf8ba091.json
12008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dae92dd61.json
102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cdaf32d2.json
2876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d87bad8d9.json
10945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c138e187.json
8550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
412b8d565.json
2037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8c3eb092.json
5503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8ee34b59.json
9016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57a93e9a6.json
6555    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd881326e.json
7210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
791254d12.json
6034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a2c23d4c.json
5658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2de32b48a.json
1433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25c7b5c5f.json
9631    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05974bc36.json
14911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e3586785.json
13800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f037aaccb.json
10284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc76a1735.json
13720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
472abccfb.json
2108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73a3a3b24.json
1725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f78e79c0.json
6528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73a17e201.json
9343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd0c6dc7.json
3210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31dbaafaa.json
8230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82ee2f3e9.json
14970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a12bb119e.json
6671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fb89d88f.json
2829    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e436c1fad.json
1566    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab3759aae.json
3738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fffd78a11.json
13094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9e604ca1.json
4623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a54b760e.json
915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff47b9a27.json
3062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9120f2894.json
10678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bed78eb25.json
11986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7811bdd84.json
10118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72389d266.json
14484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dd1cdd52.json
5384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69c9ba4b3.json
13763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e432ee48e.json
8616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
769579681.json
6295b5bc0.json
4401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
409ad5a23.json
14841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
283424d80.json
1471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b6867433.json
4456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcda9d091.json
7885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c026becc2.json
3794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a96189d5.json
5463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4948a23d.json
4315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
220e9aa26.json
3077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63337324b.json
10547    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b57ed86a.json
789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac279a25.json
7693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f557e9262.json
12113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e9308e0e.json
14939    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
733ccdc63.json
2358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2ce25661.json
5402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b53bf64d.json
3172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d939327d.json
1763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dde8ffd00.json
1148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0985e2dad.json
4715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97e08141e.json
13188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b4224c51.json
6101    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b943a95a3.json
13657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6521d5af1.json
4696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1c7e0838.json
9667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
260f532b1.json
997    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e29ff1448.json
4937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee8ddae7b.json
6221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e778cd78b.json
6219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a6cad15c.json
2400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03f8a64fe.json
14122    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ef182fc5.json
9663    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eab205e6.json
13010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
239326fd2.json
10809    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c1a39de5.json
11614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd74f5ce8.json
14569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef1d7c2a1.json
2339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
943bcd4db.json
1614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6510f0c2.json
12489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14fb52f07.json
3597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7402d13c.json
6484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05febeea3.json
2616    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f69176873.json
5391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4693e646e.json
13507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bc671d5e.json
2235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01a7b719c.json
14238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5550a68dc.json
8134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
268cdb435.json
13406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3f1c8d27.json
3133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a839e26eb.json
11118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bb2a981b.json

14722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79ec57bd7.json
8122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0af365e26.json
9367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddd632a5f.json
12316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1da458ce.json
11026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0604b559.json
9335    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02612ab95.json
4921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b98512188.json
6560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f7265ddf.json
9578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88876f4d5.json
6747    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35bb8ee8f.json
8756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c6f9a4e7.json
3092    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c8e65887.json
6114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
235572f38.json
1180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9daaa4e8f.json
2631    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c712cfd20.json
1030    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c1370c6a.json
10844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
488a81168.json
7148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f12fc9ea7.json
6783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbef1e6db.json
13586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f594a2e18.json
7722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29a9fdad5.json
9028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e50570999.json
11841    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fa63169f.json
12032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
465e2ee50.json
8009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c29059110.json
6134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eeb60466e.json
220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0fd5da22.json
9827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a7fe0b83.json
11433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
356a9cf88.json
9925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b8489a24.json
7042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8af959627.json
7677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ead05034.json
3753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29c50ee9a.json
7426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7315e345.json
12825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a85457e16.json
6732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52f3d0bf9.json
3475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd8af1bda.json
13794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dd6be0bc.json
6180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03a92a94f.json
8837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
230d5d85c.json
6194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dfa4e393.json
6992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6821c448.json
11138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09dd22091.json
3609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0e5d766c.json
10116    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4253889f.json
899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58a414b45.json
12225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e9ee4be9.json
10155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b414c5dd9.json
9845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb6bb82fd.json
4926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e4724604.json
1516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5fcc079e.json
211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8ce7d647.json
14362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d17343468.json
7510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
459729cda.json
12603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9b28d664.json
3784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd8ce1096.json
4708    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b00ce0fd0.json
13551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
944862101.json
5534    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cdb96709.json
1083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
230232e58.json
8721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cdfd6a41.json
9616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12c071b30.json
13394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ed271e0d.json
3877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a75703051.json
5364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
212157776.json
4989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f19552c0.json
2319    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb867cac6.json
7135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
740d87a41.json
6314    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e87e4110.json
4557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f88fd5ee5.json
9885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81734dbc4.json
9980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e15353d1b.json
7297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bc84c4a9.json
3075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
548df7912.json
9900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b66569990.json
5915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bb1086d6.json
2828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5685ae208.json
1299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79ace4e40.json
7592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0157cf3a4.json
5630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f0d943dc.json
8676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deb43659b.json
8081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8b9d57b4.json
1406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc6ce44c8.json
10440    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de6c0126b.json
5568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f9fd5688.json
10267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3de1d3794.json
7129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d06250ab.json
9573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faa139539.json
9461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
528115548.json
10924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68071559c.json
6326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c88eebfdd.json
11306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea15297e.json
1329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1d4e279.json
512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21493e6ea.json
669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59309ddf6.json
13411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
298ae7ea4.json
10632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
201aad926.json
5636    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bdd90b8.json
13892    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80ae0a34f.json
890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

cdc958646.json
1023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172433b2f.json
10726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d3081480.json
4375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21c281e66.json
14898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fa2d16db.json
1472    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e242ed8c.json
14525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a9d058f6.json
1913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8feefe84d.json
8535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ad53090d.json
14759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e625fc4f4.json
3080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5c2d9dd.json
12119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
982dce813.json
905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd05c2f75.json
11326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96792a909.json
10331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac3e7992.json
10608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daf1a8d08.json
638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f53ec8cd.json
5345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62e2e9071.json
1287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9be11ef9b.json
2115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9679275a3.json
13055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
979e3f8f7.json
2809    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
426bb5e4c.json
12477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e92713811.json
2374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35a62a8b1.json
5666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd7c54ba8.json
14817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81532c76f.json
3656    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc4b199fa.json
933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97f683e04.json
7333    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c60a65e8.json
10437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
053d121b8.json
8818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6e372a1d.json
1954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d911bffb.json
9788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72d77924a.json
2865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b636912d.json
3785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4747bead4.json
12703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30ea81bac.json
388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
529c2e04b.json
9786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
813db4d5a.json
4941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33f056cc7.json
10482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7a7fc91f.json
6103    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
623111d43.json
14140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdab91b8c.json
10512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f88f23a4.json
13184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a38aecad.json
7151    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62955be50.json
2157    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4edd47eb.json
7075    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c6aa4b33.json
13736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f58a37d5.json
3525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6a856527.json
9196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97e47e7c0.json
14890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
915031b99.json
6672    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53cab4731.json
4786    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
546aef659.json
14825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20ba919c6.json
2034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efbe1f3ef.json
9824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92c2878db.json
849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f67d78df8.json
1989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd6dd3835.json
5448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e442c149f.json
12047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f120723d0.json
6289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70943f766.json
9240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e68c7d50b.json
9452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca2c00404.json
8034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80599c4f4.json
10146    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d03cf923.json
5643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f93283e0c.json
1021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3c880313.json
9265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f514f45f3.json
6213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03b0568b3.json
174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b88fa24c2.json
7234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e08e93f16.json
14506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ece3629b4.json
9590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1bfba974.json
13004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50418fb29.json
7073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a43071ff0.json
1350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de0f96a50.json
4277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5158ef9e.json
9304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a38740d1.json
3378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
047c20d1a.json
10761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6276a846c.json
10810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01d0a7f3f.json
2076    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51741c1b7.json
2294    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
940048b47.json
10561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3658ee105.json
9455    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4652e4fe.json
1805    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8553b7037.json
4453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
755f10f8a.json
9429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
618e97eeb.json
3532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a091487fb.json
8576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1077fb67a.json
3365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bac2d757.json
529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0da2621e.json
4519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
048519a46.json
3458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6650d183.json
10373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
347be28a8.json
14587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18095a42f.json
9270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
141a53bee.json
12168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ddc32b12.json
875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5f14fda.json
583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f2f38f47.json
8471    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92c42a055.json
6959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc38b3b63.json
1935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c7c5555f.json
336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32cda3189.json
12666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bddc0b2c7.json
10714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b0c683e7.json
11457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

45dea4033.json
14608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d03356a0e.json
2316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e4b7018a.json
10460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3082fa97.json
9601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c2168ffe.json
10111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66064ba80.json
14620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d7275647.json
1749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d602bd84.json
11479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cb52145c.json
2362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa6b8a52b.json
13347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92df22369.json
1429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
123f15578.json
1741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9167921b2.json
11892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
affc18183.json
14193    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86fe4ed68.json
5920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
547f46854.json
5537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
093cce3a1.json
9999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37c68c4a3.json
7120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a462b563c.json
11575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51d637766.json
10274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
753654b70.json
937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
152880177.json
10131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92b5de07f.json
9140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
387a8e71a.json
4586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8566a1bd5.json
5708    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a590a1cc.json
3959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f72b332c.json
11462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6523901.json
13829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d16f1d371.json
9769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9976d9007.json
3847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b9cadd98.json
13492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f743a63aa.json
13236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
205714da6.json
8162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
930dcdef6.json
10569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfab5f493.json
5198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fabc9bfec.json
10132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28b4420eb.json
9091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d73574ed.json
2093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61afb7281.json
13333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bda483ec.json
2813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56b5845d7.json
3773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d719027fd.json
3534    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
029c248a5.json
7578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23bf0ed46.json
8110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a25c1fe02.json
3850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d0752cd9.json
90    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da3be5cb2.json
2565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
961d4ba5a.json
9570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a916e954.json
7889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f20fa5c38.json
7093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
888c22eb5.json
12461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0493336f7.json
10289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
beb0f98f7.json
8132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4fb11803.json
6195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b42873eb7.json
7589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d889fe46.json
7688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32287a62f.json
14519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b93203aa7.json
7792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7acaea66e.json
823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f2946027.json
2862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd668b430.json
8997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4982cc983.json
618ca94ad.json
1550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2b5913e7.json
1513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06dd351e6.json
1302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2406f38d.json
8816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d54c5d66.json
8020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a8f49ac8.json
14042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df07fa1b0.json
11541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fde0ce59.json
9815    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfc8a8e9c.json
10492    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21958b8f8.json
13857    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a30968a3.json
3079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bdbeb107.json
12722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bc3f09be.json
1042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5819a31d.json
10015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1fdcbfc.json
4302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
009239f92.json
1197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b799d4d84.json
6904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e809f1cb5.json
14203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbe2070aa.json
13464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f31cebfd0.json
12752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
610c05772.json
9589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8204bf7c.json
5003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d3c9feba.json
9249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b73a7ca90.json
8828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c1658988.json
14269    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4acf3e30e.json
13381    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bed4e9d5.json
13015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
577d15fea.json
13378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da84db2f7.json
7410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39c654eaa.json
14136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d7e560d9.json
7404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
beb658bc0.json
7894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b64307878.json
12030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3551e91f.json
4289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49c5dbda7.json
5013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25fce0465.json
3064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
289112dd5.json
1380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b66cae579.json
14595    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cf098e3a.json
2652    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea9d13261.json
7736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af1bc9216.json
4016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
572e98234.json
12668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

6308b5232.json
11727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d6a2898.json
442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53f434ae8.json
10977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
742462799.json
8679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffb33c204.json
10914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d4f21d40.json
3180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4fe492c2.json
12671    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b543331f4.json
12170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6e07783c.json
6459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22e73ac3a.json
14299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6acd97990.json
10821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1d86f0b6.json
10175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90b927fdd.json
4517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b31045c50.json
8390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a97a679b0.json
9932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3270683d.json
2944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24993107f.json
1592    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
166092e21.json
370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfe285c5f.json
644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5aa169b4.json
615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89788a8fd.json
2386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2f2134bd.json
3956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e6e57951.json
c1d58a395.json
3006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed7cde89e.json
11265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42103b22e.json
4954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2472c8dd.json
7312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e257f17da.json
11740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015b8b722.json
14387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff0b61121.json
8093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77b09d551.json
9530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d653ae654.json
10552    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2e22f843.json
11588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f6849a20.json
2910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5906e36c5.json
12088    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
605d07d33.json
12069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71cb2e2d0.json
3795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eaf610cd0.json
3470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
851302ab1.json
8348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74363ff2b.json
6641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c68f66799.json
1698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc13183c3.json
3140    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9fa49f8a.json
10598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
196f95fdb.json
2478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91f5bb21f.json
1782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abd7dcf2c.json
11384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2cd5b78a.json
7687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5507b63ab.json
2167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abb847f55.json
14207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b898e8d6c.json
4313    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
218cf1849.json
13390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b857d5ac6.json
7811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada93cece.json
2799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b9cc47f0.json
6525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
770eca5eb.json
2746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
326a3c785.json
11952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
687ddcca9.json
14629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
639a4bcfd.json
5716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9951b9762.json
1185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c4d6faac.json
10618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec40d007f.json
3183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1448ee0.json
6966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaa9c8e09.json
4660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
163919bd1.json
6785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0529ad4d9.json
6248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7ea489ae.json
4392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474f23a3a.json
7950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81573a25f.json
5803    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2885ade43.json
10003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9dcad5b4.json
3096    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a40116bf1.json
11284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8a2993e7.json
11477    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e8b70d35.json
11832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8c8ce5d4.json
13772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
290c3cd9e.json
6569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
797bcabfd.json
1692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d95eabfe9.json
567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75332917e.json
14230    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8803fb1c2.json
4253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00648f96f.json
1289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
007bc1db4.json
7078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b41cf42a.json
8310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d353746a5.json
9256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3935c62d.json
6227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
850cb2e50.json
14541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6257ac9e4.json
e80389ea3.json
6741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
117a7da85.json
8848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
222a3f408.json
5926    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb4078a22.json
6674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fcbb6376.json
14200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd54c995a.json
3371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d7c27d43.json
12803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b38dcdc90.json
6631    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
162e06c01.json
1135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
976fcf5a9.json
9521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b790a32cf.json
12550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4aa0c3ce.json
8341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78a99e7a9.json
12027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d09835201.json
672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f368b7ef1.json
6432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db194aec8.json
8923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
128b247b8.json
8654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac384792b.json

12401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d81a46211.json
9588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
813bfdc93.json
3070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6d358f70.json
14509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9c0e3284.json
11634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2f5253f7.json
9153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac8fa1b6c.json
10100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90dc0d83f.json
7707    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8cc85a15.json
8443    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2aadf6110.json
8389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8e6ad61c.json
6262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cb5fc48e.json
6435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f391fc44e.json
12659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef4dce041.json
2430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34d903f17.json
11787    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
965054b9e.json
3292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad9d334b5.json
8452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
369197890.json
7127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ed4ada33.json
11645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edbe94a1b.json
5021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c76163ca.json
1553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb77ec282.json
5136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c74d62ed.json
315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d4cc2bf9.json
10764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0490612e.json
8237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b4ac75e9.json
6231    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1555b08c9.json
1596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85952663a.json
13634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
650f2854b.json
7349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c05b7439a.json
2010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b7f2424f.json
13972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c121d784.json
5662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
469aab50e.json
1551    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d8e58a2e.json
5428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fe11eb90.json
5a60de180.json
13417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f3895a04.json
7319    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
810805880.json
8959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
147bd18e0.json
11206    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00eca0391.json
3244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c09e086c8.json
3720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a05e81f9f.json
3381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33add94a0.json
10242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
300c91d3a.json
12688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e5672e85.json
11527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615f2f661.json
14781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4b4681b.json
182    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2fa0b0df.json
13970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa45ffcb8.json
7913    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff0818d5.json
1964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9feb3eb3.json
13528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
502c3e7ae.json
869    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c8487ccb.json
5557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d4750032.json
5801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b10d4880.json
10960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fea56eb9.json
5647    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa11bee11.json
8807    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59903171d.json
11115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66201cf73.json
256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57b9d7903.json
7827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95a89f5f2.json
1323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a16ab2da0.json
8840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bde9cc3f.json
9865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00156db4a.json
3722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9f395ba8.json
5174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58e368a56.json
14397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e0d93659.json
9116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a8bc19f6.json
13168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85fd5df90.json
2508    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee8518e4c.json
7958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7e2eca9e.json
6914    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15b27df66.json
12000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fe10670c.json
3011    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1adf071b0.json
9472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2739ddaa6.json
6663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa0295935.json
14820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
813658b4b.json
12678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
118c1147c.json
8094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70be9c861.json
1354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c48c9154.json
521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a76cbec89.json
14517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07cc0ce27.json
8894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c412966.json
1519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb53fe33d.json
2825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
189a8292b.json
4646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e65ac2a2e.json
5818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2581f9792.json
4068    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d30087066.json
1239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4c8f64c1.json
13705    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37ea8d2db.json
6975    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1917c88e.json
8681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d9c36e47.json
3325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae3a99b36.json
6688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9df3ead7.json
86    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5335bfb38.json
12927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8179f4d9.json
13141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6b0d8aa9.json
13096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1fb39ed5.json
11516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfc3e65de.json
2236    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f532707f.json
14405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b26fcffaf.json
2334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa1a30192.json
268    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
439aafc10.json
10444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd015c129.json
13629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f7d23e2d.json
3328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a965c1f0.json
6622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be340bbe7.json
8667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cef410e81.json
3561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d1d7a4f6.json
658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b7509f97.json
7004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da4b60344.json
7069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb11a4321.json
9078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c109cb7c.json
9361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c80a9ed6.json
9234    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b21dea224.json
3948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f34d62be0.json
289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b888f72cc.json
5755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52a539ef3.json
3513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a43d578dd.json
2228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fa760b69.json
1034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2e3cf5a0.json
14739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe5bc83d2.json

1787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
785413d29.json
10710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5c553616.json
2476    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5c1c54fe.json
6050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
714b4fa64.json
8880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c670993fc.json
12166    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1253241be.json
6329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c68936b74.json
2246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d55c2e2b.json
7375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85ec1aac0.json
6650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a1a1d801.json
13578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a226d8246.json
14182    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5944cef68.json
5242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f819c7b65.json
12292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0bf2b3bf.json
12403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
521e214ec.json
10934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afdc5f01d.json
2426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9a3f579a.json
4095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5a027e6c.json
664    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d583d44d2.json
7671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
481cbcedb.json
14908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3928a4b23.json
13494    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0434520ef.json
12245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cce291a9.json
13895    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecaf2b938.json
6958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a21f5e84b.json
12218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0162634c2.json
649    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
929528b36.json
10706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38e7577af.json
3678    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e910d17de.json
1530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e554a9066.json
10620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b37af97a8.json
7380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eaf13651e.json
4458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ff737b0e.json
10092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4363acad4.json
9502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66d4911f9.json
8940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1f0c1add.json
8935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed30f663e.json
5654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deaba5702.json
9758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
829853d11.json
7001    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2083834e2.json
10539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25dc712af.json
1673    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7ada8363.json
9435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58477a7c6.json
6508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ce27322b.json
6676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f14bc8cd.json
13350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5631a9c.json
3387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bef65169.json
9487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
605ca1a51.json
2194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3dbfe4c0.json
8076    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e3d78857.json
270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e9a56447.json
11067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70edbb1e3.json
9264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01dd8880a.json
12339    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1043aca38.json
9434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9af15c8f1.json
1499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80bee180a.json
9950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f246dec63.json
9901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92b89a666.json
455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67c9d22df.json
13154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
086e528f0.json
9327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdb5b7ecb.json
7751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b0f596b5.json
191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bb118200.json
8579    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb7804aa7.json
8061    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb217af6b.json
12425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41bc94422.json
1609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a83235b2.json
14906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f497b28cf.json
2048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fcaaf6e0.json
7197    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5220e701f.json
12617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98c265a0f.json
4217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf419ae71.json
14295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e1c62c0a.json
9285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e85b81d7.json
1201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea0cb464.json
734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92caf1d01.json
645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e2af0f7a.json
9162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9b4bdc1.json
10936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dfee7db3.json
7250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a536633a.json
14309    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8632f7132.json
5268    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6efbd2584.json
5859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
270461683.json
8527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
734459ad1.json
8690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
762a1ef1a.json
10303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9a4f831b.json
12450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4da1c9e4.json
14991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f24a0672.json
12834    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f0635623.json
12178    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
249af4201.json
2248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec4ed9fe6.json
11215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36a5b3b3e.json
14114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
245d6e033.json
11789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33bfeb403.json
6090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79c15bb50.json
5923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e093c4886.json
11649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc67e8b3.json
11126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b4a987ba.json
186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e8a11aaa.json
11485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
889ae00e3.json
2961    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f7a44198.json
10679    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dd8dd451.json
2992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

d083a22c5.json
7247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
649589d9f.json
9032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97a020fe8.json
11342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56bf5e254.json
4017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2288c4fc6.json
12507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c59c51828.json
11481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a4464471.json
1188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dfb61116.json
8169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79d32926c.json
1060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b1be44c6.json
1674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b28bc9e65.json
10860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cde9b460.json
10355    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3768e2be.json
13496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c64c9e2d4.json
11890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
228d72748.json
1122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd1947175.json
9505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9e4424a6.json
11625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd2ec7bf4.json
491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f6f980c9.json
14371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b6c5e07e.json
9222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d6d161a9.json
6315    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd0d78496.json
3293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12ceeda09.json
7113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce9d5fb9f.json
2367    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e3743dc7.json
13943    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
315d0e254.json
14662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50cbc6c8f.json
6998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3006cd3eb.json
6695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
951556f0a.json
12558    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f476ed34.json
8457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba4e5336.json
13447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c673e7ed0.json
10432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0bc43dd6.json
1319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
811b66c3e.json
14935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b690774cb.json
9748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41e4574a6.json
3505    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f44a43f4.json
13658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed9daa1ae.json
13475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c72bd65dc.json
8670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7678afa65.json
3252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a42c62fc0.json
6002    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed0185e39.json
3385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74c161846.json
7527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca7aa9eec.json
7164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de92761ef.json
4296    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7b468b32.json
204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
597a7afc2.json
10161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d81afce4f.json
2985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3268dcfd0.json
12151    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67d0b57eb.json
13404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ada8871e.json
11114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
642b0dbac.json
9508    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fed43b600.json
2635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3aaac2de.json
1286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3101cf5c.json
14972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7da3838.json
5404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d466bbca.json
14788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0238b8c2.json
d21cfa860.json
10720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20e46cb8d.json
6504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd3c1a3bb.json
4752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
505ef85e6.json
1540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fd1d2d85.json
11846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9dbf1095.json
12158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa97a865d.json
5651    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
787acfb28.json
13879    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b34c70e7.json
2777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3eee4f608.json
5000    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f2c67ae2.json
6309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9405015b.json
4542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
302eb3771.json
7724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e318160.json
6157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04260adf8.json
12725    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9af8f154b.json
11834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f247a5242.json
10389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c98d16315.json
8308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bbf5133b.json
7460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e9a3285d.json
14929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bcb0a0e6.json
1266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f95b39c6f.json
1257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8e941dbd.json
5898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cbe65e9a.json
10050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3cf90bd1.json
13846    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
642ed14e6.json
978    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab2e61df2.json
5681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8bf2c090.json
656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8685b7512.json
9639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58b4ba48f.json
4164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c3d7237b.json
2477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e80b8d2d9.json
14028    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e849142b2.json
6493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
035992662.json
12184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
840949648.json
7601    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88b4f478e.json
12890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebeebeee4.json
2576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3560a3e97.json
2212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bb720300.json
6792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0090eb457.json
11765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16eefbec7.json
2903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad6e56af2.json
6482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd54dcfd0.json
14811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5f479999.json
13691    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
407ef0ea0.json
9694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9514ed3eb.json
6017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf6e18567.json
2831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22bc76cf6.json
3562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caf3220f8.json
833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c552e255a.json
1497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e97446c37.json
12648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

21fcd15c6.json
8867    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a798bc44.json
9726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79d5a2615.json
2149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fde52ef8f.json
11198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
523aeba08.json
8908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b7b7b71e.json
2714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
021cb10fb.json
10698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3948f67d7.json
d08bc2c0a.json
6632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcd601baa.json
3272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da091c79.json
11513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25fb57849.json
11360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0afb7e845.json
9731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d808057a.json
8730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7df87757.json
1399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee9e87618.json
12949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42d2aa0bf.json
13241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5da236a17.json
5847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43100edd5.json
7116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
874e791f9.json
8172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41e792442.json
2780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5b5d2650.json
9813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
326c9c979.json
10066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6261c9966.json
13260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a4fb4974.json
4758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a32cab94.json
2408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7711871ae.json
5777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4427513d.json
6735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
285758945.json
3875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7d9451a5.json
11180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6029e0ed0.json
10486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
036af6df3.json
5517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f824e33a8.json
11551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84f065b56.json
1466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01d981c81.json
10617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32f617eda.json
14404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f6b7b928.json
13257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
283d778d2.json
13556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48bfc494a.json
2516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e74deb7b.json
5322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c273ffe1e.json
4424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab7ccc7df.json
14833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0d64a249.json
14497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94b6d93ea.json
13549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de7905c9c.json
12584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33d3738f6.json
555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f526c71a0.json
13256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8a2aecc3.json
4821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e10252ca3.json
8546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a3dc1dab.json
3974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef30ade75.json
11779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
138035c7a.json
8918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ba708d92.json
2932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
254dd6ba7.json
5443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfc3301fb.json
4316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a94208b35.json
5879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e60bbc064.json
13056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac7edef88.json
6576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
926070c80.json
6506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ed94ddc8.json
7169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ab8dddba.json
14943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc2012c7e.json
7970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d2f7761c.json
1312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db3fce97e.json
3890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19db3e21f.json
4740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f1bf01b6.json
6537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
373b98352.json
8610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f2be2e0.json
14055    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0825ad18.json
4873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dfadc371.json
137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4941c40c.json
2830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0f9efd52.json
3756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a9c5472e.json
9835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5d0fdfac.json
9468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4c27e753.json
3285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9abb10f2f.json
9355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8010a808c.json
4341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
558c419c0.json
4131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c716a537.json
5842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d67619580.json
5674    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
523af701f.json
13729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c15d26817.json
12781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11d3a4c0f.json
14865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8aa48ca7.json
10382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb8baed62.json
5761    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59ee91cf8.json
8470    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d83f98eb.json
3707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e33dddf.json
4507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5adb9d9b3.json
7340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3daf36ca1.json
10982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cdaa8a5d.json
8733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee71508dc.json
4294    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f4eb5847.json
11338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba66a7a82.json
215    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb4c6519d.json
563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b01a81451.json
11700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ce77d859.json
6429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19d7de899.json
1189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2db964259.json
1840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f319a49de.json
1784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff66c239.json
1558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4732c7563.json
6371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd201c041.json
5629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8df39788a.json
340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e76b8eeb2.json
1851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21cc6a743.json
81a176a02.json
1092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c35033b.json
11822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c84e9ae78.json
13270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e13c47053.json
13463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea03ccbba.json
9354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6e536800.json
13704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bebab9790.json
558    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16d94bbb1.json
5966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68c69f5c1.json
e3749ff79.json
10637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

e6f88d19d.json
7977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41487b069.json
4211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
352522dbd.json
1615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
546957a8b.json
14177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76a063a20.json
1420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecb3e47a6.json
2758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22987c7fb.json
5531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d50e11ec5.json
107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58a10d0cd.json
386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eef41768.json
6893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c58ad77c4.json
3694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e70a2beb6.json
6581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46518b224.json
1802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ea31c6df.json
14041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c390140c3.json
413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51366110e.json
13767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c3d3fb3d.json
9996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb15b64ea.json
4293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ce342cfe.json
4618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f5205d2b.json
8793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54ec12bf6.json
10915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65a98c48f.json
5173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57f8d18fc.json
1693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34452eefb.json
9406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6dc58442.json
14613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73a25206b.json
9596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b6d1b049.json
4961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b29bbd04.json
5070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08037d4bc.json
11557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aeb15ed5b.json
10625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54314d17b.json
8437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cd5acd7a.json
7124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9abe933fd.json
4563    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dff45cff.json
10229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93f758039.json
1039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
335aacd34.json
14731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
018188075.json
5969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23b64fe21.json
10070    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4e4b1640.json
13468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f99149151.json
8736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44b6a5b46.json
1109    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7133c0c97.json
9803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36dd5c626.json
12594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fae764f0.json
c14a3ac57.json
10701    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b3492bde.json
2264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eedb995d.json
6209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea3aa721e.json
10217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe5ed81fd.json
7667    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f122f712.json
385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f3fe015b.json
7550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0133b2a29.json
12592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d4e81870.json
9269    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e6a7ea61.json
13639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a266921d.json
3259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2034bc734.json
6880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acf333094.json
1817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6afe7ee11.json
8323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c8aa65f6.json
7753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70503cc75.json
5760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69d413ff2.json
2853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
191660250.json
11825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fd3df67.json
4149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
227580301.json
1256    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6296e909a.json
1    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d4c7be64.json
3137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1927c2ed2.json
4160    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd47ddc13.json
12993    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afc71f432.json
10296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e633a6647.json
9191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a9f9f178.json
1470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66ad04874.json
6378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75642f3e5.json
12226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ea0beb3c.json
10181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2562fec96.json
14925    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
088216e81.json
1915    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c8468196.json
14901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de19fca23.json
3619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c59199ff4.json
13284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec8c5413b.json
3800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c47497b30.json
3039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a7d3c17e.json
1832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d650d311.json
8637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02adb269f.json
7238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
432904c5d.json
470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
719917454.json
10649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d042e55ce.json
7181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dcb1fe2f.json
1367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
500327aed.json
9405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88af83705.json
14571    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d999ee22.json
428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9439e71b.json
806    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3faf6a0e.json
14954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
262d7f006.json
4537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
073f265c3.json
5156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0c943132.json
12003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a89bfa0aa.json
1636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
402799b02.json
9257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
455d243eb.json
3067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
451d18ba3.json
14270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133234595.json
12216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6be26ea05.json
13563    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
206dbf18e.json
11240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
794806010.json
7385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7c489413.json
3090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cb6e5957.json
3102    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
155e1f0ca.json
4896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bf6880bd.json
3778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7494b6aa9.json
7666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
284be445a.json
294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b974ca01.json
14614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b57c4bba.json
3888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf5bf91a2.json
13199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e0c995a9.json
694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e0ae8fb1.json
1258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ab7e48e8.json
8139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb507a1cb.json
8773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
544c16564.json
14532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a45e38c9.json
11085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17be61e34.json
11271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

988f48ca6.json
1650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3e2fcc71.json
13432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
251bace70.json
11460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e1f4504.json
10670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98567db2f.json
9645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
739002fc4.json
7779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d34524f7.json
10049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6edcc1f1b.json
13050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35df10380.json
7273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbf029a0a.json
5858    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47453584e.json
2624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c9de0c0a.json
10416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11757c072.json
5841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
058f21441.json
13758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
807e3b981.json
8603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db044e38b.json
2527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c7251bc8.json
7755    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9d8b22d0.json
14329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1882ebd32.json
11862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d09e065d.json
3533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52a88696e.json
2634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0caa3437b.json
14268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f231e1f78.json
5082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e909c484a.json
3712    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95eb301ed.json
3496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
530b7bcec.json
12144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
733f9942b.json
1469    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b47183f1.json
8316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64ca585d9.json
8979    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ec7dc903.json
1254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7eef3d3.json
5434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da06ed36.json
3672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b84dad49f.json
113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26627b528.json
1146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
156c2d6ba.json
3474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12ffabf23.json
7390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27867018b.json
12683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
349fe9b9b.json
7537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abe8790ba.json
1133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8867ee30a.json
1608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21415ffb9.json
4982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d168549f2.json
4622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
396a2773f.json
13039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68ac3848d.json
9565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c83d00bf.json
2330    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b73cc0f45.json
6611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f8c97661.json
10899    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
591fa7c31.json
5825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3c2305b0.json
10258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45d1d74ca.json
12569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72bd22c9e.json
14421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
779d50e4f.json
4815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9175b948.json
9339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91c4cb54d.json
11016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b52894bc.json
11216    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
204ca9f14.json
1541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5de61cf6b.json
169    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
794c57f72.json
5029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f6931436.json
13636    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d36f47834.json
10484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae14a91dc.json
5117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe4b30cfb.json
12371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21178f3b0.json
2834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef39cee1.json
12270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
105c28771.json
8588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70335663e.json
1867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
104c799db.json
2958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bec6af3.json
3640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe3d0c6e4.json
1402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89a396d79.json
1775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b0310013.json
11440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a6d97169.json
6908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b11972b0.json
2947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a55a04a05.json
8838    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ae940ec2.json
4169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d32494f0.json
13747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05bde54cc.json
1907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e25d4dcb1.json
998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f2948e8e.json
7304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38664cbf0.json
2545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d92d4242a.json
8114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bee25f46d.json
1573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a29d1df0.json
5737    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5145f87a0.json
654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1cb8764d.json
6330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fb548aac.json
6544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b1976326.json
387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a88733fd1.json
8849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edf6a5240.json
848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
411792ceb.json
2637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e922caab.json
11478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c60e6aff7.json
675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef896feeb.json
4580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fab3c124.json
2267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79d1b0215.json
7272    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29aa0b74b.json
1328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8e2a6a8d.json
14130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d476272d7.json
4369    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f98e4f7b6.json
11211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6502dbe72.json
2119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cfba1686.json
11852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c2e29219.json
9dae4e297.json
14774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0811bfc8.json
13429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e32f5a36f.json
5320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac31057e6.json
12771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae58f28bc.json
2070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cae004390.json
2325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a6bb49f5.json
11017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0806f9e3f.json
12021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71510cf8b.json
4310    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d49ea4e84.json
2595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b178aa59.json
3364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b446dd3c.json
7227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1123cd69d.json
2074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3af82b71.json
8536    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c11ca8051.json
10424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f5bd40ca.json
2189    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
803594e09.json
1389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06395bb8d.json
6503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
813a6335b.json
14719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

1fb9fdf7f.json
6027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4ea05a34.json
3186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eb9c5991.json
2977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb3bd80d1.json
417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad56c5705.json
3714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d687c7171.json
12661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aeda3d62.json
2173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c594983d.json
135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91ef9278d.json
3522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95cdbaecc.json
10115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a67f200f.json
804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36c4871dc.json
14007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0637293ec.json
429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f245f7d4f.json
8872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6d91de2b.json
11697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f834da3b.json
4813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
988988d5b.json
24    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83dff4077.json
2489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f7c7c248.json
7662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94135f81c.json
12548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
475098962.json
8309    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ecd80dba.json
12174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b4c4793d.json
14623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9d3b9ef.json
5195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe2757847.json
14080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd93c794.json
4509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c93191313.json
4166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80fcb8392.json
3818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c70a3fcc5.json
1347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47163bb58.json
8149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
622f08247.json
5381    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae089cd20.json
13150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a21b2a42c.json
6775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a6701090.json
3644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a38d4275.json
42    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
999d24492.json
7523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec2bb7160.json
14277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e7c16add.json
12324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6090e5de6.json
3739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe879c04e.json
9746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ed4f417.json
5817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbd225f09.json
1797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1e8bbe3.json
1128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0101e748.json
604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d48855c5.json
8244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c634af483.json
7635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a40628fd.json
11938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67532bb27.json
5430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b243ba27.json
14424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd579722a.json
13455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
353c89ed3.json
9646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11a30eacf.json
13573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49113adb2.json
1490    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c02a9554d.json
13058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dff1959b.json
1978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef7bdaf3a.json
9970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef14eb18e.json
8499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0154e0f7b.json
6333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa07ee8b8.json
13433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1117a135d.json
12062    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b207cf9ea.json
12524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1c14443e.json
7867    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ccda6476.json
9436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15956c89f.json
10078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fdd78c55.json
10438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db635ae93.json
814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355743336.json
1055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c01daffcc.json
2003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cad8537e1.json
2731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db1f9bca1.json
2783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5242038c7.json
3098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27f0a51cd.json
13641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4464efa8.json
6492    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
069064d1d.json
10147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e8c2a1aa.json
882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34ed5aa64.json
3595    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e649547.json
14476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43c43bfed.json
3969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68936da8c.json
3921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eefb8d885.json
901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c86e1aab2.json
14144    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b663299dc.json
1729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5287fead8.json
9059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe65d17b1.json
8927    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14bf62107.json
10759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ce0f0aa5.json
14398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0792dbfa4.json
4528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c457ca802.json
9853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a17ff971.json
11270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ce555db8.json
11966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58225b2e.json
8379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2124f529.json
8750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8518bd6b.json
9186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55f8f6120.json
4003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b60e920db.json
14370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c469973de.json
3280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fdf2880b.json
3304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38cd559f6.json
9243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96eb3ec09.json
3910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49310cec4.json
10464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f34d9c73.json
9920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c2100f6e.json
6319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3ed20ed7.json
7123    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09b7cd500.json
7775    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3da55a076.json
5054    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a68e8378d.json
2911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c82670f8.json
10125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f33406495.json
8904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df926a23d.json
1618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f2e4a2e1.json
14244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c72cb0d9b.json
14779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9fa9ce00.json

8280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b6c3beb5.json
7904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da4a5403d.json
12979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3740bcc5d.json
6965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c60a12958.json
14449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b43155295.json
5251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd33218b8.json
4304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3433731c5.json
14155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9e82ad8f.json
11357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e633386b0.json
5683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c9f6c718.json
6303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9086e44f.json
8663    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c71d537da.json
9610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41be30895.json
12213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8837fcacc.json
10560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a4a2e683.json
13855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
456908d93.json
7998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81e692e30.json
6252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e61d62489.json
4365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba392c802.json
12083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b31f1be3.json
1663    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebd128d90.json
2600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f2a40f0a.json
4436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dc98128b.json
9986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9bfec3ba.json
553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4424b719.json
14364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62f87187d.json
3299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42bec87cd.json
12800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b99d5d532.json
117    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a4fc94e5.json
4499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
311e28b8b.json
1065    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd541f6f.json
8804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12e711074.json
14749    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b2d6b1f3.json
1835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d67ee4d1.json
9883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad5021d77.json
6924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb82bfecd.json
12336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67be298a7.json
8124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
331c0bbf3.json
7880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be376ea01.json
7744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93c9866b0.json
878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f399cf0d2.json
7128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4bb8cf0a.json
3154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99cbd42dc.json
14040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f432156e6.json
3168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42af80bc3.json
13863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
326b17344.json
5512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcf13ec9d.json
786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44f198a24.json
13686    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caf56c307.json
10784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d7578341.json
13784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d4f64bb7.json
14378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef1966105.json
13620    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b921bfb80.json
3436    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11543e9ce.json
13369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7abf263f7.json
11573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca7a148c0.json
2392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdf958227.json
14806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4c3abf4c.json
11430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f555570eb.json
9125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f65fe3e26.json
6777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90592e40c.json
421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a16f85c6f.json
11607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ceec02726.json
10028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56e3f3baf.json
7500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5aff9022b.json
14871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
121ee5fa0.json
9034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c7efd1a5.json
1479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57184a406.json
9871    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f109dab7.json
8313    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7bf646ee.json
9933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2f8022f3.json
14279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
affeb8b58.json
14192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab38d8710.json
13632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
261fc97ec.json
13601    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
788ea6e94.json
14452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c155e05c.json
12354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30b9fbf81.json
9828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37204e0c1.json
1342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc7956085.json
2693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
977104c05.json
10703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3aa622eed.json
5076    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c4b478e1.json
11594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2b8dbfde.json
13868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
056bf1b17.json
13981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
318c35c04.json
10142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfe66604e.json
13481    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8daba029.json
4271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f9b31590.json
3928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ebcc7756.json
7629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83f13202e.json
5196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
214dbc1f4.json
12977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6549ffdd.json
5729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
653b3e668.json
2867    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d6a1b32c.json
8868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7977491da.json
7223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51c4018b8.json
14154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
404eb3b06.json
10228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e3dc5d76.json
14316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de35c9f48.json
1395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46539f4bf.json
8090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a119ce67e.json
3607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2bb6a3be.json
12895    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ec043344.json
876453f9d.json
4009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ac7e0c51.json
2827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a98a5b0e8.json
2928    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4518f180e.json
8553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2679a20fe.json
13582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eac9739c8.json
13673    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb8de7f47.json
7892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44d1246e0.json
8530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e84771c5d.json
14034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c76e9857b.json
13749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dbcdd322.json
11576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3397adec3.json
1462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be0e2dfbc.json
3819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
630fe24e7.json
10983    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3208c19d.json
2445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfdbfce71.json
14522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38a7b1842.json
14009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dca0bf20.json
7689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35a6a9ef4.json
1659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5edf4d9bb.json
6251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d813cd28.json
11908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
445c703ff.json

622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf01af28f.json
6527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b693ca84.json
10    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3db0fa59.json
3428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67839e63d.json
10962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af6364af9.json
10777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1894ab073.json
12727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15ee5f008.json
8942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c120a6f75.json
9224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
113bc00e8.json
11071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ba1566de.json
1798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85fc3c314.json
26    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac498ad58.json
11736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7575471f.json
10753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2d9924f0.json
1134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e800fa6.json
10931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f38dbd18.json
13319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ae9a98d3.json
2132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04f8947f3.json
13825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d8895245.json
4547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72f891e55.json
12873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f195c540d.json
873    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fe400328.json
12924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2c44393c.json
3175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2e22831f.json
14219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
933b2b3d4.json
2352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd740c8dc.json
11232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30d293a39.json
13307    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2bcb9213.json
11992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90365353e.json
6174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c213bcac3.json
7828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
751412a89.json
11980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35907f15e.json
389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb05c1ce8.json
367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e65375c05.json
5498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a684871b0.json
8519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0ad66343.json
9629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6aa53be7.json
7529    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f13a2d89.json
5850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c96423707.json
4442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6243bdf8.json
8719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
028d42a4b.json
9717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc8401c02.json
98    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcc43d4ab.json
7204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26365df53.json
7337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ece5f3ba.json
13041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9e4762d2.json
9075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03e429963.json
4847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f28c8090d.json
12215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edef78673.json
1321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a688a434e.json
11608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d7d23a52.json
3995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
680e24130.json
2075    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
870fc2931.json
1689    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4406b18a.json
14854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c89e5d2b1.json
5614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb6276b35.json
12630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
997653f86.json
12768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf357f057.json
13194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9deb1340f.json
10987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4a3c0456.json
3346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f61e89a28.json
11419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
132cc7d6c.json
6913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b6f2ff52.json
3949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5f54d20e.json
13584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
289cc7f88.json
5482    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
660742236.json
2315    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d33840dfa.json
8082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
631c813af.json
13765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0753ad1cd.json
10791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2c896c5.json
11136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23ce26e85.json
7476    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1f01fc04.json
6586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
950dd345b.json
8475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2385d700.json
2572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef5fcd597.json
13357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
745facb3c.json
14955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71ad8e81d.json
731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c6048341.json
3214    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d0aa6427.json
6498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
739cd2d34.json
7512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0bfe80e3.json
14115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e8d158cf.json
5640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
503a567ed.json
3460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cafa50dd.json
7999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff3d455a0.json
2422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43c661026.json
12263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
711bebb99.json
5929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51f1d14b6.json
1839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c11df559d.json
5618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab8386c6d.json
980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1e6fcd95.json
6807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b6690d89.json
11347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efd805ea9.json
10190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ee32b27.json
1387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75e343c91.json
5597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88dc80de7.json
9232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
554c80a2a.json
4545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e63a7dd84.json
11313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5267f524a.json
13897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6df28d790.json
11738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69f9ebfbc.json
1888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f77a10b5f.json
1570    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
461b33f39.json
12937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
823fe0bbd.json
5493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ac6d621b.json
5751    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff6ff53c4.json
7194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca144ac2a.json
891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e115d8ff.json
1927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aa6cfaaa.json
5248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfff88c90.json
1525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1b3dafc9.json
300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f796b0a30.json
5219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d2745318.json
2690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
196d58932.json
14237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da424cdd7.json
13246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ca36463c.json
14246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

1a76d3ffa.json
13426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92b6acf73.json
9978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68d7d01d0.json
4721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb9e48ff.json
5446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b8008b16.json
9380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78ccb8039.json
7424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ec0f1e9e.json
10176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de9e02d44.json
2121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15dc4c629.json
7483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
748207a86.json
13612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
479500716.json
318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d967671a.json
14121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
311157c79.json
10920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1fcc8c4.json
12887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88cc4d5af.json
7219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0c2a069c.json
11496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d981b6395.json
14990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ca5f1891.json
350208e1a.json
14900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7db48c47a.json
14942    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff22356ef.json
3679    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6b24bc4.json
11558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb817b755.json
12197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d35a6449f.json
13904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9403ac24d.json
8303    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50af81612.json
11918    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79fd13ffd.json
1694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcfea60f5.json
9549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
953e3ebd4.json
11754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
371d7e8ad.json
3648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a3607d09.json
14359    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1751240fe.json
520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c2e0fc7d.json
1404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91633ef0b.json
6644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afe19c37c.json
8214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b6e5343e.json
5569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea3c51eb3.json
9206    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
076e5c59d.json
8688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b75b46ea.json
11525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de0202010.json
11723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffb6a7f5d.json
5697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4ae1eedd.json
14066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7faf2e49d.json
1453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c18984292.json
f124ecf25.json
10671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
706a9cd5c.json
234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58396d68b.json
2342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f80157011.json
12483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d55faa0ff.json
11134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6edf4f4fb.json
11272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91568ddf1.json
13540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7af4869d.json
3715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8b358af2.json
10262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de1a20009.json
11475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dfcfe139.json
5689    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bf5ab7bd.json
14420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67f351876.json
8920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94dc821ee.json
12608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3d8c3aaa.json
11188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b01ae317.json
2450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15cc01168.json
3333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86547ad6d.json
481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d551fb5b.json
3241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1a2d9477.json
10978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb1775dbe.json
1895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
319e533b6.json
8693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c9ea9908.json
3426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df874dd59.json
1483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e51470c34.json
9238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f15d587a7.json
1565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8bc0c25c.json
5890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b66a5bd9d.json
13245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea433c341.json
1437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
147e587da.json
8458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6333963fe.json
14638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4fcf4990.json
9562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38470b3c1.json
11128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ab4df736.json
13403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1ef30b8a.json
3758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5a240214.json
12015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
295a99691.json
14605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
899859c9b.json
7517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a4a4b403.json
6458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6c7f3a13.json
4526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87241775f.json
7198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
878214747.json
6131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0cbab08b.json
12186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1052f933.json
7080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4db45721a.json
14106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
036e015d2.json
10447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
806bcf604.json
12380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5ee02201.json
3447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b7179c65.json
9879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d5ac408.json
6668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e753137d.json
11667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e62e6022.json
72    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9123c847a.json
14933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52e555a3a.json
194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d70af36fd.json
4548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3050bd8df.json
11642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d82fddba.json
2303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15a06cb97.json
4848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21f4a6abf.json
12872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9cf525bb.json
13078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bbe4e4f0.json
2650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86f7b4013.json
1431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f595e715.json
8893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c0771fde0.json
1196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c49c9df2.json
3590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86e1089a3.json
0    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c1340a91.json
12679    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17e6747da.json
543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133af5fc3.json
11689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79186dded.json
11381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d6318af8.json
4026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03f130f5f.json
14123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7517f68.json
676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b43e7b1fe.json
11868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28f1efe3c.json
9063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf3491020.json
12853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
378406cf4.json
1211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d2c3b550.json
5299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86f41cec9.json
14063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
863738ca1.json
11354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02cd64831.json
1721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de8b7400d.json
9212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9783859.json
6515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af9d89c50.json
6567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c23b6bbf6.json
4249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
644d07ccb.json
8765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc7d90ef4.json
7299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1e153676.json
4219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9eeadf82.json
277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a27a03914.json
13900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e030b331f.json
1764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c12ee8ef0.json
10692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9817c3ef1.json
13137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f31c806f.json
14750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b077aa9ee.json
7310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7687b7da2.json
600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc4670dac.json
8050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52782bca8.json
8354    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
585a4d5b9.json
13323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a27c67eb.json
12914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ca4780f5.json
4040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb8cce181.json
10925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
548093fa9.json
10675    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acc741f2d.json
8784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21847129b.json
5930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82905a82e.json
10310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95ee4775c.json
14422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b03336851.json
2698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e30182214.json
1762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fa8b64b1.json
8067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c2aae63b.json
14621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a686164c9.json
8166    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1952397d3.json
8373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c3f9ca37.json
1754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
704737525.json
9635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9784a88.json
11637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6de0087e7.json
5771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53b442005.json
10581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f3e35156.json
13049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b8d76961.json
6655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fd464902.json
4090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6e4a6f37.json
14310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cdb41608.json
14217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9005c792.json
9649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
063495ecd.json
11854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1e590596.json
1391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
559afad4f.json
8044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aef9fc86.json
749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86d02f6a8.json
8004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36332af6d.json
5499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
094ba0325.json
11123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
470e49e41.json
12726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6f98ce2.json
8738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36b20cfb5.json
3783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9a47ac7a.json
7095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7b44276b.json
3805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f31b6eda3.json
6132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
046256943.json
14491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d28b3255.json
6892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bdd7f7ac.json
3493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77653ab79.json
7205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39366118c.json
10645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3bd4c99e.json
7532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
804e56f9b.json
5451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f60e910d.json
11334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
414e5ba55.json
8602    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a983562e5.json
7934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
489d05a55.json
561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c8960273.json
9108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e50fb0c6c.json
6900    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83705e888.json
3002    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f95b27325.json
6022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ea49aa4f.json
11099    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0a24f910.json
12994    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc93d7cc9.json
8604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e5476a10.json
9402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16316fb49.json
8704    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11960b9ed.json
710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f094e80c.json
3658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d751fe45.json
10785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42dd3f3ff.json
10371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f489059e0.json
5399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fe32151b.json
7810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7b3f752a.json
9045    2
Name: Type, dtype: int64

<class 'pandas.core.series.Series'>
73680f695.json
9519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9031a7f4c.json
8258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0063c5b6.json
6229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce9332934.json
14332    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
576dcc546.json
2571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
102c931d8.json
10818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
134e12e92.json
7962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f91cc9f0d.json
8817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0deeed2d9.json
14971    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdb0f50e0.json
3481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2aeb6a1f.json
4116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f412d0fc.json
5091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7131cab79.json
3204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
396910627.json
6710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74084fa99.json
11279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c32f8daca.json
7464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dc54e9fd.json
11040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25079d00a.json
7284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13a563b84.json
4951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b9cedf4a.json
14303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d9b202c9.json
138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3fb26abc.json
9022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5042c6414.json
2721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39a784870.json
7619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e0a9cfec.json
4960    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b05231f8c.json
8096    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a0d25864.json
6853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a93b3e4e.json
4791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df4354823.json
14886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13c67e713.json
4417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b26bf64a6.json
11004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f461cc30a.json
11894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b477ad589.json
4607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41e069381.json
4770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57b35b749.json
11487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
906ee1877.json
2356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0cd0a4cc.json
6752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2e5b8ae2.json
9766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
166345ac8.json
8069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00eced1f0.json
3976    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82db604c8.json
6218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c9b5b646.json
9559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac1b33d79.json
10631    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b940cf8b8.json
13724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b49312951.json
8296    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e81c6347b.json
426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff50c6171.json
9806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09f31b13e.json
5933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d3b5e6e9.json
10578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9180e09cb.json
13723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b8fee68d.json
9976    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4277da90.json
12284    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e343f4df.json
11061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd75bfdb.json
14553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60ce9e319.json
104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d25867cb.json
11262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68a6c1a24.json
6160    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af3d7c201.json
10684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0898504e.json
4468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62887c0ea.json
1769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afab70239.json
12664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6715d925.json
11628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87975de34.json
7395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bec55c577.json
6758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c222a4955.json
6066    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efda64fa5.json
4202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee8c56246.json
11763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f352f8dc.json
10076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb1f2f2f0.json
4611    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58a12b66.json
6774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fe0a86f8.json
11666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
492e0cc50.json
8545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
106128c56.json
7541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
577de26db.json
1233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
422059173.json
14716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d6c6055b.json
5832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8b975c1f.json
10919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
484af2d62.json
2095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16ff0c687.json
6186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7aa0bcef5.json
12451    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68b7c23f3.json
2178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcb0314b0.json
8771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02d9e61ca.json
7cc9b21fd.json
14255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
304f1260c.json
13902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82f52a225.json
12611    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39e9ecb70.json
2266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1035db262.json
4543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abfcb22bc.json
12891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
962f76f58.json
4329    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c64232b3.json
2413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab17ce306.json
2843    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133c0e6b9.json
6466    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d16562746.json
10087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb16182f7.json
9614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18810b958.json
5532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38d0a0bab.json
13930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8f35138d.json
1874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f0f81a37.json

282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb1adae2d.json
7445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9242ba394.json
10091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d90e5473.json
5115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
700de2c49.json
686    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0adebbf21.json
7564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
211b0aa56.json
12765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a372e8416.json
791    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e6d8a2c9.json
4225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b0d903f4.json
2894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80b657db1.json
14263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
596d784b2.json
5924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43021e4ed.json
5770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faa9b9b84.json
7549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a181c011.json
10194    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e6970298.json
14178    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8daa38a67.json
12314    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
175c5bce0.json
3938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e8779496.json
8084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f9abe87c.json
7256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2a899dab.json
1435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10516f3c6.json
3406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1246bed4f.json
6594    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67e6db7dc.json
13144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
257a99aa2.json
9918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d1a986bb.json
5576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6d879376.json
5222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9faeb952b.json
6589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e0380f1.json
11796    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaf465c30.json
3708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6292a7b6.json
11296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
034259113.json
9056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79420447a.json
7280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4066ef07.json
12579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04c9a643d.json
9964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2e46582a.json
12846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d2fb911c.json
7884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f012474b.json
11957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c7b2f093.json
12290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5cecf5df.json
5993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e058e06f.json
11155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11bb6fca2.json
11512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c30dd6e9a.json
81    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9104803d9.json
12673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
938bcf142.json
192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4c153877.json
5177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75fccfb43.json
12607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a9a4edd7.json
2299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b226c6c.json
13002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff9d8cb25.json
3356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baf7a42fd.json
13748    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b5a3c81d.json
1059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b729ae6c.json
5632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b9a1b086.json
6999    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab1cfc949.json
9736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c70867d90.json
11019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34d0c00d6.json
12958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7e61f3c2.json
2174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5842f1ff5.json
3    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
720db9cb3.json
265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d7204289.json
3979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04d25d8a7.json
3281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f24b6cd6.json
99    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a484694a1.json
7888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51d880078.json
14635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f9f1a2d0.json
5159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f4e5c2a0.json
11704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4544aecf7.json
1392    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23eddf1d8.json
7873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64568c4a6.json
828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
944db63df.json
1076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a45142177.json
5109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
334975a99.json
5157    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
906308870.json
13311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0907a14f3.json
8808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ee05e0d5.json
8271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ec31e51.json
14012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03f48e12b.json
4349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f291e702a.json
13709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01928bd13.json
11045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e01f077a7.json
13398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69275e62d.json
9621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26bba34a6.json
9053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1fb1b5bb.json
1876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9951c57fc.json
10113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2936408d.json
5015    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2eb9530d.json
3360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
923a03e90.json
10830    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62da2d031.json
3487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6708ff204.json
4077    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7fae9937.json
7757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4b4969b2.json
2974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41a7d5bc2.json
5186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ea675148.json
6529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e1c81876.json
14486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b6d2c65f.json
12383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fea70079.json
7646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
810ff9d37.json
13813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
330943a7e.json
10800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

b80a19455.json
4755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd829526d.json
6714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b38e94f39.json
7469    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a572b746b.json
8140    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18b6fc5f0.json
13221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c0de1708.json
10927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd53d5f04.json
6381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81a815ef5.json
384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40e578da4.json
14661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1686cafa.json
11207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a97c693e.json
4236    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e00cd0ac.json
884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee01c4e6c.json
13576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9316ce78a.json
12577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4552e7972.json
8785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c324e80a.json
8128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
282678629.json
2328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b8805c58.json
4080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c421064dd.json
13353    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b13db9ce8.json
4184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19926213a.json
2893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
549c35706.json
9775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4316f2bc.json
14253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd68d0b58.json
7801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e9959db4.json
13250    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
426662616.json
13712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40fcff82b.json
2765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb9ef04d1.json
11984    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d84fc0c5.json
3339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4212729be.json
6247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a64e72cf.json
298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32aa78316.json
1194    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adbce8472.json
3879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8435e081c.json
985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5d08e982.json
6685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
243aaaf6c.json
4072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a56ae509.json
8206    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91389ff80.json
11795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cd1cac68.json
416    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3316a5619.json
2092    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffbc3eaaf.json
4749    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45dbc315f.json
9107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12537b530.json
6763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7989fd303.json
9859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40b1839ea.json
14099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b02c50d9d.json
8890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
121c5faca.json
5006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97916de84.json
5980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ef34251f.json
4993    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22adf3b63.json
1699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05e3bc1ae.json
5439    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2aa20dbd.json
12815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9bb69a1e.json
3978    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19d8b1d8e.json
6285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad4456e88.json
8265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0ef38cff.json
14235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1f4e3174.json
12224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24ee3b57d.json
1612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b73c5a1b7.json
11054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3525855b3.json
2735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b412a3f6a.json
10425    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
938de268a.json
13327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffb315803.json
13672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ff817b98.json
2340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a662626a6.json
1360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fd78af13.json
3453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce0deaac0.json
6716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dc24448c.json
e653e3c51.json
10781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc537bc7f.json
11489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e877b448c.json
13365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19cb228a0.json
8335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e3bfe5a9.json
261    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b03114991.json
6580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dab3050c.json
8322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77035285f.json
12276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc1b742f4.json
8433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60bf93971.json
276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8859f46.json
1564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94563fe71.json
2020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfed6fcaa.json
5455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e468e8d54.json
7808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea678fb08.json
9314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71eda06c6.json
8689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24af5742e.json
9772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
789083f3a.json
8255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd67a3f2c.json
1526    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5357633c0.json
13771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ae30dd8.json
2402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dafb0cea4.json
3907    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8d244dd5.json
883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3086dc257.json
9272    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8229b256e.json
8091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cd7bfaa6.json
14864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0b82db0e.json
14888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecf521843.json
10094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c31f3d3f3.json
2767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8581566cb.json
2307    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8670bd551.json
4748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d225055d.json
8955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16a71f0de.json
6257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a0ee9580.json
2583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90204109f.json
5386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26b1d01eb.json
8646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23379775f.json
550    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5208915a3.json
12889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ec161c16.json
392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae6f25120.json
9439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63a5af53c.json
14549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d41418f7.json
7158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ce5d0b5f.json
9352    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e1e7c4ec.json
6169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

859426703.json
1683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bec6cc26b.json
11856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f1a700fd.json
5659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fab9b8f3.json
6514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fd1d2349.json
13971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7eff2bd81.json
8777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63ea7cfeb.json
3546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f18b4092.json
6175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a37e46e35.json
2951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8bf52aea.json
4876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e90137a54.json
14818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e72120027.json
3760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8267c4eb.json
13186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f03da51e.json
12510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2e529567.json
6112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79e510cb9.json
9177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edb8ace3a.json
6108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
183e445ea.json
9397    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
917c0bc2b.json
2197    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
282139c6d.json
2155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c5db9ed6.json
10207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55e32b4b7.json
1385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
746fb982c.json
7275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60a36cab1.json
8109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
629df03ce.json
6911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
babf0f6cd.json
14700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e9ce66e9.json
6636    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd4f3b8a8.json
10880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207298884.json
2984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5aa74c6a.json
4266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8940dfe55.json
10309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
059baa037.json
12460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ca9db40b.json
1442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19b7a9e47.json
2990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06fb72c12.json
10806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04ea19d2b.json
6454    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d25ad4b76.json
4370    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd1bf9554.json
9442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15b5da7f8.json
8625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0535c8c.json
7146    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
457de178d.json
6418    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe7bad7d4.json
6152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b2f6d5b2.json
3761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1be4f433.json
2975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76c276834.json
4731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03aae5768.json
10027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
517f1dc1d.json
7047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23b3f793e.json
4115    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34a6cc7b2.json
9672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af8138fea.json
9754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11ac3640c.json
5894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86f40e2b4.json
c99720dbb.json
13968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
987095c9c.json
4000    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52d65015d.json
7092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce27e496b.json
8541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c3793826.json
9537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be07596c5.json
2720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59cf08ff3.json
13007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc7dad1da.json
8036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fa23fd14.json
4518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c4d99f6e.json
9203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1cb5d0ec.json
8549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bf044649.json
2063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a39613fa.json
3429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c92de3f6.json
12448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3be154287.json
6395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ea8e240f.json
4270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b72e14bf.json
2084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dac60bd9c.json
4383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4570b618.json
1737    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8016d3648.json
13867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cecb3b8ef.json
12721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
059d8d91f.json
3844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54c5d6442.json
6183    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a29dba165.json
12139    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10a093758.json
14294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0956e39e.json
6859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea3de2587.json
8015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
725ee6572.json
5410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ed5663ae.json
11844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7630f3d6c.json
5507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c15424b.json
11367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
235a61374.json
11989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f071f1cb7.json
9682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bba2fb084.json
5417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0bc846b.json
1748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f618c35b8.json
5067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c228bf013.json
4194    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f8d00436.json
11858    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79075eca4.json
2035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdc7db9b6.json
10711    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45f9a9f66.json
4412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
451bf38f1.json
1484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
263b17d23.json
6836    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1cc143c4.json
3732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12a280806.json
2886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff5158511.json
7288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72e24597c.json
4695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b1abca6a.json
2849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
828f0e616.json
11565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa41fb473.json
2391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfb8b6b93.json
14111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51196cf13.json
10542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cc3e27b5.json
4869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71b0f7f97.json
5907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64e5f3abe.json
8380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dbcd1d36.json

9242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dfcbe364.json
4510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9fca8be8.json
14741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
107c49414.json
7330    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0256cac2b.json
10808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab519bf92.json
5830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5fd255aa.json
6341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17c4b0394.json
11974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c94ecc07.json
3887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58fceabe.json
7942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10eea956d.json
4787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b984a461b.json
7147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fe4f4b78.json
14415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef9b5808b.json
7876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c04c9cba.json
9913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcdefed1a.json
1586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ede28a9d.json
3314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6668ff629.json
10951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
216840542.json
2986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24361123a.json
8288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13a1e27a5.json
14607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4546c89b3.json
5797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e5e35de8.json
13834    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f33f3512e.json
1930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf424910.json
11024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa943b9a0.json
6421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd8c80281.json
8451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
973dddde5.json
13893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70a7a71fe.json
f235e6a5a.json
14325    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
231fe619a.json
3403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01dac4b22.json
2443    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
531452675.json
5011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
412b93160.json
7257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb8aeff64.json
610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd7b805ba.json
12391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcd6d7e62.json
1651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42e9334f2.json
5056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f653550ac.json
e49b7c262.json
13255    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e6385ded.json
8937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01da89f29.json
2832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
670535e94.json
1676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a12e3633.json
14736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
beb3a6da0.json
642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca4224e0b.json
4627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fad223ef5.json
12071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37a8dcdce.json
7789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
740d9759c.json
13325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c281122e.json
9877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46c44f7bc.json
4209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e19f2890.json
3127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73de2789e.json
14481    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
847a8b31d.json
11029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fddd8a5b.json
13706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0b36580b.json
14139    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03cdd9324.json
12488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4a508263.json
8300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
366a03818.json
304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fe4122ca.json
8814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a03da4900.json
7373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45217971b.json
13807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98f0a2ac7.json
7819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49ba2ccff.json
14630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc9c0e1e7.json
3913    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39fc7e6d8.json
4561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b8a35f8b.json
3882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6a5867d8.json
7117    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4831c683c.json
420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2ba9bbf1.json
12497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e23c47d1e.json
13163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a54497b9a.json
8951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
147a0fbd6.json
6353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
679d0c196.json
5267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
976cd59b0.json
4742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6146d435c.json
4075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b743aa88e.json
3681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd38f7a48.json
4333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37d0748c2.json
2674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d3418da5.json
2381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08fb442fa.json
13204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64f41ee68.json
2428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe7e662c5.json
3084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b368f29c.json
7875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
119903786.json
2284    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a018ef15.json
1097    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aa5ab22f.json
6534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5bb33a17.json
3942    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5728f078.json
4386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a52a7c357.json
13845    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
026c202c6.json
6683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5accbdfad.json
11106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abadb839a.json
5074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5df99d229.json
6138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc601e041.json
14980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b8ee289f.json
6299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ccf25b91.json
12738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f9a15807.json
10606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d5e7a3a3.json
1611    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1758efd47.json
2446    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf6cde86f.json
12219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
351d29156.json
10749    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c9dc0791.json
12938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e2bbb163.json

6325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbba10f87.json
13818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5149bb7f8.json
13016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddc3af1ee.json
11385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b66a74309.json
8080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd065921b.json
12179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe15cb88c.json
4466    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd0a144b0.json
12235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5486d844.json
10970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abdba6d36.json
8238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ca3f6d92.json
9029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74fb03e51.json
7911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7da9d50b1.json
10259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81c442177.json
7326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8599dc67a.json
14036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc037ca46.json
1861    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0d2a12a2.json
5559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3effb8d44.json
14241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e390710c.json
972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
642a88a93.json
845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d111847a0.json
1168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08b9a3a2f.json
3422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58a4768a6.json
4450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af847ce9.json
8516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09ef02857.json
11028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10400a0b8.json
7953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01ecd8b66.json
5298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e25112cac.json
1336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5d0fdd2c.json
8789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07914c759.json
4983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
902624c4b.json
4709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3813bc7c5.json
5605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48c5a3c40.json
6737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
532396459.json
6301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
064425a21.json
3862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7a94dd33.json
7627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baefc2985.json
2604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
274c7f123.json
9018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18c3b1a1a.json
2796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36f07fbe0.json
11169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68e6d1bd7.json
3735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f102632f6.json
9513    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
605eca728.json
14075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30e66b835.json
819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fac19639c.json
13288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee7d6cf3f.json
13019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7433339b9.json
4462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b65fa006.json
13045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20c3c2ba7.json
8423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aa2d99f5.json
1825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dac377c6.json
6852    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10a3c8b71.json
1529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
369d96f21.json
11221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a30e92cfd.json
3264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d35c1ab62.json
11877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5493d0771.json
8991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5297d9ba8.json
13581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
833408fc5.json
5982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4060848e.json
13717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cde5f25db.json
10410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5317b212.json
9551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69d8727b7.json
7865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9db446f8.json
3697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7314cb848.json
1164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8ea0c6a7.json
6617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bd867d1b.json
2601    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f6f8b365.json
13111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0063bd7e0.json
9409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc7361016.json
255    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04b073592.json
6167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a5b2eb43.json
10370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
890127ff5.json
11568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6dff6d40.json
1942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14a9958e0.json
2186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d202e4c9c.json
9727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b49012dd4.json
11909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2ac8316b.json
2313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73704a89b.json
8744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3280fa256.json
14808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f05bd40c.json
11303    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62b9cb163.json
4788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3185d954.json
1746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
581100fe5.json
11245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8167f58bb.json
1426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5698c00e2.json
614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6984c9c58.json
3641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
176e54ffd.json
13519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e706014.json
12399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb802c0c.json
8185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89446d475.json
11209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f393a9d26.json
6547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c0214da4.json
10700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dccbb182.json
1515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aff5fa8b4.json
5948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
895d8c870.json
8571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03edf613f.json
11902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
527071e27.json
11205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52c904832.json
5912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59d42b6bb.json
13778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebc345fe0.json
11891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cdbf07be.json
11349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06ee33d56.json
13600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3b26191c.json
4502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e417850b.json
3233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

259b10a3e.json
75    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d8032dd0.json
8002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
919a7dd34.json
1884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba58bb1a4.json
1040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e111f82d.json
10751    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a811328d.json
10693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e08644762.json
5743    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c7b7486.json
14851    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15d4c0bad.json
14056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38ea54f1f.json
13110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
263598073.json
10223    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7be394a98.json
917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfddf0c47.json
443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53ef098c0.json
7253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbcf2baea.json
10112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1da78c20.json
1979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab083aa2a.json
14104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5ff5915a.json
13318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a7860ee2.json
14524    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7dd71467.json
9163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc55b081.json
3196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bf834f39.json
458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
839aa5fd0.json
11434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d8622f3c.json
9082    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8f94e1ff.json
8477    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75310196e.json
1491    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4f813a7e.json
11777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7aa682539.json
2202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8249d599.json
4918    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00f63c6fc.json
6686    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06cc44fad.json
4750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7196383a7.json
5638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bbd4bbdc.json
8980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ff9e9534.json
1986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3f69b209.json
1875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdd815db9.json
10756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dacaf7cf.json
4287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c59aa98d.json
5798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe74d6173.json
12614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fa5384b8.json
11876    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e61aceb9e.json
1487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e4eb9198.json
1616    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3118bb24c.json
1745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edcaed3a4.json
14936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06bf9e676.json
992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092a37bcf.json
7303    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
392caeaed.json
4828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
199da9e42.json
10873    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33ed78569.json
8635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1667eb8a4.json
1585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be9c5d746.json
12365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13485ebf1.json
14475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c714104f.json
9850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04aa54436.json
14176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a00de73d.json
9624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3244cff21.json
13719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a543418a3.json
12928    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8507df043.json
6452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c28b3a879.json
2987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b7be833c.json
7335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b79275092.json
14875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f2879b04.json
12408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ce1c6a93.json
3932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efbd4c1e6.json
4229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
662af5b80.json
1666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e04df6caf.json
1100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2619f003d.json
14507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
567b92b70.json
1752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58dde7d7.json
4677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac59f3533.json
3651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9fae270.json
5405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f512ee65.json
7465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
006610fe3.json
11613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
533916bd6.json
2233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a79fe858d.json
927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90bcfd0e4.json
7663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c74b069ef.json
11585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df26f1098.json
9486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
435bb3995.json
3051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aece30836.json
12597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3101d2bba.json
10622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62d6817ab.json
1101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0164a9cfb.json
2638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63cc8aa47.json
7931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a7474fd8.json
4964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e5e057b.json
2244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a61a5963.json
11153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dc193313.json
3260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64e7edd37.json
13675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b3f851f0.json
8636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eabef1496.json
1172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33404ffe6.json
4107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9cab5e67.json
10732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faa62a75b.json
5928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50ae3720b.json
13336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10e723583.json
11935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f128d3ed.json
4797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f70571a3a.json
7534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f25222ce.json
7781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22230a3ea.json
11509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08267e916.json
480f33a74.json
2514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff4b9b3b4.json
10882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf537cdb3.json
12814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03db2966b.json
8941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a0adfdd0.json
6091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70f92bae8.json
3730    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e372fc09.json
1556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aa9012fd.json
14272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2614882d1.json
1224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e808d9fee.json

13992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11a993099.json
7246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
553164b93.json
5124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05d10428c.json
12763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ea9285ea.json
13958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a460a6274.json
5956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e71c9d710.json
1468    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d302ad015.json
2261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3f51f5e0.json
3885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71f895aa2.json
2718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd565b4f7.json
11463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35296e056.json
13258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83b2d9103.json
4902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
199277f1a.json
7384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7454afee.json
6275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24890da9b.json
5055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab94dbe57.json
8479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c267a86af.json
3815    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b912b1114.json
396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c1a9d86f.json
870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc371c173.json
4372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50361acf5.json
1013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c28a8cec.json
178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3a19b9dd.json
9690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b84493d.json
5467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf1b1b824.json
3618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a36bc3b5.json
7000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8a1d0a54.json
8727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fe58286d.json
1280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172555cfd.json
6000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3745aa22f.json
9896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f580ba98c.json
4319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b227ae56.json
9047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d154eccb.json
1768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13426c720.json
12522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b721dcaf.json
361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63df28877.json
6443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ad937f6c.json
11750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d822305a.json
12361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c278935de.json
14035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a053dbe6.json
8582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f3e1f288.json
11620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b623d9449.json
12811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d0315769.json
4698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d0ff357.json
10222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0ece637e.json
756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f10643d7e.json
14502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4813ff89.json
4093    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6d9a938f.json
11542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aaff4d83.json
4323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f64ee888.json
13461    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9d07d5fa.json
17    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a120cae65.json
4549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f66357936.json
6988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5b67698.json
10297    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22de1a590.json
3116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be3247b2c.json
3146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
045d9a498.json
10293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62bf4037c.json
6828    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
869a1634e.json
2087    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09eca4557.json
4579    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76de48e98.json
6274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ded8d95c0.json
10916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3e5ffe13.json
10348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9500cfff0.json
6170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
241b90aaa.json
1696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27bbc8c4f.json
9204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d758a13b.json
11311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2a9dd71a.json
5330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19cd32fd6.json
11429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
871ea8021.json
9322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3a5332ce.json
1080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c155d21c.json
4146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc4e92b83.json
5255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dc32d6fd.json
13331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57e37b00b.json
4320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50f87522f.json
2973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8a48180b.json
11370    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd819dd9.json
1623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bde40e198.json
11234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f82b8bf0.json
13121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1bc7e3c7.json
13306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d1612f0.json
12826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d94a56ef.json
6803    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc589864d.json
3135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68f3cfdcb.json
1720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12ba67e43.json
2791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afda0a2dd.json
13714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e936f5f63.json
660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9668972cc.json
1554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a12222b9e.json
13198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c22ebfb78.json
9897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
896e76b69.json
6623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc14f3a48.json
1269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c25f4969.json
6705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8132fabfd.json
11037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e80066a19.json
14705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11d741736.json
4345    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ebf6e448.json
1333    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bde802b84.json
1325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34cedf9bb.json
380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9b63ae80.json
11050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
387a2639c.json
10715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa64cfa4e.json
13201    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe7b03ebd.json
9782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fae8116c.json
9822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31104de48.json
9855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4c9325d9.json
9323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
729042a8f.json
8677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16cb3f1e.json
5954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c960bb1bd.json
11436    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc05c35d.json

7599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6316b9647.json
3021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7d371a3d.json
7650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99d5d4d41.json
14663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65dc47112.json
11036    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eb34434d.json
7276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14580436c.json
3094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32618b795.json
8064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86ac4d6b6.json
9586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ead795bb.json
430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edcc13ccb.json
9587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
087ee8e83.json
4221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bac4c29.json
2761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c239d1834.json
6480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fed21411c.json
5033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0073c33d0.json
2023    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9317ae6d.json
4190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9e6b1a1b.json
13000    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
683f1dfd8.json
2529    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6b908d22.json
8236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
005bb92d8.json
14579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a71f9ca6b.json
2818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ded648294.json
14791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1a3e3aa1.json
1583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8af4db3f3.json
835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
703f1a4c4.json
9184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b574c312.json
91471cf89.json
12642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c96f9d3a8.json
446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e92ebde6.json
8692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7efd5522d.json
7014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffa5c6c35.json
14432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df9a4b31f.json
10478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
352ba3335.json
10103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7910b841.json
11356    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b3614a92.json
490    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c2f669f2.json
1637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
603e173e1.json
13872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
518384a79.json
8607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6af981c61.json
1298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce5bb821a.json
3195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f90f6ca1a.json
1384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474db10df.json
14707    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23df34fbc.json
7990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
143027239.json
6024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4b028ea8.json
494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5701c7885.json
9916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b12fb6709.json
2318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d440b00e.json
1899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc22c806a.json
11129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
770f24682.json
6030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52ff28c14.json
6085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2813f2ff9.json
2812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a79983c71.json
1909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a9793dfb.json
13    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85f71876c.json
14555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edac63019.json
13967    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e938a436.json
6121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d985e1bf.json
14855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
079f5f1e4.json
5307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092c46fdd.json
11317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3a2d4d83.json
2869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9646e275.json
758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3828225de.json
4082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65a7711bd.json
13040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f8471836.json
6220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bee984e11.json
6490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d57b8c2fe.json
7195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
979bab13e.json
13779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baf60f1bb.json
5843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f533475e.json
487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8538f4aa1.json
6300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11c222a3c.json
2112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4ec04b8e.json
4984    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b13bde34.json
10193    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7676842c.json
2939    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
390c45d0c.json
6414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed8703dd2.json
11530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9614a6b17.json
7700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7af09e92f.json
10912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afe9d7dca.json
8618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9945b5ac5.json
4179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dd780fe8.json
12287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aafb75ee8.json
313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef91ae200.json
9741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6423eca8.json
518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7a8fea6b.json
9214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c19fa21be.json
11537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea0802eb.json
1155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f80c9dc5.json
4475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b7de4bd.json
12227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f16407c21.json
3822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65de38d1d.json
10952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6c14a824.json
14733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db4995bf8.json
11077    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d7dd6115.json
14552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d85af6c4.json
2660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9de6b8550.json
2923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
647284f19.json
12065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
681a6f552.json
9607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16673c028.json
3993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fa0de4e4.json
4143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcf2641f2.json
1528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
983160271.json
5807    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f01beeef.json
6967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8e79c8c4.json
7224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea65fe96c.json
1785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
151fabf52.json
11639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e5d8fd10.json
fd23f6a15.json
8671    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
189bb90dc.json
11745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4bdcd89c.json
5719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e297b5ede.json
8584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b685abae.json
1679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e40290fa0.json
7016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
171af089c.json
3250    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50844e473.json
13047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efb7343fa.json
5342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f17cc636d.json
9656    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f67dcb4b3.json
1304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df8425410.json
1956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
099115d38.json
3081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8813e5e4d.json
2729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

ceed27182.json
345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
977cfb864.json
5878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07b6336e5.json
9466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b554c6e3.json
12892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98b66836d.json
10452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d3448f9e.json
3801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d7111b92.json
5725    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de08c8d31.json
11416    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
420f5cd9c.json
14351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2355d242.json
8480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93ae9be69.json
11561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ef4b6cf3.json
5312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67e8df1d3.json
2833    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ad34749.json
2043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa89bfa82.json
9117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18cd75354.json
4846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2a1b5401.json
13881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a8f89229.json
12508    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63fda9824.json
7226    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3161fe0f4.json
6978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1f4af354.json
5275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
002230dea.json
4762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ef541435.json
13100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c842fa148.json
1416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8e8a47fd.json
11683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
955d40492.json
8522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
782abc2de.json
11644    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55f1edd7d.json
4598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd9a060d7.json
2072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62332ea2c.json
14765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbc6507e7.json
11835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3859838cf.json
11278    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8efcfe9c6.json
14920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
872317673.json
7160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9d9f8fd6.json
13321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69e10dd04.json
1738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2099c09a0.json
5492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94e45a1a7.json
14842    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9092993a.json
13599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
920cfaad3.json
4710    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49fac4dc6.json
11423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
271712276.json
9259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
962c84aa9.json
5481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a2b95086.json
9973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31653bea0.json
10187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1055034eb.json
10691    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d7a45689.json
9922    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ad21fd0b.json
5572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d6db9370.json
12962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3eb7ac8c1.json
7046    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86bf33207.json
1827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41fa17c7c.json
7860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3853c992.json
12694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95914d469.json
13938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cc0c6dee.json
9050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a556d826.json
10120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30aa1059a.json
9966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
727b7e63a.json
14594    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bd200942.json
821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
752c4af59.json
7060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
747125bc9.json
10191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
523912c83.json
3107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c0508818.json
5437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0490c8df1.json
12464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35542ae3e.json
14410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbe4be41b.json
4152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fb30c1f8.json
14300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e829ee7c.json
12055    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f5636404.json
4880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3207cde7.json
1868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e768f382.json
2371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
681be6214.json
6278    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
283d93104.json
11755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a88d34ee3.json
240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cee52ff2.json
11013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
082838f84.json
2719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc19f9c36.json
5796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89c8b19eb.json
4242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d66a55b13.json
7814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3902add8.json
6665    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61fa73996.json
36    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cac71d5bd.json
9371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29a08292f.json
11377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd71f9fb4.json
4667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7beccedcb.json
5899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b165fe8b1.json
14839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce6fe7377.json
4067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41ee53918.json
3085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b12e22341.json
5101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8867faa98.json
3405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a04c35bc6.json
5279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5931099f.json
11651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0737e4f11.json
35    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73d6ab7d7.json
2877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1da9f428.json
1113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b9e24b37.json
1066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd3856456.json
8983    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80f8877f8.json
708    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
648340d89.json
6037    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

f096fcbc6.json
7295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6fbfa344.json
4998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99ba1c605.json
795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9314a12d.json
8763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
660cd67ed.json
4893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
838e46496.json
5670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab8dfa983.json
2346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61bedc57d.json
6146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4be1b15fb.json
4051    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddae7aede.json
4312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e1f78a77.json
13082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0a993ac.json
1843    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f82a9cd0.json
3396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fe763187.json
7856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
654acdb4b.json
2229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a56c46193.json
4694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c778df64.json
12142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f99a5e817.json
606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b4caee59.json
4404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d16b6f6.json
10033    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b652b7241.json
3828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b0b7dd2f.json
3348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4874347b0.json
11885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa328a5ba.json
7282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f29dc8be2.json
10249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70a534945.json
3273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee7c25387.json
1704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd8224d08.json
6614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a9733afb.json
337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a6f2f7d3.json
13443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc9557824.json
11068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63c794465.json
7807    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474294e01.json
11600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bc9bf272.json
12657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc54b47b4.json
2161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dfd61242.json
10487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63a4f8b8a.json
14499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d356b9f6.json
14619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a84326ff.json
2317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b114199dd.json
1633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee5583527.json
403    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bc51f69b.json
9013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9d955ac9.json
5252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8c1859cb.json
727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a89d4e8f3.json
2300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f6cdf26b.json
7087    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7550219b.json
14095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
600f8eb25.json
3152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da1899776.json
10513    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a01ad9084.json
12942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fea8ac52.json
9089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca17a355e.json
3538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04a555b91.json
7579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86550c5dc.json
365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a399a151d.json
10343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07877aea7.json
4851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c46298f8.json
11636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9b1363e5.json
5543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4bc89962.json
14974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d77baafda.json
3835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a906ff5f5.json
12908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7d0b2194.json
7698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
276ce7f3a.json
12400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaf4a1439.json
71    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bf1bdd86.json
3e2347b40.json
8615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a234c6496.json
2836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd25890d.json
10935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84d7ac922.json
14252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab0bb2f5a.json
7976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f3bed708.json
12504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cabb4127e.json
9210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f5eab89b.json
7471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a98d5b83b.json
2419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e63e3eba8.json
11386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b807a7dd.json
11376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1b5c8b92.json
2001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d03b6d7c.json
1077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec4849051.json
5204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cc070892.json
1347325db.json
3170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f4b73413.json
7084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6806f15f3.json
12779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc14cca27.json
8966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40fa3f339.json
3553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6f768f75.json
12515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c92ce464.json
18    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d46569700.json
7878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fc640ad8.json
524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb9aa1b3a.json
10414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172b6f611.json
7132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae6a2116c.json
3838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fb715361.json
8436    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b932ab38.json
b7e584546.json
10433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
696b615fb.json
7717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
956548cd3.json
7924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e557af46.json
9342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d1c1d51d.json
5032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9928594c.json

6915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c150efc9.json
12379    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4e748c72.json
11753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9efae474.json
14276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff14c3dbe.json
7121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dc8f1328.json
1736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
689e4e3bf.json
1364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad9ad0883.json
8903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
144ad89a5.json
1808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f220ae6cd.json
2988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43a43e926.json
5491    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71419d422.json
2837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7baa8082a.json
9471    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57189db08.json
5707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30610dfe8.json
10623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72f092b4b.json
5057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61f95d269.json
7396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77d395a82.json
5427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cd149470.json
12472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
705a6dffe.json
8542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ce29bb83.json
13506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bad270818.json
5750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e315452b5.json
2488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b90e6ec69.json
909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01a07b591.json
13610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42fc9a244.json
1948    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
975cf510c.json
14813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d8dab6cd.json
2241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6f26f19.json
6119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d17892c89.json
5165    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02d6020a9.json
957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d08b5b163.json
13374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b97efdcee.json
11903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80785f31f.json
5541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59b6102ba.json
8283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7821d724c.json
4490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3e897856.json
13923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
756eaf5eb.json
4942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa9df3011.json
9413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9303d3bc.json
5873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f0abd493.json
10157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d538c491f.json
6438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
573ee1a1f.json
14831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
083787e4a.json
7455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f27915d51.json
2711    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
281e2d7e8.json
954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccdc0f862.json
4867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be21567c3.json
3141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eb152e2a.json
8611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
796774834.json
813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
399856928.json
12896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbf6ed419.json
3630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dcd7351d.json
10937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f2785c07.json
14680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21a7f4896.json
13718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a52461bfd.json
6298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3517189ab.json
11052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d43092e3.json
13562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
964cf32b1.json
9743    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b27f46ae3.json
4140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0178fe2f7.json
8716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2284e2e9.json
2628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2be9fa813.json
8512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe481f81c.json
6332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ad6f6fae.json
3776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d792dd24.json
14261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a655655d4.json
1272    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19f5a15ab.json
8858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
351586450.json
11564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57785dbb8.json
4183    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2931d3eac.json
1357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
329814145.json
5216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
390e0a648.json
12893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78fd8ce0d.json
7298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd9d97bc8.json
13948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2676e6b1.json
9863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88a5b8318.json
12317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39a66e7cb.json
9019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4436738dd.json
11774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78e5e19b6.json
13964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d755e40d7.json
9723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d8f211f8.json
12842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88f092c58.json
12974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06c5ddbd6.json
9705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc081896e.json
12735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33f89cb83.json
11547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5893d408b.json
13147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6d5d0df.json
10651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebba4f83b.json
1208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e7a3b766.json
4617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
439f040ed.json
569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092418816.json
13561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
393365063.json
10521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59a23bac0.json
9577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d29627289.json
9793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6666265da.json
14150    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d2afd85f.json
13518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b06d39b09.json
14914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
081301773.json
11971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6735cc397.json
5354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73d59a848.json
10415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a31d58f0a.json
7655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fab464fb.json
14632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba488d80.json
4832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba758b7f.json
8281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1250404cf.json
12175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40dfeeb65.json
14470    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1e2b0af4.json
13457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
113b2b57a.json
636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c99e3a906.json
10020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18a8b9b6e.json
3615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
484915b4f.json
4562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
694a730b4.json
6703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
417c09a08.json
4566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5768c4e2.json
12503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd279ad95.json
928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd067a495.json
7638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faf6a8cd0.json
1102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c02ce1bc0.json
4379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355e3bdc5.json
fe8bac73c.json
6137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b3efcfe0.json
9124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67c74483f.json
11112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2040d593c.json
7559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

9804a7d82.json
2425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0c159af4.json
8953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cb63297c.json
1865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6335f2ee.json
6307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97cd20357.json
2177    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5b48801.json
8967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad463dd0a.json
1826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01a985b44.json
5831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df880995b.json
14160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16349e686.json
5877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b4a33baa.json
11455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8425c2a48.json
14889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
775d4b52e.json
2588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cfcbd9bb.json
11706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
060d1de98.json
c7b3c09d4.json
5566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4c99a552.json
9937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d9a6398d.json
12585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfcd19237.json
4441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e61fe015.json
7573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecad98f44.json
2078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b19556858.json
8235    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
124eeac80.json
6928    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cdc6cab4.json
2590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b0ea16a5.json
3433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34dd3cb69.json
13708    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa0e8c199.json
8788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86629a3ee.json
9804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26716b324.json
8473    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474e70ba1.json
2117    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ea482068.json
6612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc607ef5c.json
5987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
532ccd0c5.json
4245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f3434f36.json
787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9809485bb.json
701    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
039509c40.json
219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f317f2e7.json
11592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce27c0f68.json
11025    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
867308404.json
85    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59c474c59.json
9448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93641e3f2.json
5406    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffe2090b3.json
6843    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8fdeb33e.json
13890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3fd60eb9.json
6952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29900d942.json
1136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c2549da5.json
7035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbfc5a778.json
9943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e04d44883.json
8863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
429df135c.json
8965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f923ff77e.json
1458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca40312db.json
10489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cfbdd28a.json
6691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85d242c14.json
12064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f58e5dd5.json
2376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fd2f589f.json
4413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abd7a3201.json
5241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89c28aad0.json
4141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca457392b.json
8596    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b9c3c05.json
14337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
188f8b07e.json
7343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5de76fac6.json
6242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0be6d2a4.json
11522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52cf4a759.json
2670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcd23d8c3.json
12211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6da4c5df.json
8685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8519e771.json
8552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc8aedde4.json
5918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2def0a43e.json
3897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37965a7c3.json
6023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f0cbc167.json
10575    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10fa4505d.json
5047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dee6cea2a.json
8447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56ba19506.json
13676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef73ab8c6.json
1250    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7c0647d0.json
11497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72acdecb7.json
1548    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7993a02ee.json
3962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a8caef08.json
842    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84b297843.json
10213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
261cbe336.json
697    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9625d0998.json
14496    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d4c1513.json
cd870fb18.json
10450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa0010ce5.json
2710    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cef0e42a5.json
2026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f6d23ada.json
4354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5366eff00.json
14195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfb59bbe9.json
8643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76495d7f4.json
10941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b8b38508.json
511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bb43df82.json
10966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
288edef23.json
3820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9907dde11.json
8634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a7b5edbf.json
290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10022add6.json
1806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bc18f57d.json
6398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b119aa181.json
2240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2101b975.json
8184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c59fe4bcd.json
9454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1350a4af.json
9431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eae8cc31.json
10165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f205876aa.json
3699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

2a726e0a2.json
9714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
507e734af.json
13238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
468ba458d.json
2957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
818df5a9f.json
14321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17bdf954a.json
457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
110d4487e.json
321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfbd5c54d.json
13249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf8325fae.json
3906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3b6d78f5.json
2062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f9cf8892.json
2574    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f26b1b5c.json
2448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f18ce587.json
2685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a76510109.json
12397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a929a9f48.json
11747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3013d9169.json
4972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23941ded4.json
2146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4931c712b.json
12785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49006b8c3.json
6059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b71a3c06.json
6766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72d753384.json
8431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d30dcea91.json
2647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
725a5345e.json
7855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8de0737e.json
13174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba4f42314.json
13776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf66d011e.json
3398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b630ac493.json
2113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
799ea79a2.json
5864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec040a1ef.json
4027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28060651e.json
10557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd4500e6c.json
7502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1663d062c.json
1917    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8057f0a8.json
12789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcecf2ba5.json
8577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd4ec150.json
13108    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b024a4ef4.json
9657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b24d9186.json
5207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
252b8d395.json
11288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecad4a875.json
8686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
363e8df66.json
12325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ae7359ab.json
5292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64a40211a.json
9518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cc43a157.json
6049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b28de653f.json
476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
696e2d638.json
4366    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c16f5a6df.json
11925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26a351904.json
3853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a75bbea18.json
2916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
570fb2f6c.json
14197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6ff21b7e.json
7764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a9e7158e.json
436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abf02f04c.json
13920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47cda4c03.json
2835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6992bbc5.json
11884    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93ccba02b.json
9576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e85c2b18.json
11977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2374a1c12.json
84e1e59d5.json
4503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44bc5f67c.json
10807    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed14eb16e.json
11579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca39efaf2.json
6084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25c1c662b.json
1274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38a81271c.json
202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a2a433c2.json
5891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01802debf.json
9636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6730a4a60.json
14639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9141b7803.json
12723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86d42fe3f.json
3729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47dda9537.json
14738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb90062ec.json
13477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8e3f9ddf.json
9528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1a9d98fb.json
11308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbd0c8f36.json
4633    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e9737811.json
9040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
467bd5bc8.json
10964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2c54ef30.json
6430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6ac8884b.json
103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf99a973b.json
14051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
752eb9714.json
7344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c996aee9.json
7314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8e6cb9b1.json
10474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39818f12c.json
5005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
920a30b27.json
6197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4df3c8b8f.json
7024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6cea4edc.json
4768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
162195d38.json
14001    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6154a6716.json
5042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96477b249.json
13876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12380b365.json
1050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f64f8a464.json
5272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cea6df421.json
11502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72a7cb335.json
228    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79b439763.json
9329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
378059791.json
6791    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f5804c61.json
13196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a5e5d34c.json
12251    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4012be917.json
2396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45b98b4f.json
9912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fb8e5e73.json
4654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bf08dced.json
3190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e73c3dc3.json
4407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91736f444.json
12705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2fecc9a4.json
10725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
798ff640c.json
11896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10e27da02.json
8254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

68a603bc3.json
5429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e73648e8.json
1718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eed4b685b.json
fbb3db415.json
1952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d0b49c8f.json
5628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c1fa0fdb.json
4049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
186779691.json
14049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e79dc4f9d.json
8407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4d84523a.json
6872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31144a6be.json
12531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15a491e20.json
1227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fcee4bee.json
6604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
180b3f500.json
7144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
485bebd4f.json
12921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0644da7d9.json
7017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bd033254.json
7862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69df3f618.json
6526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
898ad5d4c.json
12289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5390fc59f.json
12651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f41847b5.json
10429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc8518f88.json
8599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2260ef0a0.json
1607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b02d9e413.json
8217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16dc1188b.json
4678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
779bcf3fd.json
6282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2302acf06.json
5911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4de32c463.json
2850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
429296d6e.json
1246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9862e5dfe.json
8163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82f1872bf.json
14008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fad77d5b.json
7821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f3781bec.json
9833    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79799da25.json
8d970238d.json
10114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9499f293e.json
7989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d028bdea.json
862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c80811400.json
13679    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb0e74ef1.json
6226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c8613e80.json
3759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91298d5cf.json
3270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
158a55025.json
3504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a04b2403.json
4866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9d6b1488.json
623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3e19ff68.json
165    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13d30c173.json
12850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
919768bb5.json
1678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec59f8c50.json
14368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e686a63a.json
10306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b4ac67f0.json
7386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca8aec089.json
5937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1d2cb34d.json
6404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63c93929a.json
9662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b599b3fb2.json
10364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b138f5cc9.json
13795    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
894d76b65.json
6055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da7895cbd.json
14233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb61d1c46.json
12073    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
880e13787.json
13903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9385e1d2e.json
2806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b110b315.json
9300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b9d80473.json
9719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5a07b1cf.json
10500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3b52a69c.json
7482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff6118cc2.json
1925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06daf9c05.json
3397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58eb3249.json
1522    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab38d2296.json
9404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cda71c00a.json
5753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66bf65c82.json
12677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f18d332de.json
3103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e754315db.json
6380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f3f14a72.json
10813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
998488372.json
11698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f7b002f4.json
6428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80524f9cd.json
1656    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9e6aa241.json
3596    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f6779706.json
5302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d4b69793.json
7732    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
563eaa005.json
12495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10e1cbfdd.json
9841    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22051ab84.json
91    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
525947b88.json
11081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba5526238.json
14610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
859b1b236.json
14609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdbc1c567.json
10783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5147c0162.json
12646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c29a364bc.json
9939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16d4039e7.json
12277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e51267f5.json
14462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce18c7a4b.json
6907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24336f580.json
8298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27aa5bbfe.json
6583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73b5c37dd.json
10281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c17cad5a6.json
2163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
052b0ada8.json
921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a4b92653.json
8328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45b295426.json
13444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53cd96ef8.json
459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b22e78544.json
7788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c08e68b.json
2085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68838474a.json
9895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
435f8cb3d.json
10153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f35a5dd35.json

4431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
243925f5e.json
8605    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed08c717d.json
10137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62b8390e7.json
11803    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dd7c4c06.json
6123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14a16b96e.json
7231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
829889fa9.json
4637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a0cda147.json
913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd9d521c5.json
7388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f51acf95.json
13430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5884b684d.json
10793    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdcd32165.json
10680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
164462023.json
5329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f3962d65.json
12702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95d951387.json
12980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b154dffa.json
2543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8693c4e7f.json
2114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eee3ab446.json
5665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
767be5091.json
4980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57d556084.json
6944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d880df4f.json
9868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7117c4553.json
11190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37f127385.json
465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75fc7829e.json
4881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cd8131cd.json
7467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc08b4198.json
4930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05ab54e3c.json
11809    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbef8d00b.json
13910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19480ca6f.json
3395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1d1b893a.json
13344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ef8c54ee.json
7545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8a528b69.json
13067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19bdaed52.json
1559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1d05e431.json
5979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8db6e695.json
8259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a5a02164.json
4923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
764837930.json
10689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cd76da7d.json
5314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4836bf864.json
10888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
627726d36.json
4043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99558286a.json
692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1238ed024.json
1702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f642366b6.json
6815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cca2f141.json
9284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b85a3893.json
12278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7cd5b749.json
3437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
309f63a00.json
12538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b93a2c373.json
11397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ece28cf0.json
3550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3883d4f0.json
14793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fc2970d6.json
14172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e2723a38.json
4796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d2811dc5.json
14456    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc0ee2c73.json
782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d3dd0cb8.json
4599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a20eaed8.json
7566    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76024f2ed.json
13048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95c01e235.json
2743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
476d40031.json
6457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c47c94411.json
8371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8960dc21e.json
831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a67bf90d.json
1144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c546c236.json
188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3ac0a96b.json
12271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b04b200fa.json
248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c3481fda.json
14281    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df2fbc6a6.json
2143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
497312a16.json
2100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80aca536a.json
52c15bfee.json
12266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b39ead375.json
3860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfceafa8a.json
7433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
802798c57.json
12050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3998bcfec.json
195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e681e0cbf.json
13591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c6c71a55.json
8593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11b3fd45f.json
14222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0dd85af0.json
532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8b6a9eda.json
6225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c226ecabd.json
1f4a53e6c.json
7939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
518f86025.json
586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6492f0d.json
4935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fb06a963.json
6722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22c2f101e.json
8000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a0f0b8c0.json
8652    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc9c5a76d.json
1981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d43834f69.json
9490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
102482c40.json
861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
702bee848.json
189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
234a5a54c.json
21    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39d055888.json
7507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b0ae25f0.json
5442    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f42bd15e.json
8131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21bebd773.json
12319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bc07d296.json
6851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b0f69f61.json
3889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e20655a10.json
362    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2599e55c5.json
10488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7e2b4c4c.json
13451    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91697ee90.json
7640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7542076e8.json
7516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f7bf4f71.json
536    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9da26f0f.json
10669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a996f1370.json
6592    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88f79f7ee.json
9038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
136f22028.json
12165    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fce854722.json
8182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ca5a506e.json
14211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07d2a9eff.json

7871    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ff447944.json
2774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4325e9930.json
8943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64ea72fca.json
12707    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f9d7b0f9.json
2609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e16a68d.json
2237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac6d69d99.json
14978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
797725280.json
2447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45a59c4e9.json
12005    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea48a6a7.json
8278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cf7fae9d.json
9244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d39c87657.json
687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8213a645.json
1760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c44c99ef.json
11030    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5afb6da05.json
3198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b0d325d8.json
6494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45c718348.json
2451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df0933e46.json
8515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3219ad064.json
3547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1afd4033.json
7163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64c4f9057.json
2578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9aead110.json
2494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6968f86dd.json
13217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c20aa0352.json
6184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
281618ba5.json
994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c55e9baaf.json
12149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef80d0222.json
13059    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ea25b63b.json
4374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57f322839.json
9446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
838b5c426.json
13152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f1b39562.json
10788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30507c621.json
13644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91f52526f.json
8684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91c023cb7.json
8917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
222ee828b.json
9401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
388bb6170.json
9969    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6450abed.json
5997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
428fd4ef7.json
10848    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da327c74b.json
460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
104910cb4.json
14335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e21edd32.json
12583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c228bdd5.json
4024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60bbc32b6.json
2057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0f88616c.json
1010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0936ce7b4.json
8127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33eaf34b3.json
4717    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58711512b.json
12392    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
014ce5783.json
11953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
115a4b208.json
7721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07638746f.json
8037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca587cb42.json
376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3faddf18.json
3972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4b550d46.json
6704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a983eced.json
4101    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e46744bb9.json
10730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
718b14a08.json
2605    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e22fd2e.json
8391    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cad1405fc.json
14068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37bbc6060.json
1804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e42dc215d.json
1057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
799aad68b.json
5218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a3796cbd.json
4022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07dd9a0a5.json
2908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c32940f0f.json
4593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80255c391.json
6410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b69bf0e7.json
3046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fc65f2d.json
1018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd6a6d0dd.json
3637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39ba962ef.json
10008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a892f5fd3.json
13833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3029fcad6.json
6362    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f982548b8.json
11910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac81fcc4.json
6467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af49cf598.json
7623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
debec416c.json
5949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11b9089f7.json
1710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b26f1c630.json
4180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
476dc0901.json
5965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48a3fe4ac.json
4956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c584c54.json
13963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
849ce39d4.json
9934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a14ac037.json
1958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22c43e29.json
847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
add617e3c.json
3529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d116bb3f.json
14453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd0bfa1f6.json
9208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3acd4da3.json
7591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df89cc1e0.json
14064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d4e58071.json
7603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c517992c8.json
894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d99012d9f.json
5297    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dcdbaaa4.json
6980    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b8e1dd80.json
11975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2209979e1.json
12100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8170c6b01.json
4732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef690f7c1.json
11775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53a451386.json
7630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79e5de9a7.json
14583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2c1b469e.json
10947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56ddc4f47.json
3490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b985b4ff9.json
8742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7fa60cfb.json
7293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
318f45a57.json
8845    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb4eef57a.json
3955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb78d1aa5.json
11133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

018cb4eaf.json
1137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6d3839d8.json
2661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9942bce62.json
7322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
308a16b6e.json
4952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23e49bd2e.json
13405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0822c54d5.json
287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b25498d6.json
13043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c237475f.json
14208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89f389a59.json
12640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a8fc4913.json
2864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5376c81df.json
8378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c18678ce5.json
11681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1100bff90.json
7772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebb74d225.json
12843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbc39e84b.json
1349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a83d4455.json
3468    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d63b7c4f.json
8525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0045ed62a.json
12308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
416d8761e.json
11076    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc39b80f6.json
14577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60fa6acbe.json
6159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efd269df8.json
10277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33dc6b53a.json
4222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
404eab70f.json
9506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6ad8aa1b.json
8422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b94b99757.json
12689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ecaaae2d.json
6208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b6883f3c.json
11820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d5b6616f.json
9179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ba068d30.json
7315    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
618f4931a.json
12309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cd614218.json
8421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d605fa35d.json
9948    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
911464bd8.json
13983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7575df7b.json
425    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
012a1a396.json
10504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6469a2a4a.json
13631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1835a56bd.json
2148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f294123c1.json
8029    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acde4eb5b.json
5758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5f6e77bf.json
2708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12dce436d.json
4824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
756308d39.json
10713    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08fc1372f.json
13590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
338ccb571.json
6126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e54ee8e55.json
369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cf6ead97.json
9702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e748f52b7.json
3578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47a5a9516.json
7347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5fb430f1.json
12248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81614060c.json
14444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c397b09d8.json
5555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1d1e399c.json
3512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbf3467d9.json
8586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae4ab31ec.json
6190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cde0d8e8e.json
9952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f0dca87f.json
5757    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ce681aa7.json
5936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1f4773bf.json
5560    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7595f467b.json
9808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1596957.json
6827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78ad8f1a2.json
1064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
611045510.json
6392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb85ae31.json
8555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eb101936.json
6087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bce78644.json
3225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9b9b0174.json
13926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd2f64ea7.json
1225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f94ea9d92.json
2331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eeb377c0b.json
11768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fecd2bab.json
3359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dd6704a1.json
9365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c8b66066.json
4395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de993a4c9.json
2412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
072bb91b4.json
9111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74d40e344.json
5809    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e58bc75d7.json
2706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1eb5f685.json
10939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b91e1082.json
3215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8361219e7.json
5544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bfe95866.json
9697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcdf10cb0.json
11661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b07678538.json
13286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc22a5abf.json
10235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
035ff37c6.json
12590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ba4ccb80.json
14790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43c8e589d.json
8651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0902b6664.json
14598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f60ee7233.json
1303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
730a09014.json
12315    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cce8fa6c2.json
14671    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77e679018.json
11361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbd0bf6b1.json
6064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9deed930d.json
4279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
564356241.json
2858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ac47ceae.json
8712    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a1b56e66.json
11498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6344c2cde.json
2667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca74b17a9.json
12480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
040736f83.json
7061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76f668025.json
2642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd0757cf.json
10595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea9ad03dc.json
12734    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61f0927c3.json
a24a102b1.json
13932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35c761c35.json
3162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
227b372a2.json
7981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
323e4cb89.json
5549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eada14618.json

10463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db05d2fb1.json
3421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92a038846.json
8396c07c5.json
9226    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
161718095.json
6790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1577c976.json
9756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cba5c76a.json
4800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f28922e.json
5108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd5797b7f.json
778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e42f0f7a.json
11500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d596234fc.json
14479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d7cbe8b.json
12849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f785304ad.json
6602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
991519fdb.json
6860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
326355730.json
4362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e14e0fa4.json
6840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8088575c.json
13921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7648e56db.json
13279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a6884283.json
4854    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d59322d58.json
12769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d29d34cfe.json
9476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4999e2693.json
12479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf2cc0a1.json
8970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
292447561.json
2224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d714680ff.json
3352    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db0875ffd.json
8897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8eb5d1d04.json
3308    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
596aedb84.json
5617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b36167be.json
11374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6492d3b1.json
4103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff85f13d7.json
8698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f34d790b.json
12037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62583aec1.json
1910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35dcf4794.json
12733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba030cdba.json
9851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
664d0bed8.json
2483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9102809eb.json
741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52d336af0.json
7557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
679dad3c6.json
7711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a5463e17.json
585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e09a22e0.json
3873    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac3d34246.json
6899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca113d98b.json
6553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61c1f3481.json
3777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b73cf161f.json
6829    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d83aa1f02.json
801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8e1ea097.json
13831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3275bb3bf.json
13434    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207c30391.json
d806d8c60.json
10436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9af3fec83.json
4927    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0855d1dd.json
6233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
972fba985.json
c6a2b6ae1.json
9728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
884ccfdad.json
12572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
208843e22.json
13546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b4dad348.json
1993    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71edb3344.json
11571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69a1b02f6.json
10736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
011350faf.json
11145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7519b8b43.json
12936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04a5f717a.json
7719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb928145e.json
9202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8623ecf43.json
8865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e04814e10.json
2128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7115607a0.json
11197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef7f27ab.json
8489    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01c202740.json
4657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bb34f0bd.json
7526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aece6e7bf.json
44    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b901ae31.json
4945    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b820b13d.json
1153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2502292c8.json
919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b93196dd.json
7489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fa1c5c38.json
7487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15f0dc937.json
9710    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c260c7b3b.json
7102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc4989906.json
13251    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcdfc6cdd.json
12194    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35e96ea98.json
13424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5b9343c3.json
7840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35593da00.json
78    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b949e5c7.json
2350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b4bb2b0a.json
12658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0428af8ea.json
9485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0bec65cf.json
4681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6df1895ea.json
11630    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68731378e.json
608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9f914ed3.json
7740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf7d3eec0.json
25    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74f15e0fd.json
14157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c35cc3520.json
7134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2346525a.json
254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f506dd65.json
5942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eff5c562e.json
8595    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0e37eccd.json
14159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5574bf3d.json
11534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9718baba0.json
363    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa8e2a85d.json
11947    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4559bd457.json
13375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ea3193d.json
6351    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eee978cc3.json
9168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63cd0b2b3.json
8250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cc846427.json
5550    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3ae374f7.json
3812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f678d1cf.json
1199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bead49ed.json
6761    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26a7ffaa7.json
8878    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb256c605.json
2901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2697fe84.json

9668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70c811b9d.json
7278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faf64d6a6.json
12867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91c2edae8.json
9069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a3471df7.json
2662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80034deb8.json
1885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f518238a.json
14407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
081c2daa0.json
11343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff7ff0f3c.json
826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
816112569.json
5763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fd056050.json
5238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ba1009c6.json
11987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91b580948.json
11301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bcec6d18.json
4511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77c076881.json
c56dc5726.json
14431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eeb10b7a.json
308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a53cb0980.json
4649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
258fe3053.json
14003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d42b92c05.json
6976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6178884d1.json
4150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78a1d23c2.json
10162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a34b7e199.json
9759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d277a0abd.json
9926    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
420bdee9f.json
10244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be36182ea.json
4652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c504cbfd4.json
9383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c31047a7.json
433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33ddc2011.json
1361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
192303603.json
9810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
816005a03.json
2461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f6c2d090.json
13358    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
057e5347f.json
14232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42137817c.json
7331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e9539f73.json
7963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6cbd39c2.json
12905    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5fd8a091.json
9273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b17616d3.json
8995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a206ce13b.json
7754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45f72b10b.json
5694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7931ba838.json
1378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d00520ed.json
5259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cd08bb2c.json
2681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09cc3f346.json
5447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
798fae45f.json
8926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5451356cb.json
12571    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f169c299.json
12693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e643eba1.json
299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63697128e.json
3517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da928b2cd.json
11991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7eac7b01.json
144    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e2cc2690.json
541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dd6e4186.json
10465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf90589d1.json
4555    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecc64a258.json
11660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51372ce91.json
418    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd9bf8c28.json
3054    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
132346d7e.json
5631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23367e78c.json
10346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a483f0d49.json
1631    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3183085f4.json
9628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bbf44cea.json
14873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba7bdbe6.json
13974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eed29a312.json
4214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ee594f5a.json
14597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db81bf77c.json
3347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49f3710f9.json
3136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5347d6835.json
2361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05abbab5e.json
4254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0a8a88a0.json
11840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8e054802.json
13164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4beefae9.json
13268    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb11e3261.json
11685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fce612cf.json
1661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d04fbf327.json
13917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46ef61c91.json
9041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e31c1647.json
9119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c4742e35.json
1686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2262be7e9.json
9480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef7870add.json
13934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef06f5641.json
5464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80b7c910d.json
14641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4446dde7e.json
6881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7295b4948.json
5385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1542ab941.json
13617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aded1fafc.json
11962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
895f73f14.json
2776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7a324d3d.json
9761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
978526235.json
6001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d230036.json
11937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7b5ed1a2.json
14251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efe27171b.json
12743    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03f217352.json
14907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d270b074e.json
2081    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c2d37546.json
10614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
157f9809a.json
7449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
906083f6c.json
5953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c91873618.json
14304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ff979d3a.json
11880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ff148919.json
4465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a993cd91a.json
8153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87a37261b.json
3755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00b00d5c1.json
12038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e493537b3.json
9293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae1362961.json
2592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c14ddf8a0.json
7651    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f861fe441.json
4592    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
382d948b1.json
5509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f859bcecf.json
7966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2239dee36.json
13522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2836c44dc.json
8359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
675a05fed.json
11963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97a3cca4f.json
3621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c5f306fa.json
2056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a952e440.json
1742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1819e298c.json
7459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
386990598.json
4470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88bffd281.json
13745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d45e400b8.json
13607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ef02d7e9.json
14844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ed1216f9.json
1400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45ea16ef8.json
14425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a91d273b.json
3916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eb61ccb3.json
691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c29fca356.json
1174    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ab1e209b.json
4250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50339ca55.json
9287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400a15912.json
7056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cbf39f49.json
13120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4696fb463.json
4336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07102e682.json
7730    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fc9dee58.json
5901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e43ebd6c.json
8267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a676ca88.json
3418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e464fcd4b.json
121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adc3a477a.json
3514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08f54d056.json
2421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f2251ffe.json
3265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fde58f7fa.json
10748    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0690278af.json
3713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
648727065.json
7393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
802986a45.json
6591    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81d38d5ec.json
1599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
818faec45.json
14543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
591f1d67c.json
1390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7e8a87dc.json
11728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91288ac35.json
10913    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea0d7522c.json
10158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27177be26.json
5038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2665a33f.json
9211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d946f7a55.json
2754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92085e776.json
14917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea6f651c.json
3963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a3599411.json
3813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8de3a329.json
12288    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
239844635.json
11305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14084c784.json
12775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa0d42c80.json
7107    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b054e635f.json
3717    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5052e2a9.json
7338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81ecf4cda.json
5389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f8955f6a.json
700    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e88c1c1c.json
13028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b9f45715.json
9526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d965d6f3a.json
11369    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e861279c2.json
2207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f279d30c.json
5590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c05b74b05.json
8487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c37095b6.json
1759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
472e86a83.json
14977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ffddd303.json
5023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da2cbec0f.json
10180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eff316e87.json
9779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
882021db6.json
3661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015770429.json
2744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d7247d3e.json
8101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc4bbcef1.json
2135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27cd530db.json
5542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26428557f.json
4767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb77432cd.json
13036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b0103c04.json
602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a40d8c85.json
6728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45bec4a13.json
9633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f7fd8400.json
3495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c69743d6.json
8046    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8e461026.json
11772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7b7dae2f.json
11921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b9f6e99.json
7103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c06d167ca.json
8    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27104e464.json
526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
605fe21a1.json
2032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbff91dd9.json
12466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f87489d3e.json
13299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c496f946.json
9278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2db9e1eb.json
14560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df1507e61.json
2341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e31c7d5c.json
9231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1c49dd17.json
1038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07128a0d8.json
10385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94fc65b67.json
8916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
307c5ca84.json
8286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c219bf074.json
1879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8dd968c6.json
13797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e1caf559.json
5043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bb5061e6.json
10553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c200f7a6.json
11073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
836b6e6f3.json
11170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
531f9b184.json
5620    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b356b0f05.json
8945    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cf0fcd34.json
4996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4448f7d57.json
4645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
513836f07.json
1941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fdc23bcb.json
9192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ff50cbd5.json
10875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
392cb224a.json
4343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71be09737.json
10840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dea0707b.json
3991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2bb56954.json
9104    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a864757b.json
6806    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1f31ab87.json
10672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9070ef426.json
13166    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6231927c.json
5144    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2208d2be1.json
3380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c281057a.json
7453    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4866e37fe.json
3438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bc5b43ae.json
1338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f9f466d1.json
355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6210026f5.json
13847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f3f26cd.json
9379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

71655dcec.json
7921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ca52e744.json
9531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
167a6dcf3.json
10528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c8459c74.json
11958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b03c17502.json
1377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31c12668d.json
14248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c07eb487c.json
9396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a3d4f5dc.json
14676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00a1f270a.json
217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ee34f0d2.json
6535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ac38f654.json
3045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4036e0e12.json
288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b75594e30.json
1082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d01e08ee2.json
932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3aada535.json
6937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
923da13c4.json
8877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7d753c5a.json
1200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd725e47.json
3111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97ce22dae.json
12884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef14861df.json
69    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f9031dce.json
11794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab41920c4.json
5732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97c58d897.json
7616    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a385cb92a.json
14666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8143d5d0c.json
7213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a111adc75.json
2054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ead3a355.json
3121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c7476c25.json
8339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d8568dbd.json
14726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5cbed556.json
9860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2455effb8.json
7631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbdeed3f9.json
1955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbc0c9535.json
2899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d79572ae.json
5772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6db27dbb7.json
3543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1534419ad.json
3442    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6106ecb8.json
2462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0602a34f3.json
9582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13fb61859.json
87613aee1.json
8161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d25f084f.json
49    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d45562a98.json
8229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
137916924.json
816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fd65f90a.json
13425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d11425b98.json
1398    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a6b9433e.json
14752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d7a8a5c0.json
14840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b60a4eb5e.json
12043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e156e8aa0.json
9123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
597c27524.json
1355    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d99ea593a.json
bf190a061.json
8855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27dd38817.json
2892    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9a21c416.json
13101    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c1f1a317.json
12799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32148e0fc.json
1044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d83c952c.json
5747    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3269c5d7.json
11621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
095cba2c7.json
11444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6e763332.json
2560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
701c5afba.json
236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ad959e57.json
12901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41d6c5f90.json
14892    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
043d8c534.json
7973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e783a2e1.json
7451    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f310c42f2.json
822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44db1cade.json
5246    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94b587221.json
8121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19d68bcc8.json
2541    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67825bf81.json
1662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0667be3b.json
13482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c9dc7370.json
10401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b2e2526c.json
6018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
790a68c0c.json
2730    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30ca259ed.json
1574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a949618f.json
12620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f836696de.json
3579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
258026ebe.json
3129    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4752b5e0c.json
5586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80af6d9df.json
7267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f2721c52.json
1096    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53c0ebe89.json
14435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da2cdb505.json
14573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5971c2462.json
5160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4e83ee5b.json
216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3eefdcd8.json
2196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cb155233.json
12695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
514319114.json
6687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eeb50e8f.json
7742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2eda3337.json
10122    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ed224982.json
3401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31e266863.json
7835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fb0aedb7.json
9965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a5d5a265.json
6921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37d88b689.json
8001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77e6966dc.json
7839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
186920165.json
3464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca81b2566.json
4418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7000a4f76.json
8870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a0942d61.json
9    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bda94ad0.json
181    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5257c5e4.json
1343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e73545fe5.json
7368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebff4722c.json

3425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8e7085dc.json
1905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0be09ae87.json
3655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec28e0aad.json
13275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f551693a.json
2917    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
504ce7187.json
1263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98a98311c.json
68    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
000fb9572.json
14218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cf32e2a6.json
13652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
467370aaa.json
11863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f9f0dd0e.json
6579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
175926b9c.json
6894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4771e1226.json
11507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
924373704.json
12424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51c72aa92.json
9819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66dbc2985.json
6259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a12e98d8.json
8772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa40c19c2.json
8830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d93b38122.json
3479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0866146d.json
9709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60aca92c5.json
7065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6cdbebfa.json
221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a47931d69.json
2573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c12b5f5de.json
699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dfe89264.json
5208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af9eac2be.json
7568    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cd970978.json
8710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b7222d13.json
10687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c60193e34.json
12742    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
013527aeb.json
8085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14f3fbc84.json
13538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8de855263.json
9403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2117fd10.json
11450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9550556bf.json
7429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fce9a96ce.json
5343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f21d7ec45.json
2521    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7809d0dd.json
5480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff587b75.json
7448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1b4a123f.json
14039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f40b68c08.json
8633    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6114449db.json
8367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff8aefca.json
6135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82f95b703.json
10101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
221331819.json
13887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74f4cfdf6.json
3313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
769d800fa.json
7890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71aed274c.json
2949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32efae9d5.json
2909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0714145e6.json
11663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df5f12e58.json
9375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee3543995.json
7633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07eb56db1.json
3631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5abad72c.json
6496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca76729c9.json
4013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e4ef28c9.json
1617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3005b75eb.json
13025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc580a6eb.json
1705    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d0c60b6.json
320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a591a8d9.json
5781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87aff0121.json
14784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17fdf5bfc.json
12920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccb658698.json
11501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec5069cf6.json
84    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28c34e5dc.json
8731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4a48ef49.json
14067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e642352c.json
5093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96b8b56b4.json
11411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f5233804.json
5786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8020cb33.json
3213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de43c6ce5.json
12101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5b4b663d.json
7850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36b57b1ee.json
1871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
573b3ec3d.json
92    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
020fbbc9d.json
5018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
804c6c78d.json
10261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17066185d.json
3332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f72d7a939.json
4814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
419d296e7.json
11005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10b669bea.json
13018    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
399cacd30.json
3118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cad137e83.json
881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57abbd25f.json
12154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a56df934.json
13543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22ff7ca25.json
8247    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14631d97b.json
12560    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb350f2bc.json
10704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12f9b8e6c.json
960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
191043d9c.json
11670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc6abd32e.json
14348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f14c5a335.json
10847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ecc7ef4.json
7444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5a7f7d69.json
8311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9497fd08f.json
11849    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1076dcc35.json
1235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a61776aba.json
14539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98673487c.json
11425    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf9bd91e1.json
14366    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8988d22a5.json
14343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c74d9c9f3.json
7773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bbdce003.json
8218    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae3ef6983.json
5258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a393b32a.json
11168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35178a75a.json
5123    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dad8252f.json
354    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e6750363.json
4746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6480e3454.json
10109    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
020cd1d50.json
5687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

aa88c3b97.json
11102    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09db544ea.json
7377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7759517e2.json
14181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22e4974f2.json
9359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9033fea0.json
693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdc94bd91.json
8262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a9707c98.json
8049    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba77d1df1.json
3734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18ef93321.json
8008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3eb4fe4d.json
5310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0acb3bf7a.json
13602    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5043a32cb.json
11690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
355cc5db7.json
5733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c301eddcb.json
6204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74d7a26bc.json
9207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14f54fdb9.json
5865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01ac09f2a.json
6920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fe9d0022.json
12802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bca4defa4.json
5501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53e7035cf.json
6699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8ec1a562.json
1249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddf06fabf.json
3005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47787f847.json
14734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ecb47019.json
2144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9579ad7a1.json
7201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb474120b.json
5526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1052eb2d.json
10231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f447d931c.json
9653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33db028cb.json
125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c1384d1.json
13114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b504fc3b5.json
5582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d5870131.json
9738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc48054c2.json
2232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11ce5617d.json
35b51bb28.json
1547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e5f03ddf.json
12293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
549273935.json
8063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cedeef1a7.json
9190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d56096e79.json
6031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1b2aae50.json
3849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aeef2649.json
1220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e60043fe.json
11186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07cf7d230.json
14127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c43b7541.json
11062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e23c4abd.json
7290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ccd49ce2.json
8409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
904b74dde.json
1820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e013ab581.json
8589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72b6bef39.json
5538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acdf99f98.json
7625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80723d694.json
8612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7342eafeb.json
5705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
843d24f0a.json
10196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac0cedc9c.json
2542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9cf01a21.json
314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00553ae55.json
3329    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
598479067.json
9733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bee46079.json
2080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8fb0aa55.json
7758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad6992c20.json
10922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
557f3e130.json
13269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da1ee245.json
12784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb8adeef1.json
5574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d1d0f102.json
2364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e38690387.json
13952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30908fb77.json
641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c03b8b2db.json
14096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0011d7c25.json
7933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9893e2fb.json
11672    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
385b5b8fc.json
14215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de445d837.json
2848    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c70dc1bd1.json
14561    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a785a607.json
14214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b319a0cd7.json
4124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd717a456.json
8964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9c8973ea.json
13416    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be7ff8075.json
3904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e8187711.json
12006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2391fcc9d.json
2861    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25c48e7ff.json
7813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dce0ccf91.json
10036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cddbe627c.json
4806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2566d195.json
6345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd61c330.json
1300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3f157880.json
13086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06bfadf29.json
0e80de8ac.json
4757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e8cbcc56.json
8752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6e0ad572.json
6479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb74a9d58.json
9482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c82705cf4.json
5713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42d06aa80.json
10164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
854b2bc3b.json
2900    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4470adc62.json
11550    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b817da84.json
1356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b7a406b.json
6755    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dd8e4a4f.json
14743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
964dd458f.json
7521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34edfc9d5.json
10428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1a577692.json
afa46c13d.json
7354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a823f714b.json
10556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e87938c3.json
855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bbd8c277.json
5765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b93abca0b.json
9006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccc88931c.json
14667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
833c51fd2.json
1124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0955b54fd.json
11872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aa1e5830.json
2274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b46b4419a.json
7328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a39034cfc.json
5039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c40b30ff3.json
6240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
679e98b95.json
4560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a6ef9da1.json
10572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8311f29c4.json
1112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b96b7da59.json
1186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab309dd09.json
11806    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
040d87bbb.json
2603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c787ee619.json
12729    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d79d25fa.json
5961    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60f513e5a.json
3494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c240d153f.json
4837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fca79ffbf.json
14480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e989d559.json
4936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbaa4a431.json
10907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c874c7c7c.json
2929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6ff63097.json
10051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d39e0fa1.json
12831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
668e0428c.json
1810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91bcb5a0a.json
14960    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
838934661.json
12415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

2bcab4c4e.json
12549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a645311ed.json
14501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40fdde0aa.json
14745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81efac010.json
8573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
282c90ff4.json
11739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4669945ed.json
1008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5a2e7156.json
14273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8d44452c.json
13624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4be004d4.json
13959    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
783a31182.json
6570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89347826e.json
8543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc6de6d19.json
6386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
241dd214b.json
398    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b2be8807.json
4724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f1424059.json
8882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db3c2be5c.json
12581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22ae95c51.json
5565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cfe96818.json
6011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a428c4daf.json
1684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fc31b6bd.json
9144    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7aa43e1a.json
5288    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ac0662c8.json
12552    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10486a12e.json
13878    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f749cd744.json
14463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09e9110e2.json
1946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f981112a8.json
798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d20efa95.json
7536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72e995e27.json
6587    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac6fe826.json
2570    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edd79adb8.json
7893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04a30a9ea.json
9700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a08030c6f.json
6505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36681852f.json
2927    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4914da5ec.json
6717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52ffdc6c2.json
12972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7697109cd.json
12210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff891d6b6.json
13278    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e66a993a5.json
14022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1680e63c.json
11838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37bb10fd.json
2533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bf83cc3e.json
13700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1303e86df.json
4922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9351715a9.json
11680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b84ad40b4.json
2102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93eb14f37.json
9603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7564c7b62.json
4203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad6387a7e.json
6597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
626b056b5.json
2851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
528563012.json
8198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90489eccb.json
11251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e94581522.json
4330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d02baef01.json
12049    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28dc83755.json
3766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbc8619d9.json
5745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06df96299.json
6235    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
386e1a0fd.json
4895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2dbe8b09.json
3831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a21eec6d.json
14862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3a4e1dd7.json
10079    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbea554c3.json
11659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7969bc23.json
3279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e4ceb08b.json
9595    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
584ba2890.json
10607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7fd0a30a.json
10238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f600368fb.json
12904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1f5f19fa.json
6487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4068b452d.json
7329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54fa86958.json
9475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bca099371.json
14887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a47dfb645.json
5591    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5d3151bc.json
1882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56b0b72b1.json
7843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddfea1140.json
12067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d76a1b7f.json
7704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60c1c2fbd.json
5318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5290a4428.json
11529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4dd90768.json
9839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ef3d0eec.json
4314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96607bca0.json
14903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ee8964b0.json
12494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bc3e9db2.json
4337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
441594b56.json
8415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c83fe0079.json
8876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
488cefe35.json
2701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a6362374.json
10098    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
058d37dda.json
2633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff78347b7.json
3977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc8359e75.json
5587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec496eb44.json
10742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
069762ec2.json
3326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35d04e039.json
8578    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9d333b09.json
12879    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d3289417.json
10004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45e8bd99a.json
6142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61da44459.json
12728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3021613fd.json
11761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbf954ea2.json
10741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b607db8c0.json
1777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd3c902ae.json
6624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e90930a27.json
14448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
829ba7bfc.json
12010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df09bd082.json
3528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e8872259.json

2165    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f96eae14.json
1339    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
621b83ac7.json
14514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
245434d5d.json
1346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d047d078.json
10156    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbe634a4c.json
14654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89d7b4178.json
4155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a53af472.json
1432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96a5fd573.json
6286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22937e80e.json
8934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc1d76def.json
1937    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c43d4567.json
4429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d54d84b63.json
8691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ecb9aab0.json
11556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
515d9508a.json
1822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
594e3dc3f.json
166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ce80622f.json
1552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c68827b5.json
9425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9faef6bb6.json
8327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
143760a33.json
1755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aad9a8bdb.json
6879    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f72b9f33.json
1359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15dbf64f0.json
7371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dd31e8ff.json
2083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd7f4fcee.json
3507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2eaab0cb1.json
9515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e7e220d7.json
11654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f7343089.json
6768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eab1d3e9f.json
6736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c9e28902.json
4199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72a2dc93b.json
3685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c7d56a42.json
742cced96.json
6824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f60779a3b.json
89f28de34.json
8143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f90722a00.json
8424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3308b3980.json
5720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e9e0ce30.json
9221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4af765dc3.json
8531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f9b856e0.json
4569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31353ed83.json
9947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e3d0e3f0.json
11340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
418a25e6b.json
3340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7d4318d8.json
10510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8d16f3ef.json
10490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc25fb529.json
509    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e40a90daa.json
13516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba7ade913.json
5974    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fcb3804f.json
1717    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27ce98a2e.json
8766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32d8fa52b.json
2884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
628e30f3b.json
9101    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
979d48d7b.json
10200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5ee96818.json
4938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc0f5d3ba.json
2038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24737dbd5.json
5819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
890e7be2b.json
7783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
726488db4.json
11756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
918fab9e8.json
9840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
063e2d021.json
11705    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc03cb42b.json
3941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0f651276.json
14962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dbb2fd0b.json
6548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecbd85af1.json
2518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d301b5e6.json
8938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2d37c3c3.json
1823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fd97d6fe.json
10322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff4d9a3c6.json
7446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a77045d3b.json
13757    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d7d7753c.json
8232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
851c46a9c.json
5816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7fc28014.json
6141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f22aae8af.json
5163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e27fa93d3.json
13770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f08520d7.json
10074    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a7b85800.json
14206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76c073021.json
3068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1dd377ae.json
9360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf6dedb55.json
14089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53895ad35.json
2152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78cb569c6.json
5313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85114144b.json
1376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a116545f6.json
12615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f89f0e01d.json
11553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
655cfc630.json
597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09d9212f5.json
11426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
924cc5438.json
1464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ae0545c1.json
3671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ffd4e822.json
12104    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
785a95244.json
6770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fc2f9495.json
14657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3edf44325.json
8221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a53e7e832.json
3542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0291e8ca0.json
14412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
923a7163c.json
7554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fc6f94cc.json
3012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcf657071.json
9818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1239feb4.json
11823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89ba257e1.json
9385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa94b21d1.json
448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4cec9f83.json
10554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
022b37ea0.json
1724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16472756f.json
1393    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
370d9c1ba.json
4402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da9d78f91.json
10055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfe8c6bef.json
14650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ddd7f219.json
4384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
282f456cb.json
3013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94019dc75.json
4541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f3ff5116.json

3028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40713e16a.json
7402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb295209a.json
5129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edf80e3cc.json
1726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98d3a24b8.json
9049    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05312ba72.json
7746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55b9c70eb.json
9509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f117f08e.json
9923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cfec8730.json
1753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9cc0915c.json
9266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcae5bea5.json
7768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5bf5adaa.json
37e47eeab.json
5213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fd5af157.json
12806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f863a03a.json
3473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
105c00abe.json
7756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
792b0924e.json
1602    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f51a7e88.json
1443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c335ad2df.json
14515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35225eb67.json
13536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015c75c9e.json
52    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cda8c2d7.json
13874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07b2a1416.json
10326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8710e158.json
9857    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
902e7f8aa.json
9201    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61be9a64f.json
13340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92bf36222.json
13534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33715275e.json
14375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ca5ee472.json
9268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7fcfa1e6.json
14979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6c3b531d.json
8189    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fed382c0.json
3361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb8795c8d.json
3306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba4811f35.json
302d37427.json
8486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93a9e05b1.json
5176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
201d52dee.json
990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
493d9cc81.json
7797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5f08e991.json
2512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6632022cd.json
13957    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
960de1fad.json
7606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
545711134.json
902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e34280d51.json
9594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5781e566b.json
11339    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94918fff6.json
2456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da7bed1f8.json
9001    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df17a57ae.json
6321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
843f45598.json
5398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ed2fba3e.json
6293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ab64c5a4.json
1815    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa795e561.json
4454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c1c5448c.json
8440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22b593a2.json
8996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0ee00f9a.json
4948    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53c344d06.json
2918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01dc16c21.json
12540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
010a59236.json
5075    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24750a30f.json
3173    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f922bd640.json
3258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
886d23c56.json
13287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d137bf2e.json
12363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afa694eb4.json
3565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a113449ce.json
14280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca7075738.json
4463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a032cd2e1.json
10473    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf458a7d4.json
7492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fb22dd88.json
14861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e681c7eb.json
1597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d7e844a7.json
4765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c27f27a68.json
2279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ad5aa95c.json
7044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d72bc7206.json
5778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8060a227.json
9115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
196195aee.json
6453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37774c72.json
1781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b31b0fa4.json
13973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73ab55e8c.json
14611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
827ac9a9f.json
12544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2db6c996b.json
856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
945a7a8dd.json
7029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33dda6165.json
10422    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e6c38ddf.json
1218    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01c7411ef.json
11996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0149d04e7.json
7041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0118db3a8.json
6079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a72492a9d.json
8707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82c51a95a.json
5653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2039114f1.json
14575    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de67abe0b.json
1369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aff78ff8.json
10786    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4529e91da.json
6596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3069e2d3c.json
7457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e7a22c99.json
742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5510ac89a.json
10170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf77fed94.json
11124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea11b6f12.json
163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdd77ab31.json
6773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbf3097d0.json
3235    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f00413d87.json
2981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f73851f5.json
13894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ea2ddaf2.json
1791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b2ff582.json
7118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44965fd2c.json
10043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dde63c12.json
7363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70fb603fd.json
1664    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ee5073bc.json
1460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
258667857.json
87    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bcd62ef1.json
155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

6c803e00e.json
5514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
971c160c7.json
7610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bf0f354b.json
2787    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6c91bc20.json
1318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f104f8045.json
4589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff125cf8d.json
80    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84e146ba6.json
7826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a21f20530.json
8575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee5ceb065.json
1374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f1a3ce5a.json
7838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8c313331.json
2466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4331ce278.json
7899    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de2460808.json
4959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33c73d9ad.json
9277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24bbd04ce.json
12253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7561189e.json
14557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
863262193.json
12240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8208c3c9.json
453    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dbbd91bb.json
8257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adc5ada07.json
10253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20fee2991.json
13499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05dc47bda.json
14735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e42dea43d.json
6772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86c131c22.json
12764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5324ef3fb.json
11839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8f4a2877.json
10790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
610246129.json
5224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4138a8f48.json
8186    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e09807e6e.json
14948    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b70f7c3d6.json
8961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f21fee9f.json
785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef9154afe.json
2539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9351d5173.json
7657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53549acd2.json
797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2386bba2.json
13073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbd5f7a45.json
9535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72626612c.json
7909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bf8a38ee.json
6744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18751b49e.json
2707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b612d6ba3.json
893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e046289f.json
12060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e107c82f.json
6199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94438a5c5.json
2549    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1e9aae7c.json
6256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73a2be705.json
5774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d470889c4.json
11928    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e46fa829b.json
1316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9feae89ad.json
11400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54e0ac09d.json
9620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b1241ef0.json
860    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a3da2ae5.json
1630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84f308399.json
3765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03ea48efa.json
6606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6436c1a59.json
20    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed6684f3a.json
935    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0d8b0778.json
8990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5b9cbf05.json
3961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6846c8719.json
3056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f61cec80a.json
6549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a93093cc.json
12881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b84319e15.json
9680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe0e76ddf.json
12545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97cdcca1f.json
9463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4bc68f06.json
8505    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03d59fc21.json
435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8f735068.json
2452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71eac2c5e.json
12426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20f82514c.json
8213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
189eaf5c4.json
9299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
045543730.json
341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93b1ca32c.json
14262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec30a3b11.json
11202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29778124f.json
4446    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ace65bc4.json
13126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14155e8c0.json
239b75387.json
13081    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec15875ea.json
5221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
311479c63.json
788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7eecc57.json
10275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fea8ba32e.json
d9b4b1930.json
9391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
701c7e67e.json
10402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5984b6df.json
6901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ab1bbd3f.json
9575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cc84c2f8.json
402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b879a154c.json
14538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7abe9a0a1.json
7268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f7da7f8f.json
4452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c28914a9.json
12533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5f441f79.json
14079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1be4d855.json
13848    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee590e762.json
1222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62eb0363d.json
8711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7e623e5a.json
2247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85ff0f493.json
5495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
804d08f42.json
11543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82563b26e.json
12079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
167233db2.json
5380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6c917eb2.json
9725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be16b20d6.json
2434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dc7b3ffa.json
14966    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87b753139.json
7618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec6bb5fb6.json
13234    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4eccb132.json
14770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88f3a5fd6.json
8384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a710da2ab.json
1379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bd4aed6b.json
229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7560614d.json
10058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76a045292.json
10107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe22cc3da.json
12343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58a79a8a1.json
12712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72bfc767c.json
11233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ba0605b9.json
8910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b344389b.json
3413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdbe7091f.json
4734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f24000fbc.json
8653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
178629125.json
5548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d164a82a.json

14493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c9e42452.json
2509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62d911513.json
6469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d86f635fb.json
11665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f05665d6d.json
13170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9197674f9.json
12102    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d77a6813d.json
7400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
933da53ee.json
3870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d59be88d.json
746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa7548beb.json
14580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f3e4618d.json
1465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b9873716.json
5069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f2d73626.json
10923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b1f93aac.json
7733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17d90c2d9.json
14600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c401c793.json
13074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63051e3ca.json
11793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5aeba94a3.json
13994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05aad3b3f.json
13254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5017052e7.json
9489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce971a506.json
13788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd79180bc.json
2201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a952a211e.json
2658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad491b969.json
5862    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8849d3fe9.json
4817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
062b387cf.json
14088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3ae90795.json
11189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3c2316ef.json
14044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93d43258b.json
14498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9012ebabb.json
1728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
148f526cb.json
7026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fd75e77d.json
11593    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0719de933.json
11309    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3209cdc3c.json
1003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1a9104a1.json
11626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a27b7e4b1.json
1253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7db9c90c.json
5648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a8f24615.json
11047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea099a3ec.json
2599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e69c99bc.json
6643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b53990a1d.json
1792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ca64db1a.json
3456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf2b57c9d.json
8035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78551abb5.json
5376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acfbc9b71.json
10011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc46e61c5.json
14313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be7b65c23.json
249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f000f169a.json
12760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6c985a00.json
11149    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96c93dcc0.json
8350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f20390dba.json
11418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd2452dfa.json
1966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43e4cb788.json
12439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90c5437de.json
7802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a48cc316.json
13123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
845703071.json
485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58e2cf3d9.json
8640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b942f000.json
911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5ffc0a9d.json
9267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3f6438ea.json
5634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6cf89c61.json
11610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
942af9028.json
11850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e464e666d.json
14102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10711bb95.json
4025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7028ea673.json
8580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
249540f2d.json
8099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
886debfe8.json
10485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3c42e04b.json
5540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d2dec2f3.json
8641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
838c5c399.json
7475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c432261a7.json
10868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
239047f66.json
12950    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f11772123.json
11020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92c48ece4.json
2285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
514db7301.json
12922    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b887b2037.json
12647    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c411730a.json
14427    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2cd0e1e4.json
6882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82d0651f3.json
7130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b2336880.json
11179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df25863ad.json
6026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8f3da4b6.json
13928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7a24f9e9.json
8592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df89a82ab.json
10771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b03b1a110.json
8005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb051be7c.json
8387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
259dc7e9a.json
5521    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3af78213e.json
6287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
358517d09.json
14234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e24b153bb.json
12452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6697a7f62.json
3218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bf49ebb9.json
12209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff9f62e79.json
147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d3526802.json
3861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08ee62d43.json
12323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae5f13659.json
11228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb278c21e.json
5479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fe7448a5.json
10302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bd7346d6.json
5985    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
758a6def9.json
4488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e3473e81.json
14576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1775b51b.json
9972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af1c2888d.json
5663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31eb7b312.json
10009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9397426ea.json
702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab2c124e7.json
10037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ac2e7d16.json
5815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb05f298c.json
3691    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

4bbc7992a.json
13033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94aec9453.json
10571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7aefa7eeb.json
8273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
387147d00.json
8673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eff6d721e.json
10171    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9d28a286.json
10752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27bf3ae34.json
936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
949fbd095.json
7f670fb1d.json
9195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
275df2552.json
13677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95183dc31.json
6207    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ac979cf7.json
8502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2b5ee33a.json
5206    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
267162afd.json
12259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb22ed27d.json
13822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b41d5c9c4.json
5344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c810c552.json
999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c59d7c9f3.json
11210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17ba1d7ce.json
9678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d24b8cde0.json
6271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d3dd49c5.json
5494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54b6c1d72.json
14982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a237fba21.json
14969    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e8bab7a5.json
7723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd2d48292.json
11786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e37bb1e2.json
5661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
563854d72.json
11804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e2039291.json
2188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
628f11673.json
3500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
026c5716f.json
5848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba7b8cac2.json
5570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3970cb015.json
8992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cae1b9ae.json
4901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21a56b530.json
5025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d53b2d19.json
6420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
790e639ed.json
6804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98fbd3b39.json
10646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f66a72ef.json
6290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89e43a001.json
7021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9a47e731.json
9809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe2d576c2.json
1887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
530c897a2.json
3355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea4fe7ae2.json
3744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7df56218d.json
4826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08b454900.json
7533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e128e9022.json
5922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0910c13a3.json
12430    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2318247fb.json
2941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa7b75c6c.json
11596    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
721acc718.json
3316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a04a67a2e.json
3757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9999b8c82.json
14626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98e1a3f01.json
6934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e8d8e53e.json
6842    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79786edcd.json
13169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb15b5fb8.json
2060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
699ee7fa6.json
12532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c583aec6.json
3445    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f5ec6144.json
4098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fb6881ae.json
14787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fbe0f38.json
5235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76c194060.json
11826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36e02d379.json
14964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26f026215.json
10300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d37659c5d.json
14301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
042b1e55f.json
3411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ebdfc3b7.json
4420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6adc3bf2f.json
4726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37ae0cd69.json
6713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c60d114f.json
5906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d65b5a052.json
10895    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
656a0a459.json
3410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15592a54c.json
7886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d24c30b4b.json
5    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd006f963.json
14637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c626f2f93.json
14783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1ba2f016.json
12782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3543dda3.json
5416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8daff578.json
6462    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce4484c3d.json
9753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65650b974.json
12847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0993b5aa2.json
13439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e8965ae1.json
7852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
119835ef9.json
2067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85188cb67.json
4497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af32c8be0.json
14950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b01864e2.json
908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6434d0273.json
f2fba72d2.json
2820    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fa705c07.json
13787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9acf4992b.json
2956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecba82fc3.json
72b0d2b06.json
5453    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
060b52c3b.json
1510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5dc70d35.json
14984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc8c8d169.json
10874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ec1b64b.json
7910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3033b66f9.json
9112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7390b70c5.json
3271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

fa1d3af33.json
9178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c777bb01.json
10167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1acab1703.json
5471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c71db5b5.json
12788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd5ac00df.json
854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab87287a4.json
11602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a71e754f.json
2689    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1045bb4c4.json
8905    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87554ea1f.json
11946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b4017cf2.json
11693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04391c798.json
14360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0632ba05a.json
11176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3326d571.json
5166    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cc9490b8.json
4227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95696f11b.json
2611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e51ad3d5.json
5502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41c61ed91.json
3733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1f738966.json
1644    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
127daa5e3.json
13613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
982564925.json
2449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60e5899e2.json
12570    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2b59ecaa.json
1819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d3006ccc.json
9567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11e6c4d80.json
12302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
796cc971d.json
6372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a40a230be.json
14108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a2faaf1f.json
2522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1042ee67b.json
6723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8c54bc91.json
14846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27ec72a29.json
5656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
992feb0f1.json
8524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
562b8da1d.json
5945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef5b463d4.json
12568    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69a15acbb.json
6987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b1582f99.json
13774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02a8e44b1.json
10380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ba8bb04a.json
12975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c7a54cbe.json
5599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85a79f281.json
440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7df257784.json
5293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a8d98847.json
1423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
140ef35de.json
1305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45176c4c.json
3372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f7433061.json
10067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
356d9395d.json
5273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c320a6005.json
8675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48aa8ee7c.json
6541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80b25cc78.json
12523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c59513dd.json
7673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b13e4afff.json
4251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9292cee2.json
11184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7beb8f666.json
6598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b560efa40.json
10949    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f85ce1a9.json
768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67221a8f8.json
829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ec261d88.json
14058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d2fe6bb6.json
759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
714e287c7.json
5940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2e82a58a.json
14500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da7680082.json
5458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a24bb77d1.json
7269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d02861aca.json
9324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa7395687.json
7389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c3b9b731.json
11889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a5d7e622.json
8191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2179be57e.json
8018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57dcbe4c9.json
10123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b86ed0e0.json
5383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
552d8047c.json
11491    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc63194d1.json
9466aa6bc.json
6181    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea087d248.json
14062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4450245b0.json
12553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e10e3f87.json
10048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
209e4f717.json
865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f77452d59.json
1358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4482a8d57.json
12465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d05933e84.json
13458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bae0f028.json
14297    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfe83669d.json
9147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22b562975.json
7774    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
021b0b7bd.json
9781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bef897b2b.json
13979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39bff85f9.json
11095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61fa7980d.json
5682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69834808b.json
2052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4f117930.json
4206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a796c967.json
13109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
907fc239e.json
3929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97450a196.json
3083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db5d27601.json
10377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1019e087.json
8532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fe8ffc8e.json
3537    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52c49d6b6.json
6473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85d78c2c2.json
1580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a819792f7.json
7435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f5e7cf4a.json

1858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8cfbf446.json
7628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81075b785.json
3927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25c681109.json
9410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc23feccc.json
13922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3dfe1991.json
14932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5a34370d.json
13542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc3066d92.json
9307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aa9d63f8.json
7784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e5b9483c.json
4274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b62fc7bde.json
12348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddeeba131.json
9716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b95ec85b.json
1714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
348665874.json
8369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdbe9a6e3.json
1975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a426ef14d.json
13223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f66e4eecf.json
3709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38c5d4e0e.json
14327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad5118660.json
14477    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
732fa3cb9.json
8356    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e945a1e04.json
14815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e468bfbca.json
11716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4ab04385.json
12701    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6282ddf87.json
13899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38e12233c.json
1125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
164857bd8.json
6936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d404012af.json
3628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36bec0c95.json
5135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c00b7ba5d.json
14540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cec78d912.json
2071    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a5fb3c1f.json
6390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c2e6c331.json
9443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1671ccb9.json
11866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfdff0622.json
5226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ac95823c.json
9120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5c68b3bf.json
10318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e9c1385c.json
9171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e99a775d2.json
2225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa87afa7d.json
11185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7baf1366.json
10479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2f21fe63.json
11104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e86af84c5.json
10001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f94991b4c.json
8831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a56bbc295.json
4629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
764fac30e.json
3449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b32aa8dec.json
12649    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c160e581a.json
7611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
822193428.json
5423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50e35cd70.json
1014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da6950564.json
1751    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a72708bc.json
6053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88dbaffe0.json
5691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a99968c35.json
12063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b09114c4.json
3934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
215b68785.json
3032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
682b7b7d0.json
13577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0cc9df12.json
771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615213076.json
6253    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcf5f5a0d.json
2602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3afb76273.json
14213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
659dc9159.json
2290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45271caa8.json
10430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf8539482.json
8501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06904db12.json
3155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
776f7e340.json
3055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
569e2b299.json
9036    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32afa462f.json
11355    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d5fc90f3.json
5506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5d43f373.json
1740    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3d9dc96d.json
297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
382cc2865.json
8884    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfe061b7e.json
12134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
041cf403e.json
8467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65b46ef09.json
1658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd4059588.json
3086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a6becd27.json
2320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14a1d0eb4.json
10369    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e29d5a9d.json
1593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
295b1eef3.json
11286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8054bfa.json
8551    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
945a6fa56.json
13645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f20dde82.json
4619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffc44afc.json
12864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f94c942b.json
12017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f34b0a578.json
4573    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f5405630.json
13694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1020c8f00.json
4482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e31df86bc.json
14574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e250a5f1.json
4772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba42b457d.json
3283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b99644a34.json
12298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48a2630a1.json
14708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ddc14ad6.json
10621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
440676acb.json
2671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e37ad2cc2.json
12369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f031aaaef.json
6841    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bfddbc4c.json
11075    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22992ecd0.json
2926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebcdfedd2.json
940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac4c28677.json
14827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec4089e58.json
2187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50d1c2157.json
3769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f665c5189.json
12243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

f2a6e7dac.json
1111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e5d1fc6d.json
14771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38d23c02f.json
5239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbd8a4220.json
13483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31926dd6d.json
6625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e30e8240.json
10483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eef0fa0ef.json
3019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
492fe3371.json
1165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a31b05e99.json
6403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
637186543.json
11710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9521ff66b.json
8800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5fc7d4a5.json
5068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f512c3fe.json
3896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f51e72db2.json
13511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba6fee44e.json
12711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5e06c8dd.json
11330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6209194b.json
9194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19b1f4263.json
106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e158c21e.json
3201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d94f98004.json
12575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea30b615.json
6450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffab93d18.json
13896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d95c8ec6.json
8364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
558ca2c00.json
10984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44c8447f9.json
1627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93685a66f.json
2501    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62817491e.json
11086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ee370ef6.json
3992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6840e38e5.json
7074    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71deb8267.json
12481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6f877dda.json
12498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee93b2d47.json
4816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f66fa0c3.json
12056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f93a41c5.json
547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
933e0a3e8.json
197    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d418ea0ad.json
1486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90bc90da2.json
4515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f393155e.json
6400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e22b9edd0.json
2784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da405f364.json
14636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8991aff61.json
9961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32ac38a9f.json
14013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d0a7a7ac.json
13317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b23e29c89.json
11363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c906d6c03.json
7609    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fee0b4da6.json
14488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8acbc614.json
8851    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
796781fbb.json
10420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b7fd5349.json
9392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
232aee73d.json
4285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afa1e2afb.json
10085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a73915bd2.json
11090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e0d70679.json
10334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b07e0e6a.json
14454    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe3e235e0.json
906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
987baa1c7.json
175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82a108c64.json
2641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b15d56540.json
4355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
124e6af5e.json
4158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45c871da9.json
10496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0488da92.json
2882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
210c4a637.json
1848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7726d2a4.json
11177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0b5e6036.json
12687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7f20f68c.json
10946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f90762cef.json
5247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dd6775e2.json
9905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a62fcea51.json
12341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14410015e.json
4693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23874f644.json
14981    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed97f6919.json
14797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67ba0fe06.json
12138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16c55a91.json
3973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
516fcfdf9.json
7731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd5f93066.json
8860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff1613693.json
2427    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3779a7d91.json
5554    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9878da24.json
7770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01c3c09df.json
10817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
113252df2.json
4451    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88df1460d.json
11261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c81372ddd.json
13866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9347cf8e.json
5229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9a962ccc.json
5445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99c7658be.json
3242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0dc1d4f0.json
8083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26e02fdeb.json
13216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39b7ed1c3.json
2398    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f63c5c04.json
1275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
393d6bda1.json
6162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f68c70fe1.json
4096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74ca92e79.json
10824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
988c18c10.json
2296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f94e2b5a.json
14384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92e87765e.json
14464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a3bb842e.json
5084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baa4b862f.json
13500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96a0b8d03.json
6835    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2da9b0c2c.json
8529    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06296e4e2.json
200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1d40ecc1.json
13244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87520e2c9.json
8033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2db012118.json
9432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

43b6e3f2a.json
5787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c55ffdb7.json
8460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c039154f9.json
733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
897e065bd.json
8482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb7bfedd5.json
3231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a9bdc274.json
9856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63a1fb887.json
14769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6ad64584.json
1163    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8f17e0de.json
11870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22ddc666.json
14372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8411ba490.json
5693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
710dc1661.json
14535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c28877b7.json
11199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88db34068.json
9309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e8c5d816.json
6726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a5b854f0.json
12829    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55cdf4eda.json
12796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c15b3c9f1.json
274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
596d623f9.json
8059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c57a0afef.json
9261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada465227.json
10856    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5678616cc.json
12509    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f46311db.json
8014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a1702099.json
1327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17880e117.json
8377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
109d21b69.json
10859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b62a100d6.json
10663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5d4b6f13.json
10811    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f582ad6.json
8504    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
375794bcb.json
4971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d75c2ccb.json
7175    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22f6c0ac6.json
46    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3daede547.json
5535    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c336beb7.json
12923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4133ec13c.json
12105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8db729086.json
10855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a143b5edf.json
1713    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07558410c.json
6441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcf366e02.json
8276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52db8f887.json
14843    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b70b7048.json
7241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26e7f93e8.json
10214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ec72b62f.json
3262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a770c49a.json
404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc4ba2449.json
6519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b988d6443.json
5871    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f6cde44b.json
14423    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb7eb47a.json
10206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e18d31575.json
11848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8215b5e3.json
10887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d34bfde7.json
6128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aabe595c.json
13860    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea6f69d0a.json
3321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4dd82200.json
6339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27456ec0f.json
177    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17ac391be.json
2442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f888d5f54.json
5155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba42eca2.json
2203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
290cdc8ee.json
11638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc5ae0001.json
13698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e8ae40c0.json
12442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aca422e60.json
6590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dabe9ac5c.json
1179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
168f1c6e9.json
2895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7c0b9180.json
12193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ab364834.json
12652    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b7f7fcca.json
11143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f68bec222.json
14017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1ba2169b.json
929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a4178fe9.json
1054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6645c764.json
14385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcdb6907c.json
11320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ccb8778d.json
3864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b660c6af.json
6375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0bcee7e2.json
4958    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b2316d19.json
10685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ef3f5030.json
7045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b7007847.json
9215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db5e33633.json
7082    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb570c67a.json
9693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0627105f6.json
11532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef9196721.json
5558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
515462e67.json
995    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53db5839b.json
11117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb1a745e6.json
9734    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2172fb9fa.json
14143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c5feed55.json
9604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6116358.json
10290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c139389d.json
9021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1c66420e.json
11293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fb135352.json
8649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4e96e3ce.json
11415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfa39b9f1.json
14074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df59dd59f.json
4720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ed037049.json
9152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
900b47573.json
4038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1632981e.json
14293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29f54c6ff.json
142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee10dbace.json
10457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00a1a8af4.json
14118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6942a43f.json
10699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dd9f107d.json
714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a69070a9.json
4546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3a0fa212.json
11933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fc1c066e.json
12586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05fadeacd.json
9189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
468cec390.json
961    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a4e70a21.json
14406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f90575a63.json
13227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c1e8a6f2.json
5178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a338df612.json

3649    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b210e38f0.json
5536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fe561ed9.json
1621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
289d0bc8a.json
4913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
473280639.json
12242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
870ff72ec.json
13136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31b3d9b10.json
1422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3bafdff5.json
10423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79d56bb63.json
12418    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3666cdd80.json
13105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18553e89b.json
9523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e3457b81.json
574    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99dcd9020.json
323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
485887f4c.json
14916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
685cbaf7f.json
1022    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
942b2ba7d.json
8986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f922ee758.json
2347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f12dbf17.json
4113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31c2215c1.json
7854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d71eb546.json
12692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d862cd26.json
2118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e82bfd8d.json
6297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c7136c2e.json
9129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f759dc332.json
13545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
407af6f7d.json
14885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
531e56f63.json
4979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48f8d1d90.json
4645fcfae.json
14542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4512e1ea8.json
13314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b1628128.json
3568    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4d225c88.json
12744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b906d9b78.json
8343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9f692e74.json
9031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d3d1070a.json
11788    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf5700a80.json
1388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf78e66fd.json
4423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a25a5ad9e.json
12773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfc46890f.json
10543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fab6916e.json
6069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d7fd1ee8.json
9131    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20b7e24b2.json
14369    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76c3b16af.json
12643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d653b602.json
2826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6ce1ed64.json
5619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6366b7f4a.json
1195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e402f3b2f.json
3334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e3bec724.json
11983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7930e4752.json
4978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03926867a.json
8701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
971817521.json
11524    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5182392d9.json
10299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35bd82365.json
7938    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea42fc56.json
14151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
474ee7e00.json
7481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f454ac205.json
12346    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1effd827e.json
14589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fec0008f.json
11731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a9d18d89.json
6985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
402e83205.json
6956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be8901107.json
1855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9d566df8.json
6664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c2324232.json
8118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49382f7cb.json
4286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b859b9fa0.json
7321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ae247e90.json
13769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82e86dcbb.json
5392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfe4df8c6.json
1293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd0c6dcb3.json
3937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
599d24d23.json
4783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b1f83255.json
1488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da80c8aa2.json
1688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d4d75d35.json
2554    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8bc66245.json
13095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fcc4951d.json
6516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f47679843.json
12254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
244cca93e.json
7684    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49360414f.json
1680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2c44e0b3.json
5319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fee07184.json
12635    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73ec4c916.json
11002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7775c4f.json
579    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8cfd914.json
7025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86ce90970.json
6731    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2dbd92b1.json
8485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e02dbb6d5.json
13214    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9883a048e.json
63    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6b64b212.json
2802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31e9530cf.json
8585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9166a802a.json
4347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b05a3ca1d.json
934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26901ccb0.json
2326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1c40a1eb.json
1532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5de721c8.json
10928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f2dd031a.json
4553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78929e879.json
6222    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df76ee4c1.json
1062    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f03af5072.json
13326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

6d98621a6.json
6730    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5730742ae.json
6200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fa65607f.json
13235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b01c8995e.json
14673    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a09a76aba.json
10507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87a679d31.json
8052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14bff008a.json
5703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48c598ef0.json
4626    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e08c4940e.json
12160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
982ffd67f.json
12212    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb8620132.json
695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae524a36a.json
754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f7932c0d.json
5664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c9fdd0ca.json
2764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a963b8732.json
12866    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6afc6acee.json
7479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
befafd8d3.json
13392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e72a77ee4.json
14891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75ee37fa5.json
7200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4894fe2a.json
7979    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1170cc46.json
7952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45320bbe7.json
48dd04601.json
8526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1833aa7d6.json
6074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fd0d7864.json
10959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f43a68579.json
12162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3332eb59c.json
164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc6976a96.json
10803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
550f8a3da.json
13277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24fad6b0b.json
8331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9162433d5.json
5845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0a797901.json
4351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6959f1ca.json
12628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3abe5d8c.json
13648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1ca516d7.json
10390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcdf98438.json
13052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
859b2a95b.json
5121    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e5b2baa8.json
12331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f77be41c3.json
7914    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6808adf0a.json
1507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
727a1c793.json
1131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bef49a74b.json
10643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f72e457d.json
10172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9ff29578.json
1221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d84d3a2f.json
12951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3711579ed.json
11458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd365668d.json
9557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34c4e74a9.json
14913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a90c3dbd7.json
9376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2204552c.json
8919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b08012e7f.json
7980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08a9b6f29.json
4670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6608d48b2.json
7959    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcf546cb8.json
2475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1398adca0.json
11544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed5b8276f.json
12127    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01603d6e2.json
8869    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ebe9f7af.json
12318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d4adbcc2.json
10896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
481a37c0f.json
10227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f771cce5.json
10031    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f559980ed.json
8594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9df9b11b1.json
12554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
752491221.json
253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98ae607d8.json
5214    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eceb03b88.json
6210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65d10be4d.json
203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff867121e.json
8590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c79a5547.json
7301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
799a41eba.json
11193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19dcd4753.json
b0d54f76e.json
12883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b593502c5.json
1444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e8887c13.json
9861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7c99d389.json
13187    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa27f275a.json
12985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64f06dc3b.json
12349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd2084cc9.json
9499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3778f601.json
10635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4530b1d0.json
278    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41ee5af3c.json
10177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f05dae9bb.json
7535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf497e792.json
3931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0350cce0.json
6263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64a3f89ee.json
13687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09a41530d.json
5291    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
943611bd0.json
12329    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
122092781.json
11323    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e66d0c392.json
5701    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aae0d180c.json
8197    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd059b5b6.json
10456    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fcd7cfe0.json
4861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47fd4a840.json
1953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22145fe75.json
2856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb9527612.json
4165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
269d8414a.json
10878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14efbbb85.json
1605    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
069fc79d6.json
2124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0392c0c81.json
533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
122683077.json
8745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2ac2859f.json
13113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c692e208.json
7664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db24c8108.json
1244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
335f2c11b.json
6906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d3d3b938.json
2028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a908a708.json
13230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79318b69e.json
7283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dea0253b6.json
7367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e48ad81b.json
1908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b62619afd.json
12925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a355a6873.json
14582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6beefaeb.json
2439    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49a832741.json
8342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2f8667a2.json
4856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
676b51817.json
11605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94af242ed.json
12832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
520dc7925.json
2168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c87b301c0.json
1668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de0a86ccf.json
5645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd18b6cf6.json
5717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3367a65d.json
2677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b833f9624.json
11294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efa71e34a.json
13692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be4c2e0d5.json

8234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14ee9a2bb.json
7547    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
098b6e1e6.json
5282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b59e875ed.json
5107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c52b99ee2.json
9722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1b183683.json
8279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e5d357f.json
5187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53cfa1a3c.json
13552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c65cbe7b2.json
5171    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8f7d9542.json
6745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a37a24a58.json
11058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e34e1ebe.json
10592    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b9fd4034.json
13478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6120ace5c.json
5161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f83c963d2.json
8624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fea9183f6.json
14069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fad982f0a.json
3843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85b57bb1e.json
1041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e25e889.json
6577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4a6e9cec.json
7407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67e77a11c.json
9423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86da09472.json
7951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b2fc7a10.json
8874    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaad1ddb5.json
13302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d2e1dd01.json
13532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f366f264.json
4109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24357b578.json
10612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
160dcaec8.json
7263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
767a3b706.json
13977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
704502836.json
6520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca75db93c.json
13882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a69ee8f61.json
11283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ab8ae91b.json
3871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9593c0350.json
14510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04a6267e4.json
1509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1528d2a61.json
4614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d99c980a9.json
10336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0340ac5f7.json
13239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f80bf9a51.json
3207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57ffecfd8.json
12024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b9ee40b.json
4860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e21ecf520.json
1362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7b07aaec.json
10534    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99459c30d.json
2960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6e7b6870.json
13488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e16fc7feb.json
4988    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1a6fb38c.json
2983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6341e0577.json
14766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172332f53.json
359    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b13247816.json
1475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
036c684d3.json
9004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4f31b018.json
6245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
052c95a93.json
8751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06adfc154.json
8301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98c1efd96.json
11314    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba16e7f4b.json
9315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcf17ac48.json
8548    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c859ef92.json
13668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b2aaf395.json
11238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a90d6fbee.json
6610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c17339fe.json
6874    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03a3fb084.json
9301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29466dcf4.json
1337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
076ec7e18.json
12475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
054f35a8c.json
8569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3089a5bd8.json
1072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b47b947be.json
12007    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e758e4c0c.json
590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8a1f3d1b.json
4997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dfa8e172.json
2625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c30c4a49.json
8349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4f7394ef.json
5212    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07e6b5eae.json
10870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab9f715ad.json
401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf0dd40e3.json
13806    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d72ec242.json
2283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a46ad5cc3.json
12444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11ad894e6.json
1058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4248ee26d.json
14523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56a0c2ccd.json
3675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5205f8ab.json
11847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400bc90ee.json
9260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae42b09ce.json
8167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c383e3e7b.json
14006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eba013abc.json
11851    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dac37d01d.json
10650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9a854207.json
12406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d35b8c727.json
13261    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6568f907c.json
8988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
394c13865.json
14678    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8128cefd.json
489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4463deb9a.json
868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb7f34ac5.json
4609    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df6205194.json
4461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc7f99ad7.json
12600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbf4de1e8.json
7515    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3105b0012.json
4495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb3101bcd.json
9686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e25d4fb8.json
9346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
991c722c1.json
10148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04dc94c39.json
13727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ff7245bd.json
3147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e58b35b6.json
13808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16a371487.json
11009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aeffc6dfd.json
4868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bd82188f.json

10890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9295d02bd.json
11598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caf786c94.json
14196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fd5ff08e.json
538b47698.json
14205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e08649ba2.json
5853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99c110585.json
9209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe3d33ae1.json
12097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fc4ac031.json
663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3b415951.json
12984    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
963520a2c.json
10491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22a8a017.json
14746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcb565f06.json
11208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd0b58409.json
6513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd7ee75c5.json
1156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5b7f6fbe.json
6188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8079e3a1c.json
7287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eddccf6ff.json
11955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2befe2607.json
14168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f1ba804c.json
14284    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d48d94920.json
9012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cd363542.json
3153    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8750b910.json
12598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
052160ae6.json
6191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6e6e7d6c.json
5062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f41112ee1.json
6778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c33220375.json
12096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25b3328fd.json
1545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5c51218f.json
7596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b34dce3d6.json
4273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3106dcd5.json
5991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d080818c3.json
127    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f260b3da.json
13606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d55edd17.json
9349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef8782012.json
9262    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4785a8894.json
9464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5aeec694.json
5081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d341fbfd6.json
29    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7ebdb47.json
9363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7e7211e7.json
4577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caa967274.json
3501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fddd6ef11.json
14967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9c0de515.json
7898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a9f1c036.json
14438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5b6f17f5.json
14740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e723eee29.json
1517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d8ec2cff.json
4276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58e8cb9e1.json
12285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e6de643b.json
5470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f612d5506.json
6495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d67e7fcf.json
3746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
511b4a044.json
9878    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c833c8c4.json
6322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ceeeb9f2.json
13128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c5a98448.json
7038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a2270c3e.json
10885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a734e866e.json
4388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
205dd56e1.json
14604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d3930bb1.json
6675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
056437112.json
775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ae326dba.json
10024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d8d037a2.json
10381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8eece1c0c.json
4449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3de1de812.json
3382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c51c9e136.json
2632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf6ef8c07.json
8914    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53eda13e6.json
10406    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd81fa60a.json
8521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be59708a0.json
7864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cdb90323.json
13665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2405c5660.json
3431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc7b01af6.json
7668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7af4cab5e.json
10820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5e351a09.json
2310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1262c956.json
7408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
331476348.json
5073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26a4d7052.json
6279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94ec1c180.json
2679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bea067f2.json
6559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16ffedcf8.json
14019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9eef9dca.json
5715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84d1eb4ab.json
13210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada44e887.json
1921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc9773fa5.json
1647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edac3b595.json
12249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bc347d2d.json
8539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
193781ef0.json
14618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2af9db4dc.json
277e3979a.json
6155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3e85821d.json
11154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dd6363f0.json
4897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88c0e21d1.json
4472    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af2ec000a.json
3827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9eca51592.json
12241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a4b6ea39.json
9849    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b74e375f.json
8743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc70e613.json
79    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63ddd39f4.json
1242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1171c9a41.json
505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2400b537a.json
6822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de0f0272c.json
5149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
984efb177.json
4039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1878035a.json
1900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82530d72e.json
12171    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1499fbe78.json
2915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8f6ede8c.json
3516    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c16df543f.json
10551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71ef1c6c4.json
14242    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b60f948e.json
14723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d7d16ce1.json
3642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9893500e1.json
5588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59097271b.json
11035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daf955524.json
14050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69daafdd4.json
2713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5aced80cd.json
10032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31893804f.json
1794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
215f9a760.json
11899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6185f59bf.json
3263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75c84313d.json
3982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c89dcf5ae.json
2301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91e996718.json
5780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91e1bffc5.json
1890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

037b1c131.json
3053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
341420028.json
13696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a7798d2b.json
12767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e333feca8.json
10780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7a55f716.json
12662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c296a253.json
9459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c9d562ac.json
11893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0c1504db.json
6891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e50b52c9.json
9090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62d09ac7c.json
9420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afb45dfc6.json
6009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3629735d.json
7728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2f9689c2.json
1281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
222afe2dd.json
6873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2683c99f1.json
2329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf574d89c.json
11312    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf87b176d.json
4435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94aecc3fb.json
11508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
458adc77a.json
6043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0d5ff33a.json
2525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0c26af32.json
4102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23cdf5f21.json
13726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
573f51aca.json
9017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7eb03730.json
1260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c611f493b.json
3417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
518e71b74.json
4237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e65daf4dd.json
3573    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fea00b643.json
1147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24d3b54ec.json
1960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0d254628.json
13564    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95fc36030.json
7050    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e301ab49c.json
1646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd7102d9.json
2257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
794a45833.json
350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83defd365.json
2198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b32cba75.json
3817    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b3387bd7.json
10605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea2542b58.json
11406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ad53619d.json
3282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df0a5e6c5.json
10654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fda1395ab.json
6979    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0b9282c8.json
1660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ffe99b25.json
1771    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64c1c412b.json
475    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee24b09bb.json
12709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7fddaed.json
3097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae0c5671e.json
4006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99ed50a86.json
4238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff498c903.json
7316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05a05d562.json
5243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b65f9305.json
7941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afa07a0d6.json
4411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cecf7977d.json
13566    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4221001f.json
3855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c43ca0a88.json
13013    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0e2880ae.json
4290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0be7da0d.json
13486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e09bfe1f.json
13397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ac51d5ce.json
4875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d4940497.json
12505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccccfeabe.json
5882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2cd25e49.json
9002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b70ec3788.json
14076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e362e64bb.json
11201    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78631549e.json
9291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c2af85fe.json
13419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
537b5f09b.json
8564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8240f1522.json
14149    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
931fd5858.json
9555    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
226e8fe7c.json
4473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
800680beb.json
9478    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6556750a.json
863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e241fc7da.json
13544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2cf852c0.json
4801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68860d109.json
3320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
139f58538.json
9647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b6cb317b.json
5373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b1211e80.json
3042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
166040493.json
5420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98da79d01.json
10431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20e75472d.json
7543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f12e6d07.json
8820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c263fbc4.json
770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a977f3331.json
5938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0e392bfb.json
5975    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06ed12b93.json
4995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdeeb6fe2.json
11781    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b5c799b5.json
7101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f2daa8e3.json
7067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffef9a2af.json
2913    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3821d75e9.json
9829    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89792afe0.json
10942    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8044a4f7e.json
12360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8d22c965.json
3627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
006d301e9.json
5327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7de2f688b.json
251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae38b9254.json
1348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f69a878a6.json
12641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d58ebf3bb.json
11319    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43bae1c6d.json
8374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c62b4a8e.json
13940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a72e084a4.json
971    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0a9578bb.json
346    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73c2c22ca.json
4280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3f841674.json
517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2852d3c30.json
6574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d6c8d486.json
3310    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dae967f1.json
10989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba79cfddf.json
13843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b4b4cb9c.json
4587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8df0bb3b3.json
89    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67115d437.json
6575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34f6111bf.json
13247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac813296c.json
10954    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61003963a.json
9644    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cc20af0a.json
8394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1985add1.json
9114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b40ce1b96.json
10532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
085c9be4a.json
1049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8908c9d99.json
784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56845ff26.json
8042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cde24ccc.json
8947    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af9325798.json

11175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f0e90bdd.json
0f311b358.json
1043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3604fc814.json
7192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ef8bed36.json
10409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
296bafb6e.json
3246    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f858046c.json
2293    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be579e6ed.json
12402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71cdaadb1.json
7796    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eb30abb2.json
12777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d711b01.json
3966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c752844d.json
6711    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9cb42d59.json
11912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dc33902f.json
12740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba2d4e877.json
4650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73501589f.json
989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caa5d1e6b.json
14338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2563127ad.json
2852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
850632538.json
2252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
329058ec1.json
11135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c659e8a32.json
9884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1265050f.json
6468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08e8e74c3.json
9846    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
850875906.json
b386bb45c.json
750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b86b0db65.json
1902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b7ead040.json
11567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e348d720a.json
3454    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ad4a880.json
12528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0503dd75.json
9051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf9ce53b3.json
3676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b1b5fcfc.json
5397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
059a68bf0.json
12616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d5afdb0f.json
8252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d840b5a02.json
6336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9185b2ed3.json
8650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b65f00ae4.json
13596    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45d814813.json
8406    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400c2ccab.json
5469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0f46aa3e.json
5642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8335d65e0.json
4915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f18704f7.json
9998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41a6a7467.json
11811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f08b9d3c3.json
12478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc9b4b692.json
578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c7a8ea18.json
5348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f5d44f43.json
10843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89c2d660c.json
14905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d74c2e08.json
6539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b440a9cf1.json
11998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef638b9d9.json
4763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef5a07ae2.json
3983    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad111a12a.json
11859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a06a5244.json
7714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fefb3826e.json
5358    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc8388b28.json
2291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3a680ce0.json
12306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c69bdf768.json
2343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4235841ea.json
9540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff2224b9d.json
7804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac45f71e3.json
13989    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
858b1443e.json
13193    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77a74852b.json
5188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c60f7300.json
14730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
588ac0ef1.json
5810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49e00fc7f.json
13931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e03ec2a98.json
13076    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ea10e37f.json
2672    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a76fa694e.json
3788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8de51ad1e.json
8204    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
345b95213.json
10339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b0da38ae.json
13603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee34f3079.json
9780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6c14900d.json
9387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcb42ee1e.json
12128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3639e2409.json
12012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0adfa8a60.json
1414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39b3fe88f.json
11358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84fdd34c7.json
8168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9243b2c43.json
7847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e01a6de2.json
14239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dcee3363.json
14165    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d32f11b0.json
4056    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ccdd1a98.json
11951    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c17f26c4.json
871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4bffbe04.json
9433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9151664a.json
1170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f7d6b89e.json
544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9595d1f6.json
14180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d517a321.json
9473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dcbe818e.json
688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78332e36f.json
5308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a32e58f2f.json
14173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a2f44ddf.json
468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88edfa259.json
9619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2037a7b0.json
1255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96ad2141c.json
12273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdcd82280.json
10379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af4483325.json
6948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d584af81.json
7379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29170247f.json
5326    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6003cc8cf.json
2373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f94d8a2ba.json
10524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6c3faeed.json
11392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbaec0999.json
659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e0d923df.json
6228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99a9c9a23.json
10265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
409ccc60e.json
6296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c67aca639.json
12690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b4690d1f.json
1577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bec9dd86.json
8930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72b0f5c4d.json
1520    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b8832432.json
6809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
298feb02b.json
7484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b2e5e410.json
3330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b386d20ba.json
6865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffdad97e5.json
14282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb1f56ed.json
14616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6202e7d4d.json
4359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
225d2e242.json
7690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82b3d7fc6.json
7023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a8770d75.json
13162    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4af42055.json
2127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

5a089c77f.json
9524    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
856005eae.json
7604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bff1ab0b.json
5714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91add3784.json
2551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
377d9bef6.json
12988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48f20f515.json
1816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd16029b7.json
8264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
360f2c8b9.json
14392    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80fcac43d.json
762    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25f055b91.json
12798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9b7b72b4.json
13438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b4a0d698.json
13080    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b5e81279.json
11597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35ec69571.json
1707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38ed119b6.json
5059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f4378ff6.json
1916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e42fd0fed.json
1757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b214efd1.json
13020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44d722701.json
10023    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1f08c5b2.json
1331    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c93e37265.json
1231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b38a74866.json
16    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1be58123d.json
14856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aef2fa931.json
12654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12b1bce04.json
7593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42e7de7c0.json
730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f19658d12.json
14185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f15ed6ab.json
14450    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
788e8757d.json
3918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e833d08bb.json
12327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c2040263.json
13525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dfa1e78c.json
14201    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cea63a41.json
519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7395053bc.json
685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c77a68714.json
2282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96cbe1e48.json
4833    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a88845c74.json
8672    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01c6d3224.json
10624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b129e668c.json
3698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
854319675.json
1176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93329ec1a.json
12793    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5f76fab6.json
13301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9833d4b.json
9936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0566e4db.json
3134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5573e21b6.json
13580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25ffa1850.json
6648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f829fad2b.json
13272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01bcfcde8.json
7659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e392586a.json
1703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eab258a9.json
8363    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ceada263.json
9712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f95db0cb5.json
13371    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d38bcdf49.json
439    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5d514b10.json
2286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02d644003.json
6734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cf66aed4.json
7503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ca38a180.json
7191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65c2785b3.json
9252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5a4c2890.json
7170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd37ccdd5.json
1158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26988350b.json
13180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2c9dd7d1.json
10950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a87da606.json
10766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91efb738a.json
2935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1548b685.json
10526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43156136a.json
1961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e24f14d6.json
609    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4df3f4bc3.json
9057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d622bf92.json
12588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf42a225d.json
12185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9a014dbb.json
872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59d4947b6.json
779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f70251906.json
224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a4ce4c6e.json
9927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2618aa6a2.json
6667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
573f877f8.json
9870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8271c7e3.json
6196    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c924a03e8.json
1582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f32059805.json
3266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cb8fe436.json
324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01f7fdb78.json
360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
949cb7ee9.json
810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
095de41ba.json
5017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c5e8cc5d.json
486    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
411bba4e8.json
7748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11b20ee8f.json
2015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3832783a.json
8563    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed97d1485.json
7441    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ba094bf4.json
10838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
299e17017.json
14402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46ed43d61.json
10696    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ada9a854.json
5999    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e5f1623c.json
14125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bfb8da14.json
2086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6da753c92.json
13248    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d6b89eff.json
9255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dafa7b63.json
8901    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e562fa52.json
2675    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40c0fdccb.json
6620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e50a5575.json
7031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f4291ce6.json
2566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e0d0a9af.json
1860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
802a18435.json
10760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95b5a7b19.json
6254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b4a3074d.json
9312    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81b753aaa.json
11203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d8e820b0.json
12576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29d752f7f.json
3130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d980c361e.json
8483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59e24567e.json
1012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
620ebd7ab.json
10045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82607d1cf.json
9428    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
513062327.json
10374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a8fd6707.json
1972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc4b95345.json
12470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21f945788.json
5914    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9791b85de.json
8417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6e45accc.json
6342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60ddc474c.json
13671    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
650a1a505.json
4272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb41cd1c5.json
3303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9252b5dc8.json
12085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
058394848.json
8325    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36e1415c8.json
12697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6223c652f.json
8680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

dda9d6e6a.json
9794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
671ffc570.json
43    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cfaaa67a.json
7452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ffc5c1b.json
8459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a2e1d05b.json
6618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d837f80dd.json
4457    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3185aa328.json
8554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecafbb542.json
12413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff7707a35.json
3789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42a8d4f4a.json
3350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4247730f1.json
7912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfbbeec5a.json
9170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0aa84916.json
12345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dcb51c02.json
12898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f0eacbdd.json
210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
286ab1e93.json
7984    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9391d398.json
14919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c92cdf20c.json
3485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8da7afcd4.json
9175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
507db6e4f.json
12423    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9427b3749.json
14408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c43be9e6c.json
4122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa773690e.json
9042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31f59daf4.json
6295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9daa740bb.json
5401    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5330c4588.json
7960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0977caea0.json
2258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52ec30101.json
10851    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
166947bb4.json
7081    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3863ab300.json
11171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4eb08c79.json
9218    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbff353ce.json
912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a8cbb0c8.json
5646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ba019cb8.json
7350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e60195d5c.json
6063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b532e9588.json
10601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcf8ec029.json
3298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d6cd8ac7.json
6364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2f984796.json
13777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2628915bb.json
14220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e3607e1f.json
9979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
470fba174.json
10250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b558d016b.json
7586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a52daa7e.json
13414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3584bf68a.json
12995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
595b8d58f.json
9149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97baac4eb.json
3551    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08bfdc66f.json
11682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5f1ea56c.json
9703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20d4ea30e.json
575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df706fd55.json
11563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
070faf086.json
752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5c41169c.json
7286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8d840693.json
1747    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1afdc26fa.json
12368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6a2a2e37.json
1204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2c03cb2d.json
3905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6db28991.json
3577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a31d4c0f0.json
8297    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
887b5144a.json
7553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfdab2894.json
6389    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccbd1f9fc.json
13361    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d23a8d771.json
765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce2004c9e.json
1567    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4657ae5ac.json
3120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9ac456b3.json
11132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5521c7e1.json
2773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36a9087d7.json
10328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e808828dc.json
12126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
533c528ec.json
4850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d3ee6378.json
12432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdb03c163.json
4071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e914bdd82.json
1793    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d279eb58.json
7632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
373880ef5.json
8240    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25e0e0edf.json
12118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9702a20bb.json
10126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0063f83c9.json
4773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bce0e17b9.json
13880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45c2eb379.json
1733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
067d0ccd3.json
2553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe83618e5.json
2009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6561001c8.json
2199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db27a0a42.json
11483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3e32d538.json
5020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e4420002.json
9009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f78e05ef.json
8119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a528683b3.json
2480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d1d8655a.json
5652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13dbd2170.json
11797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b932e373.json
1009    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea39d7ec.json
3113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5943167f1.json
5976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7975df564.json
12018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49f6a8909.json
8365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4033fee1a.json
12414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5053eb47.json
5200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef4059fae.json
10832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cde886ff.json
9659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7188b5e8c.json
2610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c5dd1f7c.json
916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4475834d.json
1536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e90451ea4.json
3139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9ebb9992.json
1048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a90a4805.json
14578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ace21b6b1.json
40    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f677061e8.json
4427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73d7bb2ce.json
2840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc4d1c61e.json
4231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b501f1d8.json
8045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16fb340bf.json
1780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
945346188.json
6795    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
966598774.json
2395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e09c0a3be.json
14315    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fc5c49c1.json
14184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4efe77aa0.json
6273    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2a04b6e4.json

5369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ab4a7a66.json
8767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f22f3578c.json
1750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
916165c1b.json
3100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c930b139a.json
10163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18aa41749.json
6426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc2ae1787.json
3804    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64070899d.json
3476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8eb134074.json
1118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf20ac1c9.json
13167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ca18c1e3.json
3200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88030e16e.json
689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e58931ea.json
14622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0244298a9.json
11039    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bc54baef.json
5051    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
447233a49.json
4532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
553b61d90.json
11915    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d867b8ee.json
12230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34b96cf6a.json
3647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
245b99f60.json
6994    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afb230f5a.json
2406    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c81b943f6.json
9421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61d4dc56b.json
4809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44c308937.json
7817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
042dfb970.json
12589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2145e15d.json
3832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
373f757c7.json
14395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a845ba4d6.json
14342    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b59ef7ee.json
4760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
774de959c.json
12351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6e25d716.json
10145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc563b215.json
14356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4695c4fb3.json
6719    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4415e636.json
628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ba58565e.json
3324    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4103336dd.json
3232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65614e7f4.json
3936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9bf3b7ed.json
10400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
734123308.json
14922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca90f9062.json
13124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acc76c678.json
4440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4ce7a1ed.json
8202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ea65996b.json
13206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ab1bdc9.json
1162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd617c72c.json
1071    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d77a66a2f.json
14339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d669183f.json
8492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9403bf0ec.json
14550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a9a33d29.json
7705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0adca3f66.json
3391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
621a16b0c.json
3814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83976eb62.json
11671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67d853896.json
2061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fd59d272.json
13537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
473caf456.json
7805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77a6f71e8.json
10002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53fba6573.json
8152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dace0494.json
1880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9f512b8b.json
9935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbc6d3812.json
11757    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f28036d8a.json
3958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb652ec07.json
334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d1ea2aea.json
5462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ee5f72b8.json
8130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a72ca4ed6.json
9617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d83749129.json
10609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44dcffea3.json
13804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
feec7a438.json
3826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b37d04bd6.json
14307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0e2d8d15.json
10636    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8b827be1.json
12947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2de05ee7d.json
6799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
348591b3f.json
8629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
324266c95.json
2312    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a7207717.json
1440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e72112bc.json
3142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b4a22c83.json
7477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
965adb809.json
2141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b1cf81d4.json
4625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e203eeaf.json
9166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
888116751.json
5802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eec3cbd6e.json
11021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a464e436.json
13618    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dae13a47e.json
4807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d15a5363e.json
13820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2689341e7.json
14946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
079565e72.json
0ed8d0f9c.json
4415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
647fe8d68.json
6742    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e298c61fc.json
13487    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
363a00ab0.json
2801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
570fdcc4d.json
10558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a86f09670.json
10391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54e731fab.json
14821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c9f807c1.json
13489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22a91e143.json
12530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac6adc2e4.json
11110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2177b28d2.json
9655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
881d46cc0.json
1620    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51df78553.json
1177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

30fff49fd.json
2982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e1a54250.json
9836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a615bfca.json
14403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccb7df174.json
11845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ed0c2a41.json
4469    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ce643dc5.json
2665    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29193bf76.json
8759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27cf74bf1.json
14132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6c159277.json
7104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5afa2e561.json
11469    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d139783fa.json
6419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abc9c4207.json
3114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
677968b60.json
13024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8326fa5.json
1998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec83e77f0.json
8620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fca85f778.json
551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14831f659.json
2209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b09fa9385.json
8026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d6bb4a66.json
2490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cd1d06ab.json
11970    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc88ebe46.json
3208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0aa2ce4a9.json
10072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc3ebf72a.json
2055    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d02f91fc.json
9904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adc7713b1.json
1829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b67a29908.json
11200    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e204110aa.json
1735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5353b2283.json
10359    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaadb1aac.json
9088    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c3f79b11.json
4389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01142a354.json
14399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
031a01c36.json
2562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34482d66a.json
2618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7276be56b.json
14163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d89ce4c76.json
4476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84b36d951.json
7317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a83d95ead.json
14992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39adf62b4.json
12109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a1d75edd.json
10350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
941eb9304.json
14567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40c204453.json
10202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a3e60ced.json
5266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efeabd288.json
13400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62dc0532f.json
5773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d4c495dd.json
9356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ae342ed5.json
4078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fdebca57.json
12220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bec49d8b7.json
2068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51226d067.json
3165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a719040f.json
10140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87b60f563.json
8761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0a0a48a0.json
12382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25c7d6c3b.json
133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
372433bc5.json
8892    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81b5f684a.json
975    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a64ca36ca.json
7418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3a372f31.json
13473    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6e56c908.json
5379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
040771e8e.json
233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
858854bb5.json
1897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
213cf987d.json
6511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cbc3433e.json
8764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
269db95d5.json
14693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7fa5b815.json
751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a6fea502.json
6427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7f9361f9.json
13633    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c3222742.json
1783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1a2da8ef.json
10523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e759fed0.json
8120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72c38b9ab.json
4052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38a780df6.json
13161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff9ce365b.json
12759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
001b1507c.json
11520    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f41a024f.json
14204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bed5b657b.json
12894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e4049f6d.json
634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a016a6a0.json
14777    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d9dd14b1.json
3943    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac34b6e29.json
14223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c7dd9982.json
8427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
079332bdc.json
13785    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e47aeed72.json
12696    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdab8ba8e.json
112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6134ae21d.json
6523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87f206cea.json
4058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4652decf5.json
5064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d350f881f.json
13919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3e73475f.json
12520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ce40c2bf.json
4186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96703e01d.json
2073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab5964338.json
8717    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da9b9db54.json
8797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
031a0e45a.json
5253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c03fe7452.json
4029    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cec359a78.json
939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c896760b.json
9816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
117059fe3.json
10953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
262c36889.json
10209    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7aef49fb2.json
9377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8e776446.json
1649    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1390d450.json
4822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebd3ca9e6.json
2268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e825b8b9f.json
772    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
406f92f52.json
2459    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
752b2d9c5.json
4925    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ee566501.json
8448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
093620671.json
6637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56d6e2c8b.json
11396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
522d0728c.json
10044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a819945dc.json
4722    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
618bb4def.json
11046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6dd5e23.json
477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2048c71d.json
13568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44c117982.json
3482    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1436092b4.json
6470    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092e6a628.json
1640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0fde0412.json
6867    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ca443ef0.json
6701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67e7da152.json
1094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d08d2829f.json

10644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45d2ddcb8.json
74    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f78266ab.json
7225    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa07f7477.json
593    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d9346cfb.json
8233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
566dcbd9f.json
11767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0abff77fe.json
7294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d70a0499.json
10884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e95bb9197.json
2170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
addb9bc2d.json
14023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac49bdbdd.json
523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54b687d7c.json
13978    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
385028a00.json
1265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d101a0c3.json
10314    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0764fb9a.json
13646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a516d6ea0.json
12385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ccd9729.json
959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec138f2a8.json
1282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb3b2ad1f.json
2563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d2f2a305.json
3563    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd4b05b8c.json
666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ce285f99.json
2311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a1f2a306.json
6424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65b05f438.json
181f3796e.json
8040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a41b62aa8.json
9675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c70e9de2.json
2795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e129ff4a1.json
4137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35f9132e5.json
8368    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ad55549.json
8347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
754240b6b.json
7940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
478312b59.json
1856    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4f05fe80.json
13655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0f6f4bd2.json
9807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8fc9bc28.json
6724    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e507f855b.json
10282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afec4c35e.json
1296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea2ad17c5.json
11412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
227bfa6b8.json
11878    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc1b809db.json
7626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a0ebb3d1.json
14434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb74d75c2.json
1778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8483b2161.json
4933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae17429ae.json
8810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64ea61ea7.json
3131    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c720ee024.json
11499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7509ed502.json
9510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5746676d.json
2012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc7a53ba0.json
8176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc7f7797c.json
14867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7af4ce3d.json
858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b22f97b3.json
3010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
063521459.json
9834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db2d1ccaf.json
14254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
158b502d3.json
6910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a0d03a9f.json
13716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c1b4bb55.json
3666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9f772c36.json
4686    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2160f2109.json
6294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
918471707.json
13984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cfd4e3bb.json
7558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0605aab21.json
14471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8655a46ed.json
4568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82ab0ebbd.json
9181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa6c44396.json
6933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cd340cfd.json
10550    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aabc0113.json
2912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ab429fcb.json
8178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb42f77fd.json
1190    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8e2f840e.json
12252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19f38a3f0.json
393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04af86059.json
13911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e704dadb.json
9615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28cf4a84d.json
5655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff311279.json
11181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4e102aa3.json
6961    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10f1688d4.json
12028    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99b263dea.json
12454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1e4b433.json
1508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0633474d9.json
4716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a9f15d94.json
14469    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a249a34f9.json
3846    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e12936b0.json
3917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87143ebd2.json
5680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86d203b94.json
1103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
516646a4f.json
9739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c275f0975.json
9381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3f2f166d.json
156    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b0f07923.json
8847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bed563dd.json
13527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0935ab38b.json
6370    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dde4e26d1.json
9320    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4168bfd52.json
6694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48cb3c66a.json
9796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4175a27e1.json
2390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ff9cda01.json
11743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
640e18ef0.json
979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
625543b75.json
11372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f017041ca.json
6868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35bbb3a85.json
14014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
254c3305f.json
2811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25a834a2e.json
14472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cb450c62.json
10772    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a07fdc22.json
7372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96a35824d.json
13428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c76d9c5b9.json
4317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
888a7fc17.json
8330    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fdb3a2a2.json
10199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
030387828.json
6406    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5997cc138.json
7895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8b38c65e.json
5169    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b4f31dc0.json
6316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f4f3cd98.json
5657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdd50f583.json
9351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44aafd1b1.json
14599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd6cb40d8.json
3770    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbe30d86f.json
13118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdfa41872.json
1844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
885c668e4.json
12136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
509180812.json
13436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01f976ec9.json
8105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
229beedff.json
1866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46d9b2934.json
13119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5776e3791.json
12471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c862b8a3.json
2251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73ae816ce.json
7228    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48a2123f4.json
10971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7b533990.json
10773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc8bbffa4.json
7254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3508d0b46.json
4023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5fda5ac5.json
5363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

d6ff1af86.json
10972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2256216b1.json
5723    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f39fef7c1.json
941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5634cfd98.json
3459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6d6d4aca.json
8642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
798f4a1e4.json
1142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
546cf9e37.json
9274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f5f5782f.json
781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64da323a1.json
7370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
787086e9d.json
2880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53b3ef282.json
8503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3945aa2e.json
9372    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aa0769bc.json
7869    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea1318971.json
7624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd898f38.json
5183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0096c460.json
2847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1338d152.json
9055    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9b0d3370.json
1632    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c14d8650.json
13883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ff3ff516.json
9350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67dbd5ed9.json
507    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59a08eeec.json
8041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d25638f81.json
312    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e70a5a3a.json
7734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a04923326.json
7607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6ea19029.json
13330    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1116d6c4.json
11422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
040a9a6f9.json
7863    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1164babb.json
7165    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60b9421cc.json
227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c69ce3b59.json
11316    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4891fdacd.json
3239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19c0c9d93.json
13341    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3983e7c06.json
10814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
157e3e074.json
607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d899c9ef7.json
3123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e3994257.json
4790    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51398fac1.json
10327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bcb2c2b5.json
6116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b01f5e06.json
11531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08aad5787.json
12031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37419ab7.json
9995    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a36e3c034.json
8065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e43a342a.json
8931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7383d83.json
13711    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acc81bdf5.json
12627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
706c85343.json
988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abe27623b.json
11001    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e936b0102.json
7089    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9c151e72.json
4928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
686b90dfc.json
12526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
473af1ce7.json
13925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17ba9f283.json
7242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecfcb4430.json
5696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b78b30c18.json
4965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd5a7effb.json
1434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
148686ce8.json
12129    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13be42d0e.json
13656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b96e5f6a6.json
5244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96462a567.json
10839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a7d70a4f.json
3301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35203bd2a.json
13479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f02a1c14.json
1445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dc593f4e.json
10243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15bcbb6e2.json
2598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7d23de06.json
1457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc695e9d0.json
7851    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02af3813e.json
5746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
071753413.json
11468    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02c7d1b74.json
13197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d31e4c6c8.json
59f987236.json
13218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee83e7a09.json
d6cfa5d4b.json
968    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0736a22f.json
9134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff2cf88a0.json
8181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
251f4dd60.json
3833    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89bcd0921.json
14439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fecc5cf7.json
50    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bec28b35.json
13130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc1457818.json
242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5183f369d.json
5941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c62a2a817.json
10737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39444f259.json
12229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e82e76cb.json
6499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c7fc08e6.json
13954    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d072a58e5.json
5225    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e793c38.json
5739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b99186353.json
12837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
180f1ef16.json
13766    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cdf29720.json
11881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbcf45977.json
7040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02468e968.json
2676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
902087c95.json
2991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dff15fc4.json
8060    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16002dd9b.json
3602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
387701d9d.json
10315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f1a882b3.json
3478    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3402b3970.json
4616    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
414d8422f.json
3874    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3853ff1dd.json
6238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73066f6ff.json
807ea3b72.json
3167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44fff524f.json
11601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56147c737.json
14113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
765bd139e.json
12195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5ba03e9a.json
2481    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
619d6fdf8.json
9745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c749028bb.json
5673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48cd2ebaa.json
9724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d59c369c3.json
2804    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ded3b183c.json
9457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09b5921e9.json
2753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95e06e711.json
8779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cba1503b.json
3620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada1e6f38.json
12857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64a0deeb0.json
9984    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bedd7f1e7.json
1477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
597ff6946.json
11635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ca64b428.json
14692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ef431298.json
500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9c78e9fb.json
11514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d21dc4a8.json

514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e0ce6020.json
9460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b677eae2a.json
11328    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca46b14de.json
2183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
182faa94d.json
7641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e24a30aaa.json
7943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b022c1924.json
841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71d834666.json
1187    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f91147e5f.json
629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0510d2767.json
3274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f7b3566f.json
10285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1938a57f.json
6463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1377d2c0e.json
12328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c23cf72e.json
6802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7942a5180.json
2295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc526d236.json
1317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146aa46b3.json
10841    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94d2d552b.json
9673    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eaef39ceb.json
5254    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0efe2c72.json
5474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dd5c500a.json
11159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e64404196.json
6739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2f3db726.json
13312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a566e5a44.json
9070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8b34f964.json
1712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b8db7cbe.json
13366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf76c794a.json
4437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f500d6361.json
8747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b47109e90.json
13399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99daba941.json
5181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1539be087.json
5099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4dd57b11.json
13837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
876dd37df.json
8488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b6e5aca.json
109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e570d64ac.json
12564    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1ecc1b26.json
153    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43f99cecc.json
4108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c90570913.json
9747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
628439a3a.json
6304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26d0bfe44.json
14860    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4821de20.json
1936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cc8c07d5.json
6012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ea2638e9.json
7008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5aeba57be.json
9437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deeea2b65.json
1047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
004c2f355.json
14684    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
221cc9a2b.json
5215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4f17eace.json
8227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ff4a6c99.json
5962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d0fcdd6d.json
14603    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9b44c0c.json
11417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb19c3013.json
6013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
143d10038.json
4818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0d18f038.json
8846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
301a245e6.json
10086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
508df8433.json
2839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e25c09b2.json
1171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15600cfea.json
11167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
263f0704d.json
13761    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66dda45c4.json
347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172c8129a.json
2175    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff43926c3.json
9296    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b4c0f3b6.json
3834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c9d75ab9.json
9677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cb5c5f68.json
14520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fcdf3368.json
5371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
767b3b7d0.json
1841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aad08c47b.json
2607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1871dd283.json
4581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5df81f99.json
449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d005caf41.json
4079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c74126469.json
6139    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf9e48222.json
3358    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5dc02b69.json
7364    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de9e7e87d.json
13337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a7f8a828.json
11011    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aaf058b6.json
9931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3681bfdb9.json
5624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2b9c5176.json
9632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c1adfa96.json
10921    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ece153328.json
14732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ed73fc84.json
5972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9819716c8.json
8416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50811e391.json
10097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b410bfdfe.json
9545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f7a70728.json
8574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38c82bfc5.json
7680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b54ee792.json
8404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebe1f2665.json
2906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7aae61018.json
13296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0b6196d9.json
1028    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a868df43f.json
9370    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd5d07137.json
8334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe6bd5d82.json
10354    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
695ae7cbe.json
9424    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6984b9727.json
2648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ed23a049.json
10497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
846e720dc.json
616    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9f2b6e32.json
5460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0e26c028.json
6754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86d20d7e4.json
12228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04c4a7493.json
6903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f39ec246.json
13852    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22499988.json
7923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee2e82f01.json
14396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef836c3d3.json
11712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0be5af159.json
14682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34fcc459a.json
2027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09c00211e.json
9479    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d6e2292d.json

14701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d136a793.json
2823    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed1ea1e74.json
10173    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ece6b26b.json
11072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bb85e53d.json
10904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b51b41933.json
4601    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f4e4f83f.json
12675    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33a6694b0.json
5637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c1cbec2f.json
1959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76301f924.json
5035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49e7b59e9.json
13469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ae60c34e.json
10613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce0fbe463.json
9516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d4cf29f6.json
13859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2aaa0c8b6.json
5686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7006ed96.json
5808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1caf9686d.json
3816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77d7f8364.json
11449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48317c9e5.json
9949    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33a9dff78.json
10054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0dbd7901.json
1229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edf3478dc.json
6557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c947d8169.json
8544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b9bed882.json
3599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbd704c14.json
10563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf22b5a35.json
12090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec5af82ff.json
13588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a4d22688.json
5603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
443682c9f.json
3782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092fa68bd.json
4820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37fadf608.json
5775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fae1e95de.json
2808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
655eaa578.json
12653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06b533b04.json
3781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96a1bce27.json
794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c33e8db3.json
4725    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2352b7f0e.json
12300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8040ff400.json
6816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51020fbd4.json
6067    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acfaf9210.json
3465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f394d4aad.json
9136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dccbfd25.json
13569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
169184766.json
4871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c9133a83.json
7696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a2816f0f.json
6237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c790696c7.json
10426    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1940b59e7.json
4890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
151d50f53.json
1025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
004a26127.json
4743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f42161740.json
12746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6bb64d82.json
5295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b871dbaa.json
5688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29a2ecf1f.json
3284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40156a896.json
10106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fd0556db.json
10872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e01e4a2fb.json
13099    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
011a11cda.json
4842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43fe381b3.json
8079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
619f26bfc.json
2321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffc5cef6.json
14801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9f90bdfe.json
9805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c1981df1.json
1210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4f1bc76e.json
1007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a16c6d55d.json
4804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a6f0c997.json
2544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63c049a9e.json
9237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
608a58c8e.json
14221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eea123bb1.json
8104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0f4115e6.json
9374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d3aef491.json
923    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2566ab3a5.json
7672    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
732b578ff.json
12356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
094636517.json
3923    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26c1fc882.json
7251    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
486f89692.json
10294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d00ca4d0.json
13021    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ea3cf8d4.json
11350    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7988bce47.json
5128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e83e05a06.json
2959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4223dd4c.json
13498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f0e01c1d.json
4663    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
994450113.json
13011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a59ae5ed.json
4326    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07b994326.json
1267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9827921f8.json
13003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1db33c30.json
13854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb0180584.json
952    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e02b6a2d4.json
698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
467614705.json
1031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c98188040.json
1845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da697d5ba.json
13320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9ec75efb.json
10900    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32ef0472e.json
681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00b23513e.json
4284    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6637d165.json
674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f729f19c5.json
5826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bab1eacd.json
1322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66832a1e1.json
2019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59b224cc9.json
680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0d97f130.json
11078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df0b49ce7.json
2528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea72e6c5.json
193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ba2a5c50.json
1671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7402f657.json
11269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ee56e81a.json
626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a86bbc71f.json
12435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80f1863b8.json
2379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee63ca0b4.json
3662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
469894776.json
14581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc7ea0a3e.json
6368    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0111f92ff.json
4648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be917151a.json
9445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dde0775b8.json
3268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8773f250c.json
7716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6335be38.json
12116    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed194417f.json
9286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ab29b3d4.json
2531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e12b9baa.json
14047    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23c4874d8.json
8813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4badb22cb.json
9688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79f358573.json
9847    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3eaa698d3.json
10159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b0662306.json
12123    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c14530f38.json
6957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e881542f.json
6317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61b6e170c.json
5616    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f87c02978.json

12094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d41f2a466.json
8077    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0f2d927e.json
8981    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a6bc9e55.json
9035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b752d78e.json
13515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92dcf8a4d.json
1766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40fbb932c.json
5162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a86cf6b79.json
6942    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4574e3de4.json
349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e16bb6356.json
9985    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93df8b5c7.json
9155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bfca7e65.json
7766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59bedbb97.json
14142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0b9f2902.json
14566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09417404f.json
5990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
130797334.json
3515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92189aa31.json
1744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0fb6cd44.json
2411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77d4eba90.json
5335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66409739c.json
12048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b533529a6.json
14085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09e39377f.json
8517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
989e61978.json
10683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28cc87730.json
13343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207c24fd3.json
7088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91054dc16.json
10603    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6704c5fd7.json
3404    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bb7dbfc2.json
7032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d1067e63.json
2655    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ba9dfe93.json
7353    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78dff2667.json
8948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce788268c.json
948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f7bf1b32.json
14224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8b05d43d.json
4666    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
760c7d8ac.json
1588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45ba264f2.json
6387    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d19f035bc.json
4500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
832110a99.json
9776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8a47785.json
527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0659c05d5.json
10351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b188b50cd.json
12527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab48d21e0.json
3660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7f4e4fb5.json
14773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0a1e1ecd.json
9438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77bff1468.json
13640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a47d1c94.json
12034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c95b7659.json
1496    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f0efae69.json
6764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4718084c.json
7119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
776354931.json
7327    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0858e3a6e.json
8933    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a77d17ef8.json
7726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a13e47c3.json
7472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27226ea0c.json
2134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fa3ab674.json
8493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a4c1709a.json
3267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca902248f.json
2231    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65e65ba4b.json
1828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bda2d149e.json
302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86aeb2732.json
11192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
530aac28c.json
14511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e7159da4.json
4882    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f42303f4.json
5904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26848ac26.json
1032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35cc85250.json
2064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e456bf863.json
10956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd53ebc9a.json
14512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
661bcb904.json
895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe056693f.json
4808    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
843910e74.json
3101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12c4ed873.json
3255    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc4747d5c.json
13885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4c4a926f.json
6106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48769873a.json
2557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
872d79999.json
2694    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccbaa4592.json
11720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1b7a178a.json
4408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0ec9b89c.json
5497    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d78d1dec0.json
263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b0b88ac2.json
239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3c7e1bf4.json
12906    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88bc9864c.json
7262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
765039f34.json
6702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6366dd2f9.json
6556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
868904c66.json
5378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf7c0f270.json
8420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2330704c.json
14521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c03a9912.json
10768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4989496c6.json
3159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
369dc90b6.json
1485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a311c6dc.json
5130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
062f73a4b.json
10179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aee21db9b.json
13520    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59e59bd5a.json
4544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da353217d.json
8827    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5d60ca48.json
14340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ef0ffe23.json
6812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6917782f7.json
10733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
155126a9f.json
4999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac1a70774.json
13070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8f60eb7e.json
5671    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8172e598.json
12991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b48d47214.json
5140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68ab069e3.json
3633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26fdc2915.json
1672    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dff83c9f.json
11006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ac21f5d.json
12997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
411bb17a0.json
10404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3b589e13.json
8058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c7dbce06.json
13077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d919bd302.json
1511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44817c8f4.json
1606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d18ee078.json
2502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9598a1528.json
3736    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
598f1fdae.json
3768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5b9449db.json
2963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5e083218.json
1081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4f476ab1.json
14947    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb248693.json
5170    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4da0a8ee1.json
3510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be84c367d.json
2904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
699365a99.json
10398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe726b9d1.json
14829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d08cf8cb2.json
7090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2edd6e44.json

1108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
848c1d759.json
1206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
560232264.json
39fb68722.json
12856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50ef65df7.json
14556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0bc14f47.json
184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7f3d97f9.json
12629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97a80f8b3.json
8769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5382ef1e5.json
4443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cd806c03.json
5028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba72b4212.json
11677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bf818d30.json
13102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f61c4cead.json
2088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95e69fe79.json
13304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
792c38c44.json
4872    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
502d58dea.json
11366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dcff2b5b.json
6313    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19272319c.json
2769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f4fff7b2.json
5184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a0395c7f.json
4784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67ef0c9a6.json
5092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d7c4455c.json
4624    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3583095d0.json
4301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46b603304.json
1152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b822d0566.json
4259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f2ddae0d.json
10997    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cf927527.json
2678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d6cb5b69.json
6677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a3ff7445.json
1971    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e1a6a1f0.json
14048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
885b7eb9b.json
1232    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2e4ec0c2.json
2995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5a4898db.json
4223    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9bc357f0.json
70    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51714821c.json
6953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b0b5d92.json
9338    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc0935a84.json
14988    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41bbdb352.json
6461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b47d7f0d.json
3702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daa543c46.json
4187    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb1afbaf2.json
9449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7754af59.json
5567    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48553ec94.json
3908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2cbdb23.json
13088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53561f52b.json
11960    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e1853b79.json
13557    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf4bbdbfa.json
6562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cda31e59d.json
5677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e79487c5d.json
11127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17b2d4cd6.json
7019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
230e1df8f.json
6042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98686f3bc.json
4339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
087313ba2.json
4501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6083e589b.json
3737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e60c80ab.json
14357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ced0659f2.json
1154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89a41673f.json
2615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48088c0e2.json
3037    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dce01bb7e.json
3295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8660ad37b.json
2407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae518aff9.json
6875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a71cafdcf.json
3960    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f15fc3d8.json
13243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82dd5838f.json
2272    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35bbdb5fd.json
12189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10ae2697f.json
2593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e7aa5866.json
6003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91f0cb0a9.json
6006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae219ff80.json
5596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ce98d199.json
748    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
662564431.json
11000    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7b5bf2f.json
13265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
533f52fff.json
3488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22abde55b.json
9228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a64e4905d.json
14782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e4020da.json
4974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db8a8df8a.json
10241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b86fd668.json
2213    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
783a33f4c.json
1bc97732e.json
9400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7330b19a5.json
1015    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed1f38a40.json
4252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
330f0e19a.json
10446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
047514286.json
8095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab3d83bd1.json
13203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b89a89c58.json
11307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d86d7a70e.json
4741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fbfd7f45.json
10999    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37cd2095.json
925    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d58c146d6.json
7498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec5aeb98a.json
2359    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c723171ff.json
4433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef15e6473.json
4172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a23f0020a.json
584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31b919935.json
11926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49b868ae2.json
9784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63e388a8e.json
12042    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2486fcece.json
3612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55295d374.json
7556    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc50c89d3.json
10388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f44ba1344.json
5403    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07c284733.json
10047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1953d1cd.json
2534    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b65dc15af.json
13839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4a00203.json
5612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
945bf5e17.json
4034    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8d35b6c3.json
6081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c5fe8151.json
14065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c3cb3d44.json
3040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e63eea2f7.json
4630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
454aa9e20.json
9887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6868acfce.json
2017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1803e4c27.json
8338    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2264970a.json
7501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d7573c5e.json
6883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2463e0981.json
12239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cba2fb07e.json
6367    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
185ea5010.json
12556    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b5fd0e44.json
8665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
951d3ae42.json
6621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5af48975.json
4583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f3e23878.json
1853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eadb7f25e.json
7816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8619af42.json
7993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a9fd8dcd.json
6689    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87e6807c7.json
11581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f75e3aa2.json
10615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172d395a5.json
2305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bf976dd7.json
7679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

cbd289193.json
6709    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cf741863.json
7239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b71eb2942.json
11742    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b6457bf5.json
4464    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd2dc39e7.json
11258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f47129b2.json
9199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0b1f82b1.json
11622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e2a19b16.json
8936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
896e733b5.json
1988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9619060db.json
7965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e976f3d3a.json
7002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
936fc22ce.json
11769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f410b0841.json
14830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ee76f8a2.json
3856    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f36088f5.json
7281    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d6d190d.json
2622    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
defebd6b4.json
8735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e77a97ac.json
1219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
382b4212b.json
4792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
331a14422.json
14005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bf4a2ca7.json
11229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0fcfeb0f.json
237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e0b14cf6.json
761    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8445b97aa.json
8973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
990eec1b0.json
6016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c79019195.json
9158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f3e70321.json
8106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4de6ea51.json
12095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c9d9842b.json
13731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f6b92b4d.json
13889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
931a50b80.json
8449    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9fe690c2.json
3878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59c9f850a.json
8993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0e241d57.json
13023    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c2fa49e8.json
7053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cdb5d61f.json
5520    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53abbdf1d.json
2510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bf4445c7.json
10587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71c3a53f0.json
8156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dc936ac7.json
7184    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b6b2524b.json
7791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
765da0e39.json
5888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f19397eed.json
6283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc3fe68d2.json
3220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
729d8ba72.json
11618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7a134121.json
7636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcec3d919.json
8023    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e1033fe2.json
10834    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f7080e6b.json
14092    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bddd63050.json
9311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e39a9ea7.json
10735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a904d6da4.json
7837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d90bd59c3.json
7311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
314e041cc.json
9821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e93afb8ff.json
1093    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5262ce2b.json
11318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65829d12f.json
9752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8233b736.json
725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12890e9dc.json
3443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b7aad341.json
4153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef0fde5be.json
5185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3264fe773.json
6281    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd8e8d7a1.json
7682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c67b1fa40.json
11920    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4be73c550.json
736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae6db87d4.json
14289    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bafa8c847.json
8776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bde1336b6.json
5927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21fc38738.json
9536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c6329c92.json
6100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad4a30fcb.json
9553    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65266fe36.json
89d4cef63.json
5727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02a13b2cb.json
3802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
802b1f331.json
14714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12ccd5019.json
4600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a31508650.json
7215    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5ff2b987.json
13efc38c1.json
8725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8be7beff.json
12153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6029bf590.json
1061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba11aaaa.json
530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
541400630.json
9626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91e8e97b1.json
6120    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
041dd606f.json
2351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f336dbe0f.json
5263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5a7d4dc9.json
2239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8913e5b27.json
14186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
368b2adc1.json
130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6b5ed0f7.json
13290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1ef3e54a.json
2586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f734bc3b5.json
11484    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccd3e236f.json
3902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
844dfd2b4.json
5589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afe326f34.json
5635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ba0c6894.json
373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16abc088f.json
2180    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57d8f9bdb.json
1572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7bb5cf59.json
11643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cce33a82.json
4028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc1319810.json
14814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42d94df4c.json
6224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8755daaed.json
5133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
865ee6652.json
3248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd056b65a.json
12182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cda0894a.json
5036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b26ccfdf.json
9768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4277c6de.json
4163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb9e42bd.json
5515    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aca81d4a7.json
10330    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
840fbaeba.json
7560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5df16a32.json
199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0322aa5b0.json
5748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe16bb525.json
5086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
954a6e415.json
2712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b25d569cd.json
9852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50bbe8e31.json
10127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb8d79ada.json
7539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63e212498.json
8419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05f00d521.json
8088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
560d2b399.json
9093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

428877021.json
4455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
870e7158b.json
10812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1099a5406.json
11813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c0273869.json
11461    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b7f2c603.json
9953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f48b3cebb.json
11536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a14fbb8e.json
5249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10050c93f.json
2204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c82c5903.json
14367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
245bfe92f.json
2640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24fc91fae.json
2436    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac9fefd28.json
11741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf8aa8f96.json
12301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
323f562e0.json
9151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27c5bfcf1.json
10266    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb5f471dd.json
158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
048df7861.json
13751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18e41c818.json
12117    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4622342f4.json
9777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
358f7abba.json
11243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e329595.json
6216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f15cd5cd9.json
8277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af514b027.json
4799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50d2b5839.json
8146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
652f89d34.json
2733    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1021dc35.json
9909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54791dc58.json
139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
865619d53.json
12146    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf2ae9919.json
2668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8420d063a.json
12044    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a78a1859.json
10434    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9fdc3e4a.json
3858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fa5bde3c.json
7799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e1727250.json
10541    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19caeb6b5.json
1504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6d59d514.json
2365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c929fefb.json
6396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbb0a9ac2.json
11691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e248258bb.json
11764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a92c2f233.json
2323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36bb93372.json
13472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b8614414.json
573    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19982272a.json
6781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7cb6e33e.json
13869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2deaf1e4.json
14120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0e61e2f0.json
9185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e93ec1c41.json
9064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17c5ded7d.json
10799    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e78e9736a.json
12543    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d3f0380a.json
10702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c932005f5.json
11773    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
500728fdd.json
8907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f6488260.json
12807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d9d9f2cf.json
13509    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
172305d1b.json
11784    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6c93a605.json
8382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75135cca9.json
12876    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e50174698.json
13913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b923cef0.json
8974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
017d966eb.json
14689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28bafb2ee.json
6546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fab074a0d.json
2397    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b231e001.json
12366    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c15f3086.json
1149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd2b84b66.json
13237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4909dc5af.json
14927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f24991ef7.json
769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46bb277b5.json
3161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f949d065.json
1366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9474822.json
3187    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85e0c743b.json
6377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b32339429.json
6239    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3004c3401.json
172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a44d42407.json
97    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45c278a7d.json
7761    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42ea2e045.json
7405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72482852e.json
4690    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7f77b3bd.json
13104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c5b817a7.json
10493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
372d1784a.json
5095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11db3b853.json
12258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f91ffd577.json
6919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2fe1eb7b8.json
14010    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89fd79488.json
1648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92ee0c92b.json
3227    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acf289a37.json
11353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e15b26ed8.json
5834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fd83540b.json
3191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4df0d1886.json
5ad497d30.json
10986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1736706f9.json
10629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
678d21531.json
9762    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0dec8779.json
64    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d51de36a1.json
4962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
919820452.json
11380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de884d234.json
3754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6239b2f3.json
4835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f639ea65.json
12491    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

d41aa1c62.json
6876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
940b0ad69.json
8062    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1652a3e1e.json
7398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1be2a9e8.json
5351    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8563bddec.json
886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deff069a2.json
38    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f1896e5d.json
12416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ca799ab8.json
9298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed89380a6.json
10280    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5c42ae26.json
4777    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e35d4d3b.json
7070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95bc62678.json
4005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00709d75b.json
2738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c2f67527.json
3852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
941880ea3.json
14973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ca8be82b.json
5710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
382e4bddd.json
1075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce344f70e.json
2468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58695e2f5.json
2133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b64e30a78.json
5440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
780dff088.json
10102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67b1168ba.json
4766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d50d37f8.json
6182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
500fdf3b1.json
13721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90f09b568.json
13810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b446053b6.json
7683    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa0f2c425.json
13553    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f3fd67e2.json
3909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d97fa45c.json
7345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11f062cb4.json
815    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ff2ae40f.json
9550    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95d2a0bdf.json
452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2d87dd35.json
14291    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f470d9f4.json
12353    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe5d572be.json
2596    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de4de2e7c.json
14081    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9715a897.json
1382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99c2ceb33.json
8826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71eb4e3d5.json
1531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef3fad107.json
12669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e2e049e.json
7419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b8c686ec.json
1896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
356f1ecfb.json
10529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92bf4bb1a.json
1569    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
198a73c5e.json
12986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fceb751c7.json
6982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bda912e4e.json
1373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d163b731.json
14987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cfd979dc.json
7571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08e703dfc.json
7645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0909c2bb.json
8199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4eb7f4df.json
377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bcda757a8.json
14388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0038c9343.json
4844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f01b64ff7.json
5477    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06fda20a2.json
14570    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23ab1d5b8.json
11853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdcaefa4b.json
13460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c4520bd5.json
3623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b0d28fab.json
8648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2edce7d92.json
8333    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8049d235.json
2691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86ff8539d.json
10495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f03dc1f4.json
11711    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1763b8b7.json
4299    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d805a1c90.json
9483    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eddc2e2ae.json
9858    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed390241b.json
12755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
682ed2e7b.json
2656    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fcf1b40a.json
12776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf37d753e.json
9182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acd81a109.json
5986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba54e88a9.json
4525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da6bb3100.json
279    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
771156bfd.json
12078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20f870155.json
9347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29bcccb7c.json
2130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d061bc124.json
14350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0617d9287.json
4228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc195b43d.json
4201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08dfce1e7.json
12256    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
412d6c47d.json
5203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53759835a.json
13480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
477d22816.json
12110    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f4c6ada3.json
3338    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de01d00eb.json
4073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d83f60849.json
4089    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91306f563.json
10375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbbf3acfc.json
7597    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
418e88441.json
5012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a77b63ee1.json
7735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36b7411f9.json
7334    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d994c86f0.json
7818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8af1b11ce.json
13407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bd8b2b8d.json
4929    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbcfcf50c.json
11886    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b94af372.json
12294    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8526200d3.json
339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b56430cd.json
1160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d22eb6266.json
8659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d27ab123.json
4348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
196b39897.json
11007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2267e1584.json
10345    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b446b436.json
10819    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7e23bfbf.json
9310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
536475bf3.json
3461    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d23a71937.json
13465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9868e4015.json
3968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12d48709c.json
1489    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b95d067a2.json
4260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39afc4a19.json
3072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c08403e9f.json
12660    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39816161d.json
10881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615df1d7d.json
14400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0415fa071.json
6849    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a009a2f0f.json
12236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d1fa8ddf.json
503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1c4a5d5.json
12714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57b1f782b.json
14768    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e6fa700b.json
5839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf5c8352d.json
9233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
640683dd9.json
7109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23829dc63.json
10897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
855de7c89.json
812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a578345c4.json

920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6824120c3.json
8783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4f69489c.json
10559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7754f4f3f.json
9522    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56f9dbc59.json
3895    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ad59da0e.json
2999    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d96987111.json
12093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3427692e.json
7422    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baf95d8dd.json
12004    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d87736bc.json
5100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b15f3794.json
9527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95af6f72b.json
4883    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40de6ecb5.json
13313    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f502df1a.json
807    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5d3858ae.json
13297    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13757a086.json
14878    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
056cc22d2.json
973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fc14401a.json
4946    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b4b4e40c.json
717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b102f525b.json
444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acd9e66f1.json
4524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40f9864d9.json
14210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e83794bd.json
7182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ce866a04.json
6344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ef23b94f.json
3424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1cd176b5.json
4069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c05ee4b2.json
8638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5f105607.json
2762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6f39e0e4.json
8141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d721ed589.json
1095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd70d885d.json
12396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41ce762ce.json
9358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
076a67405.json
13127    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9981290b2.json
8078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11f773e2f.json
11231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80b137b2a.json
5996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74f987b01.json
12816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae30afe08.json
13888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79a9a7b05.json
4554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0a4d02cc.json
13969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66038a4b3.json
14266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
351eefe3e.json
5419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cae5c7ef1.json
14447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf98480e0.json
4088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
246c3850a.json
10461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f21f48009.json
11194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a99a82e6d.json
11782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4733d5e7a.json
9085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b15c42d3.json
14135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f45bb293.json
11945    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07b9322e2.json
13521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff9a1fec.json
5519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed4604a70.json
13659    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26662f4f9.json
8770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
39e0f5513.json
5795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
295dac1ce.json
14002    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0b704c99.json
14928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a94fdf2d.json
5782    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aefff4a06.json
6991    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02f7300db.json
4673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eac15ca35.json
4874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83d94a6e6.json
5579    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c32eb7405.json
1943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea159d8da.json
47    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a84afa62b.json
1682    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
729f4d5fa.json
6890    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86f4297b4.json
12188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a762f7ab.json
12758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f33563b9.json
12724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
826c26e34.json
9529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d6b8efdc.json
4776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d5be4060.json
6565    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6438c6b3f.json
14642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
951f0f32a.json
9127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68a3c10cb.json
3854    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c9382d17.json
9500    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec5670386.json
12932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b872f1aa.json
8875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0124e47a.json
3287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
800a7c025.json
351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c63b71f0d.json
14648    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fab063ed4.json
3752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eee1e783.json
9357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8300e943e.json
13071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b90faeb5.json
13669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36f1dc3b9.json
2260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dca27ec4.json
2184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e375cb119.json
4556    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b4f32911.json
14446    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eda415d15.json
4195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
934546487.json
11053    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbefe3979.json
11373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fa341801.json
7167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c59cecac.json
259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bbcc7ea5.json
10341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cfba936a.json
9698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
782eb0d9d.json
595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b858c084.json
6110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c62324387.json
7020    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86afe98e6.json
437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d88f3ee34.json
5472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6acce195.json
1036    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60bc5ce92.json
13008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

55247ed35.json
10968    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ba9cb4a0.json
8048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72b996452.json
8732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a6dc2b1b.json
7538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7c661670.json
832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d21ed8b84.json
3799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20cb13be9.json
4100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e11e6cf89.json
5139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c95af948c.json
9720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db0b0bea6.json
4053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a430bd08.json
5932    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef70f3263.json
5304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2533f425e.json
3919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44a541574.json
11023    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24554cdc8.json
3322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b4e331cf.json
7576    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f29afd123.json
9348    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8368a0a44.json
12420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d1ff4264.json
5125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e5038eb5.json
11471    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fceca5de.json
564    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2485efd0a.json
12217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3b7112e2.json
2705    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb714a80a.json
9593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6138cd70d.json
4063    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33a8b9601.json
11315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afd3ded05.json
10211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f3e5cbd8.json
1006    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
505034c5a.json
9618    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c56432da8.json
8210    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72f6dbb1d.json
6679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5bf7aabd.json
14283    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fac67d06.json
13567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38506d4ea.json
2171    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c054c4ef.json
245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c64fbad.json
5525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73013560f.json
12599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1df182906.json
4335    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99ba6513a.json
5900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f574b0a.json
12868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa189a931.json
183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8d0907ae.json
65    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bf2506a5.json
4002    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a609b82b.json
14658    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6bf713e5d.json
9083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c007007f.json
1245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
868fb91f3.json
5182    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
873996ad0.json
2069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfd38a572.json
7049    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a8ac8bff.json
6475    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c110b9d2.json
4367    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18bc7bf4d.json
12077    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa2c37e6a.json
14147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1c03b3d0.json
7054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e77b5a78f.json
12513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bd394ec8.json
12208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfa2afea2.json
10589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92a173c59.json
6551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d75e5771.json
1870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c93e86f5d.json
4606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f6c8d13e.json
1976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46c5fd256.json
14183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e08b9ce5.json
1579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fff6f2f61.json
2567    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0dca551f0.json
2564    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
814430b64.json
9007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2aac285e.json
5394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec794cf89.json
14562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
239495f90.json
4795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
331a745e8.json
7866    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5f1f0a3.json
946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdc5ffaba.json
12911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75ca94b67.json
5285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b31d7b1e.json
12862    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ac437438.json
8070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c39c602a7.json
5885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15adc8d48.json
8841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a1e12a30.json
9707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a682b74e.json
4235    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4963e95ce.json
3587    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a4203544.json
3384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dd12152a.json
10308    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56c329fdf.json
12052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf1762a3a.json
11119    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a17d8cea.json
4751    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e399c659.json
8660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82c90e313.json
9364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37e2f042b.json
7438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba20d5a08.json
9599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
700a93465.json
566    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
574e7393b.json
11729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4348b169a.json
11888    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
839404d8c.json
7098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a6e8e4eb.json
10992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30ece8658.json
6331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9193e335e.json
1069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e736f4022.json
11108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4fb514b2.json
4416    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f98750599.json
576    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a7a6f554.json
4940    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28af3f2c9.json
8962    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c7949266.json
7249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b6f92bc2.json
11257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdf4d775f.json
4680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f796d3f9.json
1184    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee6e0abe4.json
3891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e44bb666d.json
11335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3e339d6f.json
8861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f680cd37a.json
1492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb4f09e0e.json
13849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5b782f4e.json
9138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b56fecb8.json
11961    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c36ffffdc.json
3217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c318c6ccf.json
13937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc5892ce1.json
7415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ada2f8b6.json
6192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e99c4a55d.json
1129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
453125325.json
12446    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d815333bb.json
5585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e388a963d.json
2195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01958f464.json
11762    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

710126170.json
11675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
026ebf139.json
335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8d014d03.json
11441    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d181cbafa.json
12099    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4060caeb1.json
368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0243911ea.json
3243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02f63f8ff.json
6425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fce6f8dff.json
7108    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dffd9f2ff.json
6788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d72dafbea.json
7681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a89fe4a5.json
6912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
081199ea2.json
7139    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be604ea67.json
3748    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c05a138b.json
11472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2136a3c04.json
14785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f49099d52.json
2208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab10e0e8c.json
12567    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d18218a56.json
12335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
628fd5227.json
14704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d6a996c1.json
1126    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9cfb355a.json
5008    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
966aaf6e2.json
6599    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
640e0b69b.json
7849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5767a3da.json
12753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95b24de4a.json
6161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24d1c128d.json
13853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b530d418.json
10124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5096467b6.json
5112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df2051351.json
6402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db4a0242a.json
3016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b5af7749.json
7155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5bc7aaa8.json
3466    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0d71d1af.json
12261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71390d670.json
8963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1368f0b22.json
11431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
305524cba.json
5794    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30eb0f9e6.json
8462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8cca430f.json
8456    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca39f5e93.json
1252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c0c76a42.json
10533    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a65d163b.json
14322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98aec0679.json
5955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0443d6f82.json
266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7942b62ef.json
4718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abf1716a9.json
13145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca121ab91.json
cd9c84ec2.json
7140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc2881a97.json
9561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cf06742b.json
12458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de34278bc.json
3452    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c1fd43ef.json
12964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0a4b28f6.json
12468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ebe2f16c.json
7171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e54866fe5.json
12011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43d31be6c.json
9164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f85ae1408.json
13079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bb802fa1.json
2657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca28c5e51.json
7859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb423070b.json
3696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fef340804.json
10083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f3eb3f8.json
8729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bbca459e.json
6171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3968a6b0.json
7930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cbc1fb81.json
7365    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0de6709ab.json
9183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69ae5dba1.json
8720    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
628a224b2.json
4920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d2394669.json
10311    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0940ecf2b.json
bb5917ca8.json
14347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7f98a1a1.json
8842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04d4ce3a4.json
13420    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8519aacb.json
7585    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10ba7efac.json
10892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a78b3e0b.json
3544    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a58fef87c.json
2332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1086c8df9.json
6373    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d08f7b70.json
9627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a3efc6c4.json
9156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bab19cc57.json
11247    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b7262ad7.json
3650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63ba3f4a7.json
4986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6ae0d580.json
1601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aac5500a.json
5939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b041aab9f.json
13176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a29c12bef.json
2324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c24516b64.json
2938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19af88854.json
12804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e68926f8d.json
3368    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c2a1ed3b.json
6187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69b2e9f3f.json
7232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
394217006.json
8815    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
706d1c836.json
12809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
919ebd16f.json
10582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8e0a06ca.json
3751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c5079e85.json
7437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25d4bd6e1.json
5533    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8685a0b1c.json
11268    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f02ef09d7.json
2870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
124f45c2b.json
783    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cfbd44df.json
6234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
594c46c16.json
5812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9725fc542.json
10073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9725bf4d2.json
808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b8fd895c.json
11932    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4f9be28d.json
4376    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58a7e1caf.json
9027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eab44dad9.json
13474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f891608d9.json
13384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67ab87b4a.json
2532    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5118055f4.json
6008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
965b31ba7.json
12680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
310b5199f.json
1949    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d13d93f69.json
272    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd0002db.json
2953    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5188ce75b.json
2789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5597af31b.json
10850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21206933c.json
14394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d01112d4a.json
13997    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d79d37b3.json
14363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd654a9e7.json
13790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6abcf6c.json
14285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b98610e10.json
13702    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb5162df6.json
12968    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac2f56dbf.json
14645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24abd7725.json
13873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b780980c1.json
13017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

8364bf2eb.json
9205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae64cc2e7.json
4212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aa3952c1.json
528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db10909d5.json
8145    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3b6b7d2e.json
14897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ea7c5d48.json
1408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36d7fc2c5.json
12855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d584d51b2.json
10674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8876247a.json
13768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3fc0b07a.json
4676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e2e48bb2.json
9648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d20353ed.json
6930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcba09ff1.json
161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a93c04347.json
5571    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c62c854f.json
5306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f663a91e8.json
11843    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ce065496.json
5083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d6d03de2.json
14148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b12f497f.json
6628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35d860fe5.json
3104    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9d49b198.json
9020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56ec0a2ef.json
10545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73d65de2d.json
10449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22d381889.json
12150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf74b13ab.json
955    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eba773cbe.json
7217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
802290aa5.json
11032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c547fc4f7.json
843    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
106e252d9.json
5433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18dab2783.json
5113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
120ae4dd3.json
7712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd9e9d9e2.json
397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5f9a9c4a.json
12900    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68eacf03e.json
7699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1d8d917c.json
1383    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10741c443.json
13598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a96856173.json
12670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4ab38d7.json
10641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a768123bd.json
6646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfbaff540.json
1284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
104d9b198.json
12706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6f77d754.json
14710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7b201da2.json
12265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab22c3350.json
2463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
664a120bf.json
6412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5ce44276.json
8628    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14c70761a.json
14548    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c458c51c0.json
1892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ca31b395.json
12221    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
514e33268.json
3520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e2cca514.json
14379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7959e3491.json
a2ec6f8a8.json
12869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b748dc1da.json
11043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff832cb7e.json
1173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc628c147.json
10864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78b07d4e0.json
415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7559336dc.json
9542    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b92f9684.json
10676    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7c7ede79.json
12437    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6eee0e191.json
11510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc2925be3.json
10093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21579dbcc.json
4477    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc3434ae1.json
8408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e27976e9.json
802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c69af3423.json
14202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14272c5c7.json
8430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc3053f45.json
4032    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df12e4d3b.json
2191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53ac79c6c.json
2013    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1f80f7d1.json
10894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54cccb3cb.json
11139    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4bcfbb1c.json
6409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb6c5726f.json
14816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72c626d6c.json
3400    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6219a1e79.json
6698    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d649e887.json
9864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29fd25bc8.json
10747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0e8d63df.json
2902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32acc8a7a.json
8125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1380b76cf.json
14586    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71a92867d.json
13733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a3380641.json
13242    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c7a874ee.json
8647    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
489dad256.json
4368    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30917edfa.json
3182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebf5e5e77.json
5172    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b2abe02.json
11379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
04e7d89c0.json
1037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bec6fb5cd.json
9641    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
829ea64cc.json
1834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e77f9e778.json
11087    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e989ad83f.json
7030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9e27a268.json
4535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
410707dda.json
7595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d867c4016.json
12405    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c3a05812.json
502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
380eaa884.json
3297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13469fc6a.json
7079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac8229264.json
8844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af75249aa.json
14869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3befd2af6.json
9141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
655bbbcc8.json
3383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
400e57095.json
1202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89f229ee8.json
6832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66f430d36.json
2101    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8d07c37b.json
706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b3ec0f96.json
552    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb2dc3fb7.json
10694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f4b91187.json
11629    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92fa4a896.json
10442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc5f63812.json
7715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf86cc5ea.json
13560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8705145ca.json
408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31ac53fd2.json
10930    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbd703fb6.json
8133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
859bcc995.json
619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a2ecd24c.json
8998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28d20bc71.json
1995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bac8c1a73.json
13901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e6b452b.json
2011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06ecc204f.json
840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a6dbcbbb.json
7096    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ef11ed6e.json

1715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b310f969f.json
14355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a03330405.json
3480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2808ff8.json
4911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2faee359e.json
6148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbf2d6b55.json
11583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
646fe5d09.json
9765    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23a5c1e87.json
9412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5c4ef4c0.json
6072    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e87214dd2.json
6448    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
162c1d98a.json
9890    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4aadf23c.json
4306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b3559bf2.json
8386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
842c9622d.json
9458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9a96204.json
493    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e49eebb3.json
4350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8c336257.json
2156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a30ec0916.json
11147    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffb3a78e1.json
6040    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ce37d745.json
12019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ecd54695.json
2162    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
619dcb4e6.json
9838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29af2b6ec.json
7848    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd5e5195.json
4886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
631fa08ed.json
1919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
380e603cd.json
12990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7727b4dae.json
4805    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0d50b9f1.json
13650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e3e41b78.json
627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef1c393e4.json
7569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8e376a50.json
10480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad8b0d9d1.json
2594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfdde77ff.json
3035    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57f2482cc.json
6720    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7caa6d216.json
14794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe1c36fb1.json
14098    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa2a3d9c7.json
7649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc0952bea.json
9942    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
350116b16.json
2193    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d8760efc.json
13346    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6464f2352.json
10723    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
640dbb3b6.json
9289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
167fafe7b.json
7995    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e88aaa263.json
11874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f07e7abf.json
2433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae886e80d.json
11459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3afe6f1fc.json
1352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d6350e54.json
3944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0a66003d.json
13084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18427ab22.json
14319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa68a3672.json
13814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d95a1a81.json
3653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ae292968.json
9305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73c4d95a2.json
11267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea9003f0f.json
8340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c66def50c.json
5880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ee752de1.json
2885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d2ebdff.json
14259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
552ac34a1.json
2253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d02feb234.json
14612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c36943627.json
1800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98437e7cd.json
6615    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07ae95ddc.json
5505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1de957113.json
8557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3dacde96.json
4361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c92b59557.json
9054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76d3ef2a4.json
14670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d676283f.json
12016    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dea6d23b.json
4154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e103f7612.json
1962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f81264ec6.json
12167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eb219818.json
14336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20bad295b.json
8426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7998c5869.json
11152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2c677e93.json
4247    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1ed265ef.json
3353    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26039ba4f.json
13558    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48ceb84a0.json
9167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b25c2d2d1.json
3392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e920f96d.json
7432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a080c1037.json
14760    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
204a3b926.json
976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
072ae6d9e.json
447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f77b4edf.json
9229    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
718a5d950.json
2106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9869aad59.json
4387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae03f99f2.json
230    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71c3f9254.json
721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a46794d88.json
3370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
194acc3f9.json
3117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc8459867.json
4171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1217eecab.json
12639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21a1b528f.json
5820    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
497ef36aa.json
4798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cae4a15b.json
10626    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f331aa22.json
3665    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f7beaf2.json
9b0744be7.json
5201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47fb86cbd.json
3703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0133b0214.json
13183    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb4e0ddb3.json
12582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da962d158.json
6718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
337405507.json
13753    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ff1a0cae.json
7099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7a37173d.json
13699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
044548f89.json
501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
749afb385.json
12836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d1640f3e.json
12321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7adb5f44c.json
3807    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0e24b0aa.json
11655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3e66cb5a.json
10105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de993d8ad.json
724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7344d7f5.json
2469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1635eac9a.json
10758    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
097dd9931.json
4602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4302e8f50.json
8739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4910ac042.json
9977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fab1170a2.json
10724    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0338fcdaf.json
4399    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2257ac60.json
2393    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edf0ff7e4.json
557    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb1f799df.json
3508    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76b818bdb.json
12238    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8421c66e6.json

10068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
267841852.json
9303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52ed9719f.json
5071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7268e9e21.json
9118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b91ac808b.json
11867    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a575d70f3.json
7996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81694b7db.json
2535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd8312dcc.json
8560    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06abc52ac.json
3701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3712c63fd.json
5838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8489f930c.json
4802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b00e4262e.json
7292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
865e968b4.json
703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a73b9eafd.json
3386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16ac32123.json
2810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
522b73db7.json
7795    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af7125abe.json
10506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15937e540.json
2137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21d8f0d2f.json
3441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5407c6e1a.json
8055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecc77653a.json
7341    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1818e562.json
3669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09d7272ad.json
14137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b66715e26.json
11364    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75b726ba0.json
10005    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c08a034c.json
3626    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
279895e23.json
9302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ff51137d.json
9369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87e1b0c16.json
0c4e78176.json
8468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3a52fbbe.json
4445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b6fe231b.json
5034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
672bc370b.json
5943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69a1bfaa9.json
5547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47aacf137.json
5804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a99dadaf.json
1571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b34e983.json
12551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3181e5424.json
62    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4106b7290.json
7978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afc933f32.json
12848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cea2544a7.json
14467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bce56e27b.json
5045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d2f6b042.json
11730    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9849173ee.json
8414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09e64ce2b.json
14082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e65ffa3c.json
3409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1258aaebb.json
13830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092b4242a.json
5908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6ec35f31.json
4291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff873a820.json
5564    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79abb5387.json
6543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24488c53a.json
5459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff5ea4f84.json
4892    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96353db69.json
12506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccd20906b.json
14727    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41ae99ff2.json
7180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b4003be8.json
13012    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53bcfd67d.json
809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65e601b18.json
13587    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bb0600a7.json
1099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7cfbc8e9.json
10186    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5146f799b.json
6058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9449dcc18.json
7741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e9946952.json
12956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5783d40a2.json
1973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b9a9eac7.json
13134    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79f8f767e.json
4992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fb2a918d.json
4595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
691a8b7ea.json
431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64904cb52.json
2967    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c594bfb0.json
6320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ac69be1.json
707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf1b733a7.json
14753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f735cd71.json
9d876d83a.json
6136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93b289505.json
13233    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2d7d59c9.json
13219    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7856db41.json
6124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5115cce8.json
4127    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3485ea1db.json
11669    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74088eee1.json
1203    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67db5accd.json
9974    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90055a5f2.json
7782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7bb75711.json
10268    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
928fba0c4.json
3939    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0a7a4dfb.json
7613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb2a61d2b.json
11641    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a18843d35.json
7352    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
487416da5.json
9785    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ceee65059.json
12929    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3b89c2e8.json
12121    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c5a912a5.json
14349    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74f16e441.json
12125    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f9697729.json
7279    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efddad023.json
8726    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6610ebd3.json
4643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d5e4949a.json
3809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c38d0b5ea.json
11778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
322b32801.json
4852    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa3df8921.json
10012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df70eb456.json
8285    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af8cd40e0.json
14687    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf3bce1cc.json
13799    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f4a72311.json
14554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a0cfdd56.json
12525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30dd541af.json
1001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c680abbe.json
2537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a828ec3e.json
3407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
636d6a0d9.json
7968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
250f59089.json
3646    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7993d67e3.json
11791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15e5b0e7d.json
6323    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75758ad3f.json
3689    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ace3a3299.json
12143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3db150833.json
510    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccf8c71f6.json
9778    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d67c5c6cf.json
1719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd6528981.json
3189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7fd7a703.json
1818    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a783228c.json
13370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60923a60d.json
14330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df1d3b1ec.json
11521    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bf71f7b1.json
7600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66f6cd1cb.json
1396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca4a8f0c2.json
14850    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a17130c3.json
11948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b11611ff.json
4161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f57a5c0ea.json
1924    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
964b2fec4.json
10417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b744f152f.json
640    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43b5d3f4d.json
12310    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6469bb262.json
8510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86dec16a3.json
8393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7023f6b45.json
4135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f3c2e36.json
6086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffd2e82a9.json
7431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
553d1ee3b.json
14100    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81670cf7e.json
11056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f08275fdc.json
3095    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c9696bc5.json
4248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faf4fd269.json
4493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bfb759ce.json
5881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48f2b0d54.json
14419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cd55a3dc.json
6021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69f8a53c8.json
2925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5124cdcc.json
4775    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615af86e9.json
1413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a7bcfea4.json
1716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c4c55b39.json
9052    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0277b9d3.json
7260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
955e7c5cf.json
6839    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4afff6dd.json
4288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23a1e62d8.json
14011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c9e913d7.json
6348    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92d830572.json
9520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c89e09ae.json
1261    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35a135b13.json
4147    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a5091ca2.json
7642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fe9ef7ce.json
8803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08710204e.json
12112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7c487e58.json
3052    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec0fd1a7e.json
10798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c31c7db9.json
3990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9e86cf3c.json
7697    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c662b7876.json
6376    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be7fbd988.json
7490    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5902c3051.json
1830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
630e96c9d.json
4521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbd6b3064.json
14033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f64813f9e.json
11391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec13e5f25.json
2437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d565f7c6f.json
9692    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbabe4e51.json
3435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c67c5f4c.json
2104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98231df17.json
12206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17ef602ce.json
2166    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
096c37d99.json
11130    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a7a99c23.json
7519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e317b2a73.json
285    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df8ad80b3.json
1089    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6189ea84.json
14212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7f781c99.json
12340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e7d08fa6.json
7018    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd9ee4a38.json
5096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f27a94272.json
9276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8be7f8b0.json
4756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c3f23fce.json
4298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
448659511.json
7844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a963a6979.json
11341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb5ecf136.json
12330    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1712ba40e.json
9959    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
795a443ea.json
11378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c1c16ac86.json
10755    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc5e81c00.json
969    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9568ee6f.json
2455    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c54ab239f.json
10468    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f9379256.json
5250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a56bb056.json
6895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad2423b1f.json
5863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29f5cedc0.json
10237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba13c272f.json
14764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a0862717.json
5964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
055825f1c.json
11057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d54759a77.json
10017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c6fdbcb4.json
9605    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05486faf5.json
4126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fc52b599.json
14231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14f9ffbbc.json
6382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef8ddd70b.json
5120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3408d846.json
11873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4463622c8.json
1205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84efe95e8.json
10152    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51cdc726a.json
11131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
195c119c9.json
2883    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b501efb71.json
13654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fac4ca24b.json
7750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
321d04634.json
8111    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81ea0e01a.json
8790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
087fbda7e.json
8224    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b515d697.json
2220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9c5b665b.json
9696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18ee92cdf.json
2771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aaa67ff2.json
6474    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed6812520.json
6897    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ade6b8efc.json
6111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd7732e86.json
9630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bb136045.json
14264    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98128b920.json
13621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1a67cee6.json
1613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bd2d5882.json
1084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18556365a.json
9533    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
915f0b42a.json
3275    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
703f38466.json
483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bf6cdab0.json
6949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5f80598c.json
2871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c76384236.json
2493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
512bf1e8a.json
6929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
059cfed40.json
9751    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddbb99929.json
10525    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc76d9fa5.json
6335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e89b91d44.json
6489    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc2fdee71.json
5220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd3cd5fcc.json
14547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0532bf9d3.json
2978    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0f3c756a.json
13628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfebb0955.json
6019    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5417ca8e6.json
9598    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7adb2ab9b.json
8192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5b1713d3.json
3377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8534310cc.json
2399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebabceece.json
8453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e27ac6865.json
3374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ef276c3b.json
7694    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a5ec1a49.json
1984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d18cc71d.json
6748    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c44a94d4b.json
1945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7c004380.json
4050    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e410583.json
13032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08d17d82a.json
6223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0be585cb.json
9467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35149528a.json
14904    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a4b42306.json
11652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f38727a35.json
5485    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18c7d13d3.json
6407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4446dca3.json
10304    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d0551d53.json
13085    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ed14130d.json
11964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ead9fb6b7.json
6927    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
484346fbc.json
8859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b8ab594e.json
11390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1de8d0099.json
5931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2b16f8ae.json
8137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
366a4544f.json
6561    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f85c03bb.json
10134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a84451ae.json
5601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f016dcab.json
14896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8111713a2.json
13871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85e72abd0.json
5065    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7a19c5ac.json
3088    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
733b7cb27.json
11725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea062393d.json
4309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5b2c6fc0.json
8528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fe96f804.json
9395    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
861c903b6.json
4900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9099eb9ee.json
11329    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac7609b80.json
10407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada57411b.json
3138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98caf2809.json
2091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e9a13862.json
2581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b5c446cc.json
13653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bc0357ce.json
5756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6094997dd.json
12756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
529025eb8.json
922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9a1cf69.json

4447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbfaa79cb.json
14358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50d766c25.json
2970    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bdc7be69.json
7161    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e07812482.json
405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3dbf1e95.json
8089    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd7bea671.json
180    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
988308307.json
6291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88b992d13.json
8068    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
145883970.json
296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8509ad722.json
13856    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5df34957.json
4157    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
403aa5c4b.json
2429    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d70f6a57.json
12431    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff3127ad.json
13570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20bf4bf39.json
6205    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43c623f94.json
9193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6be0a8fcd.json
1024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
603fa62e1.json
14037    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f056ab9fc.json
4719    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e1a2937a.json
11631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
175af62c1.json
8768    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b113401e2.json
7975    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae5059b40.json
3366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40501d365.json
8113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fd9076d7.json
9086    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
067f49481.json
5513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64f5e2165.json
14677    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68b8dab3b.json
13208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ea44a5b0.json
6284    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3e488484.json
5234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c6a5b5ac.json
5237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7199d2d4c.json
6642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db9ff390f.json
10544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47caf7ad1.json
12912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e74dfc90.json
4492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db61b1f31.json
12140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65c1d2996.json
13572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c49629a90.json
1372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94610095f.json
5317    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e995f65fc.json
3112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aac9127c5.json
3091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e61a7b46.json
9941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6e52b75b.json
10908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5595a935.json
424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35b728d0d.json
8975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aac1167f3.json
1911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aebf47483.json
8834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ae269152.json
5971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f222f11f.json
2024    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
721017d68.json
1310    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efb36dced.json
8700    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de7114b0e.json
6449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67efce2e0.json
267    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a124a31ee.json
1926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97094f7ec.json
10319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b56e6500a.json
6751    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
850b0f686.json
13780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7976886b.json
11336    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01b8e6c14.json
13298    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f53b95c90.json
5988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a144cca8c.json
12412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a0180eb9.json
1862    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f04b1556.json
1340    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d73e917de.json
12106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6b97e7ca.json
3110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
508f87cfc.json
3668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
769ad37c5.json
13508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b16fae336.json
3839    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f83695eb0.json
3375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32141c266.json
5868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68046ca33.json
4845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fcc3cefe.json
14685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
467faacc0.json
14170    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f84b22dae.json
5523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d51b2e785.json
8157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8f2a5210.json
8216    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c48b210e.json
12272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cde10c57e.json
4181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff0d8c7b.json
13722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5909a21cc.json
14836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58fe1756c.json
715    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc7706b56.json
14628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1965d2288.json
4390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00f997463.json
10090    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59e7b5f52.json
10298    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5152dbfe1.json
6032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aa39ed52.json
10520    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f2573b47.json
5154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7be93837.json
1968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd2451ab4.json
2410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61fa95b3b.json
4065    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddb881657.json
6451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2876d101.json
10034    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fd545213.json
9318    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb860243c.json
12612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90ce48a71.json
4916    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f4fb6f7e.json
943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abd366564.json
11443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c05a9c0c8.json
1549    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f158bcd9e.json
11570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cadcd5ad8.json
11438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8af1e7a3.json
14430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88487194e.json
12260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9468e2ed1.json
14030    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7f1bb8d32.json
12606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

881a77dfb.json
13735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85594fcaf.json
6564    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff127e4d3.json
13276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09acd6b31.json
594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23baf0395.json
5791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e7b512bb.json
3030    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33cabff1a.json
9613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a7885841.json
9685    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63d254530.json
4328    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f04c098ed.json
7577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcfae453e.json
5438    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6326958d4.json
2863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93692767b.json
7605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8910ea0f4.json
3688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4dc1e8fe.json
9462    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
54bbc1b84.json
3526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6575f08d.json
4840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdb71d0c8.json
13259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caa616482.json
8583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29edf6e20.json
7608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24be8e826.json
7676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4809e7d1.json
6858    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ece99daf7.json
11662    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a970b89c7.json
4321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17a5487d2.json
2423    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8afcd7b7e.json
8401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5962cfdd9.json
12436    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4999bce7.json
14852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ae2246a7.json
7922    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b0896bbe.json
8438    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27a8bdbf8.json
1386    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5f1eb8b6.json
5223    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f77a6e11c.json
8028    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3750cec1.json
11978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36731724b.json
13382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7316c548e.json
13647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ce86e3a2.json
8509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65051faf7.json
4085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fbb112b7e.json
167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21e4ca7d1.json
4267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43cf0f713.json
1931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce0294cec.json
5779    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f467ba22.json
11403    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f07e2b51.json
11302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55f34f8f5.json
820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de591574b.json
10466    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebc749f21.json
3388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f93ea9f9f.json
3837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11948e0ef.json
3033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28f9f4ec4.json
4738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d9197e7e.json
2797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73f5dad5b.json
2750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d41649df9.json
6272    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d243fce57.json
4110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bed675184.json
14789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b61f8d97.json
9547    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f2623cb9.json
1568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f22842c0.json
14043    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99a0196aa.json
13998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c879064dc.json
d26ebd584.json
8e1111452.json
3964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f3d368d3.json
9106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3eaae43f3.json
12020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
113204c87.json
7403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f2faf77.json
13262    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d07d9ab13.json
1799    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e47644c8.json
11875    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ba7b7b9c.json
8558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2558c319.json
539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3995ad50.json
5048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5475edf9.json
12089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7067c4dc.json
5592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09898b12e.json
3069    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fe8ef73d.json
51    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75bfbc825.json
14931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e96c2483c.json
6931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42a28c241.json
12433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
694caa813.json
690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55c563104.json
10537    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d725d001.json
12493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1936c68a5.json
8043    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d8b93dd1.json
7366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef86c51b2.json
1872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80e8288c9.json
3022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
488c8d0aa.json
9854    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c15c93964.json
7236    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21b933087.json
5749    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e12f4152.json
12074    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d605cb217.json
6365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6deb30e1.json
9602    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
460ac160c.json
2021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1f16a59a.json
11064    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae3ff3cbc.json
11464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c580ca06.json
987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9868c3935.json
10240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50682d0f1.json
11172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a85630773.json
3894    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af005c575.json
7701    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
64b1db30c.json
12967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb0dddcf2.json
4505    1
Name: Type, dtype: int64

<class 'pandas.core.series.Series'>
db745332f.json
10459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fd0bd843.json
10418    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84c1afe03.json
4513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c42e5a129.json
3632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4b90955c.json
10721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e88f72461.json
11156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e140177f.json
3868    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4ef3ff97.json
12976    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a972fe14a.json
7071    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
784ec5ba3.json
10948    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bcc3be83.json
4275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b82af067.json
6185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05f99fc56.json
136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c49480455.json
13491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3feae3fb7.json
4973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3330252db.json
11587    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63a542d16.json
6605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6236b3b8.json
2441    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fae628c13.json
8669    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ff169a48.json
12919    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2dfaf69b5.json
5726    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a37c82165.json
11721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58d54417f.json
10313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca9841ab1.json
3645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bec2fe7ad.json
14792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35f9818a7.json
996    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a92b06d0f.json
964    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f892c5908.json
4853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25560b530.json
679    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9feaab54.json
5855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55fcdea2f.json
123    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a633ab6c.json
12250    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
271bb0de8.json
3093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d14d62508.json
79a352e54.json
9732    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07218c870.json
5766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48dd9f35f.json
12645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bca8b44ae.json
1846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b22d0224.json
9770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba311fc1a.json
366    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff10041de.json
1259    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ac089108.json
6163    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a34cf041b.json
4480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
267f0065c.json
12870    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca3dbbaa3.json
3763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6984c8d7e.json
1237    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4060a70e.json
9316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3e70d2b0.json
2473    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45457bdc.json
8385    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
791560e54.json
9408    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71d3ecea7.json
14941    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff706f8cc.json
7adc5209e.json
326    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a90da3a12.json
8657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
902114441.json
2344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9e9c9efe.json
10580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c50a42095.json
7555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
429017e9a.json
9799    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efe569ca6.json
4460    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ad691ca4.json
12915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4745e5286.json
2378    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c1890dc7.json
12046    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25b827551.json
2816    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e0bf99ea2.json
11936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
401553149.json
13006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ff246254.json
8902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a34d34ab.json
5465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee2c40165.json
14688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
095314294.json
9957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9999c355f.json
8396    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e496f46.json
11413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c33c82dd5.json
4523    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
643eab5c6.json
5684    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
debf8e7e9.json
7068    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd763ab11.json
14158    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94bcf0199.json
589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5328a3ad8.json
4409    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c75b9082.json
352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e935b385.json
14428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
534fff3cf.json
7440    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b3332622.json
7264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b56301b6.json
2435    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adfa73768.json
11103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d508e63a.json
13756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a19eea86b.json
7800    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
805dcae38.json
2491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2eb4fa594.json
6786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5163abb6e.json
5325    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fb186834.json
10743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d8f22942.json
5789    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d380185bc.json
3667    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78a8e1b01.json
1918    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac3a5c473.json
5193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bbf00182.json
2136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e678bcc42.json
14558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
823d5bd7e.json
11142    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fc6599fc.json
9353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f1e6e8ed.json
10590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ad1d75b2.json
4055    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9609a0b86.json
53    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d54e67c.json
3211    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d663ffeb.json
10536    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e74e45c.json
3219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa5957d1c.json
3559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
126cfd595.json
10144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7feb1774c.json
4300    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cdf69df6.json
7414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1653516e.json
12601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecd574ddb.json
11161    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3dd7e6a7.json
12748    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
17d9c9586.json
9563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6989638e.json
7185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
577c72b39.json
5061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a40a8c0ce.json
11089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab599a6ac.json
381    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5346481de.json
11290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d870d5767.json
9691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f194db92.json
5738    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8d96cdd0.json
14681    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a9efa973.json
6442    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad937498b.json
12357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9223ca4fa.json
6922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53bb1d133.json
7897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a447e958.json
7709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32f29129c.json
5060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ada6358f5.json
13689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb9a64e6f.json
6250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2be70a4c.json
898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8f9d07f2.json
13172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48333a921.json
1590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7da5a824.json
10065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c17b66965.json
13029    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88819fc55.json
3240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63b5f502a.json
6647    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6caab3194.json
14473    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cb849b69.json
1814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a546bfb7.json
9902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
286afff7c.json
12943    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7d2f8186.json
13035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6d7271e8.json
7710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f972a14d5.json
7222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59e6d1d66.json
5508    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
245bd5ca0.json
6939    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfe7a59b4.json
4177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46687a6d1.json
13209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51c04983b.json
7230    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
618430208.json
12945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4460cb03.json
10789    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e9358756.json
8261    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03c1e47b4.json
11137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90983a905.json
10883    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c34b20922.json
14634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bf7bccc9.json
13140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6725c11b.json
6211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
603892936.json
6609    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69c8c9463.json
1116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cfbb4616.json
4512    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5b5eccb6.json
572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22cf2902d.json
12981    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69c1801cb.json
11574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a030d758.json
10219    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
787a8c11d.json
11041    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdf4a9ed9.json
6154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4e56218b.json
11274    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
374b76068.json
4551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6d378000.json
10338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d20ea312e.json
2931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d147c39fb.json
11831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6db8c5110.json
6536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e801cb768.json
3851    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff8e7c016.json
11432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1816081f.json
2090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b0238af8.json
10579    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36d764abf.json
9079    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d8bc908b.json
12827    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6914ade58.json
9092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b6629627.json
11157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
559e15485.json
3617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1307cb03.json
13195    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9786bb3f7.json
8355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97f0e7ec2.json
3414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6a84a290.json
14318    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c803d826.json
7037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5474cd2c2.json
4118    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9296c9064.json
3226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60f317698.json
1506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc9168a46.json
10516    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c2f127c7.json
6045    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6b7b63de.json
10413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8685546cb.json
12944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
372f9cf86.json
2737    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e16882f44.json
7552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb939ea9e.json
1731    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6ad159f1.json
5867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac52ba660.json
2717    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d87fbd92.json
13380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8009b7ac8.json
5088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a8746c09.json
13431    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deb7136ba.json
3892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
902a255d2.json
9390    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3304185a1.json
677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14bbc5876.json
11322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
482d05dc8.json
13660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
684567fc4.json
13840    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49bb70e36.json
100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b88fdc7ba.json
9488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e9a53eb0.json
11383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec0ef9572.json
6236    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0a1f2b90.json
9967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09bc86c05.json
14872    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f5f178e6.json
982    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1de2c7e27.json
9046    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b38b60d2.json
1932    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c6a4b965.json
5168    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4fb9949b.json
10467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5afe2ebbc.json
824    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5de1d0c34.json
5854    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38063ee14.json
3393    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
881580d4b.json
7391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a2b50582.json
2099    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
775da0afe.json
4905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74b9e9fc0.json
12963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c82b8b2c4.json
10392    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c46efe8f.json
12903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7999c9bf.json
4414    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b76a6d7fa.json
13713    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd8817ccb.json
892    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6a16ab86.json
7653    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdd2cac09.json
11569    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
814740bc3.json
10340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be1ab222c.json
8187    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d6f10684.json
13459    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b2b69d20.json
5191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e38f07d89.json
12622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f36876126.json
7178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01919fe72.json
14754    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
421ea515e.json
14679    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
deda21b9a.json

1598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af76ac5bf.json
5395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67e41958c.json
6538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7448f3165.json
1903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed74a9822.json
6607    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ee7776db.json
10852    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e3680561.json
2372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68cdd6d6b.json
504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddb95945a.json
12445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2514503e7.json
5783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50b022696.json
5409    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8377bfe97.json
5967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e4e77074.json
1857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e54f4e06.json
7634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
216550479.json
13554    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50af1151a.json
11178    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a98163c8.json
5546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59d95faef.json
2030    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe5dc391c.json
2089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91e663cd2.json
12499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37a11cc19.json
3560    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24e2a6ff5.json
13098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c54b26d73.json
1397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d373c973.json
6334    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
201ea7802.json
11220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f17d4ab32.json
559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91b088719.json
10837    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c30f7cde0.json
2937    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba512b8f.json
13051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
926c92b39.json
29ffe21fe.json
14847    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
938bcb826.json
6814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4133efff0.json
8196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b03c494a.json
9292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a3113fdd.json
14546    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81eb7857d.json
3119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3c79cf76.json
2702    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c61f6507e.json
120    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f6fe20fc.json
7458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f86c83084.json
13504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ac0ddea0.json
12187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4236c9245.json
8518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d47275d4.json
3415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96e1f20e7.json
1226    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d635d0b4.json
7513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2de2cbdcf.json
6909    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75d255222.json
5190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44da8c2a0.json
10708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c234e165f.json
7248    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6d60a265.json
12591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e01e4a748.json
4204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7142b615.json
9681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faec94482.json
8428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf51903db.json
1450    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d767b639.json
13898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b88f141d5.json
2176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b869dec56.json
8540    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1ceeda99.json
14437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b08020b7.json
4044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6de9b701.json
11646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57cd5663c.json
8073    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
818d4a56e.json
5917    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4427541c0.json
9441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
72418da1c.json
10301    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c36860383.json
10361    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddd926335.json
3935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad5250ecf.json
9122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70b7cb06d.json
3108    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
506bacb46.json
13138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7f7e01c6.json
8775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c135e081f.json
1977    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a91262f6.json
4810    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c39e5de99.json
3343    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b8c51377.json
3899    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0133d72c.json
5776    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6dc2f0739.json
2621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ea111bbe.json
7355    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
138c79a01.json
8190    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b2b9935.json
10192    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e12797ab1.json
6477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d6298b6e.json
4612    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
959064f3c.json
14451    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c737c30d7.json
173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31b7a54b6.json
13220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fc17b073.json
12389    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e69df38b4.json
7339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24fee0cc4.json
13289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d09752d1d.json
1270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea7fc7f4f.json
8215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
506fa1d6e.json
13212    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3163e9acf.json
14953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10bbe5ea4.json
10910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6348b55cb.json
1341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4ebfdf22.json
6098    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
392d3346e.json
124    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01ba4e94d.json
956    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d7eff0cc.json
4371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b26374255.json
14278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9922b4f91.json
3634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d0f8ad16.json
9826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146f076cf.json
13173    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0ac9ee6f.json
10653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b5df2f3d.json
10448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc5dade47.json
5598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d55a0cb3.json
4879    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63647ce22.json
11437    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d1c281f9.json
3503    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea303d329.json
1401    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

45d12329c.json
8370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e458086.json
1215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53923463d.json
3998    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8aeff9ad9.json
3581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4887999cc.json
2897    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2401dd6df.json
9886    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31912a7d7.json
9132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28a0ae4fe.json
8138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
215903d75.json
6682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c467f8702.json
10804    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc1c9f8d5.json
445    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ef928aa7.json
8836    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29b04f54d.json
11519    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02a084920.json
6973    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
379d5e10d.json
10133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2f39a17e.json
2968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1a9e48a6.json
9801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
967fa3210.json
11074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f043910a.json
13594    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2127c6e1f.json
3439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f0cb510a.json
128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e67f4856d.json
12518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96ad633d6.json
3798    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f6003c18b.json
14344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28c4588e5.json
12440    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13c4c2d4c.json
1555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d777bbcd.json
1217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7d44898b.json
7221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb00c8969.json
6986    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf8e988f5.json
6759    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83166fea8.json
8302    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9358ef6d7.json
9099    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f2c63312.json
1288    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee0eff05e.json
6769    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e6223402.json
10041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f4f97c61.json
8290    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
310f053bd.json
9321    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e59c8fc76.json
3901    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aa40019a.json
6531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7de7e8fd.json
11668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc9036716.json
12320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6570928.json
c011bc363.json
4224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eca179f5f.json
65b70bad8.json
9706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
100aed9a3.json
7675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2dc697f6.json
247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4374d6f52.json
14494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e32c29f03.json
10822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92f84c5b7.json
2513    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
307b61689.json
7342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f348564a5.json
8714    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcaae830b.json
14531    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c008b0b7.json
12996    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb1286b1c.json
10405    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8dd18a5a.json
1563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f58424835.json
14559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
675bb16b8.json
7277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e165fb1c.json
1403    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef0822572.json
8708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d5f190cf.json
d79342c8d.json
2309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2105b697d.json
14615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2aac3e0ac.json
11151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0acd95320.json
2993    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a88c7fa4.json
6932    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8da358d1.json
1833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a0e8c15b.json
5290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11aa441fe.json
3920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
163adc370.json
4665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95e9ad1b2.json
6088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a62c06932.json
6524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57bf84005.json
8027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
638447198.json
7829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2340f8360.json
2479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da7fe1120.json
12312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd485150e.json
442822be3.json
4877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c107ce2b.json
14093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f13821512.json
2994    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
382dd71c1.json
6831    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23c8c5957.json
13793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d172f3eb.json
8484    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
077001793.json
1363    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
616e51d8c.json
12667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf2e67122.json
11650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a427984f4.json
1812    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
feff505f1.json
7378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35ce89b5c.json
13031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0baab7556.json
767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b49c33f08.json
9552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4aa9a342e.json
4213    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4d341b10.json
3216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b3e95995.json
10757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41c09806e.json
6821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69975d223.json
11717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ee33e45d.json
7988    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c31714ab2.json
6984    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2d464e39.json
14706    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f0468771.json
11869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
687c0c2cd.json
7480    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c73c8b6d1.json
3786    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b31d0dd8d.json
12820    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c04edd3c.json
12718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fce53107.json
7207    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

eac772633.json
9015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
728a08a8b.json
4403    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
532cac389.json
2041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
672e9e752.json
7763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7395e5c70.json
8999    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f05838eb7.json
7159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dc007dfa.json
6797    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c399cb06.json
8852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb9b9400e.json
6168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d304409b.json
6995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af8fdab18.json
14857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a8fc6614.json
14492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
534104c8e.json
4684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d03d5988.json
6393    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8580c770.json
9650    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e21ad5a7.json
8705    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3152276a.json
9971    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
401fcc4c5.json
11554    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
440ab06be.json
13179    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e303359a7.json
13178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87fa5c42b.json
8956    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85094deda.json
1320    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e8d0eedf7.json
14776    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44a0bfde6.json
6369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5fc91ab6b.json
5623    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ced5d057.json
7920    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d56553e2d.json
5370    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
695925a2a.json
2998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ebe13a93.json
4931    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cb6dfa5b.json
13310    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ab0ddda3.json
9073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad6cfec5c.json
5315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaca75307.json
12395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
611970ebc.json
1332    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9d621157.json
14411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e876d171.json
7369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
624fadbd4.json
5876    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e736f310.json
12502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b2a0338e.json
10151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e3640544.json
39    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a3c86cde.json
12025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4e0d125b.json
1447    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b46246db.json
13200    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9488e6011.json
13906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d0367e19.json
8972    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01e93552a.json
10517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79b3d41e2.json
6241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f734b97c.json
981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c52908c2d.json
8269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1093437e.json
13949    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f70f8112.json
14930    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
799cbc9e1.json
4597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b8229f52.json
5633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad90d4962.json
1368    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5ebfd099.json
11410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55b797c90.json
2945    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e79f310db.json
857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5c0db93a.json
13821    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e28a90f6.json
6601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
760d9a4f3.json
6153    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57aa560b5.json
7752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4cfd0fac0.json
6706    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d6f14681.json
11254    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c631dbf7.json
7946    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9586639e9.json
6855    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da5d1c5ba.json
10360    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
60875e5f0.json
8922    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93849e2b5.json
565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7020fa9a.json
252    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ac37cc7d.json
5709    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88666f74e.json
2138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
487f74408.json
11421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
063d8c58b.json
3780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d8a35224.json
10668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19904f24d.json
2366    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e282d2bdf.json
10740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98c08df17.json
14845    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3580fea4.json
4888    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1962ab4f.json
4771    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09b3b9dfd.json
3953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
451d17b57.json
12362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
030f32f08.json
4398    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1274381b.json
13792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f376f922e.json
1562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e3d235d8.json
13117    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4082acebb.json
5650    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aee44eb09.json
6445    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3170958f.json
e6dc7116d.json
12573    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c4b2e0c0.json
8639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adfd0f0bc.json
14624    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e1ba1796.json
12514    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6bc32c73.json
4410    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
799c6852c.json
6593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd6c93d05.json
885    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c66641a1.json
582    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aabd8c0d6.json
13524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4db543276.json
12813    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
883e7d058.json
4704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
624b5493f.json
7258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f8a564a2.json
2722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e26548e11.json
13715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76358e754.json
1088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4413f9855.json
3635    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0cc3078c.json
11990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

582c02d86.json
4340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ff9b83f0.json
4944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15f00daac.json
6845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ebb0dd45.json
5518    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15a828f9d.json
7654    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75bc667ae.json
9908    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83d36f269.json
2817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ffb40e20.json
624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18f45d2ad.json
1796    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94a4357dd.json
2243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
492f70d19.json
2415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bcc7910d.json
5860    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6aee1d8da.json
4559    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cb067b2f.json
7647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
447be811f.json
11260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dabcf0e55.json
14902    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0722660e0.json
13593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f72ec09ba.json
11435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f88144b9f.json
4263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ab904da2.json
12926    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58ef3eec9.json
1881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99be827e6.json
5660    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
543130f60.json
32    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
237343008.json
8038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
228117dca.json
7133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb9cffdff.json
705    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca0bf0760.json
13842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab35738e4.json
13228    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c76e6356.json
5728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7c4936a9.json
14893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f995bc16c.json
8209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7374edef0.json
8506    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa5f5ccf9.json
3593    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
881aefbb9.json
10143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce3a876b1.json
9814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6c6adc4a.json
12982    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ee223a17.json
41    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
109823680.json
6838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b1b9876d.json
13385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ba7056bb.json
3234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e750bb89.json
3946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7c607873.json
13132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
645914c88.json
9670    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41612698d.json
3912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8573077f3.json
7928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f68fcd05.json
11351    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75a4a14ac.json
463    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
343c1f526.json
8754    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44c2e1fd1.json
2841    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
867057e77.json
13091    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7b84bc3b.json
12563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ea3739e8.json
5583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
448770499.json
2643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f71d5c047.json
7842    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9f0a5dfb.json
3545    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f346ac72.json
577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
093a35049.json
1104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e52438a0.json
7153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6df350974.json
205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb307c1f0.json
6971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f506d3fd2.json
11714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
add3c45c6.json
9512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ff766a26.json
8864    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6df796ba.json
14073    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
409d5bc3d.json
9600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb6c579d5.json
7083    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93ea39e5f.json
13456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14c6c68e2.json
1247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1557f91e8.json
8158    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8779a4a1.json
1533    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7c6fc160.json
5700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
694653d6a.json
10234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7575371db.json
2695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a5e70892.json
8107    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1067bd14b.json
10352    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
745fd19b8.json
4590    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e5aa922d9.json
11295    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c78cc1272.json
4434    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d433a5827.json
7918    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b3763054.json
8256    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4c9eaede.json
947    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
591909a93.json
13440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d33f713d0.json
4675    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f39938992.json
13539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b1a68a60.json
8251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0eaa0e3c6.json
11657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e53cf2373.json
877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d20ba693.json
3498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fad4fb461.json
4176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6460390c0.json
14188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c36b62a9.json
743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aef6836e4.json
13215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c82f54ef6.json
14258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bad338993.json
6243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
487abc5e1.json
580    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77f9b1470.json
2725    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d784a800.json
12282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eee0b299c.json
7126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca92437c1.json
11814    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d86e9d9d.json
1628    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aac68c707.json
2517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38abad64b.json
12716    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24d9b76ae.json
647    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f024e91b9.json
1412    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40b31be60.json
6193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab293b191.json
5837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c91ae76a.json
1811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee9c2fd46.json
10531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c40fd781.json
14386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3664119b9.json
13410    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
668177e57.json
8794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7e1904f4.json
260    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0401d349.json
14834    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4d6997e3.json
271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5d9feff2e.json
14057    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ce183889.json
58    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c28dc555.json
2206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
103dd7bb1.json
2952    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8398c83ec.json
13332    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddb8bed60.json
12624    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0ab24656.json
14365    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8bc5380ca.json
9275    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d238a62.json
8740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ee6dae8d.json
14152    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e8101664.json
7058    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ddad75c0.json
10062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37ed9080d.json
1722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4fafe948.json
4148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

bf5c5cded.json
2077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
869c8208d.json
5852    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5c803412.json
12075    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebef2903c.json
11387    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02cf14499.json
10933    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4a2fd15a.json
7291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5110ff5f5.json
10039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8eed143b.json
13467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3060de782.json
3132    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
992170cac.json
8630    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d765ae877.json
57    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
249b350de.json
6532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfa67dca2.json
3598    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4ba15dbc.json
6150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1e2ecc3e.json
8024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eaf87e39e.json
13097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45408f88d.json
7652    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e0be9e49.json
2555    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abd80f666.json
14859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8100c2485.json
6015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13264f4f4.json
8397    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2161e0a2.json
3840    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c62de8a15.json
3000    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
724736153.json
2620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd4c95d9.json
5500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8c6c546e.json
6568    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cbe33a44.json
11015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dfee20c2.json
9891    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
483f1aae8.json
1985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b551658f4.json
1478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
121abd2ba.json
13155    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6593fb48.json
2238    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48615e613.json
12023    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1d86e6ea.json
14110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b756bfae3.json
5336    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa686c375.json
10061    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3a6f353d.json
14915    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18a87116d.json
5483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36010cec4.json
81d6d070c.json
9198    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48b418070.json
143    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3521fe7b3.json
10006    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2625dcb50.json
8853    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61338b2e9.json
9798    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e7db4c54.json
6383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
03f0fc32f.json
14675    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f26e3e182.json
3420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87b715441.json
14536    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4450385b4.json
4012    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc8caa6d2.json
10917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
325d0e364.json
14718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ec9e919.json
14077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e9e903c6.json
10195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff7d25ffb.json
2172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5bbf322d.json
3716    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1e7ada2f7.json
5968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c332aaf.json
8332    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0459c7bb7.json
11584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fd755cc6.json
3247    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
102ed9019.json
12394    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f10d4a75.json
12092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1db8335c.json
14442    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c0450f2f.json
2756    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc09a719b.json
8306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45d384cb1.json
11255    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81fddeac7.json
12674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f9a836f8.json
10276    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
59047a5a1.json
1965    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e3e99760.json
8400    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63e2cb92e.json
9217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efbf1703a.json
27    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
871ca78ab.json
11939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8c280f1.json
13060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4effbea00.json
5721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b3b37546.json
14963    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81f1d4d5c.json
7648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9664bcecb.json
3951    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c43ecb3e1.json
357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7d65135d.json
11101    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e994888f3.json
12805    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e7ca23c9.json
12082    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19cf5ba9d.json
10305    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
442ab63f2.json
6029    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed10d7ee5.json
3290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a763a055.json
95    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
41175dcb5.json
12449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eed6f01c9.json
7765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbdcd94a9.json
11048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65e386742.json
6039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4748cdef4.json
10286    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d6149d17.json
5504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
617ee6976.json
9494    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2ae5fa7d.json
621    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a4c95abd.json
7059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
179462b6d.json
4011    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ecaa8636.json
3638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e28bad751.json
6350    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df9b18c1e.json

8319    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af0494f60.json
13409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46f656f13.json
2276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3cc573384.json
3531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c39793853.json
13960    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8c19a325.json
14699    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
351d1e748.json
10787    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75f94bea0.json
11676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c23b2926e.json
1419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c18106b39.json
10295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
824db46ba.json
4506    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d08c85ef.json
6433    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7321cbf99.json
10985    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f849d1829.json
1106    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9934b985.json
14652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31a2e04d7.json
13643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e911008b8.json
11606    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa323e99f.json
2969    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6c836abe.json
10511    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cb3529bc.json
3467    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1fb9506a.json
3682    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
383e5b82e.json
11837    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbab88df0.json
10232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d61dd6a6b.json
3810    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baa309426.json
13684    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
388cd5b9c.json
11259    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a050484c.json
3659    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8c71e90a.json
8039    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0eec326f.json
3945    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5adb4e661.json
12108    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a89af346d.json
14443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
752c2658d.json
10906    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd2f5699b.json
9384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a5a05ef7.json
14025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96cf0efdb.json
11979    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
791c8a511.json
6010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae946bb63.json
9137    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ba39bba6.json
4859    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19f0ef706.json
4849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
187b92014.json
11713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d76c4ec1e.json
6502    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b58cef42d.json
13935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ec3a7275.json
14592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd8bb16c6.json
8282    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7eb0b42b1.json
3462    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c18a1acc6.json
9695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b251f717.json
1371    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b8610245.json
9417    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1edbf1acd.json
9539    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7359384d.json
257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be5f7a129.json
10634    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ee8b9d0f.json
2866    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7fbd95a9.json
718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b5a5458e.json
10129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ead80817.json
5396    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
488bfc285.json
613    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a706b0eb9.json
2645    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
065906a54.json
9169    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
807ba246d.json
12192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ceff22c4.json
12838    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8717133d3.json
13057    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3fa5b2be.json
10307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2430b50b4.json
1375    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69b79d62d.json
5103    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a015cce59.json
4691    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d8793638.json
739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e77e1c78.json
14474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08006836a.json
14544    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ccb2482.json
2292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b94ddd6a9.json
1734    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a3ae56f1.json
3bb49d7d9.json
14046    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58805776d.json
2126    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ba83a496.json
7149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecd83e25d.json
5627    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
082c6dee3.json
3024    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
277014d80.json
2584    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5bcc82f8.json
4764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed7c0ebb1.json
3185    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9b641d69.json
13442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f9b11590.json
14465    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae19ab91d.json
8112    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7650ed0f0.json
7881    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9e753cc1.json
6172    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb9390214.json
8915    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40d175d61.json
1657    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98f5b7ecf.json
7822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fd284f8.json
7136    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0850d4334.json
6662    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f983f20b.json
5141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57ac7373a.json
14229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13d0266c5.json
617    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27c0034f8.json
10007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b945f406.json
12026    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e380d9a2.json
931    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eba3b5c0.json
2216    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c64dd197.json
14038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14398288b.json
7122    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
476b3dbe5.json
7614    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a4bbdd8d.json
8801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba8d53f1e.json
764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21260b18f.json
10876    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
146b9d6e7.json
7aa58b134.json
12780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae9a09ad6.json
2824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
236dd6cca.json
8623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7c6e0401.json
7220    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5f82d04e.json
5919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
21b90ff68.json
1454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05492e461.json
10642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
73dedcf29.json
8898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c0ca0676.json
1538    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1027c621c.json
10372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5176f7eb.json
1407    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87cf6fd3d.json
6324    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615f5dc85.json
12998    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b0298091.json
12429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dcd8bc8a.json
5027    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f358dea9.json
3725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f3f2899c.json
13309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83233d345.json
8195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6258b0d76.json
2575    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
311ee8343.json
6684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cda44cdf.json
12374    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6231ed9b3.json
7563    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
276f26435.json
4193    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb76bfc79.json
2989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a9d11c50.json
6887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

6a48f776b.json
1542    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ebc60bb5.json
9469    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca1df3f71.json
14296    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aba00e1f9.json
3311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1314e3f92.json
11113    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2b92d7a0.json
9795    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88d5f9129.json
4035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee36e2198.json
13316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2cd71ec2.json
2280    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebd78e1d4.json
286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4e01721aa.json
907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ef52fe8b.json
9750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4ea89ddb.json
2105    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f99231609.json
5488    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa6fbdf20.json
11865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55b799287.json
11766    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cf93cab0.json
5276    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ca780c35.json
732    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abfad94f2.json
9258    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bb0c8226.json
7409    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c13da6b92.json
12137    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8de170932.json
10042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
631a6a27e.json
12084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb442ee5e.json
12307    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bb4cc5d3.json
13734    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bac34e381.json
9831    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9914ea40.json
12999    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
390f4fae4.json
3523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a76190c5.json
30    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
885af161b.json
6485    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
75a286d8a.json
11277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82137b39f.json
222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4f22a5ba.json
11617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f892df3a1.json
7110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbaabed93.json
14138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dcd70e1e3.json
5362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5792107ef.json
10648    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5d79ff56.json
6244    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d7f7a155.json
14870    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b62618f55.json
1756    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0142670c8.json
13912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d6fd0eaf.json
3806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0497c5ed8.json
5078    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a01ab5b30.json
14989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4385e043.json
1521    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a3a45096.json
1074    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0697d76d2.json
10794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ecc626163.json
14529    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5f846518.json
4074    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a36b60379.json
6884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1db76bd72.json
3229    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38360bf6b.json
11264    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
461185d51.json
11224    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
944a5fec2.json
3038    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7656e70f.json
11362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c9dcd3fb3.json
10357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca35f4b19.json
7387    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec182ebc4.json
2192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f569b3a29.json
14585    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09ca98f7b.json
5167    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57b57989d.json
7243    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b272e59.json
11195    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4ade8bb2.json
1894    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cbe99be7.json
2432    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c1bb3cd4.json
14848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4b96c3f3.json
6269    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7538304d6.json
5510    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfb8034b5.json
6089    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
288445cbd.json
8644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac94029d4.json
2375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cba8264f9.json
11160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08a71b8d1.json
12625    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b233246be.json
5245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b95539f0.json
6025    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16f2fa5c7.json
7986    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f584e226b.json
7302    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dfcbce94d.json
2306    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea9d28227.json
12177    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35f8b4bff.json
1159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d69a1f2a1.json
11577    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3759a1d40.json
6639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1930bcf64.json
10845    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9cb2f0fd.json
13608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5acfe9ed.json
3362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
793e89809.json
3677    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5cabf5331.json
4047    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5419155f2.json
1138    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a93ff4e92.json
6070    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8fda5b3b.json
7590    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2de719b88.json
8375    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2708d814.json
5340    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b28951b61.json
2226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20fc75f2c.json
6793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a92258c0e.json
6306    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6e06e37bc.json
10745    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
653f94080.json
13526    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b631b7e4a.json
2703    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0c81c563.json
1765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf2f22377.json
12562    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b2aa880a.json
9889    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f56c9eb67.json
8203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bbfc5274f.json
5524    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4416baea8.json
5360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a031e3771.json
10586    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ac5a9faf.json
9247    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db7fc3cc9.json
8513    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e1858e7f.json
7265    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f8654865f.json
1638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bea8484a3.json
6292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da78c5792.json
2263    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61fdcb2ec.json
2458    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
efb2cb92c.json
6964    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3b4b6a8a.json
11673    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7991808f5.json
7439    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1367c404.json
6517    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2148c2ef6.json
316    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3ae3e118.json
1067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
475564ad6.json
11632    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f235ec16.json
1928    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
927ee6390.json
12818    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a9223451.json
14380    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70b3d1f9c.json
176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95e92b082.json
12790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58132cc85.json
3309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ad565311.json
13651    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f48338adb.json
8678    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

a7b91a377.json
14518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3fa09b97.json
7463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3338e5ec6.json
4531    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6c4d7b09f.json
3145    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ba16b529.json
13368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06634513c.json
3124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
449290a8b.json
3762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82216cb2a.json
10141    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2cf62da9.json
3787    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08767d88e.json
12474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd59fdd99.json
2440    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26dfe8b29.json
4685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
338dddea9.json
7896    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9199119d.json
8402    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d52f229d1.json
12295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e00282d72.json
10718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fbc3ca27.json
6360    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6396a580.json
11088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a91141912.json
3606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cf645af3.json
11994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56ab5d935.json
4661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2490c888.json
76    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8d9108c4.json
10349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cac98ce6.json
7887    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3fd77fe8.json
02387e247.json
12199    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b539effd.json
1873    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
493215800.json
10110    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da4da9308.json
12917    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e133ab2f1.json
8102    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a51506e1.json
4491    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6679c179c.json
1223    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
adb33dd61.json
6767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cfc647dc.json
9797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d9bdbca9.json
2368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28fe42572.json
2579    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2edd45e56.json
5300    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6230b6c50.json
11150    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0db65104a.json
11589    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2082ad764.json
830    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4edc9ecc5.json
9197    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0fb13b2e.json
11474    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26cd1c2ee.json
11545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7dcbe3383.json
14078    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faca11616.json
5762    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68df0b84c.json
2504    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f477f306f.json
8346    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f867cc417.json
3291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67af2d880.json
10995    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1b34954b.json
12264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0143edd0a.json
4305    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1eb6e3ae1.json
6267    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97bb6502c.json
1421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f7aa1d3c.json
683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99b55ee76.json
7179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c8ab73ca.json
9295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8055a2ba.json
8823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
022429d5c.json
6327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa4b23487.json
5829    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6220663ba.json
10969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3111f360.json
2763    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9085cdde.json
13864    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e46373e2e.json
8924    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a479a1a6a.json
12352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27e8956dc.json
11684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3740bea8.json
10863    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fbc4677d.json
12636    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5918330ac.json
9664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c71d630d8.json
13547    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
82f899eaf.json
4955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2027f2dfd.json
5893    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
027c23f6b.json
9622    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2691a20c0.json
4021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a99b34f95.json
14795    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6d815d3ef.json
2230    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
903a75804.json
7588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ab53c55c.json
1994    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c6dc89df.json
6151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4f5588c6.json
1498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18734d13e.json
3652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f104904f.json
11879    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
afefc6424.json
13413    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
708d4eb55.json
10979    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
029641a1a.json
12708    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c42cf01ba.json
1992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aee8fe5a.json
14664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d52c77d14.json
11093    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cba60aeb.json
5742    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a322972da.json
8490    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
062de1f53.json
5909    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
edbffc8cf.json
14171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1084ba1bd.json
12732    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dee525fcd.json
344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8c555240.json
10584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b04b1c7a.json
8017    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4efae0f1.json
14187    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f068b8fdd.json
1591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef0b07c6b.json
13159    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4d8bf7feb.json
11407    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f4aa5ad9.json
8511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3757e3734.json
9077    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79314275c.json
6721    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1727cfc45.json
880    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ad3a6503.json
8245    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

61bf517f2.json
6068    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdffad31f.json
12875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3913a43f9.json
12715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e924d284.json
3342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da8d4a273.json
1045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45904d2be.json
10387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f6dc1747.json
8249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12d514ef2.json
540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0636650db.json
488    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3b017517.json
6693    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b0fa13e1.json
8609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c967561d.json
4030    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cace2b412.json
14292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
567c1ab71.json
12555    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e617dd078.json
12989    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6c9fd936.json
13322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf6000a98.json
11010    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25952f8a0.json
13106    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4b37d5ed.json
6343    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fe3f6afa.json
2936    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76d876216.json
5874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1aaa74b35.json
9704    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6259561f.json
5286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
69d95bc54.json
5301    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6783a1c6.json
9143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a23bdbdc.json
3540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
198357b7e.json
6765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a00eaa0fb.json
4736    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f31090450.json
14778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac35bae60.json
14504    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f70a1bf5d.json
1290    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15b6026b1.json
8016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a7027972.json
5551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
756025f7c.json
10853    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf5eb5d00.json
6349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6b91edb8b.json
13609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bad8f7276.json
7357    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
badeec277.json
3718    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10554e146.json
11408    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb67eb5d9.json
3450    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
acb614bba.json
2558    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6517af927.json
6801    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7803e9e5d.json
10393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f72db59b3.json
9160    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93219ad95.json
12521    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
703105908.json
10178    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e83fbe2a.json
5116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
434a2904c.json
4884    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2380da455.json
8656    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
835fdb873.json
13274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6309f250d.json
6176    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b497fb8eb.json
12865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ff5a1ca1.json
13338    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb89569d8.json
13062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44cd12263.json
2838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11a3fb06e.json
5788    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06cd6c623.json
9317    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed2fc6f4f.json
12337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1326c53f9.json
11969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95b0b4cd9.json
10208    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e01bb78f2.json
14346    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ee1c77a0.json
8208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b24f7e7f.json
6808    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
032aefa61.json
9037    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ca659fd81.json
10099    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cc463360a.json
1642    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d0e2179a6.json
4145    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cfb6fe9c.json
4342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ffe15ff7.json
7882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a66c7ec50.json
8608    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6627a8ab8.json
1767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee5f5db50.json
2530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2986194f1.json
10505    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee9ba4990.json
14674    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af93d5c2b.json
10040    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
973278f56.json
8144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d574448ee.json
10088    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c2a20543.json
3639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a2544358.json
10518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e8f72190.json
5227    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e4ab25214.json
13674    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0bd83ba72.json
14457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0aebdcbc4.json
5973    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e772235aa.json
2898    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c4f5efa8.json
6109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42149c9e3.json
8159    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
be5595abb.json
6189    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68e6f19f5.json
14274    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e454518b8.json
8757    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d8dd930a.json
4714    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3760c73b1.json
3017    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0864eb66d.json
10610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eff4a47b5.json
8895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1facdfb28.json
4781    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98b1b003d.json
3925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
caaf719c3.json
5846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46a5f0ba6.json
13693    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
437b01de4.json
9611    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ea357093.json
2775    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c81a8045f.json
12373    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2bbe22924.json
8444    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a154e41c.json
11612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34090e9d6.json
11292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48594b089.json

10976    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
133cc5f19.json
903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab4ef2577.json
11540    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4226db5f.json
2495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1fe2758a.json
4565    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c9dbc88e.json
3950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49e140a8e.json
11591    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
861d65847.json
4514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ebee32b.json
10421    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a734045b.json
3915    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ea9bb5d9.json
7271    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19f4d65b7.json
1019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ccd14639f.json
14588    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ebe54ca6.json
8787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
016dcf8d4.json
6104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1c1dbf8a.json
1581    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
113920513.json
11331    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3eb8ef7b3.json
9968    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c1cc2c24.json
3008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
786486296.json
10367    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0beacc42e.json
4205    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24c1b4eac.json
5580    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2962fc103.json
3926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94d930dae.json
2507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56d3aa3ac.json
14877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35cf91e6e.json
8723    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9882871d9.json
9992    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c8d2ed523.json
6054    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d7e57f81.json
1758    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4e09a814.json
4234    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cb14d1ba1.json
14713    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b82ec4b47.json
7948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c0b75d155.json
12377    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79f8b048f.json
612    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b24ac527f.json
2380    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40ea976de.json
11092    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e98593be6.json
2568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6831a72fd.json
2058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71d36d5c4.json
12610    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2b3baca1.json
4534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7f7066b6.json
14985    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f261c9968.json
7495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45e750d0d.json
3188    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a6d369bb.json
10889    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f41a7de83.json
050277142.json
1016    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
20e4dbf48.json
12676    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ba69dec6.json
639    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
06666dc09.json
9946    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
faf13c5cd.json
3790    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2dd7e8c2.json
13395    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a662f1d7e.json
5978    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3c8fda0f.json
12791    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
416cb5d6d.json
11003    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd7f76b49.json
12710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d8db1c19.json
5303    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
71f245b82.json
1344    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
703c9a23b.json
3583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76a8ffac4.json
4943    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb900ff8a.json
1449    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
af1035c81.json
48    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a21528ec.json
6143    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65470d9c0.json
7992    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ba66d1e1.json
14286    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d50b449f0.json
1311    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7827eee65.json
12916    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e2b3f60c.json
13530    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b30bcaab6.json
9581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
960f1a1d8.json
12529    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd5275a60.json
4467    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
117fb58c9.json
5339    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4bef58278.json
8581    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3dd380ccb.json
13503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1882fa24c.json
13294    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cdfa0548e.json
12041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51d815775.json
4914    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8fc22fd2c.json
2008    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dea01911c.json
2270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a7ec71e7.json
6060    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c18cc87cd.json
8799    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8673a672d.json
5041    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
871a00e21.json
5814    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b714e611f.json
7551    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44bba906d.json
657    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d5aedc48b.json
6563    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3480a9d2e.json
3369    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02c40b53c.json
14895    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3c273e42f.json
713    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
319f3e6e7.json
6669    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c44215cc8.json
14461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f13ba84ac.json
7156    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a630f3a73.json
10593    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9498e0379.json
3796    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2259cf6f8.json
8821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
658e4415a.json
8231    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8648922dd.json
12739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b74f88cf.json
10499    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf020a716.json
7235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f58a286e.json
14835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37cec5261.json
14649    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08d198666.json
4689    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e27bdcde.json
5824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50fc25dbe.json
9708    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
830b62870.json
5014    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f1dc8864e.json
13941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df72d8a20.json
10287    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c135c6b15.json
900    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33f28ad35.json
12500    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
12e747332.json
1594    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
609e37f6a.json
8291    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96b7978d2.json
3965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

dcc0d8482.json
6733    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0499e1ea8.json
12959    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b6f1e40a5.json
10774    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab0609017.json
3257    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1fa13f8d.json
10292    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b1c82382.json
9094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f01ff3e.json
5607    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2eec623c.json
13737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d596aea32.json
11399    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88cdc9a60.json
8850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7413a61ae.json
10064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae16e308d.json
5857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a5be413e.json
6552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
141b5d279.json
13192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80c4e9e4d.json
6972    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fb24264ea.json
1452    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87f75c842.json
11191    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3facf6055.json
9572    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
596c81470.json
11887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a93eb0d6f.json
5835    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cfd87918e.json
2684    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85f63b533.json
14032    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62613fb88.json
3048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1adc56d3c.json
14084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01d646ea8.json
9491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0597b1859.json
12086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e3239219.json
10419    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e76c8e39.json
11    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b72a62a33.json
8481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
125edf869.json
5374    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99eb49749.json
1690    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d876343e.json
2538    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52ad1225c.json
14527    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf795bb00.json
1313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8ccf4b62.json
4539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
225f72952.json
10038    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
774bd5a80.json
13664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
990e04b81.json
8741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
22e507b33.json
10384    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1772727a1.json
6036    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9159b6df.json
4682    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66faa15c8.json
4391    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d73b2a4c6.json
1241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
166650836.json
5896    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
65e75b92e.json
3209    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6a0b1762.json
11098    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd56db16a.json
4610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cd091f4cf.json
10386    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cdad4b1c.json
11014    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e2fdd907.json
13069    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5da0df190.json
13273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a5c652b5.json
232    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f3235380.json
13817    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6272ed019.json
13291    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1afdf61ec.json
319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3ff1ea74.json
8819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9beedceb9.json
10638    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93ef02488.json
6249    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51b7034e6.json
11182    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f2ff942f1.json
3797    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a561b2487.json
2559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a6729b6f.json
10321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1108027ef.json
7809    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
248c027cb.json
14458    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a97a37056.json
13072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c1f97540.json
13359    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b945da83.json
8425    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4555f9273.json
11559    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7314ad440.json
9568    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
68d430cbd.json
2683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee15edbb0.json
4198    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
335eacf2d.json
13377    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f108e7bc.json
6366    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58b069530.json
7525    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ae84e47c8.json
9773    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a98716d75.json
13929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81d97fa9f.json
414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea7ec0562.json
1448    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
084e59fdc.json
10138    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e9a64836.json
1685    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db5a260fa.json
9456    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
179c21d17.json
9148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5e1856e1d.json
6700    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daa73505c.json
6264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ae51e685.json
8381    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7da4e981.json
1503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5d7daf1a.json
8958    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
812ec1ab5.json
12237    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9761c645f.json
10763    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ed60e624.json
7575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b1bdd40.json
3484    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed6e38af6.json
11967    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9dd5cfcf.json
14715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31d921827.json
11904    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffaa73202.json
2582    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba580074c.json
12783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
112ae92e0.json
2629    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3aa4a07dc.json
8507    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7af7d9cb6.json
965    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1ef0568d.json
9802    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09807c555.json
7063    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b5974bdd0.json
13710    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f0f70e44.json
7879    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a55f8d58a.json
2460    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc0b9984a.json
8358    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d51f4560.json
3345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

a1999eced.json
10729    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9a379c0e.json
9844    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f0721fa8.json
13402    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
896bb46bd.json
1315    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9414e54b1.json
12941    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a72a34bdf.json
834    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed8e10562.json
3044    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40bd89515.json
8715    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b97569bc9.json
14631    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c037929.json
11420    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3386d639.json
4091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a53ed96d.json
14487    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84fbd99d9.json
2696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c68815d52.json
6113    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ccf125f1.json
2591    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2b949618.json
11533    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
840c965cb.json
9532    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e86d8e932.json
7949    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d1f2ed1b.json
11337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
076d6f830.json
5278    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c014197ab.json
13752    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
56f62a309.json
10251    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ad9215c4.json
14665    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cba08869.json
9744    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0e6c32c9f.json
2524    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
da5295aaf.json
1295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8910f2f5e.json
1119    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
84c0ff0a2.json
9787    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f45171393.json
5114    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff601e5ec.json
6877    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9fb31e59.json
5668    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47fc12331.json
5031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1349f68db.json
9062    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cff111e4e.json
13627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34872e9a7.json
13782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b8976d821.json
283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba04f3e21.json
9825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86855ddfd.json
7411    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
532b5a798.json
14584    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
78cf59390.json
13828    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
615afad71.json
4613    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
784e466b1.json
14015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f94c2a347.json
2250    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dd89c859.json
12953    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8cd96bf75.json
7877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
14357e2ed.json
774    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b5249852.json
4504    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d23a1962d.json
6600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ae4a77ba.json
14312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b1638a20.json
4084    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81d82bda3.json
5913    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c443e54d.json
9026    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cefba5d32.json
12347    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3fb62c05.json
11476    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1082982dc.json
6800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f53e55959.json
13683    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
37bf6da18.json
646    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce50f376f.json
1944    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1ed602f2.json
10801    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7daf7af9c.json
4353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a381e49c9.json
5552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2937acb6.json
2891    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aca6b6256.json
13865    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7a002088.json
4644    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3897d3cb.json
643    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf9bc2dc8.json
9150    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4225add43.json
1234    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9e263ee2.json
4950    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b52c73ef1.json
5528    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
688b3183d.json
8461    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91a2b97ec.json
6347    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e2daa33db.json
14617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0c9daa0a.json
14703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31081d71d.json
5080    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8a3c4f49.json
6681    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c723cf91.json
11266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba7d1a755.json
11624    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2e138d7a.json
4421    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1940d9eb3.json
13764    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
640a267a9.json
8304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
83b2fae5e.json
4397    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ed55129a.json
4991    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8a15669da.json
11783    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86219b4fe.json
11083    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a366ce2a5.json
10221    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4540f8e9c.json
4097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
99a994cb1.json
7713    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf5d1a04c.json
13415    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e5ba0e42.json
2859    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c92cdde7f.json
3570    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f0bfe5a9.json
7033    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f54d6a569.json
11552    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79ac40056.json
13619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
67994352b.json
10767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
62bf39bdf.json
10943    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
731a2ef80.json
2979    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46e25aa2b.json
12222    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d6fe9ec65.json
9876    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
263e34731.json
14216    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f0057428e.json
1351    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

c8c55eb19.json
13133    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
23463f8a8.json
10204    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f304e7fb3.json
7780    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd3804c20.json
9495    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5bd859977.json
4825    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9744dcc69.json
620    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df4d893b9.json
9419    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d63d5fe8b.json
10394    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9e4d6df7.json
4638    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7e8df1a9.json
10104    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81d404558.json
3058    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec8608c1c.json
3728    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
344b9632c.json
5759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfdc4cd9d.json
4133    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d30559d8.json
4707    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
269a6756f.json
11732    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f40de2f6f.json
11446    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e62e5aa26.json
196    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d353b436f.json
13838    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
282c0ac61.json
6337    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dbcae6f7.json
7443    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b50f927c.json
14874    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7331834d.json
3502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
853fc56da.json
4688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08f038689.json
7131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1883fea05.json
12164    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2907a1335.json
10060    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
504e4ec84.json
9ce816de6.json
7637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
58d1adc55.json
3499    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b596f518f.json
12388    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34fd2f89a.json
9067    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
181823d5f.json
10257    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
708189e17.json
9637    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e935ae1d8.json
2752    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02d66a1be.json
11546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7d93d4e8.json
4912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09c629b05.json
735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
de12dc945.json
1970    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6740be5a3.json
6093    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02e51a9e2.json
12602    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2ff35ef73.json
14381    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec57adce7.json
5240    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
067cacbb5.json
5228    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7cc040670.json
7100    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ab2bb4a0c.json
73e86b2fe.json
10502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7cb34ee2.json
6312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
18da94e9d.json
5368    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d05a7ab1.json
11393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c1f20f6e.json
0c3f6001a.json
1701    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb64e3d68.json
5296    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f212d0cdc.json
7900    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bc0f89d8.json
22    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ecdd04af.json
6178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c1ac19c2.json
13832    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7be274e0.json
14391    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb43b6a0d.json
9496    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c87651546.json
9906    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b55fbaee.json
5148    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
568a5ab51.json
8388    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6ce0ccf2.json
6962    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24afd5f54.json
1132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5a7de784.json
3884    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b94ae06d.json
3636    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fffd9b5a8.json
9517    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d3c3c390.json
5264    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee50b9066.json
13862    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ee6fe581.json
4858    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e11a3158.json
7739    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c3ed4c50b.json
7806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7e2ce5b3e.json
3128    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9b09190e4.json
9096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5170bc70.json
1940    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66a287bdf.json
10168    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ff05d4438.json
738    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b36762d2.json
14091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f03b04b1e.json
309    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4b4f217f.json
12934    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a38a1059.json
8601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b03983a09.json
12244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f1b7bea6.json
5813    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef7c5813c.json
10833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c538efa0b.json
6902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ba7ae0448.json
13391    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6f8ae496e.json
14912    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aecff5a85.json
10397    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b3fa60bc7.json
12717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3a0e3b527.json
1035    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1b0baf8a.json
9128    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a22daaa5f.json
6202    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc43fbfe4.json
1264    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
390689a38.json
1501    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
359dd0b52.json
3477    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b0355a1b.json
2281    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e925bdf02.json
10944    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3d0a4c45a.json
5411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
befa8a395.json
10342    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7473aaec.json
6061    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf74322de.json
14287    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcc138c39.json
4655    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
208beeb80.json
7955    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dc40c2612.json
4191    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
43ff07bab.json
11442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
feb06d776.json
13987    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
006ffebaf.json
11898    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0c918c91.json
1011    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98565468b.json
8687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c4f6cca8a.json
5669    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5606b4630.json
9341    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f25e91baa.json
8270    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b51d75d61.json
7202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a19707195.json
10599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dff24075.json
7833    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94a0eb345.json
6214    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef55e89bd.json
2654    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c9a90078.json
8465    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ecc1200a.json
3830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1976719f7.json
10938    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a7153881.json
5496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a978a37e7.json
12291    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9568aa267.json
4639    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0f27a7baa.json
11166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

a426fc504.json
7868    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc2ac0b04.json
11528    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec7952240.json
8293    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7fb5c3b87.json
10664    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf6a56d33.json
13946    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63a3f229c.json
8786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b686d33cd.json
12001    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
029469d58.json
4094    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
215345b52.json
8478    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcd21f3ec.json
432    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77b890534.json
11609    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c8053564.json
2997    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ad66b0f44.json
4295    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4faccedb.json
12902    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98bcfde91.json
14767    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
249112486.json
206    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c919eb44b.json
1505    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
061378b30.json
241    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05f84991b.json
8053    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa16a892d.json
9881    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46df0393a.json
10021    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a2b2f53be.json
2096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0d5d436f4.json
13725    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df6048227.json
8056    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
11d50c573.json
3171    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daeac2b84.json
2277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8511f09c2.json
13435    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9191da7b5.json
11480    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1baea0d16.json
6830    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b3d754de.json
5562    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbf6b6e42.json
9514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b40818da6.json
13816    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a6756c71.json
11299    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
001a1aaad.json
9848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f23f9105.json
5610    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ef640aaf.json
4957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
154d24447.json
760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
839733624.json
11453    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d8603dd80.json
11566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1fd342e17.json
15    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8189ff9ac.json
14260    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f6029457.json
11111    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f385d9645.json
8780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ca8ebdbd.json
11218    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
870e5566b.json
4178    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
42b3d53f8.json
7027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3313aa06f.json
14697    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a4c903a3d.json
7514    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b459b60b.json
8228    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d0f353e2.json
8971    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9575b655.json
2498    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48c838ef7.json
7747    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
48899f983.json
10383    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
451d64f26.json
13811    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
091a5da01.json
13282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36a216956.json
753    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbb64ed77.json
5271    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c5dbd29f.json
6977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd8f94a94.json
12384    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4dc6822f8.json
14393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7438f5d52.json
4363    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
722beb3aa.json
3524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9eb70b7c4.json
2103    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
064217ca4.json
2131    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b100db162.json
12910    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27b708edc.json
12519    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4756b380a.json
13379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eff541eff.json
11447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c042fa2d5.json
9910    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31e2399a9.json
9543    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db4165316.json
14045    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
45600eaab.json
160    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e826027f6.json
6268    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c37d5c957.json
b11ae7451.json
3367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d5eababe.json
9990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
33752346b.json
11688    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
24aaed171.json
9426    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c16e813b.json
12741    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a02b467d.json
4977    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d68301fb2.json
9911    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4c26cf05d.json
3600    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
842b21328.json
479    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
107c30c6d.json
12821    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bb6183eb.json
4004    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b8b0a817.json
10443    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
805461ad6.json
12404    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
552bb16e5.json
14382    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea853814a.json
11995    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4158fbb67.json
5792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c0ddccc8.json
59    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53d6d37c8.json
799    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffe5a0271.json
14153    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a3727cc47.json
6784    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f95b343a.json
6379    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bb7dfc592.json
3857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0f76e19b.json

9988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9e6da2bb1.json
3848    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91bab29e9.json
8135    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a07440416.json
8802    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8c93a6e28.json
588    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ac495f25b.json
6926    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce26d6864.json
10665    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d4e91ab0.json
3792    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0ae5f9681.json
3073    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db23b96cb.json
10535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3b3349318.json
14166    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5112569f6.json
1277    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a1be07d5.json
12737    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b35c61109.json
13667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fff4a6420.json
1939    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f152b2fd4.json
12969    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0c47e700c.json
10865    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6102346ee.json
5202    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
95b94b4ac.json
6652    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
156ab0f97.json
7621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
092b32197.json
10527    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2560aee80.json
2770    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f6a0e54d.json
12682    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c1aa4142d.json
10769    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3a4afef1.json
5151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dd28c706.json
5625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2e116036a.json
5022    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4199f1957.json
12372    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dbd4f79ef.json
14245    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a875ef01.json
10667    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c787403c.json
2094    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3227c4f2e.json
12637    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
183c947eb.json
1852    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
261c4115b.json
4697    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
015da0878.json
12877    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fe8b174.json
5090    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
831505752.json
10762    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0eeaf438.json
4054    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0af142ee3.json
4608    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
879c40dfa.json
9740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7bfe2d68f.json
7496    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
80ebea85c.json
110    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddc628647.json
5887    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
63f2e0940.json
4425    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30319970f.json
4215    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
342400751.json
12882    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5264d253b.json
4990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c07c1abf.json
1183    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
879ce67b8.json
2486    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
91d0ba5c0.json
3354    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3fbc3fa12.json
12156    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28ce3c3ea.json
7011    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
53037f091.json
3020    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b76e8c452.json
13226    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
767907867.json
9981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36fd9e13d.json
10765    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a5ba2ea7.json
10185    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a7277559.json
9481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dc8f0fd4.json
4064    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6cf7d415b.json
6857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
31dcdb872.json
5741    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
918408d22.json
4188    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf49e1549.json
1353    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30764a1fa.json
11744    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79ef1fd27.json
4963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
954243934.json
11235    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47d383f21.json
7048    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b72bbd6db.json
8718    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1bff3e46f.json
13861    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e3a29829f.json
6073    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
066521b34.json
1157    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b1ddc50c.json
13387    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c039d8c1.json
5444    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
09f514bd9.json
5134    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ea16468.json
5132    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
98e211da3.json
1192    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9d64175e7.json
8566    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3a92c453.json
12463    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e74dd0579.json
8722    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5e4cfab0.json
670    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c14b2f3da.json
2417    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6151d695.json
7615    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5b1528841.json
12411    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4eb9088a2.json
10823    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44a0c16bc.json
11640    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
678140b71.json
8969    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8cdba660.json
154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f62e604d6.json
827    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1ee4a9e81.json
5415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a5edf3e84.json
13412    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f19ac5ab.json
599    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea055de86.json
8429    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
539177546.json
10695    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26284d23a.json
13571    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
225d332dc.json
8600    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6661d0fff.json
5925    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ec697bec.json
3007    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ff4a6c4f.json
12344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bce2ed853.json
11125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
97b32f734.json
11735    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27ab49f1a.json
3721    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10b46b83f.json
6464    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bfa9377c9.json
4357    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
51d3a70bf.json
1578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8378c8af1.json
1922    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79f41f755.json
3472    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7eae805cd.json
14717    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e101e353.json
6095    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bd870f5b1.json
1130    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
574919b00.json
7428    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9bd70dc2b.json
4574    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

1ba539b66.json
8912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f7f769c37.json
7524    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea319fdec.json
1085    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ce0b81f5.json
1051    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
369da3ef0.json
12750    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd2cc8576.json
1743    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16d7f208a.json
11097    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b2b52ccf2.json
2164    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0038234c6.json
6270    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ee2d66134.json
7413    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ea05e0a19.json
8321    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c2109fcac.json
6595    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f9e3a51c1.json
14633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77014fe37.json
10963    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01ba86830.json
14838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
505c5d7c6.json
2680    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
463706ace.json
7567    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7a050445.json
1502    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29e6c171d.json
1838    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0cce7d218.json
13908    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ad784999.json
7462    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b0ad07cfc.json
11174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
16ce3524b.json
9414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46b9595d0.json
3427    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c41283409.json
10926    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a0e71d03a.json
6518    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9aa0e02ef.json
14530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fafa7ddb0.json
9220    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28af5e0d3.json
11217    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7e3c3270.json
14109    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1c5d6ba9.json
12378    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ddfb6f66.json
12535    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9eb98f34c.json
284    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ec9289df.json
13604    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6784b2fcd.json
5367    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e6ae12115.json
10019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f022849c2.json
12443    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a14caa3ea.json
2394    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2c0a3e57e.json
2742    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bf2f87f17.json
11934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd9375e71.json
1589    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ffebad2e7.json
3457    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8dd8a7b9e.json
4903    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a1502f80.json
1790    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8e68a9075.json
10263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02401db5e.json
12698    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a09008d49.json
6850    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a5da8156.json
8661    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ec53a8725.json
1957    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1716cd645.json
10312    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b586e1ea4.json
10846    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
070014779.json
3825    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e89119f29.json
7936    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36f3f7027.json
5102    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87a16f3fb.json
8194    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d5f95d9a.json
13703    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c958b75b3.json
13826    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26aa722e1.json
13760    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
308034707.json
11572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f073c005e.json
5289    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5f4f3347f.json
6125    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e66ee4be8.json
8572    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
36ddc4f2d.json
7183    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f246cb734.json
3750    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1942485f8.json
8806    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
590a78f0d.json
7266    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a9294a9ea.json
9929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c61aef5bc.json
6356    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0a1b57b57.json
9735    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
25eec77c6.json
3253    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
176ef71db.json
7233    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0b90767fa.json
7208    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2dd62cf2.json
796    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7c3423bab.json
13739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3ecdd4122.json
1779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01186c9fc.json
7252    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90e1edc71.json
712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ebae250e9.json
13990    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
81bc89458.json
14926    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fecfc736.json
2822    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
52af450f8.json
2782    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d734c881a.json
2614    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
907f77c78.json
6871    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
586585da9.json
3337    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f50d4f5bc.json
13112    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9dd3b3bce.json
7154    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5247209aa.json
105    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
852296968.json
4385    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c0aa9866.json
11332    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3f50cc4fd.json
8155    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f99af9837.json
4174    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a8f43bea5.json
8795    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ef475fbe.json
728    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1104fe6bb.json
115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27a7a1795.json
14414    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c42153e51.json
3109    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aecba8ecd.json
1212    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1c901d8d7.json
8597    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93cfea76a.json
14653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2d3d873be.json
4819    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d56fbda82.json
5994    1
Name: Type, dtype: int64

<class 'pandas.core.series.Series'>
8f9bfc9f4.json
4059    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d4b5c41ac.json
12313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
44867700c.json
11454    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bc4f18ced.json
9800    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f3392f18.json
2606    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1154c26ac.json
3988    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f75724b44.json
10604    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fe2cc3feb.json
10929    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
207d61997.json
201    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1533ebfd4.json
9154    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1d5a59ca9.json
11070    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c74abc080.json
2724    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dde9d290a.json
7307    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7075c1306.json
4327    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6a7310588.json
14390    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e472219f1.json
2577    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
556549333.json
9103    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9a9f6c753.json
454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5c30eceb2.json
4712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc43d7ddb.json
7745    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
0fa25b7e5.json
3643    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f82aa539c.json
4459    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
991eba9f9.json
4793    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e481cf862.json
2265    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7a23819c1.json
13462    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
07ee44cb8.json
4653    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d277ab24d.json
12935    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fe6f98a5.json
8824    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6db506983.json
9574    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9fd2b640f.json
6635    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
898476994.json
8243    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1f4871c30.json
13484    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bedb1ef9.json
11116    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2932eac8e.json
4558    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b121d3be8.json
7493    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50262523c.json
3509    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f4028c04.json
2353    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
eb5ce7ea2.json
10135    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
119f813b2.json
3491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
66cff2ed9.json
9592    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
818cf6f02.json
1546    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2f3677597.json
5578    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
94f9f7789.json
13993    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e9075c9.json
4261    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e32467940.json
12609    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2cb9ce5ac.json
13875    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6fdb43f0b.json
7692    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
05935bf08.json
944    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fa53dd6cd.json
13349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cab92d5a3.json
2934    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9430042a3.json
11249    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a700a780b.json
3319    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61c5987cd.json
3027    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5753890a.json
9634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f48a8fe6.json
14647    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c5db00aa6.json
4283    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93dc36260.json
4778    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7b49d0924.json
1912    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
00e50c7a7.json
10022    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c66f97de2.json
3228    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19745f3dc.json
2424    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fdd191ba0.json
4297    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2196b0156.json
6391    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
38fc09756.json
9382    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abf38029d.json
4634    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
30c864619.json
6779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
493ab5d96.json
14433    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
787f3055b.json
11943    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8ccaceef5.json
7583    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e1cd37f6c.json
2142    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
49f12d27b.json
9282    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ed8dd7a7.json
11539    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
96ba0193d.json
1512    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a64c0560.json
7313    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
182aec7a4.json
8263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
dd13b36c6.json
4669    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a1188fdb7.json
2503    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5314d64ac.json
6658    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
46152db3e.json
3575    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7d4fceffc.json
6696    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
79b514f79.json
740    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b854220cb.json
10739    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
548351895.json
7767    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
bdd606969.json
1167    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5ab714faa.json
11451    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aaedd873d.json
12    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2b1477c3c.json
11633    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5a3ea9e8a.json
6780    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f74ad48ff.json
8812    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2a19120e7.json
2497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
db3f7a11d.json
1494    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ef8d291b0.json
10849    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
40843af1e.json
7447    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2483a71c4.json
3349    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b517c8c90.json
13966    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8760ee6e3.json
11445    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
19fe29040.json
4244    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ddc2e31c0.json
10149    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b2150d3a.json
2031    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
aa03b987e.json
4144    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f29aeba4e.json
4779    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a7ba4d7e1.json
8627    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
50723f2c3.json
2335    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4f7fc967a.json
5545    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f4c9a0b24.json
11096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
939ca33f6.json
8792    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
598f49a8f.json
8534    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d3f0d22a7.json
13642    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e995db95f.json
3980    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e998d6d60.json
3176    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
319ae7620.json
8666    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ed3e206a.json
3089    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
57aecbbcf.json
4019    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
556599752.json
6619    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2eaccd3bf.json
13292    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
85c4e7a41.json
8450    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

cdf03dc31.json
5905    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
952501bdb.json
1141    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
15538a661.json
10903    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf8d949f9.json
5611    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e540c1ba5.json
66    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f928a7e7f.json
13393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
354e9fc50.json
11140    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
70a90deaf.json
4151    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9c788a6bb.json
6483    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
abebcf1e4.json
14124    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
35d9045fb.json
11042    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d246be504.json
8746    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fc9cf8b8d.json
3911    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fbe0c2e5.json
6645    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
578b82f50.json
10583    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8df053c7e.json
2855    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3e411bd12.json
9003    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1cccac540.json
3203    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
697c8c6c9.json
13680    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce5e6e407.json
11687    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8d1dce21f.json
4919    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ed9948860.json
6156    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
32ad56035.json
14601    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
61ac3c78c.json
129    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a818af93.json
4759    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d02c3d99a.json
2217    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
55c827f51.json
14625    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b663aafeb.json
10344    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
266aee5b3.json
2169    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cbd8840cd.json
9326    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c12883eaa.json
4048    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a6fea1d1a.json
8822    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
181d40c5e.json
10481    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
705ce0ebd.json
14199    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
87fadb3df.json
4239    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
47ae048a5.json
13707    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d7cefb8e9.json
6062    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
86386b0c0.json
2454    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1a2c91362.json
5695    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e7fdf6d1c.json
8022    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d973f1d5c.json
11511    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b617ce1ce.json
1869    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
28e151af1.json
5294    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8de1c1ca1.json
10867    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a243c61c6.json
3764    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
728ed1c0e.json
4907    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a43540943.json
5699    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daad5c208.json
12844    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
cf44e1a59.json
3115    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8b34370aa.json
1aa8ed8dc.json
6712    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4072b0841.json
9661    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9cc2822d9.json
6990    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd139f4e4.json
8491    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
2959602fc.json
2065    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4b5532afb.json
10530    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9ca400496.json
10918    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b9f8cf52a.json
4086    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76b366645.json
13688    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4a874872c.json
11241    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9684a1603.json
8885    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6842b7ff9.json
9415    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5eb355cea.json
11263    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7169c3e3a.json
2123    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b7a54fea5.json
8621    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
3bbbccce4.json
13329    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
755abaa79.json
8136    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d1f444e66.json
5981    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c7d02bfca.json
14975    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f253bd6aa.json
668    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c382bae22.json
3987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d9b894731.json
11746    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b672b7465.json
5118    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d25a850ae.json
2304    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
26edfaa28.json
9921    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5dc7d3dc7.json
8211    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
13e385580.json
11623    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
92e74870e.json
8617    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
baf49463a.json
3015    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c53fb8a18.json
2314    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c6c8c73e5.json
1523    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
88c07e663.json
2948    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a63f6c6a1.json
5277    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4ad983a9d.json
8066    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b4835265a.json
a56d6eceb.json
5256    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
29d36f5b3.json
6007    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
822b31b85.json
10210    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
8f9010452.json
14786    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
daed3d063.json
13157    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
34dc86aae.json
14832    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7112952b7.json
3177    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
df091dc6b.json
13148    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
4fedc2eb6.json
14803    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b34a57b41.json
11345    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f51667d46.json
9893    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
9f56880b6.json
7442    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f3a5451b9.json
6725    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01f4746ef.json
5441    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
10eaafcd9.json
8949    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
f5e35ea02.json
12880    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c763886a6.json
3497    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6ade0f2fe.json
4794    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fcf377cce.json
492    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
93d842736.json
1495    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
968c82e07.json
12072    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
01c62e03b.json
14179    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
657a54d36.json
4430    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74e18bd5e.json
4114    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fed799a78.json
12476    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
74c7373bd.json
12605    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1b1fdfd71.json
7091    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fd820a71a.json
6149    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
27cede3cf.json
322    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>

7b5012939.json
6230    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
77c9c2e64.json
4987    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
b1d288322.json
4857    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
ce6afb606.json
10686    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
89df794d1.json
6258    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
375a0eb3c.json
10096    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
610ece7bd.json
9960    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
7ac41d8ae.json
12322    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
6153f9d64.json
3335    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
90fe2bf72.json
3727    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
02126e289.json
10498    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a371e0164.json
13181    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
76fefc6ab.json
10273    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
c46e29741.json
e239373ff.json
11051    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
fadae6510.json
2619    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
08f40f232.json
10826    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
1dc90fbb8.json
4393    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
d2f216860.json
2355    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
5af078de1.json
3009    2
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
e9dec895b.json
7362    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>
a86ec27e9.json
13352    1
Name: Type, dtype: int64
<class 'pandas.core.series.Series'>